### ISSUE TITLE
x/crypto/chacha20poly1305 regression, now panics

### ISSUE THREAD

**Issue by benma** [gopherjs/gopherjs#1025]
Here is a snippet to reproduce the problem:

```
package main

import (
	"github.com/gopherjs/gopherjs/js"

	"golang.org/x/crypto/chacha20poly1305"
)

func testchacha() {
	key := make([]byte, chacha20poly1305.KeySize)
	aead, err := chacha20poly1305.New(key)
	if err != nil {
		panic(err)
	}
	msg := []byte("Gophers, gophers, gophers everywhere!")
	nonce := make([]byte, aead.NonceSize(), aead.NonceSize()+len(msg)+aead.Overhead())
	_ = aead.Seal(nonce, nonce, msg, nil)

}
func main() {
	js.Global.Set("gojs", map[string]interface{}{
		"testchacha": testchacha,
	})
}
```

Compile with `gopherjs build -o test.js`.

Load in a browser:
```html
<script src="test.js"></script>
```

Execute in console:

```
gojs.testchacha()
```

You will see this error:

```
test.js:1452 Uncaught Error: chacha20poly1305: invalid buffer overlap
    at $callDeferred (test.js:1452)
    at $panic (test.js:1495)
    at Object.$packages.golang.org/x/crypto/chacha20poly1305.chacha20poly1305.ptr.sealGeneric (chacha20poly1305_generic.go:34)
    at Object.$packages.golang.org/x/crypto/chacha20poly1305.chacha20poly1305.ptr.seal (chacha20poly1305_noasm.go:11)
    at Object.$packages.golang.org/x/crypto/chacha20poly1305.chacha20poly1305.ptr.Seal (chacha20poly1305.go:62)
    at testchacha (snippet.go:17)
    at Object.v.$externalizeWrapper [as testchacha] (test.js:1908)
    at <anonymous>:1:6
```

This regression comes from this change in x/crypto, where the build tags were changed for `internal/subtle/aliasing.go`:

https://github.com/golang/crypto/commit/be400aefbc4c83e9aab51e82b8d4b12760653b47#diff-31568a1efa7b47a907232185869dcbb02a8607ace0bc64690535af232284bfadR5

Before that change, aliasing.go was built by gopherjs, and everything worked fine. After this change, aliasing_purego.go is being built by gopherjs, causing the above problem.

**Comment by benma** [comment]
Possibly the GopherJS `reflect.ValueOf().Pointer()` code has a bug?

cc @x1ddos @FiloSottile, in case you are interested or have some ideas about how to solve this.

**Comment by benma** [comment]
I found this, which seems to be a GopherJS internal to implement aliasing.go:

https://github.com/gopherjs/gopherjs/blob/master/compiler/natives/src/crypto/internal/subtle/aliasing.go

I guess somehow it stopped being compiled after the build tag changes.

**Comment by benma** [comment]
This PR resolves the problem: https://github.com/gopherjs/gopherjs/pull/1026

**Comment by nevkontakte** [comment]
The pull request has been merged so I'm closing the issue. Although I'll reiterate my caveat from the PR's comment:

 - The fix will exist as is, as long as it works.
 - If we decide to go forward with #1021 and we don't find a way to make this approach work with overlays for outside of the standard library, the fix will be removed from the overlays.
 - We *might* set up a forked version of `x/crypto` as a substitute, if we find a reasonably automated way to keep it up to date with the upstream. Cryptography in particular is one of those domains where being out of date can be an actual vulnerability, so if we find no automated solution to maintain a fork under the gopherjs umbrella, it will be up to the community to create and maintain one.

**Comment by FiloSottile** [comment]
If there’s a patch that's not too gopherjs specific that we can carry upstream to avoid a fork, I’d be happy to help land it.

**Comment by nevkontakte** [comment]
@FiloSottile I appreciate your offer, I too would very much prefer to avoid a fork.

I've spent some time [looking](https://github.com/gopherjs/gopherjs/pull/1026#issuecomment-846294857) for such a patch, but could not come up with a good one. If you'd like to try yourself, here's a summary of the problem:

 - The problematic function is `AnyOverlap()` form https://github.com/golang/crypto/blob/master/internal/subtle/aliasing_purego.go, it checks whether a two arbitrary slices overlap.
 - Both the default and purego versions of the function rely on obtaining a pointer to the beginning and end of the slices in question, just by different means.
 - Naturally, GopherJS's runtime provides us no access to the continuous address space, and there is no obvious way to emulate one.
 - The only approach that would work in GopherJS is to check whether the slices are backed by the same array and compare offsets. Unfortunately, Go offers no safe way to get slice's underlying array.
 - This also wouldn't be a bulletproof algorithm in a general case with normal Go: even when built with `purego` there's no guarantee that unsafe wasn't involved at some stage when creating those slices, so they _may_ overlap even if backing array pointers seem to differ.
 - Ultimately, with some substantial changes to GopherJS runtime implementing `AnyOverlap` in a portable way doesn't seem possible.

What I didn't explore, and where an opportunity may still exist, is tracing down uses of `AnyOverlap()` and getting rid of them, or maybe considering a phony version that always returns true or false. Although I am not sure about performance or security implications of such a change.

**Comment by benma** [comment]
Same issue appeared again with x/crypto moving the package from `subtle` to `alias`. Fixed by https://github.com/gopherjs/gopherjs/pull/1227
