### ISSUE TITLE
`master` branch no longer understands import paths that end with a version

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#1033]
I don't know if this is actually a regression in `master`, or if it was a bug that it worked in older versions.

To reproduce, use a versioned module import path such as `github.com/go-kivik/kivik/v4` and create a `go.mod` file:

```golang
package main

import (
	"github.com/go-kivik/kivik/v4"
)

func main() {
	_ = kivik.SessionCookieName
}
```

As expected, this works with all modern versions of Go. It also works with older versions of GopherJS:

```bash
$ go build .
$ gopherjs version
GopherJS 1.16.1+go1.16.3
$ gopherjs build .
```

But as of the latest version of GopherJS, it no longer works:

```bash
$ gopherjs build .
main.go:8:6: undeclared name: kivik
```

It seems it's still working as of the 1.16.2+go1.16.4 tag as well.

<hr>

As I mentioned at the outset, I'm not sure if this really counts as a regression, since I'm not sure this ever should have worked.  When operating in GOPATH mode, it makes sense that `github.com/go-kivik/kivik/v4` is interpreted as `v4`, not `kivik`, so the new behavior seems more consistent with GOPATH build mode.

However, this behavior also means that code using modules, and intended for use in GopherJS, must use explicitly named imports for these things, i.e.:

```golang
import (
	kivik "github.com/go-kivik/kivik/v4"
)
```

This isn't that much of an inconvenience, so I don't mind doing it. It's just an unexpected change.

**Comment by dmitshur** [comment]
`astutil.UsesImport` works correctly when the name of all imported packages is exactly equal to `path.Base` of their import path, but can produce incorrect results in situations where that isn't the case. Perhaps the fix is to replace the use of `astutil.UsesImport` with a version that takes actual package name into account. (It requires imported packages to be loaded, at least enough to know their name, and arranging that might be tricky.)

**Comment by flimzy** [comment]
@nevkontakte, @dmitshur Do you have any feeling on which is the actual correct/intended behavior?

If I use the `main.go` mentioned above, with no `go.mod`, then even upstream Go behaves as gopherjs (since it's operating in GOPATH mode).

Was it an intentional decision to support module imports in GOPATH mode in GopherJS, or was that just a "happy accident" at some point?

**Comment by nevkontakte** [comment]
> Perhaps the fix is to replace the use of `astutil.UsesImport` with a version that takes actual package name into account. (It requires imported packages to be loaded, at least enough to know their name, and arranging that might be some work.)

Yep, making this information available would be ideal indeed. I am currently also considering two middle ground options:

 - Find a way to instruct `go/types` to ignore unused imports, which would allow us to prune function bodies, but not bother dealing with imports.
 - Take a step back in function body pruning and only remove the ones instructed to (via a compiler directive of some sort). It will solve the problem I originally encountered and will have a much more localized impact on the build process.

> Was it an intentional decision to support module imports in GOPATH mode in GopherJS, or was that just a "happy accident" at some point?

To be honest, I'm not sure what role GOPATH mode plays here, but the current behavior of GopherJS is a bug. Like Dmirti said, astutil.UsesImport is unable to understand that a particular import is being used when package name (as per `package` directive in the source code) differs from the last component of the import path. That leads to the import decl to be incorrectly removed by the logic added in https://github.com/gopherjs/gopherjs/commit/58c1058cb3db0d3a6d0303037051f1db057e29a9.

Whatever module-related logic might be also at play here is completely provided by the `go/build` package. However, it's compatibility with modules is kind of ambiguous at the moment: it works in some cases and doesn't in others.

**Comment by nevkontakte** [comment]
@flimzy could you double-check that the issue went away? Then it would be a good moment to cut a new release.
