### ISSUE TITLE
The \src\runtime\fastrand.go does not exist

### ISSUE THREAD

**Issue by RICEVAGUE** [gopherjs/gopherjs#1049]
Hello, I have installed the gopherjs by "go get -u github.com/gopherjs/gopherjs"
And I could run the "gopherjs" command in CMD.
However, I get a error when I tried to "gopherjs build x.go".
The error information is that

[31m[compiler panic]  open C:\Program Files\Go\src\runtime/fastrand.go: open /\src\runtime/fastrand.go: file does not exist

 goroutine 1 [running]:
runtime/debug.Stack(0xc0000d4c60, 0x5cd780, 0xc000621530)
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0xa5
github.com/gopherjs/gopherjs/compiler.bailout(...)
        C:/Users/go/src/github.com/gopherjs/gopherjs/compiler/utils.go:786
github.com/gopherjs/gopherjs/compiler.Compile.func1(0xc0000d76f8)
        C:/Users/go/src/github.com/gopherjs/gopherjs/compiler/package.go:135 +0x9e
panic(0x5cd780, 0xc000621530)
        C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
go/types.(*Checker).handleBailout(0xc0001e8000, 0xc0000d6ae0)
        C:/Program Files/Go/src/go/types/check.go:245 +0xa5
panic(0x5cd780, 0xc000621530)
        C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/gopherjs/gopherjs/build.parseAndAugment(0x731b80, 0xc00019c4c0, 0xc000166f00, 0x0, 0xc00061b100, 0xc0006211a0, 0x28, 0x27, 0xc000491740, 0x2a)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:267 +0x1f53
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc00018ef30, 0xc000166f00, 0x0, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:670 +0x6fb
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc00018ef30, 0xc0001918a7, 0x7, 0xc0001abda0, 0x2c, 0x9dace0, 0xc0002fa000, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:578 +0x109
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc00018ef30, 0xc0001d55e0, 0x0, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:625 +0x12eb
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc00018ef30, 0xc0001b0ab1, 0x14, 0xc0001ab4a0, 0x1e, 0x0, 0x27, 0x26, 0xc0001ab500)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:578 +0x109
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc00018ef30, 0xc0001d52c0, 0x0, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:625 +0x12eb
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc00018ef30, 0xc000190a69, 0x6, 0xc0001b45e0, 0x1d, 0x0, 0x26, 0x25, 0xc0001aab10)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:578 +0x109
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc00018ef30, 0xc0001d5180, 0x0, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:625 +0x12eb
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc00018ef30, 0xc0001903c1, 0x5, 0xc0001900e0, 0xa, 0xc000008000, 0x2d9678f7098, 0x561550, 0x4cf7a0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:578 +0x109
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage.func1(0xc0001903c1, 0x5, 0xa, 0x2d9678f7098, 0x5d0380)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:682 +0xc6
github.com/gopherjs/gopherjs/compiler.packageImporter.Import(0xc000192dc0, 0xc000192dd0, 0xc0001903c1, 0x5, 0x5ec6a0, 0xc000192c01, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/compiler/package.go:111 +0x67
go/types.(*Checker).importPackage(0xc0001e8000, 0x1c, 0xc0001903c1, 0x5, 0xc000190380, 0xa, 0xc0000d6390)
        C:/Program Files/Go/src/go/types/resolver.go:161 +0x6fd
go/types.(*Checker).collectObjects.func1(0x72a300, 0xc00018f110)
        C:/Program Files/Go/src/go/types/resolver.go:250 +0xff2
go/types.(*Checker).walkDecl(0xc0001e8000, 0x732750, 0xc00019a540, 0xc0000d6968)
        C:/Program Files/Go/src/go/types/decl.go:423 +0x139
go/types.(*Checker).walkDecls(0xc0001e8000, 0xc0001a3700, 0xb, 0x10, 0xc0000d6968)
        C:/Program Files/Go/src/go/types/decl.go:410 +0x79
go/types.(*Checker).collectObjects(0xc0001e8000)
        C:/Program Files/Go/src/go/types/resolver.go:240 +0x246
go/types.(*Checker).checkFiles(0xc0001e8000, 0xc000196238, 0x1, 0x1, 0x0, 0x0)
        C:/Program Files/Go/src/go/types/check.go:263 +0xb3
go/types.(*Checker).Files(...)
        C:/Program Files/Go/src/go/types/check.go:250
go/types.(*Config).Check(0xc00019b700, 0x6452c5, 0x4, 0xc00019a4c0, 0xc000196238, 0x1, 0x1, 0xc0001d4b40, 0x0, 0x208b47, ...)
        C:/Program Files/Go/src/go/types/api.go:370 +0x158
github.com/gopherjs/gopherjs/compiler.Compile(0x6452c5, 0x4, 0xc000196238, 0x1, 0x1, 0xc00019a4c0, 0xc000192dc0, 0x0, 0x0, 0x0, ...)
        C:/Users/go/src/github.com/gopherjs/gopherjs/compiler/package.go:178 +0x775
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc00018ef30, 0xc0001d4050, 0x0, 0x0, 0x0)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:690 +0x836
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc00018ef30, 0xc0001923c0, 0x1, 0x1, 0xc00019033c, 0x4, 0xc0001900e0, 0xa, 0x4, 0x622c80)
        C:/Users/go/src/github.com/gopherjs/gopherjs/build/build.go:554 +0x3ff
main.main.func1.1(0xc0001923c0, 0x1, 0x1, 0xc000192150, 0xc00018ef30, 0xc00019a200, 0xc0000d7c20, 0xc0000d7c20)
        C:/Users/go/src/github.com/gopherjs/gopherjs/tool.go:125 +0x2e5
main.main.func1(0xc0001ba000, 0xc0001923c0, 0x1, 0x1)
        C:/Users/go/src/github.com/gopherjs/gopherjs/tool.go:164 +0x1a8
github.com/spf13/cobra.(*Command).execute(0xc0001ba000, 0xc000192390, 0x1, 0x1, 0xc0001ba000, 0xc000192390)
        C:/Users/go/src/github.com/spf13/cobra/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001bb400, 0xc0000d7f38, 0x8, 0x8)
        C:/Users/go/src/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/go/src/github.com/spf13/cobra/command.go:902
main.main()
        C:/Users/go/src/github.com/gopherjs/gopherjs/tool.go:583 +0x1337

[39m

Could you help me fix this problem?

**Comment by nevkontakte** [comment]
Unfortunately, Windows is not a supported platform at the moment, only Linux and MacOS are. However, [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) works well for GopherJS, so maybe you could use that?
