### ISSUE TITLE
Code in Readme does not compile js.Global. versus js.Global().

### ISSUE THREAD

**Issue by elsanussi-s-mneina** [gopherjs/gopherjs#1093]
The source code lines in the Readme.md file with "js.Global." did not work when I tried to compile them using

I get the following error message:
js.Global.Get undefined (type func() "syscall/js".Value has no field or method Get)

After running the following command, where surround.go is a file on my computer.
GOOS=linux gopherjs build surround.go

I tried using "js.Global()." with parentheses instead of "js.Global.", and that works for me.

Version numbers:
% gopherjs version
GopherJS 1.17.1+go1.17.3
.

**Comment by nevkontakte** [comment]
Hi! Please note that there are two "js" packages: `syscall/js` from the standard library and `github.com/gopherjs/gopherjs/js` provided by GopherJS itself. The two packages are similar, but not interchangeable and examples in the README use `github.com/gopherjs/gopherjs/js`. GopherJS implements both to facilitate compatibility with the code written for Go WebAssembly.
