### ISSUE TITLE
bug: $module is not defined in browser

### ISSUE THREAD

**Issue by EwenQuim** [gopherjs/gopherjs#1094]
This one is a bit disturbing. I have got a very simple script that works perfectly on node but not on the browser.

```go
package main

import (
	"crypto/ed25519"
	"encoding/base64"

	"github.com/gopherjs/gopherjs/js"
)

func SignMessage(secBase64, pubBase64, displayedName, message, messageId string) string {
	sec, err := base64.URLEncoding.DecodeString(secBase64)
	if err != nil || len(sec) != ed25519.PrivateKeySize {
		return ""
	}
	pub, err := base64.URLEncoding.DecodeString(pubBase64)
	if err != nil {
		return ""
	}
	msgToSign := append([]byte(message), pub...)
	msgToSign = append(msgToSign, []byte(displayedName)...)
	msgToSign = append(msgToSign, []byte(messageId)...)
	signature := ed25519.Sign(sec, msgToSign)
	return base64.URLEncoding.EncodeToString(signature)
}

func main() {
	js.Module.Get("exports").Set("SignMessage", SignMessage)
}
```

You can easily reproduce it with `gopherjs build -o lib.js` and this small html file:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <script src="./lib.js"></script>
</head>
<body>
  Test
  <script>
    console.log(SignMessage("test", "test", "test", "test", ""));
  </script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/46993939/147396230-0783c676-df11-4ded-8191-8ae681ce8ea2.png)

**Comment by nevkontakte** [comment]
Hi @EwenQuim, this is working as intended.

`js.Module` compiles into `module` variable. It is only available in runtimes that natively support CommonJS module spec, which [Node does support](https://nodejs.org/api/modules.html). However, browsers do not support CommonJS, so this variable is undefined there. You can probably make it work if you pass GopherJS output through a bundler like webpack, which emulates CommonJS environment.

I will update `js.Module` doc comment to be more explicit about this.

**Comment by EwenQuim** [comment]
Thank you for your quick answer, I'm on the right tracks now.
