### ISSUE TITLE
Simple example tutorial

### ISSUE THREAD

**Issue by vkuznet** [gopherjs/gopherjs#1099]
Hi,
I'm new to the library and would like to explore it. But I find it very difficult to find out very basic example how to write Go code for JS functions I may need to use in HTML. For example, if I have this html:
```
<input type="password" id="password" placeholder="password" onchange="funcA()">
<button type="button" class="button" onclick="funcB()">Action</button>
```
how I should write the go code for it? There is a `main` function which I would assume should define everything. Where `funcA` and `funcB` should be defined and what the purpose of `main` in this sense would be? I think new users will benefit tremendously from such simple example.

**Comment by nevkontakte** [comment]
Hi @vkuznet! There are a couple of ways to do it.

If you want to export a Go function into the global namespace, you can do something like this:

```
func funcA() { /* do something */ }

func main() {
  js.Global.Set("funcA", funcA)
}
```

However, if you are looking to set event handlers specifically (as you example implies), there is a cleaner approach:
https://siongui.github.io/2016/01/11/gopherjs-dom-example-event-binding-addEventListener/

Good beginner documentation is, unfortunately, something that GopherJS is currently missing. If you could consider contributing some based on your experience it would be greatly appreciated!
