### ISSUE TITLE
error during build: Error: 'xxx' is not exported by src/utils/xxx.js.js, imported by src/...

### ISSUE THREAD

**Issue by iwctwbai** [gopherjs/gopherjs#1109]
An error occurred when use ``` vite build --mode production ```

```
error during build:
Error: 'gotools' is not exported by src/utils/gotools.js.js, imported by src/....vue
    at error (...node_modules/rollup/dist/shared/rollup.js:159:30)
    at Module.error (...node_modules/rollup/dist/shared/rollup.js:12437:16)
    at Module.traceVariable (...node_modules/rollup/dist/shared/rollup.js:12795:29)
    at ModuleScope.findVariable (...node_modules/rollup/dist/shared/rollup.js:11416:39)
    at FunctionScope.findVariable (...node_modules/rollup/dist/shared/rollup.js:6392:38)
    at ChildScope.findVariable (...node_modules/rollup/dist/shared/rollup.js:6392:38)
    at Identifier.bind (...node_modules/rollup/dist/shared/rollup.js:7681:40)
    at CallExpression.bind (...node_modules/rollup/dist/shared/rollup.js:5281:23)
    at CallExpression.bind (...node_modules/rollup/dist/shared/rollup.js:8863:15)
    at VariableDeclarator.bind (...node_modules/rollup/dist/shared/rollup.js:5281:23)
error Command failed with exit code 1.

```

**Comment by nevkontakte** [comment]
Hi @iwctwbai, can you provide [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and explain how it is related to GopherJS? From the error message you've provided it isn't clear that this is a problem with GopherJS, rather than your build setup.

**Comment by iwctwbai** [comment]
@nevkontakte 
I use vite to build the project, the reason is that vite do not support bare module imports(https://vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling)

One of the solutions provided by vite is via the default export option(https://github.com/vitejs/vite/issues/813#issuecomment-691799104)

Is it possible to consider providing configuration default export options

**Comment by iwctwbai** [comment]
Another problem I found is that the exported js file cannot pass the vite syntax check

even without -m compression

**Comment by iwctwbai** [comment]
method like he said https://github.com/vitejs/vite/issues/813#issuecomment-691799104
gopherjs gives a lot of errors

golang code, and I am using the latest version of gopherjs
```
package main

import (
	"github.com/gopherjs/gopherjs/js"
	"go/format"
)

//go:generate go env -w GO111MODULE=on
//go:generate go mod tidy
//go:generate go mod download

type GoFmt struct {
	Success bool
	Data    string
}

func Format(str string) interface{} {
	res, err := format.Source([]byte(str))
	if err != nil {
		return &GoFmt{
			Success: false,
			Data:    err.Error(),
		}
	}
	return string(res)
}

func main() {
	js.Module.Get("exports").Set("gofmt", Format)
}

```

**Comment by nevkontakte** [comment]
Thanks for the additional details. Unfortunately, I'm unfamiliar with vitejs, and I haven't heard about anyone using it with GopherJS before, so we are in uncharted waters here. At the moment GopherJS integration with ES6/CommonJS module system is largely unexplored. The example code you provided looks correct to me, so the issue is probably at the interface between GopherJS and the rest of our toolchain.

Could you create a small, separate git repo with the GopherJS code and vite configuration similar to what you are using and provide the exact sequence of commands for me to reproduce the errors? I'm not an expert on JS tooling (my interest in GopherJS was largely motivated but not wanting to deal with it, heh), but I would try to give it a look on the weekend.

**Comment by iwctwbai** [comment]
Thank you for your contribution. I'm not very familiar with Vite either, but I need GopherJS so much that I dropped Vite and continued to use WebPack

**Comment by nevkontakte** [comment]
Sorry I wasn't able to provide more help. For what it's worth, improving integration with the broader JavaScript ecosystem is something I consider valuable in the long term. However, in the short term neither me or @flimzy have sufficient time to work on this. If you might be interested in contributing here, we'll be happy to provide advice and review.

**Comment by iwctwbai** [comment]
It's very kind of you. Thank you very much for your help

**Comment by iwctwbai** [comment]
I see. Thank you very much for your enthusiasm
