### ISSUE TITLE
Possible to convert js code to golang code?

### ISSUE THREAD

**Issue by zerobuilder** [gopherjs/gopherjs#1124]
Possible to make such a function? Input theJS file, Output the Golang code.not on the command line.
just like this [Chinese Fiddler extension](https://dl.pconline.com.cn/download/2820922.html ) ,but generate golang code instead of convert js to E language

**Comment by nevkontakte** [comment]
I don't see why it wouldn't be possible in theory, but I'm not aware of such a tool, and GopherJS isn't one. As such, I'll mark this issue as resolved.

That said, depending on what you are trying to achieve there may be other solutions to your problem. For example, there are several JavaScript interpreters written in Go, which could allow you to execute JavaScript code in your Go program. It's not exactly what you are asking about but the result could be very similar. I'd recommend you describe your higher-level problem and you may get a better suggestion. GopherJS issues isn't a general-purpose discussion forum and has very limited audience, but you could join [Gophers Slack](https://invite.slack.golangbridge.org) or any other Go community to ask there 🙂 Folks in those places tend to be a diverse and friendly bunch.
