### ISSUE TITLE
Hello sir, would you like some command line history?

### ISSUE THREAD

**Issue by nugaon** [gopherjs/gopherjs#1138]
1989  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
 1990  sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
 1991  go version
 1992  go get -u github.com/gopherjs/gopherjs
 1993  go install -u github.com/gopherjs/gopherjs
 1994  go install github.com/gopherjs/gopherjs
 1995  go install github.com/gopherjs/gopherjs@latest
 1996  gopherjs --help
 1997  exit
 1998  gopherjs 
 1999  go env
 2000  go env GOROOT
 2001  export GOPHERJS_GOROOT="$(go1.18.1 env GOROOT)"
 2002  export GOPHERJS_GOROOT="$(go env GOROOT)"
 2003  gopherjs
 2004  vi .profile 
 2005  go env GOROOT
 2006  goroot
 2007  go env
 2008  cd /usr/local/go
 2009  ls
 2010  cd pkg/
 2011  ls
 2012  sl
 2013  ls
 2014  find / -name gopherjs
 2015  sudo find / -name gopherjs
 2016  /home/nugaon/go/bin/gopherjs --help
 2017  ls
 2018  cd ..
 2019  cd
 2020  cd swarm/bee
 2021  ls
 2022  git status
 2023  git pull origin
 2024  git log
 2025  git pull origin
 2026  cat Makefile 
 2027  cat Makefile | grep binary
 2028  cat Makefile | grep build
 2029  grep --help
 2030  cat Makefile | grep build -A 3
 2031  cat Makefile | grep build -B 3
 2032  cat Makefile | grep build -A 3
 2033  /home/nugaon/go/bin/
 2034  cd /home/nugaon/go/bin/
 2035  ls
 2036  pwd
 2037  cd ~/swarm/bee
 2038  /home/nugaon/go/bin/gopherjs build ./cmd/bee
 2039  history

**Comment by flimzy** [comment]
Closing, as this appears to have been opened by accident. If this was intentional, please edit to clarify and re-open.
