### ISSUE TITLE
use js dependencies in run command

### ISSUE THREAD

**Issue by clsx524** [gopherjs/gopherjs#1144]
Hello, I am trying to use d3 library with gopherjs. I imported d3 with `var d3Root = js.Global.Get("d3")`.
It works fine with browser with `<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>` in index.html, however when I run `gopherjs run main.go`, it cannot initialize d3Root correctly. I have installed d3 with `npm install -g d3`.
How to properly install and import js dependencies with `gopherjs run`?

**Comment by nevkontakte** [comment]
Unfortunately, there is no transparent integration with npm modules at the moment, you would need to use a bundler like webpack to make it work. Also note that `gopherjs run` executes your code with Node.js, not in a browser, not sure it makes sense for d3.

That said, you can [bundle additional JS sources](https://github.com/gopherjs/gopherjs/wiki/Bundle-additional-JavaScript-with-Go-packages) with your GopherJS package. There also seems to be a [bindings library for d3](https://github.com/iansmith/d3) specifically, but I'm not sure how up to date it is.

**Comment by clsx524** [comment]
Thanks. 

In order to use d3 in backend, one way is to use jsdom. I followed the guides to bundle it as additional JS resources and the build went fine. However, when I run it, it still complains about not able to find jsdom. Do you have idea if jsdom is compatible with gopherjs?

```
jsdom := js.Global.Get("jsdom")
```
The jsdom variable is undefined.

**Comment by nevkontakte** [comment]
The .inc.js mechanism is pretty straightforward: it takes the script content and invokes it at the time when a Go package is being initalized, more or less like this: `(function() { /* bundled js code here */ }).call($global)`. There is no special requirement for the bundled code to be compatible with gopherjs, it just gets executed in what is a close approximation of global context. If it defines global variables, they will be visible to any code, including one produced by GopherJS.

So the question is, does the jsdom library actually define the global variable you are trying to access? I haven't tried using jsdom myself, but I see no reason why it shouldn't work in general.

**Comment by clsx524** [comment]
Got it. the working js code is like this
```
import jsdom from "jsdom";
const { JSDOM } = jsdom;
```
So I translate it into 
```
jsdom := js.Global.Get("jsdom")
dom := jsdom.Get("JSDOM")
```
JSDOM is exported in jsdom api.js [here](https://github.com/jsdom/jsdom/blob/master/lib/api.js#L327).

Besides, not relevant to this, I also tried go-js-dom but it failed at `js.Global.Get("node")`. should I include this node from somewhere or it's builtin?

**Comment by nevkontakte** [comment]
Can a repository with your exact setup, so that I could take a look?

I would note that

```go
jsdom := js.Global.Get("jsdom")
dom := jsdom.Get("JSDOM")
```

is semantically equivalent to

```js
var jsdom = window.jsdom;
dom := jsdom.DOM;
```

not to

```js
import jsdom from "jsdom";
const { JSDOM } = jsdom;
```
