### ISSUE TITLE
GopherJS 1.17.2+go1.17.9 requires a Go 1.17.x distribution, but found version go1.18.6

### ISSUE THREAD

**Issue by canercetin-randomguy** [gopherjs/gopherjs#1165]
How can I install the latest 1.18 GopherJS?
I installed 1.18.6 version of Go specifically according to readme,  installed GopherJS with
```
go get github.com/gopherjs/gopherjs@latest
```
, but 
```
gopherjs version
``` 
prints:
GopherJS 1.17.2+go1.17.9

help?

**Comment by canercetin-randomguy** [comment]
```
go get -u github.com/gopherjs/gopherjs@latest
```
returns GopherJS 1.17.2+go1.17.9 version again.
```
go get github.com/gopherjs/gopherjs@1.18.0-beta1
```
returns
```
go: github.com/gopherjs/gopherjs@1.18.0-beta1: invalid version: unknown revision 1.18.0-beta1
```
...what?

**Comment by canercetin-randomguy** [comment]
did
```
wget https://github.com/gopherjs/gopherjs/archive/refs/tags/v1.18.0-beta1+go1.18.5.zip
```
unzipped to folder, launched
```
go install
```
and it works but christ, you are writing Go 1.18+ is required and if you are not installing from source you will never run it with Go 1.18. ask yourself, how many of the people are installing packages from source?

**Comment by canercetin-randomguy** [comment]
Reopening to draw attention.

**Comment by flimzy** [comment]
This is behaving as intended. GopherJS 1.18 is incomplete, as it does not yet support generics, so it has been released as a beta version. This is why it is not picked up by `@latest`.

This is explained in the release notes: https://github.com/gopherjs/gopherjs/releases/tag/v1.18.0-beta1%2Bgo1.18.5

We are making progress on adding generics support, so hope it will not be too long before this is no longer an issue.

**Comment by nevkontakte** [comment]
@canercetin-randomguy `go get github.com/gopherjs/gopherjs@1.18.0-beta1` didn't work because there is no `1.18.0-beta1` tag in this repository. There is, however, `v1.18.0-beta1` tag (notice the "v" in the beginning). So `go install github.com/gopherjs/gopherjs@v1.18.0-beta1` works the way you would expect.
