### ISSUE TITLE
readme version mismatch, easy fix

### ISSUE THREAD

**Issue by nfstein** [gopherjs/gopherjs#1169]
The [readme instructions](https://github.com/gopherjs/gopherjs#installation-and-usage) state to install gopherjs@latest which is for the 1.17 release but the go installations below are for the 1.18 release. When I followed the instructions locally, gopherjs was broken until I switched my gopherjs installation to v1.18.0-beta1+go1.18.5.

**Comment by flimzy** [comment]
The documentation still refers to 1.17 intentionally, because 1.18 is still in beta.

**Comment by nevkontakte** [comment]
I think this has confused several people already, so we should just update the README instructions for 1.18-beta1, since this is what most people want anyway.
