### ISSUE TITLE
Proposal: Move all Circle CI configuration to run on GitHub Actions instead

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#1214]
**Background:** When the GopherJS project began, GitHub Actions didn't exist, so it was appropriate to select a third-party tool. CircleCI was selected, and it has served us well.

In the years since that decision was made, GitHub Actions has been released, and matured significantly. In September of 2021, we began using GitHub Actions for the task of reporting build size on PRs.  Then more recently, I added another GitHub Action to run `golangci-lint`, which was approved and merged without any discussion about GHA vs CircleCI.

This means that as of today, we have some configuration for GitHub Actions, and some for CircleCI.  This _works_, but isn't perfectly ideal, IMO, and it would be better to standardize on one or the other.

As I see it, the main case to be made for CircleCI is that most of our configuration at the moment lives there, so would be the smaller delta.

The main case for GitHub Actions is that it would require fewer things to maintain.

**Proposal:**

1. I propose that effective immediately, we officially adopt what appears to be our de-facto standard, that any new automation is added to GitHub Actions, rather than CircleCI
2. We state as an eventual goal the retiring of CircleCI, and moving everything that exists there, into GitHub Actions over time.

I don't see any particular urgency to this task, but as we occasionally have requests from would-be voluteers for tasks they could help with, this might be a good candidate. So I bring this proposal forward for discussion.

**Comment by nevkontakte** [comment]
I agree with the general sentiment. I think the only feature github actions doesn't support (and why I didn't actively attempt to move off circleci so far) is automated test splitting. CircleCI can use test timing information from previous runs to evenly distribute them into 4 parallel shards, which we use to run standard library tests. I'm not sure what's the best way to substitute this on GHA would be.

Other than that, a few potential considerations come to mind:

 - Does GitHub actions provide us enough open source credits to run our relatively expensive test suite?
 - Do they provide Windows and Mac machines?
 - How does performance compare?

**Comment by flimzy** [comment]
> * Does GitHub actions provide us enough open source credits to run our relatively expensive test suite?

Good question. I don't know the answer.

> * Do they provide Windows and Mac machines?
Yes. See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

> * How does performance compare?

Also don't know.

**Comment by nevkontakte** [comment]
https://github.com/gopherjs/gopherjs/pull/1327 made the tests complete quicker, so the non-crypto shard passes in 10m, and crypto under 5m. I think this is good enough for the time being and we can reconsider test splitting if the run time starts creeping back up again.

Thanks @grantnelson-wf!
