### ISSUE TITLE
Gopherjs returns an error that says no mtime found for source file

### ISSUE THREAD

**Issue by improvisor40** [gopherjs/gopherjs#1225]
When I try to build with gopherjs it returns an error that states "No mtime found for source file "main.go"  assuming time.Now()", what could cause I really want to embark into a project and I think this is restrictive please help!.

**Comment by nevkontakte** [comment]
This is just a warning and mostly indicates that build cache won't work for this build as effectively as it normally would. The compilation should complete successfully nevertheless. We would need to know more about your setup to help you more. Which OS are you using? Which file system? Which go and gopherjs versions?

**Comment by improvisor40** [comment]
Thanks, I'm using debian 10, and a virtual linux file system on android (with userland). With go1.18.5 as my golang version! And gopherjs version is also GopherJS 1.18.0-beta3+go1.18.10 (this is what it showed when I write "gopherjs version")
Thanks again.

**Comment by nevkontakte** [comment]
Well, this probably means your file system doesn't support mtime. Like I said, this shouldn't prevent the compiler from doing its work, even if it will be slower for you. If that's a problem, consider using a file system that has mtime enabled.
