### ISSUE TITLE
Attempting to import net on Windows fails

### ISSUE THREAD

**Issue by nightexcessive** [gopherjs/gopherjs#123]
Attempting to import the `net` package and build on Windows causes a panic, as net.init() attempts to make syscalls.

Code to reproduce (needs to be built on Windows using `gopherjs build`):
```go
    package main

    import (
    	_ "net"
    )
    
    func main() {
    	println("You should never see this on Windows, but it appears to work on the playground")
    }
```

The given code works on the playground, but will immediately panic when built on Windows.

**Comment by neelance** [comment]
Fixed. Thanks for reporting this issue!
