### ISSUE TITLE
build error M:/work/tool/go1.23.1.windows-amd64/bin/go.exe test -v [M:/work/code/go/src/github.com/visualfc/goembed/parser] # github.com/visualfc/goembed/parser.test link: github.com/visualfc/goembed/parser: invalid reference to go/build.parseGoEmbed FAIL	github.com/visualfc/goembed/parser [build failed]

### ISSUE THREAD

**Issue by epowsal** [gopherjs/gopherjs#1346]
M:/work/tool/go1.23.1.windows-amd64/bin/go.exe test -v [M:/work/code/go/src/github.com/visualfc/goembed/parser]
# github.com/visualfc/goembed/parser.test
link: github.com/visualfc/goembed/parser: invalid reference to go/build.parseGoEmbed
FAIL	github.com/visualfc/goembed/parser [build failed]

**Comment by flimzy** [comment]
It's unclear what issue you're having, or whether it's related to GopherJS. Can you please provide some additional information, including which version of GopherJS you're using, the code you're trying to compile, and the exact steps necessary to reproduce the problem?

**Comment by epowsal** [comment]
last version. go 1.19 no build error.

**Comment by flimzy** [comment]
I'm sorry, it's still not at all clear what you're asking.

The command you pasted into the title and original description appear to be unrelated to GopherJS.  I'm going to close this, but if you can file a complete report, along with all the information I asked for above, please feel free to re-open.

**Comment by ianvernon** [comment]
I'd like for this to be re-opened. I'm experiencing the same issue using golang 1.23.3:

```
go install github.com/gopherjs/gopherjs@v1.19.0-beta1
# github.com/gopherjs/gopherjs
link: github.com/visualfc/goembed/parser: invalid reference to go/build.parseGoEmbed
```

**Comment by flimzy** [comment]
@ianvernon: I think it would be good to open a new issue for that, with a clear explanation of the problem you're experiencing.
