### ISSUE TITLE
use of "netgo" build tag

### ISSUE THREAD

**Issue by extemporalgenome** [gopherjs/gopherjs#143]
I've seen at least one gopherjs binding that uses the `netgo` build tag to mean "this is for gopherjs". `netgo` is also used by the gc compiler suite to mean "don't use libc based networking" (mostly for DNS resolution via LDAP and such). The gopherjs build code sets the netgo tag, but as far as I can tell, this is coincidental, and semantically conflicting to the official toolchain's usage, since the official toolchain's use is meaningless outside of the context of building native code.

If gopherjs' use of it is indeed coincidental, perhaps a more pointed tag, like "gopherjs" would be appropriate.

**Comment by ajhager** [comment]
A long time ago I went searching for for the correct tag, and I thought I found 'netgo'. Neither 'gopherjs' nor 'js' seemed to work at the time. If it is something else, I will update my packages.

**Comment by shurcooL** [comment]
There was a time before `js` and/or `gopherjs` tags were introduced, but eventually things settled on just `js` (@neelance can confirm; it's used inside gopherjs' own source code).

**Comment by extemporalgenome** [comment]
If there is not an official build tag, perhaps the README should at least document that much; if there is one, it should be prominently documented.

**Comment by neelance** [comment]
The `GOARCH` of GopherJS is `js`. You can use it as a build flag: `// +build js`. The `netgo` tag is set so GopherJS can compile the `net` package, just as @dominikh said. I'll try to find a proper place for documentation.

**Comment by neelance** [comment]
Are there any other opinions on documenting the build flag? I'm not sure where to put it. How important is it?

**Comment by shurcooL** [comment]
Either the README or a linked wiki page. I think most people will have this question, so it's better if they see the answer without having to guess/investigate on their own.

**Comment by dominikh** [comment]
It could fit nicely in a "What /architecture/ does GopherJS implement" like section, explaining a) the GOARCH value b) the size of int, uintptr etc

**Comment by slimsag** [comment]
> It could fit nicely in a "What /architecture/ does GopherJS implement" like section, explaining a) the GOARCH value b) the size of int, uintptr etc

I highly agree with this!
