### ISSUE TITLE
variable arithmetic misinterpreted as a constant operation

### ISSUE THREAD

**Issue by extemporalgenome** [gopherjs/gopherjs#144]
Given the input code:

```go
package main

import (
	"fmt"
	"math"
)

func main() {
	var x uint64 = math.MaxUint64
	fmt.Println(x, x-1, x+1)
}
```

The GopherJS playground reports:
> prog.go:9:17: math.MaxUint64 (untyped int constant -1) overflows uint64 

While the gc toolchain compiles successfully and outputs the expected:
> 18446744073709551615 18446744073709551614 0

**Comment by neelance** [comment]
Thanks for reporting this bug. The constant `math.MaxUint64` was the problem, it became `-1` due to a bug in my gc data exporter.
