### ISSUE TITLE
Feature request: js.Null

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#145]
IIUC, the initial value of js.Object and null in JavaScript are different. I found out that I need JavaScript null instead of nil when, for example, calling gl.bindFramebuffer whose second argument must be Framebuffer or null (not js.Object nil).

```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

func main() {
	var null1 js.Object
	print(null1) // Object {$key: function}
	var null2 = js.Global.Call("eval", "null")
	print(null2) // null
}
```

Now that there seems no easy way to get JavaScript null with GopherJS. can we have new API to get such null, or is there anything I missed?

**Comment by shurcooL** [comment]
> for example, calling gl.bindFramebuffer whose second argument must be Framebuffer or null (not js.Object nil).

Have you tried it? What happens if you give it js.Object nil?

**Comment by dominikh** [comment]
Passing an untyped nil should work, as that gets translated to null.

**Comment by hajimehoshi** [comment]
Thanks, but now github.com/gopherjs/webgl can't be compiled.

**Comment by shurcooL** [comment]
> Thanks, but now github.com/gopherjs/webgl can't be compiled.

No problem, I'll fix it.

**Comment by shurcooL** [comment]
`honnef.co/go/js/dom` needs to be updated too. /cc @dominikh

**Comment by hajimehoshi** [comment]
> No problem, I'll fix it.

Great. Are you working on it now? If no, I'll fix this.

**Comment by shurcooL** [comment]
I am, but I can only make a PR, I don't have push rights for https://github.com/gopherjs/webgl. /cc @ajhager

**Comment by shurcooL** [comment]
By the way, to update any package automatically (ala `go fix`), you can do:

```
gofmt -w -r 'x.IsNull() -> x == nil' *.go 
gofmt -w -r 'x.IsUndefined() -> x == js.Undefined' *.go
```

**Comment by neelance** [comment]
Merged https://github.com/gopherjs/webgl/pull/8
