### ISSUE TITLE
Require modules?

### ISSUE THREAD

**Issue by JohannWeging** [gopherjs/gopherjs#146]
As I mentioned in this post: https://github.com/gopherjs/gopherjs/issues/56#issuecomment-68377715. I'm trying to get atom programmable via go.
I need to require the atom package: https://github.com/atom/atom/blob/master/exports/atom.coffee.

Is there a way to get gopherjs to produce the line:
```js
atom = require('atom')
```
or set the requirement by hand? I don't want to do the path resolution by hand.

**Comment by shurcooL** [comment]
I'm not sure, but would `atom := js.Global.Call("require", "atom")` work?

**Comment by JohannWeging** [comment]
Looks like it worked. Now I feel stupid, didn't thought of it.
