### ISSUE TITLE
Different results in Go / GopherJS when casting from one type to another

### ISSUE THREAD

**Issue by flyth** [gopherjs/gopherjs#147]
When casting like below, GopherJS seems to create a new copy of the object for each cast instead of reusing the old one.

```
package main

type Foo struct {
	Value int
}

type Bar Foo

func main() {
	x := &Foo{Value: 1}
	y := (*Bar)(x)
	y.Value = 2
	z := (*Foo)(y)
	z.Value = 3
	print(x == z)
	print(x.Value, y.Value, z.Value)
}
```

I will take a closer look as well but maybe someone already knows how to implement a solution after reading this... :)

Thanks!

**Comment by shurcooL** [comment]
Nice find!

**Comment by neelance** [comment]
Yes, I know about this issue. I wonder why this is even allowed by the Go spec. Are there valid use cases for this? It clashes with the way how GopherJS works internally, but there might be some tricky solution involving `Object.defineProperty` to create a proxy object that still reads and writes the fields of the original object.

**Comment by flyth** [comment]
I've run across this in the go-capnproto library where they compared two pointers like in the example above.

The main problem is that the issue wasn't easy to spot, because no errors got thrown (in my case the output of the library was simply wrong since it created new buffers all the time).

That Object.defineProperty workaround wouldn't fix the pointer comparison, right? Do you have any idea on how to fix that one as well?

Thanks for your help :)

**Comment by neelance** [comment]
I'm sorry that you had the trouble. I was hoping that this would not affect real world use cases, at least it does not in the core packages. But it seems like I have to take care of it now.

Luckily you can't compare `x` to `y`. For `x == z` we would have to make sure that `z := (*Foo)(y)` does not create another proxy, but instead reuses the original `x`.

**Comment by dominikh** [comment]
> I wonder why this is even allowed by the Go spec. Are there valid use cases for this?

I've used and seen it used several times in the past, and it's a nice way of swapping out method sets for the same underlying data. 

It's the one instance where Go's conversions are true casts.

**Comment by flyth** [comment]
Wow, that was fast - thank you very much for your efforts! :)

However, there still seems to be an issue with functions defined for those structs:

```
package main

type Foo struct {
	Value int
}

type Bar Foo

func (b *Foo) Demo() {
	print("FooCall")
}

func (b *Bar) Demo() {
	print("BarCall")
}

func main() {
	x := &Foo{Value: 1}
	y := (*Bar)(x)
	y.Value = 2
	z := (*Foo)(y)
	z.Value = 3
	print(x == z)
	print(x.Value, y.Value, z.Value)
	x.Demo()
	y.Demo()
	z.Demo()
}
```

y.Demo() fails in that case.

**Comment by flyth** [comment]
That did it ;)
Thanks again for your ultrafast responses!

**Comment by neelance** [comment]
No problem. ;)
