### ISSUE TITLE
'gopherjs test' doesn't recognize import path '.'

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#148]
`gopherjs test` fails with this code:

```go
package foo

import (
    . "."
    "testing"
)

// ...
```

```
import ".": import relative to unknown directory 
```

`. "."` is a useful idiom for testing, so I wish it could be available.

**Comment by shurcooL** [comment]
I think it's related to this line (among others),

[gopherjs/build/build.go](https://github.com/gopherjs/gopherjs/blob/d30b2ca127879c603c5a8a6d02abb92a51b99e3b/build/build.go#L60)

Second parameter, `srcDir`, needs to be set to some folder because [`(*Context) Import`](http://godoc.org/go/build#Context.Import) interprets local import paths relative to the srcDir directory.

**Comment by neelance** [comment]
Would you be really sad if I don't add this? I just tried and it quickly became a quite ugly change.

Relative import paths are not very common, there is even an issue to remove them: https://github.com/golang/go/issues/6147
The Go spec says `The interpretation of the ImportPath is implementation-dependent but it is typically a substring of the full file name of the compiled package and may be relative to a repository of installed packages.` So technically GopherJS does not violate the spec.

**Comment by shurcooL** [comment]
I think it's reasonable to make this a lower priority if it's turning out to be an unclean fix.

**Comment by hajimehoshi** [comment]
> Would you be really sad if I don't add this? 

No. I didn't know that Go compiler technically doesn't have to interpret relative import paths. Please feel fee to close this ticket as "won't fix".

**Comment by shurcooL** [comment]
Or maybe label as `priority-later`, similar to https://github.com/golang/go/labels/priority-later.

**Comment by neelance** [comment]
Marked as "wontfix" for now. I will reconsider if there is popular demand.
