### ISSUE TITLE
Mysterious panic happens when js.Object is keys of a map

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#155]
```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

type Key js.Object

func main() {
	one := js.Global.Call("eval", "1")
	x := map[Key]string{}
	x[one] = "foo"
	println(x)
}
```

```
panic: undefined is not a function 
```

I understand that js.Object can't be keys of a map, but it'd be better if we had a kinder message.

**Comment by neelance** [comment]
Checking that at runtime would degrade performance of every map access. But what I could do is detect that `js.Object` is used as a key in line `x[one] = "foo"` and throw an error at compile time.

**Comment by hajimehoshi** [comment]
Thank you for considering it. Checking that at compile time seems enough.

**Comment by hajimehoshi** [comment]
Thanks!
