### ISSUE TITLE
Implementing Go interfaces in Javascript

### ISSUE THREAD

**Issue by tomlinford** [gopherjs/gopherjs#158]
With the following code:

`lib.go`:
```Go
type Printer interface {
	Print(string)
}

func PrintTo(printer Printer, str string) {
	printer.Print(str)
}

func main() {
	js.Global.Set("lib", map[string]interface{}{
		"PrintTo": PrintTo,
	})
}
```

`js.js`:
```Javascript
lib.PrintTo({
    Print: function(str) {
        console.log(str);
    }
}, "Hello, world");
```

It seems like this code should work fine because the Javascript object is implementing the `Printer` interface. However, running this yields (on the `printer.Print(str)` line):
```
Uncaught TypeError: undefined is not a function
```

Adding a ` || methods.length > 0` at the end of the if clause here https://github.com/gopherjs/gopherjs/blob/master/compiler/prelude/jsmapping.go#L217 fixed the problem and continue to pass the tests. My thought with that fix was that while `interface{}` gets used an `any` of sorts, it makes sense to try and do some typecasting. But if it's an interface that's just going to be interacted with via the interface methods, we might as well use the methods directly.

**Comment by neelance** [comment]
Using the methods directly is not a good idea, since the parameters and return values need proper externalisation and internalisation. Also, a JS object does not fulfil the characteristics that an internal Go interface value needs. Your fix might work in this case, but it will break in a lot of other cases. It is not possible to implement a Go interface with a JS object. What is your use case? Maybe we can find a good alternative together?

**Comment by hajimehoshi** [comment]
Ugh, the latest change prevents me from using `type Foo js.Object`. Now isn't it possible?

**Comment by hajimehoshi** [comment]
Sorry but the latest change I meant was not related to this issue.

**Comment by neelance** [comment]
Yes, `type Foo js.Object` is not useful any more. Do you need it?

**Comment by hajimehoshi** [comment]
I've already updated them to `type Foo struct { js.Object }` so I don't need it any longer.

**Comment by neelance** [comment]
What do you use it for?

**Comment by tomlinford** [comment]
Ah, that's a good point -- I guess my example was a little too simplistic.

Here's a sample use case. Suppose we want to make a go library that checks to see if a particular version of go is out yet. We then want to combine this with a javascript library to show something fancy if the requested version is out. Our go code might look something like this:
```Go
package main

import (
	"net/http"

	"github.com/gopherjs/gopherjs/js"

	"honnef.co/go/js/xhr"
)

type OutYetListener interface {
    OnResult (bool)
}

func SubscribeOutYet(listener OutYetListener, version string) {
    go subscribeOutYet(listener, version)
}

func subscribeOutYet(listener OutYetListener, version string) {
    url := "https://code.google.com/p/go/source/detail?r=go" + version
    request := xhr.NewRequest("HEAD", url)
    if request.Send(nil) != nil {
        return
    }
    listener.OnResult(request.Status == http.StatusOK)
}

func main() {
    js.Global.Set("lib", map[string]interface{}{
        "SubscribeOutYet": SubscribeOutYet,
    })
}
```

So I guess it's sort of like doing Javascript callbacks. Perhaps the correct approach is to write some `go generate`d code that acts as a glue that lets Javascript interface with Go interfaces with callbacks?

**Comment by neelance** [comment]
`func SubscribeOutYet(listener func(bool), version string)` should work fine. In this case, GopherJS can take care of properly turning the JavaScript function into a Go func.

**Comment by tomlinford** [comment]
Hm yeah, I think this problem is just going to have to get solved with autogenerated code. I can think of two approaches. (Examples are from hello world above).

The first is OO-styled:
```Go
type nativePrinter struct {
	js.Object
}

func (p *nativePrinter) Print(str string) {
	p.Call("Print", str)
}

func NewPrinter(obj js.Object) Printer {
	return &nativePrinter{obj}
}

func main() {
	...
	js.Global.Set("bind", map[string]interface{}{
		"Printer": NewPrinter, // nice that we can call this whatever we want!
	})
}
```

```Javascript
lib.PrintTo(bind.Printer({
    Print: function(str) {
        console.log(str);
    }
}), "Hello, world");
```

The second is more traditional JS callback-ey:
```Go
type nativePrinter struct {
	print js.Object
}

func (p *nativePrinter) Print(str string) {
	p.print.Invoke(str)
}

func NewPrinter(obj js.Object) Printer {
	return &nativePrinter{obj}
}
```

```Javascript
lib.PrintTo(bind.Printer(function(str) {
    console.log(str);
}), "Hello, world");
```

Anyways, going to close this. Thanks for your prompt replies!
