### ISSUE TITLE
Question on js.Any/interface{} conversion and reflect.ValueOf/reflect.Call.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#160]
Hi Richard,

I have a utility helper `Wrap` over at [`github.com/shurcooL/go/gopherjs_http/jsutil`](https://github.com/shurcooL/go/blob/15812aa0f6e7280f76a8036c5dbfacae6cf198d4/gopherjs_http/jsutil/jsutil.go#L12-L52). It's somewhat rarely used, but still useful in the context of using gopherjs with `html/template` templates.

It allows wrapping a `func` that takes specific types such as JSON structs, `dom` types, and generic `js.Object`s and takes care of conversion from all `js.Object` parameters. It makes the end result code much cleaner as you don't need to manually convert those types. It was discussed and implemented in https://github.com/gopherjs/gopherjs/issues/93.

After the recent `js.Any`/`interface{}` change in 1dae489721d66fc0b05af4976b0ef45cbd564c07, I am getting an error in the following line:

```
in[i] = reflect.ValueOf(args[i])
```

```
jsutil.go:26:29: can't convert js.Object/js.Any to other interface type
```

The problem is that `args[i]` is of type `js.Object`, but `reflect.ValueOf` expects an `interface{}`.

The goal of the code is to pass `js.Object` parameters through unmodified, and only perform some type conversion for other types. But I use `reflect.ValueOf` so that I can do a `reflect.Call`.

I'm still wrapping my head around `js.Any` and its implications, so I may be missing something obvious, but I don't see a way of making it work so far. Is it possible to change my code to make it work without changing GopherJS? If not, how invasive would GopherJS changes need to be? I may be willing to give this utility up if there's no good way of making it work, but it did work really well previously.

**Comment by shurcooL** [comment]
Okay, I _think_ I may see a way of making it work without GopherJS changes, but I'm not sure if it's a good way. It may work to introduce a (yet another) wrapper for `js.Object`, just so that `reflect.ValueOf` works on it:

```Go
in[i] = reflect.ValueOf(wrapObject(args[i])) // This will work, because it avoids the js.Object to interface{} conversion.

// This type may need to be made public and used by the 
type object struct {
	js.Object
}

// Wrap js.Object so that it can be used as a parameter to reflect.ValueOf.
func wrapObject(o js.Object) object {
	return object{Object: o}
}
```

Would you recommend doing that? It doesn't seem great because of the extra layer of indirection, but I'm unsure.

Also, going with that approach may require the target func signatures to change from:

```html
<span onclick="GoHandler(someJsObject, event, this, {{. | json}});">{{.Bar}}</span>
```

```Go
func GoHandler(someJsObject js.Object, event dom.Event, htmlElement dom.HTMLElement, foo common.Foo) {
	foo.Bar = ... // Use foo, event and htmlElement.
}

func main() {
	js.Global.Set("GoHandler", jsutil.Wrap(GoHandler))
}
```

To:

```html
<span onclick="GoHandler(someJsObject, event, this, {{. | json}});">{{.Bar}}</span>
```

```Go
func GoHandler(someJsObject jsutil.Object, event dom.Event, htmlElement dom.HTMLElement, foo common.Foo) {
	foo.Bar = ... // Use foo, event and htmlElement.
}

func main() {
	js.Global.Set("GoHandler", jsutil.Wrap(GoHandler))
}
```

(Note having to use `jsutil.Object` instead of `js.Object` in the `GoHandler` signature.)

**Comment by neelance** [comment]
Yes, I see that this is not so good. I'm currently working on an even better solution for js.Object. Then your original code should work again.

**Comment by shurcooL** [comment]
All right, that sounds great, thanks for looking into this! :)

**Comment by neelance** [comment]
It's ready. Please give it a try.

**Comment by shurcooL** [comment]
Trying now, but it seems the packages that started using `js.Any` will need to revert back to using `interface{}`, right?

Currently getting:

```
dom/dom.go:825:48: Any not declared by package js
```

**Comment by neelance** [comment]
Yes, `js.Object` implements `interface{}` again and this time in a fully compatible way, e.g. it also implements `fmt.Stringer`, etc.

**Comment by shurcooL** [comment]
Ok, I did `gofmt -w -r 'js.Any -> interface{}' dom.go`, and now everything seems to compile well, including my `jsutil.Wrap` helper.

**Comment by neelance** [comment]
Nice!

**Comment by shurcooL** [comment]
Thanks!
