### ISSUE TITLE
Jasmine API bindings

### ISSUE THREAD

**Issue by JohannWeging** [gopherjs/gopherjs#161]
Hello,
I'm currently working on [Jasmine API bindings](https://github.com/JohannWeging/jasmine) and can't get [spies](http://jasmine.github.io/edge/introduction.html#section-Spies) to work.
In short, spies track function calls.

If I define a test case:
```go
package main

import "github.com/JohannWeging/jasmine"

type Foo struct {
	Bar int
}
func (f *Foo) SetBar(b int) {
	f.Bar = b
}
 

func main() {
	jasmine.Describe("testing spies", func() {
		var F *Foo
		jasmine.BeforeEach(func() {
			F = &Foo{}
		})
		jasmine.It("tests SpyOn", func() {
			jasmine.SpyOn(F, "SetBar")
			F.SetBar(3)
			jasmine.Expect(F.SetBar).ToHaveBeenCalled()
		})
	})
}
```
It throws the error: Error: SetBar() method does not exist

The call "jasmine.SpyOn" calls the java script code:
```js
this.spyOn = function(obj, methodName) {
    [...]
    if (j$.util.isUndefined(obj[methodName])) {
        throw new Error(methodName + '() method does not exist');
    }
    [...]
```
How can I make the function "SetBar" of the instance "F" visible to jasmine?

**Comment by neelance** [comment]
I think you'll need to use `js.InternalObject` to get access to GopherJS's internal data structures. However I can give no guarantees at all about how those internal data structures look like and how they will change in the future. In the Go world, something like `SpyOn` is simply not possible and I would recommend to not violate the Go spec by using such a JS hack.

**Comment by neelance** [comment]
Feel free to reopen.
