### ISSUE TITLE
Question: Does js.NewArrayBuffer provide new functionality, or is it a convenience/helper func?

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#167]
`js.NewArrayBuffer` was added in 59323cd88acd2923912b367ed99deddfeeb44f66.

If it's just a convenience/shortcut for what we could do before, what would the equivalent code be?

**Comment by neelance** [comment]
See #165 . It was possible before with some `js.InternalObject` hack, but I did not like the solution and wanted to provide an officially supported one.

**Comment by neelance** [comment]
@dominikh asked me to explain `ArrayBufferView` vs `ArrayBuffer` some more:

The `ArrayBuffer` is like a Go byte array of some fixed size. The `ArrayBufferView` is an abstract type, the concrete versions are `Uint8Array`, `Int32Array`, etc. Each `ArrayBufferView` is backed by an `ArrayBuffer`, just like a Go byte slice is backed by a byte array. Each `ArrayBufferView` has an offset and a length, also just like a Go slice. However, this offset and length and the read/write methods of an `ArrayBufferView` depend on the concrete type when finding the correct byte position in the underlying `ArrayBuffer`.

Hope this helps a bit.
