### ISSUE TITLE
Import of net package causes os.Open syscall in net.maxListenerBacklog

### ISSUE THREAD

**Issue by nwidger** [gopherjs/gopherjs#169]
I just ran into an issue using the latest versions of `github.com/gopherjs/gopherjs` and `github.com/gopherjs/websocket` which seems to be caused by `websocket` importing the stdlib `net` package.  `net` has a global variable `var listenerBacklog = maxListenerBacklog()` in `net/net.go` which gets initialized during package initialization.  In the browser at runtime this initialization causes a call to `os.Open("/proc/sys/net/core/somaxconn")` which triggers the following error on the JS console:

```
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
```

The solution that worked for me was to add the following stub to `github.com/gopherjs/gopherjs/compiler/natives/net/net.go`:

``` go
func maxListenerBacklog() int {
	return 0x80
}
```

where `0x80` is the value of `syscall.SOMAXCONN` for Linux.  I'm using Go 1.4.1 on linux_amd64.

**Comment by neelance** [comment]
Did this fix the issue?

**Comment by nwidger** [comment]
It did, thank you!
