### ISSUE TITLE
Valid (but obscure and unsafe) Go code that doesn't work in GopherJS.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#170]
Hi Richard,

What is the support status for "unsafe" package? It's listed as "(no tests)" at https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md, and on playground I get `failed to load package "unsafe"` error, but when compiling locally it seems to work to some degree.

I have some valid Go code that compiles and works correctly using `go`, but not `gopherjs`, so I wanted to report it here. However, this Go code is very unsafe and relies on deep knowledge of internals of Go compiler and reflect package source code. I can _very easily_ create a workaround for GopherJS that will make it work by using `+build !js` build tags.

So the priority of fixing this is extremely low, and I don't think you should worry about it unless it's easy for you, or you really want to/consider it important. I'm mostly sharing this since I ran into some valid Go that doesn't work, and by now that is a very rare occurrence.

http://play.golang.org/p/vqsgfzeFBa

```Go
package main

import "unsafe"

func main() {
	var i int = 5
	//upf := unsafe.Pointer(uintptr(unsafe.Pointer(&i)))            // This works both in Go and GopherJS.
	upf := unsafe.Pointer(uintptr(unsafe.Pointer(&i)) + uintptr(0)) // This works in Go, but not GopherJS.
	upfv := *(*uintptr)(upf)
	_ = upfv
}
```

It works in Go, but using GopherJS I see this error in the browser console:

```
Uncaught TypeError: undefined is not a function
```

The generated JavaScript looks like this:

```JavaScript
var i, upf, upfv;
i = 5;
upf = (new ptrType$7(function() { return i; }, function($v) { i = $v; }) + 0 >>> 0);
upfv = upf.$get();
```

For reference, this problem is happening when I try to import a real-world package `github.com/shurcooL/go-goon` when building with GopherJS. The problem code is [here](https://github.com/shurcooL/go-goon/blob/192dc9eb9a47276336d580a1a7b2d8d8079fa69e/bypass/main.go#L62-L74). But like I said, I can easily fix this on my end by avoiding the problem code, so feel free to close this if it's not worth fixing in GopherJS.

**Comment by neelance** [comment]
GopehrJS's support for `unsafe` is very restricted. It only supports some very special cases in a hacky way to make the `syscall` and `reflect` packages work. In general, `unsafe` can not be supported because that would require to emulate the memory characteristics of `gc`, including pointer arithmetics etc. I'll update the compatibility table.
