### ISSUE TITLE
Slice Int Converting to JS Object instead of Array

### ISSUE THREAD

**Issue by fabioberger** [gopherjs/gopherjs#171]
Hi there, 

I'm currently writing a Gopherjs Chrome binding, so that people can write chrome extensions in Go. Thanks for the great work on Gopherjs, its awesome!

I am currently implementing this function: 

```go
func (t *Tabs) Move(tabIds []int, moveProperties interface{}, callback func(js.Object)) {
	t.o.Call("move", tabIds, moveProperties, callback)
}
```

And am testing it by calling: 

```go
prop := Object{
	"index": -1,
}
c.Tabs.Move([]int{29}, prop, func(tab js.Object) {
	fmt.Println("Done moving: ", tab)
})
```

However, Chrome is complaining that:

```
Uncaught Error: Invocation of form tabs.move(object, object, function) doesn't match definition tabs.move(integer or array tabIds, object moveProperties, optional function callback)
```

The comment in js.go suggests that slices will be converted into type Array: 

```
all other slices and arrays    | []interface{}                  | Array   
```

But it looks like Chrome is complaining that it is receiving an object instead of an array for the first parameter to Move(). Any idea why this might be happening?

Thanks!

**Comment by fabioberger** [comment]
I figured out that if I use []interface{} instead of []int, it works. Is this considered best behavior to always use interface{} and let Gopherjs figure out the types? 

This works: 
```go
func (t *Tabs) Move(tabIds []interface{}, moveProperties interface{}, callback func(js.Object)) {
	t.o.Call("move", tabIds, moveProperties, callback)
}
```

**Comment by neelance** [comment]
The issue was most likely because `[]int` becomes an `Int32Array`. It's already listed in the docs:
```
| [?]int32, [?]int               | []int                          | Int32Array        |
```
Is this written in a too complicated way? Maybe I should improve this. What do you think?

**Comment by fabioberger** [comment]
Ah ok, thanks for the clarification. I thought the "?" meant that this was for fixed arrays only and not for variable length slices. Perhaps instead of the question mark, you could put the "*" star from regex to denote zero or more numbers here. Just a thought.

**Comment by neelance** [comment]
I've modified the conversion table. Is the new version easier to understand?

**Comment by fabioberger** [comment]
It looks much better, thanks for taking the time to make that clearer! Great job on this project in general, I'm super excited about being able to use the Go in the browser, its like a wish come true!

**Comment by neelance** [comment]
:-)
