### ISSUE TITLE
Embedding anonymous interface considered as has-a on javascript side

### ISSUE THREAD

**Issue by thoratou** [gopherjs/gopherjs#174]
Hello,

New issue found with anonymous embedding:

http://www.gopherjs.org/playground/#/oI6PPIZ-rp

```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

type Parent interface {
	js.Object
	InnerHeight() int
}

type parent struct {
	js.Object
}

func (p *parent) InnerHeight() int {
	return p.Get("innerHeight").Int()
}

type Child interface {
	Parent
}

type child struct {
	Parent
}

func Print(o js.Object) {
	println(o)
}

func DummyCall(o js.Object) {
	println(o.Get("innerHeight").Int())
}

func DummyCallParent(p Parent) {
	println(p.Get("Object").Get("innerHeight").Int())
}


func main() {
	parent := &parent{js.Global}
	Print(parent)
	Print(parent.Object)
	println(parent.InnerHeight()) // returns the good value => OK
	DummyCall(parent.Object) // returns the good value => OK
	DummyCall(parent) // returns 0 => KO
	
	child := &child{parent}
	Print(child)
	Print(child.Parent)
	println(child.InnerHeight()) // returns the good value => OK
	DummyCallParent(child.Parent) // returns the good value => OK
	DummyCallParent(child) // panic: Cannot read property 'innerHeight' of undefined => KO
}
```

We get no issue with "method" calls in this case (see InnerHeight), but we get some issue giving the final structure to a function or method that uses to embedded interface (see DummyCallParent).

Note: The result is even strange for the parent simple case as it returns 0 instead of giving the "Cannot read property 'innerHeight' of undefined" message

The example here is simple the understand the basis of the issue and should be easy to understand.

However, we could have some very tricky results with this behaviour (this is how I discovered the bug and it took a while to figure why):

```go
type helloWorldLayer struct {
	cc.Layer
	//other data here, not useful for the test
}

scene := cc.NewScene()
layer := &helloWorldLayer{cc.NewLayer(), ...}
scene.AddChild(layer)
```

It uses my in-development cocos2d-js binding (https://github.com/thoratou/go-cocos2d-js)

In the case, the AddChild call will delegate to the javascript code. All function calls are OK, but at one point it tries to access the internal layer data and fails.
For the developer point of view, it looks like a missing constructor call.

The workaround is to change the last call by:

```go
scene.AddChild(layer.Layer)
```

this seems to be an issue for all public-interface/private-structure based libraries.

Sincerely,
   thoratou

**Comment by neelance** [comment]
Thanks for reporting this. My plan is to turn `js.Object` into a `struct`. Then those problematic cases are not possible any more.

**Comment by thoratou** [comment]
Hi neelance,

Thanks for replying.

It will be a major change (in compatibility term, so it will break most of exacting libraries) as js.Object would not be embedded anymore in interface,
but it seems to be a manageable none in term of migration.

However I'm invited in the way it could be implemented and how it could fix it.

If I understand well, the idea is to "flatten" interface binding for the generated code (so not have javascript objects for each interface level), isn't it ?

**Comment by neelance** [comment]
> It will be a major change (in compatibility term, so it will break most of exacting libraries) as js.Object would not be embedded anymore in interface

It was never the idea to embed `js.Object` into other interfaces. Usually it is used as a field of a `struct`. Which existing libraries are using the embedding in an interface?

**Comment by thoratou** [comment]
In deed, embedding js.Object is just a way to provide low level access for quicker investigation.
It is only useful for early development stages, as final versions shouldn't provide such kind of access.

**Comment by neelance** [comment]
Discussion of the proposed changes here: https://groups.google.com/forum/#!topic/gopherjs/ymuX_hSNSSE

**Comment by neelance** [comment]
Fixed by changing `js.Object` into a `struct` and https://github.com/gopherjs/gopherjs/commit/2ce56997ea2908f34704dc1c7fd773f0e5a7eea7
