### ISSUE TITLE
backward compatability break

### ISSUE THREAD

**Issue by sagiegurari** [gopherjs/gopherjs#176]
I updated to latest gopherjs which requires go 1.4 (i took latest 1.4.1)

I used the following simple go file:
https://github.com/sagiegurari/node-go-require/blob/master/test/helpers/main/main.go

so I have now access to a 'New' function to return the pet pointer object
var pet = jsModule.pet.New('my pet');

but the returned object now has no functions or properties (should have the SetName and Name functions but it has nothing).

**Comment by neelance** [comment]
Please take a look at `js.MakeWrapper` http://godoc.org/github.com/gopherjs/gopherjs/js#MakeWrapper This functionality is no longer implicit.

**Comment by sagiegurari** [comment]
thanks, it works good.
