### ISSUE TITLE
"Error: cannot internalize" into custom wrapper of js.Object when it returns null

### ISSUE THREAD

**Issue by fabioberger** [gopherjs/gopherjs#178]
When tab is null, if the return type in the callback is simply js.Object, it will return "null": 

```go
func (t *Tabs) GetCurrent(callback func(tab js.Object))
```

whereas if the return type is a custom struct with js.Object embedded within it, a javascript error occurs:

```go
func (t *Tabs) GetCurrent(callback func(tab Tab))
```

The error is: 

```js
Error in response to tabs.getCurrent: 
     Error: cannot internalize chrome.Tab
```

Where chrome.Tab is:

```go
type Tab js.Object
```

This ends up creating runtime javascript errors for any custom struct with js.Object embedded within it whenever it returns null instead of the actual object expected. Is this avoidable? It makes for very poor error handling.

**Comment by neelance** [comment]
```
type Tab js.Object
```
is not a custom struct. Try
```
type Tab struct {
   js.Object
}
```
instead.

**Comment by fabioberger** [comment]
Thanks for the reply Neelance, 

Below is the original Tab object I was trying it with and getting the same error. I have also tried just a simple struct with only the embedded js.Object and am getting the same error. Any ideas?

```go
type Tab struct {
	js.Object
	Id          int    `js:"id"`
	Index       int    `js:"index"`
	WindowId    int    `js:"windowId"`
	OpenerTabId int    `js:"openerTabId"`
	Selected    bool   `js:"selected"`
	Highlighted bool   `js:"highlighted"`
	Active      bool   `js:"active"`
	Pinned      bool   `js:"pinned"`
	Url         string `js:"url"`
	Title       string `js:"title"`
	FavIconUrl  string `js:"favIconUrl"`
	Status      string `js:"status"`
	Incognito   bool   `js:"incognito"`
	Width       int    `js:"width"`
	Height      int    `js:"height"`
	SessionId   string `js:"sessionId"`
}
```

**Comment by neelance** [comment]
Is `tab` really `null` or maybe `undefined` instead? Because for `undefined` I see a code path that might cause this behavior.

**Comment by fabioberger** [comment]
If I call the String() method on the returned js.Object, it returns "undefined":

```go
c.Tabs.GetCurrent(func(tab js.Object) {
	fmt.Println("tab: ", tab.String())
})
```

Prints out:

```go
tab: undefined
```

**Comment by neelance** [comment]
Okay, then I know what the problem is and I can fix it. :-)

**Comment by fabioberger** [comment]
Oh great! Let me know when you've had the chance to fix it and if there is
anything else I could help with!

Fabio

**Comment by neelance** [comment]
It's already fixed. ;-) Didn't you get a message?

**Comment by fabioberger** [comment]
Ah great! For some reason I didn't get an email about it. Thanks! :D
