### ISSUE TITLE
question: is sourcemap supported?

### ISSUE THREAD

**Issue by sekimura** [gopherjs/gopherjs#179]
It would be nice if I can see the original go code in Web Inspector Source panel.

**Comment by hajimehoshi** [comment]
You can get .map file when you execute `go build`.

**Comment by sekimura** [comment]
I can see the .map file generated. What I meant was sourceURL explained https://developer.chrome.com/devtools/docs/javascript-debugging#source-maps

**Comment by neelance** [comment]
GopherJS generates the `sourceMappingURL` entry at the end of the output file. Accoding to your link, `sourceURL` is meant for evals, so I don't see how this should apply to GopherJS.
