### ISSUE TITLE
relative import

### ISSUE THREAD

**Issue by shibukawa** [gopherjs/gopherjs#180]
Hi,

Import via relative path is valid for golang 1.4, but gopher.js can't build it. Is there any workaround to build it? or is it bug?

```go
// main.go
package main

import (
    "fmt"
    "./sub"
)

func main() {
    fmt.Println(sub.Message())
}
```

```go
// sub/sub.go
package sub

func Message() string {
    return "hello world"
}
```

```bash
$ gopherjs build
import "./sub": import relative to unknown directory
```

**Comment by shurcooL** [comment]
I think this is #148.

**Comment by shibukawa** [comment]
OK. I understand you guys have identified this issue and it has lower priority. I will rewrite relative paths into absolute github URLs. Thanks.
