### ISSUE TITLE
Recent Refactor of js.Object causes struct to need dereferencing

### ISSUE THREAD

**Issue by fabioberger** [gopherjs/gopherjs#184]
Whereas before I could chain js.Object methods:

```go
onAlarm := a.o.Get("onAlarm").Call("addListener", callback)
```

Now I need to dereference the returned struct and write:

```go
onAlarm := a.o.Get("onAlarm")
(*onAlarm).Call("addListener", callback)
```

Or else the following error is thrown:

```
../../alarms.go:58:2: invalid operation: onAlarm (variable of type *github.com/gopherjs/gopherjs/js.Object) has no field or method Call
```

**Comment by shurcooL** [comment]
Something's not right with your setup.

http://godoc.org/github.com/gopherjs/gopherjs/js#Object.Get returns `*js.Object`.

`*js.Object` has a `Call` method, and it requires a pointer receiver. See http://godoc.org/github.com/gopherjs/gopherjs/js#Object.Call.

So doing `Get(...).Call(...)` should be fine.

**Comment by neelance** [comment]
@fabioberger Yes, shurcooL is right, this should work without problems.

**Comment by fabioberger** [comment]
Upon updating Gopherjs this particular issue went away but others have surfaced. 

In all libraries that previously expected a js.Object returned, a *js.Object is now being returned: 

```
../../../../../honnef.co/go/js/dom/dom.go:1250:25: cannot pass argument n.Get("childNodes") (value of type *github.com/gopherjs/gopherjs/js.Object) to parameter of type github.com/gopherjs/gopherjs/js.Object
```

Is this something that every library must update and is considered better?

**Comment by neelance** [comment]
Right, the change is not backwards-compatible. We've discussed it in the mailing list and it was welcomed by the community. The `honnef.co/go/js/dom` package is already updated, you just need to make sure to have the newest version: `go get -u honnef.co/go/js/dom`.

**Comment by fabioberger** [comment]
Oh ok great, thanks for clearing that up. I'll be sure to join the Mailing List for future notifications.
