### ISSUE TITLE
Support for sync package

### ISSUE THREAD

**Issue by hackwaly** [gopherjs/gopherjs#188]
I see `runtime_Semacquire` and `runtime_Semrelease` are implemented. So, I think these maybe missed.
It's required by `sync.Cond`, which is used by some packages (such as github.com/inconshreveable/muxado).

**Comment by neelance** [comment]
Thx for reporting this. The `sync` package is not fully supported atm, see compatibility table. I will take care of this after merging the `assume-blocking` branch to close #89.

**Comment by neelance** [comment]
Fixed by 47c8aceb4ea6d26e0658da17b1c58cd96479edc5
