### ISSUE TITLE
wrappers no longer exporting functions

### ISSUE THREAD

**Issue by benechols-wf** [gopherjs/gopherjs#190]
I am not sure exactly the bug here but I will describe the issues as best as I can.

First this commit (https://github.com/gopherjs/gopherjs/commit/8f3b91cf3ba7ab0116a65d61b6e5f17f42ef1c3d) caused our  library to have runtime errors ( Uncaught Error: runtime error: non-blocking call to blocking function ).

Then this commit (https://github.com/gopherjs/gopherjs/commit/b188fae5c8b95887771cc652d42798d3f84bd676) fixed the blocking issue but now instead of my functions returning objects they are returning the function that generates an object. 

Then this commit (https://github.com/gopherjs/gopherjs/commit/a099d49c444733074622e326dcfea91476f705e0) fixed the issue with generating a function instead of a wrapped object. However now sometimes the externalization of the return is causing crashes:
In externalization I end up on this line after being called from js.go
```javascript
    case $kindString:
      if (v.search(/^[\x00-\x7F]*$/) !== -1) {
        return v;
      }
```
The error is "Uncaught TypeError: Cannot read property 'search' of undefined"
The return of the called function is of type "map[string]interface{}". 

Another issue:
```javascript
    case $kindSlice:
      if ($needsExternalization(t.elem)) {
        return $mapArray($sliceToArray(v), function(e) { return $externalize(e, t.elem); });
      }
      return $sliceToArray(v); 
```
ends up calling 'sliceToArray' 
```javascript
    var $sliceToArray = function(slice) {
      if (slice.$length === 0) {
        return [];
      }
      if (slice.$array.constructor !== Array) {
        return slice.$array.subarray(slice.$offset, slice.$offset + slice.$length);
      }
      return slice.$array.slice(slice.$offset, slice.$offset + slice.$length);
    };
```
which then throws this error:  "Uncaught TypeError: Cannot read property '$length' of undefined" on the line `if (slice.$length === 0) {`
The return type of this function is A with a hierarchy something like this:
```go
    type A struct {
      Stuff []B
    }
    type B struct {
      MyValue []*C
    }
    type C struct {
      Value int
      AnotherValue string
    }
```
Also C has many methods associated with it that do not need to be available to JS at all.

I am trying to track down the issue myself but am getting a little lost in the externalization code. Hopefully I can make a PR to fix this but at the moment I am not very hopeful.

**Comment by neelance** [comment]
Is it possible to create a short test case that demonstrates the bug?

**Comment by benechols-wf** [comment]
I am trying right now but having difficulty reproducing it with a simple test.

**Comment by benechols-wf** [comment]
It looks like one of the inner functions is a blocking operation which results in something different coming out of the stack of function calls before it is externalized. That might be causing this.

**Comment by benechols-wf** [comment]
Here is some code to reproduce the issue:
```go
package main

import (
	"sync"

	"github.com/gopherjs/gopherjs/js"
)

type C struct {
}

func (*C) GetMap() map[string]interface{} {
	v := &sync.Mutex{}
	v.Lock()
	v.Unlock()
	return map[string]interface{}{
		"asdf":  "the value for asdf.",
		"other": nil,
	}
}

func main() {
	js.Global.Set("myPackage", map[string]interface{}{
		"GetC": GetC,
	})
}

func GetC() *js.Object {
	return js.MakeWrapper(&C{})
}
```

then the JS
```javascript
require('./mypackage.js');
var c = myPackage.GetC();
c.GetMap();
```

**Comment by benechols-wf** [comment]
Also strange - the inner function that is causing the chain of functions to be blocking, isnt' actually blocking at all. There are no blocking calls and I can't figure out why it should be blocking

**Comment by neelance** [comment]
Thx for reporting this. I found a much easier way to implement `js.MakeWrapper` and it also fixes this bug.

**Comment by benechols-wf** [comment]
Just tested - looks like everything is working great now! thanks!
