### ISSUE TITLE
Optional special comment to mark calls recursively as not blocking for improved performance

### ISSUE THREAD

**Issue by neelance** [gopherjs/gopherjs#193]
While we're happy that we can now use blocking in whatever way we want, it seems like performance has taken a major hit in some cases. That's why I want to propose the `//gopherjs:non-blocking` comment.

This comment will tell GopherJS that the called function will not block. This automatically means that all recursively called functions will also not block (this is different to what we had with `//gopherjs:blocking`). If the code tries to block nevertheless, a panic will be thrown.

This comment is completely optional, it just makes it faster.

I am not yet quite sure about how to implement it, but it will require two versions of each function. That's why this kind of depends on the dead code elimination described in #186, because else the output will really get too big.

**Comment by elliott5** [comment]
I have code in TARDIS Go, which I modified from golang.org/x/tools/go/ssa/ssautil, that attempts to find candidate functions that will not block, which you may find helpful to look at for ideas for automatically setting  ```//gopherjs:non-blocking``` on some functions. See how [VisitedFunctions](https://github.com/tardisgo/tardisgo/blob/master/tgossa/visit.go) (which is used for dead code elimination) also sets the usesGR map to see which functions need goroutines. ...and if you can see any problems with the logic, please let me know ;)

**Comment by neelance** [comment]
Okay, I might have found a way to implement blocking in a way that affects performance much less. Maybe we can get by without the need for the special comment, I would prefer that. Wish me luck. ;-)

@elliott5 I am already analysing a lot. Problem is that for func values and interface methods you don't know at compile time if they will block or not. What do you do about this?

**Comment by elliott5** [comment]
Where you do not know if a func value or interface method will block or not, I think you have to assume that they will block I'm afraid, that's what I do.

It may be possible to an [Oracle](https://godoc.org/golang.org/x/tools/cmd/oracle) analysis as part of the compile phase, to improve on this situation in future... but I have not tried it yet because of the "Caveats" and "Troubleshooting" sections of the user manual.

As an alternative, when calling via a func value or interface, you could allow a non-blocking comment in the code at the call-site.

Meantime best to tell the community to refactor their code not to use func values or interfaces if they want it to run fast!

**Comment by albrow** [comment]
Right now I am definitely in favor of `//gopherjs:non-blocking`. It would help improve performance of my projects (and I think @shurcooL's  too?) and make using gopherjs more practical.

If your idea does work and you can figure out a way to optimize blocking calls, that would be incredible! It also might change my opinion here. Please keep us up to date regarding your idea for optimizing blocking calls. I wish you luck!

**Comment by shurcooL** [comment]
I echo @albrow's comment. Good luck and thanks for awesome work! :)

**Comment by neelance** [comment]
I've reached a point with the new approach where I can run the benchmarks of #192.

|                     | BenchmarkParse  | BenchmarkXMLDecode | BenchmarkDiff |
| ------------------- | --------------: | -----------------: | ------------: |
| Before              |   2374000 ns/op |      1293000 ns/op |  204800 ns/op |
| After               |    708500 ns/op |       370666 ns/op |   73150 ns/op |
| Assume non-blocking |    569500 ns/op |       262800 ns/op |   65300 ns/op |

Looks like I'm on the right track. ;-) It is even only a bit slower than the old version 30fcbd836780ca9b8c9694f5491cf3b2a502f1a8 which still assumed non-blocking by default. For me, this would mean that there is no need for `//gopherjs:non-blocking`, but we can do further testing before deciding that. My benchmark results also don't really fit to those from @albrow in #192, maybe you were using an older Node.js version? I'm using v0.12.0.

**Comment by albrow** [comment]
Yep, good call. My version of node was outdated. Let me updated it and check the results again.

**Comment by shurcooL** [comment]
> These results look fantastic by the way! Thank you.

I agree! :+1: I hope @neelance doesn't mind more praise but I really feel this work is outstanding and it's hard to stay quiet. :p

**Comment by neelance** [comment]
It is done! Phew!

Now let's see if we still need `//gopherjs:non-blocking`.

**Comment by albrow** [comment]
Here's what I'm seeing now:

|                          | BenchmarkParse  | BenchmarkXMLDecode | BenchmarkDiff |
| ------------------------ | --------------: | -----------------: | ------------: |
| **Assume Non-Blocking**  |    458000 ns/op |       170500 ns/op |   50133 ns/op |
| **Current Version** | 562500 ns/op | 274000 ns/op |  70350 ns/op |
| **Current/Non-Blocking** |      1.23 |             1.61 |            1.40 | 

It's awesome that we get this improvement for free, without having to change anything about our code. Some people might still want `//gopherjs:non-blocking`. I'm not sure how important it would be for me, but I will have a better idea soon. As I'm building out more apps with gopherjs, I'll report back.

**Comment by neelance** [comment]
Thx for evaluating the new approach.

Implementing `//gopherjs:non-blocking` would be a lot of work and also create some problems on its own. Since the difference is not massive, I'd rather like to spend my time on more important issues. Later I can also try to fine-tune the new apprach.

**Comment by albrow** [comment]
That makes complete sense. Thanks for your work, and I look forward to whatever else you have coming down the pipeline!

**Comment by neelance** [comment]
Currently I see no need for this feature. Closing it for now.
