### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by benechols-wf** [gopherjs/gopherjs#194]
You might already know about this so feel free to close this if the fix is part of other ongoing work -

I have a call that includes a log.printf and it gets into an infinite loop starting with 'blocking_print' -> 'blocking_output' -> then thousands of calls to 'callDeferred'

**Comment by shurcooL** [comment]
If you're using the latest commit (3ba1b361c1d168781da42e26d207dd610419612d), I believe this is a known current issue, see https://github.com/gopherjs/gopherjs/commit/3ba1b361c1d168781da42e26d207dd610419612d#commitcomment-10092496.

**Comment by neelance** [comment]
Might have been fixed by cc417a60d11f93d6a6589ca45829c79eb4db268d. If not, please try to create a small example, because `log.Printf` works for me in general.

**Comment by benechols-wf** [comment]
Looks like i dont see that anymore - closing the ticket!
