### ISSUE TITLE
Panic does not work as expected when there's a deferred call (due to infinite recursion).

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#198]
The following program works correctly:

```Go
package main

import "fmt"

func main() {
	fmt.Println("hi")

	panic("something went wrong")
}
```

![image](https://cloud.githubusercontent.com/assets/1924134/6763913/36ccf4ec-cf51-11e4-8b8b-0f6c0127b900.png)

However, when there is a deferred call, I see 100% CPU utilization for a minute and then:

```Go
package main

import "fmt"

func main() {
	defer fmt.Println("bye")

	panic("something went wrong")
}
```

![image](https://cloud.githubusercontent.com/assets/1924134/6763921/a7d5a634-cf51-11e4-98c4-02e5b110b6de.png)

This takes makes it not possible to see the panic message (and takes a minute to see results while using lots of CPU).

(Using latest commit of GopherJS as of this post, gopherjs/gopherjs@4ae1861da588ffd3572672ccc8a03b2a5c7d3764.)

**Comment by neelance** [comment]
It works for me. Is someone else seeing the bug, too?

**Comment by mibitzi** [comment]
I tried it, but was not able to reproduce it either.

**Comment by shurcooL** [comment]
Hmm, I'll try again. Maybe I did something wrong.

**Comment by shurcooL** [comment]
Odd, I can't reproduce it now. I will look a little more into it.

![image](https://cloud.githubusercontent.com/assets/1924134/6771176/b802bd5a-d094-11e4-9e7c-1c1a7ecda2f4.png)

**Comment by shurcooL** [comment]
Sorry, this was my fault. I had accidentally forgotten to rebuild one binary (but not another) that I use, so the binary was old while gopherjs source was newer. Rebuilding with latest version resolved the issue.

**Comment by neelance** [comment]
No worries. :-)
