### ISSUE TITLE
TypeError: Cannot read property '$blk' of null

### ISSUE THREAD

**Issue by fabioberger** [gopherjs/gopherjs#203]
Hi there,

When calling the `Omnibox.OnInputChanged` listener in the Gopherjs Chrome Bindings, the following error is thrown every time the event happens:

```
Error in event handler for omnibox.onInputChanged: TypeError: Cannot read property '$blk' of null
    at $b (chrome-extension://jcdkoahigpljijhbgdbaokkamaacehkb/test.js:18567:68)
    at v.$externalizeWrapper (chrome-extension://jcdkoahigpljijhbgdbaokkamaacehkb/test.js:1683:24)
extensions::uncaught_exception_handler:8 handler
extensions::uncaught_exception_handler:100 
exports.handle
extensions::event_bindings:384 EventImpl.dispatch_
extensions::event_bindings:247 
dispatchArgs
extensions::omnibox:121 (anonymous function)
extensions::event_bindings:254 dispatchEvent
```

Might this have something to do with blocking/non-blocking javascript code: https://github.com/gopherjs/gopherjs#goroutines?

Thanks

**Comment by neelance** [comment]
I did not reproduce your specific case, but I am quite sure that this was the bug. Please try again and tell me if I'm right. ;-)
