### ISSUE TITLE
First CL for Go subrepo that contains code for JS architecture.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#208]
As far as I'm aware, this is the first such CL:

https://go-review.googlesource.com/8793

(For context and motivation, see https://github.com/google/gxui/issues/49#issuecomment-84324901, including following and preceding comments and linked issues.)

I've just created it and it's still requires review and feedback, and it may or may not be accepted. But I'm optimistic. After all, it serves a concrete need (any package that imports `golang.org/x/mobile/gl` can run in browser, in addition to already supported platforms), and its code is largely hidden behind `js` build tag so it won't affect other Go compilers.

/cc @neelance Richard, I'd appreciate if you take a look at it and see if everything is as you'd expect it to be.

### Build Tag

One observation/comment I have is about the build tag. See https://github.com/gopherjs/gopherjs#general.

Currently, `js` is considered to be the architecture when compiling with `gopherjs`. This required me to add `// +build !js` to a bunch of other files that had `// +build linux darwin`, since I am running `gopherjs` on OS X, those files were being included and conflicting with my `// +build js` files.

Would it be better if instead of setting `GOARCH` to `js` and keeping `GOOS` as whatever your OS is (e.g., darwin, linux, windows), `gopherjs` set the `GOOS` value to be `js` and left `GOARCH` as something else (perhaps also `js`)? Does `GOOS=darwin GOARCH=js` or `GOOS=windows GOARCH=js` have meaningful benefit? I would imagine the generated JavaScript would be the same if generated by `gopherjs` on Windows or OS X, etc. (Although that may not be true, `gopherjs` may use different standard library code based on `GOOS` it's running on... But is that desirable?)

Anyway, my main point here is to ask, is setting `GOARCH` to `js` better than setting `GOOS` to `js`? Have you considered both? If `GOOS` were to be set to `js`, does that mean I would need fewer `// +build !js` entries, or more, or the same?

Thanks!

**Comment by shurcooL** [comment]
Another point was raised about the `github.com/gopherjs/gopherjs/js` pseudo-package import path.

### `github.com/gopherjs/gopherjs/js` import path

This creates a coupling somewhat between `golang.org/x/mobile/gl` package and GopherJS compiler specifically. However, I argue it's not a large problem and can be worked around in the short term, and when the time is right, perhaps it can be renamed to something more general.

In any case, I think now would be a good time to re-evaluate this pseudo-package import path. Do we want to keep it as is?

Some notes:

1. The package github.com/gopherjs/gopherjs/js is only imported in glweb.go and types_web.go, both files are "hidden" via the "// +build js" build constraint. So when a user does `go get -u golang.org/x/mobile/gl`, they will not end up fetching github.com/gopherjs/gopherjs/js because the build constraint will not be satisfied.

If the user does go get -tags=js -u golang.org/x/mobile/gl, only then will github.com/gopherjs/gopherjs/js be fetched. But if they're doing that, they probably already have github.com/gopherjs/gopherjs/js anyway, so it's not an issue.

2. Suppose there's a new Go to JavaScript compiler tomorrow. It can reuse the `github.com/gopherjs/gopherjs/js` pseudo-package for its Go to JavaScript interactions needs. It's just a fake import path that the compiler treats specially.

But once there's more than one viable Go to JavaScript compiler, it may be desirable to rename that pseudo package import path to something more general. Perhaps it can be a part of GOROOT namespace, like "js" or "JS" - similar to "C". I think that should be fairly safe from conflicts.

I understand that `github.com/gopherjs/gopherjs/js` was used because the exact interface for Go <-> JavaScript was being developed and iterated. There were some changes to it that came from usage and discussion. It only makes sense to make it something shorter and less gopherjs-bound once it's considered stable and general enough.

**Comment by dominikh** [comment]
Having a "special" import path for js, a la C, would cause some issues. You usually want your code to compile with gc, or process it with tools like errcheck. So the `js` package needs to actually exist in your GOROOT or GOPATH, it needs to be importable. Now, the `gopherjs` tool could create that package in your GOPATH for you, but that means you have to install GopherJS and execute it at least once. It would also have to keep it up to date when the interface changes. Not to mention that it gets a bit icky when you have multiple GOPATHs and it isn't really clear where the `js` package should go.

At the moment, it's an ordinary package with an ordinary import path that can be installed via `go get`.

**Comment by shurcooL** [comment]
> At the moment, it's an ordinary package with an ordinary import path that can be installed via `go get`.

Would it be more accurate to put it like this?

From the perspective of regular Go compilers (gc, gccgo), `github.com/gopherjs/gopherjs/js` is a normal package. It needs to exist so that it can be go gotten and go built.

From the perspective of GopherJS, `github.com/gopherjs/gopherjs/js` is a pseudo-package similar to how `C` is a pseudo-package for regular Go compilers.

**Comment by neelance** [comment]
### GOOS
Right now, the output really is different depending on your OS. That way, syscalls with Node.js can work on Linux and OS X. In earlier versions of Go, there weren't even the files available for the other platforms if you didn't build Go with cross-compile support, but I think that has changed now.

Is this desirable? I am not sure. I have thought about setting GOOS to e.g. `browser`. If we do this, then we'll need to provide stubs for the `syscall` package and we would need some mechanism for switching back to the real `GOOS` if you want to use your system's syscalls, for example for testing.

### JS package path
The package is also read by GopherJS, just some functions get replaced by JS code. I need this package to be in sync with the GopherJS version. I think the case of some other Go to JS compiler is quite unlikely. If it really happens and it wants to be compatible with my `js` package, then we can figure out some shared solution. Otherwise I would like to not make this more complicated than it needs to be.

**Comment by shurcooL** [comment]
That CL did not get accepted for reasons primarily unrelated to GopherJS. The revised decision was to defer making the addition of WebGL support until a later date, when the internal refactor of `mobile/gl` package has settled. I will be revisiting that in the future (and in the meantime, the `goxjs/gl` package is working well for current real-world needs).

I'll close this since there are no more actionable items left in this issue. The issues/comments I brought up as a result of making that CL have been addressed above.
