### ISSUE TITLE
backward break

### ISSUE THREAD

**Issue by sagiegurari** [gopherjs/gopherjs#211]
The api is not stable, every now and than things break.
I took the example from your site http://www.gopherjs.org/ (with a minor change to export via module and not in global):
```go
package main

import "github.com/gopherjs/gopherjs/js"

type Pet struct {
	name string
}

func New(name string) *js.Object {
	return js.MakeWrapper(&Pet{name})
}

func (p *Pet) Name() string {
	return p.name
}

func (p *Pet) SetName(name string) {
	p.name = name
}

func main() {
	js.Module.Get("exports").Set("pet", map[string]interface{}{
		"New": New,
	})
}
```

And i'm able to require the js file, however when doing new it fails.

```js
var pet = mainGo.pet.New('my pet');
```

The error: 

pet.go.js:1784
    return $externalize(v.$get(), t.elem);
                          ^
TypeError: undefined is not a function
    at $externalize (pet.go.js:1784:27)
    at Object.v.$externalizeWrapper [as New] (pet.go.js:1756:20)
......

**Comment by neelance** [comment]
It works for me. I've compiled your code into `test.js` and created another file with 
```js
var mainGo = require('./test')
var pet = mainGo.pet.New('my pet');
console.log(pet);
```
The output then is `{ Name: [Function], SetName: [Function] }` as expected. Are you doing something differently?

**Comment by sagiegurari** [comment]
same thing, i took latest git version.

**Comment by neelance** [comment]
Which OS and Node.js version?

**Comment by sagiegurari** [comment]
windows 7, node 12

**Comment by sagiegurari** [comment]
go version go1.4.1 windows/386

**Comment by sagiegurari** [comment]
you can also take a look at https://github.com/sagiegurari/node-go-require and run the vertex.js there as a test

**Comment by neelance** [comment]
Could you please upload your GopherJS output file somewhere?

**Comment by sagiegurari** [comment]
ya let me try

**Comment by sagiegurari** [comment]
https://github.com/sagiegurari/node-go-require/blob/dev/test/temp/pet.js

**Comment by sagiegurari** [comment]
I think the go get failed or not completely worked last time, because i did go get again for gopher and now everything works good.
sorry for the trouble.

**Comment by shurcooL** [comment]
Make sure you don't forget to use the `-u` flag when doing `go get`, as shown in README:

https://github.com/gopherjs/gopherjs#installation-and-usage

If you don't include `-u`, `go get` will not update to latest version.

Just sharing this tip for future reference and others that may see this issue.

**Comment by sagiegurari** [comment]
ya thats what i did.
i figured there was some error during the update which caused to have a mix of versions or something.
when i reinstalled it seemed to work.

**Comment by neelance** [comment]
No worries. :-)
