### ISSUE TITLE
It's easy to get an infinite loop with the watch flag

### ISSUE THREAD

**Issue by wolverian** [gopherjs/gopherjs#212]
`gopherjs build -w` (notice no files mentioned in the command) notices the rebuilt js files and builds them again and again, ad infinitum.  

Would it be possible for the build command to figure out itself which files are a part of the source files, and only watch those?

**Comment by neelance** [comment]
Thanks for reporting this common pitfall. The fix was quite trivial. Sorry for taking so long.

**Comment by wolverian** [comment]
Thanks! :+1:
