### ISSUE TITLE
Function.prototype.bind called on incompatible undefined

### ISSUE THREAD

**Issue by matm** [gopherjs/gopherjs#216]
This simple snippet (taken from the JQuery binding example):
```
import (
    "github.com/gopherjs/jquery"
)

var jq = jquery.NewJQuery

func main() {
    print("JQuery version is " + jq().Jquery)
}
```

produces the following error on Firefox 37:
`TypeError: Function.prototype.bind called on incompatible undefined` at line 2224

Here is the line from the compiled Javascript:
```
return new JQuery.ptr(new ($global.Function.prototype.bind.apply($global.jQuery, [undefined].concat($externalize(args, sliceType)))), "", "", 0, "");
```

Where does `undefined` come from?

**Comment by rusco** [comment]
Strange, it works fine for me on FF 36.0.1/Win7 and on Chrome 41/Win7. 
I will try out the newer FF version later.

**Comment by matm** [comment]
Okay. I'm using FF 37.0.1/Linux/amd64. Same issue in Chromium 41.0.2272.76.

**Comment by rusco** [comment]
I checked right now with FF 37 all all works fine. Could you emit "$().jquery" on the FF or Chrome console ? You should see the current jQuery version, in my case I see "2.1.1".

**Comment by matm** [comment]
Well, nice catch, `$()` was null because I had a typo in the import path of my jQuery file... Thanks for pointing this out!

**Comment by neelance** [comment]
@matm It's resolved, great. Have fun with GopherJS!
@rusco Thanks for helping!
