### ISSUE TITLE
crypto/rand is not supported in browsers

### ISSUE THREAD

**Issue by dchest** [gopherjs/gopherjs#217]
Trying to read random bytes from `crypto/rand.Reader` throws returns "panic: open /dev/urandom: permission denied". http://www.gopherjs.org/playground/#/8mKbrn5ZXO

GopherJS should probably use `window.crypto.getRandomValues` in browsers and `crypto.randomBytes` in Node.js.

**Comment by neelance** [comment]
Thanks for reporting!

**Comment by dchest** [comment]
Wow, it was quick, thank you! I started writing my own implementation, but yours is simpler. Could you also add a check for `window.msCrypto` below  `window.crypto` (this is what it's called in IE11), or should I send a PR for this?

**Comment by neelance** [comment]
I had the file still open. ;-)

**Comment by dchest** [comment]
Awesome :) One more small thing: https://github.com/gopherjs/gopherjs/pull/218
