### ISSUE TITLE
System call warning on (crypto/rand) rand.Read()

### ISSUE THREAD

**Issue by roger-zr** [gopherjs/gopherjs#219]
When I execute this small code on my browser:

package main

    import (
            "crypto/rand"
    )
    
    func main() {
            b := make([]byte, 16)
            rand.Read(b)
            println(b)
    }

 I get the following warning and b is set all to zeros.

warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md

**Comment by neelance** [comment]
Please upgrade to the latest version. It is very likely that it is the same as #217 which I just fixed.

**Comment by roger-zr** [comment]
It's done and now it works as expected! Congratulations for your work, it's very good and useful!

**Comment by neelance** [comment]
Thx. :)
