### ISSUE TITLE
Confusing behavior with exceptions inside goroutines

### ISSUE THREAD

**Issue by christopherhesse** [gopherjs/gopherjs#225]
I have the following code:

    package main

    import (
    	"github.com/gopherjs/gopherjs/js"
    )

    func main() {
    	document := js.Global.Get("document")
    	{
    		f := func() {
    			print("works always")
    			panic("uh oh")
    		}

    		input := document.Call("createElement", "input")
    		input.Set("value", "works always")
    		input.Set("type", "button")
    		input.Set("onclick", f)
    		document.Get("body").Call("appendChild", input)
    	}

    	{
    		f := func() {
    			go func() {
    				print("works once")
    				panic("uh oh")
    			}()
    		}

    		input := document.Call("createElement", "input")
    		input.Set("value", "works once")
    		input.Set("type", "button")
    		input.Set("onclick", f)
    		document.Get("body").Call("appendChild", input)
    	}
    }

Included into a page like this:

    <!doctype html><html><head></head><body></body><script>%s</script></html>

I am using the newest version of gopherjs from github.

As the code indicates, I create two buttons, the first one produces a message and exception every time I hit it, the second one only works the first time, and I can't think of a reason why that should be.  Any ideas?

**Comment by neelance** [comment]
Thanks a lot for reporting!

**Comment by christopherhesse** [comment]
Wow, blown away at that turn around time, thanks for the fix!

**Comment by christopherhesse** [comment]
Tested and seems to work great!

**Comment by shurcooL** [comment]
> Wow, blown away at that turn around time, thanks for the fix!

@christopherhesse See [slide 26](https://speakerdeck.com/shurcool/go-and-gopherjs?slide=26) of my talk about the GopherJS project. :)

**Comment by christopherhesse** [comment]
I guess this guy is probably getting sick of all the wows.

**Comment by neelance** [comment]
Please don't stop. That's one of the best things about this project. ;-)
