### ISSUE TITLE
GopherJS build panic

### ISSUE THREAD

**Issue by rusco** [gopherjs/gopherjs#230]
http://www.gopherjs.org/playground/#/GpNESSPL-S

main_1() and main_2() work fine if I run them as main(), but the last main() function crashes at compilation time. GopherJS does not like that I handle over a callback function to "on".

The playground shows the panic only on the console.

**Comment by rusco** [comment]
The gopherjs playground has a hiccup currently, here at the go playground: 
http://play.golang.org/p/P8epCreRWt

**Comment by shurcooL** [comment]
> The gopherjs playground has a hiccup currently

Sorry for off-topic, but is this an ongoing or reproducible issue? If so, can you please report it at https://github.com/gopherjs/gopherjs.github.io/issues so I can fix it.

**Comment by rusco** [comment]
Sorry, not reproducible.  Next time I will look closer at the console logs.

**Comment by neelance** [comment]
As always, thanks a lot for reporting the bug. This was a tricky one. ;-)

**Comment by rusco** [comment]
Hi Richard,
are you sure the playground example compiles fine now ? 

Now I get a "panic: nil info" message. But the network guys mess around with our company's firewall, so I am not sure whether my go get -u command worked fine or not. I will do a fresh setup later this afternoon to check back. If possible update also the playground code to make sure the latest version is online.

**Comment by neelance** [comment]
Sorry, my test case was trimmed down and my first fix missed a case. This should work now, please try again.

**Comment by rusco** [comment]
:+1:
Thanks a lot Richard !

**Comment by neelance** [comment]
:)
