### ISSUE TITLE
Self hosting with node

### ISSUE THREAD

**Issue by andrewchambers** [gopherjs/gopherjs#235]
Just curious, anyone tried to do a self hosting build using the node syscall package?

**Comment by neelance** [comment]
I tried that once and it worked. Only spawning subprocesses is not possible, so `run` and `test` did not work. Haven't tried recently.

**Comment by andrewchambers** [comment]
Cool, I'll close. Might be an interesting thing to add to the test suite, building then rebuilding self and comparing.
