### ISSUE TITLE
Feature Request: `gopherjs test` support running and verifying example code.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#239]
One feature of `go test` command that is handy for short/quick/easy to write tests is that it runs and verifies example code (if it has a concluding comment with "// Output:").

See https://godoc.org/testing#hdr-Examples.

It'd be a nice enhancement if `gopherjs test` supported that too.

**Comment by shurcooL** [comment]
It would also be good if GopherJS supported the `TestMain` functionality added in Go 1.4 to allow custom setup and teardown per package (rather than per test). It's described [here](https://godoc.org/testing#hdr-Main). /cc @slimsag

**Comment by shurcooL** [comment]
This _would_ be resolved by WIP implementation of #388 or by @flimzy's PR, however, both efforts are blocked on issue https://github.com/gopherjs/gopherjs/issues/381 being resolved.

**Comment by flimzy** [comment]
Now that #381 has been fixed, is it worth me working on supporting examples, or wait for #485 to be completed?

Thoughts, @shurcooL ?

**Comment by shurcooL** [comment]
It's up to you. I don't expect #485 to be done soon, not within the next month. So feel free to go for it, or wait if you prefer.
