### ISSUE TITLE
Passing objects to Set without externalize

### ISSUE THREAD

**Issue by andrebq** [gopherjs/gopherjs#241]
Hi,

I am trying to make a wrapper around the Polymer library to allow the definition of Webcomponents using Go.

One issue that I am having is how to Set a Go value into a js.Object without the externalize call. Here is the code:

	Base struct {
		*js.Object
	}

	type HelloElement struct {
		polymer.Element
	}

	func NewHelloElement() polymer.Element {
		return &HelloElement{
			&polymer.Base{},
		}
	}

	func getTypedThis(this *js.Object, ctor ElementConstructor) Element {
		    /* ctor here is the function NewHelloElement */
		typed := this.Get("__typed")
		if typed == nil || typed == js.Undefined {
			val := ctor()
		            /* val here is *HelloElement */
			val.setThis(this)
			this.Set("__typed", val)
			return val
		}
		    /* typed here is *js.Object but should be *HelloElement */
		return typed.Interface().(Element) /* error here */
	}

When the execution reaches the marked line, the following error shows in the console.
Uncaught Error: interface conversion: *js.Object is not polymer.Element: missing method setThis.

From what I could read, the externalize call on this.Set("__typed", val), detects that val have a embedded *js.Object and returns that object (which in my case is an instance of my Polymer element).

When the call reaches the js.Get, it returns the *js.Object instead of the Go object (the *HelloElement).

I don't know if this is by design and cannot be changed or this is an actual bug.

**Comment by shurcooL** [comment]
Hi @andrebq,

I know the [`honnef.co/go/js/dom` package](http://honnef.co/go/js/dom) does something similar to wrap DOM elements in nicer Go wrapper types. Have you looked at its source to see how it does that? I'm just mentioning this in case it's helpful.

**Comment by andrebq** [comment]
Hi @shurcooL

dom package solves that problem via the wrapElement function which checks the constructor of the *js.Object and returns a new struct with the correct type.

I solved the problem using a similar technique but adapted to handle webcomponents.

I was looking for a way to do it without creating many short lived objects, to alleviate pressure on JS GC.

**Comment by shutej** [comment]
Is this the same problem I see here?

https://github.com/mibitzi/gopherjs-ko/issues/1

I'm not really understanding internalize/externalize overall.  :-(

**Comment by shurcooL** [comment]
> I'm not really understanding internalize/externalize overall. :-(

I suggest you start off by doing simpler things. Read over docs at https://godoc.org/github.com/gopherjs/gopherjs/js carefully. GopherJS supports internalizing JavaScript `Bool` into Go `bool`, for example. The table displays all types and how they are converted.

**Comment by neelance** [comment]
@andrebq Is there still an open question here or can we close this?

**Comment by neelance** [comment]
Closing now. Please reopen if the issue still exists.
