### ISSUE TITLE
Problem in run on windows 64 bit

### ISSUE THREAD

**Issue by myalexer** [gopherjs/gopherjs#247]
Hello
after i run the example in windows os  , it return this error :

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4330a6]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/js.(*Object).Set(0x0, 0x44bd40, 0x3, 0x43a3a0, 0xc0
82006210)
        E:/workspace/src/github.com/gopherjs/gopherjs/js/js.go:35 +0x26
main.main()
        E:/workspace/main.go:8 +0xea

goroutine 2 [runnable]:
runtime.forcegchelper()
        c:/go/src/runtime/proc.go:90
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        c:/go/src/runtime/mgc0.go:82
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2

why?

**Comment by shurcooL** [comment]
Can you post the source you're trying to run?

Also, are you compiling it with Go compiler or GopherJS compiler? It looks like you're using `github.com/gopherjs/gopherjs/js` package and compiling with Go. That package is meant for interacting with native JavaScript APIs in browsers. It can't be used using native Go, as that wouldn't make sense.

Read its documentation at https://godoc.org/github.com/gopherjs/gopherjs/js.

**Comment by myalexer** [comment]
package main

import "github.com/gopherjs/gopherjs/js"

func main() {
    js.Global.Set("pet", map[string]interface{}{
        "New": New,
    })
}

type Pet struct {
    name string
}

func New(name string) *js.Object {
    return js.MakeWrapper(&Pet{name})
}

func (p *Pet) Name() string {
    return p.name
}

func (p *Pet) SetName(name string) {
    p.name = name
}

--------------------------------------------------
i compile it with Go compiler 
how compile with Gopherjs ?

**Comment by shurcooL** [comment]
> i compile it with Go compiler 
> how compile with Gopherjs ?

Take a look at the [Installation and Usage section](https://github.com/gopherjs/gopherjs#installation-and-usage) in the README.

**Comment by neelance** [comment]
@myalexer Did you get it running?

**Comment by neelance** [comment]
Closing this because it's stale. Please reopen if something still does not work for you.
