### ISSUE TITLE
Bug with escape analysis and loops

### ISSUE THREAD

**Issue by jeremyschlatter** [gopherjs/gopherjs#250]
For this program:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for i := 0; i < 3; i++ {
		foo(&i)
	}
}

func foo(i *int) {
	fmt.Print(*i)
	time.Sleep(1)
}
```

`go run` prints `012` and `gopherjs run` prints `000`.  Removing the time.Sleep call in `foo` gets rid of the bug, as does manually unrolling the loop in `main`. I think this is related to escape analysis, because for the unrolled loop `&i` is marked as escaping and translates to [this](https://github.com/gopherjs/gopherjs/blob/59a4ddb172c5f03832905c48e017a75f82a07cd2/compiler/expressions.go#L213-L215), but for the original (buggy) loop `&i` is not marked as escaping and instead translates to [this](https://github.com/gopherjs/gopherjs/blob/59a4ddb172c5f03832905c48e017a75f82a07cd2/compiler/expressions.go#L216).

Playground links:
http://play.golang.org/p/mbpenTZOGh
http://www.gopherjs.org/play/#/mbpenTZOGh

**Comment by shurcooL** [comment]
> I think this is related to escape analysis

This looks like a valid issue to me, and I think your analysis is likely correct.

**Comment by neelance** [comment]
Thanks for reporting. I just saw your solution. I actually like that one even more than mine. I'll merge it, okay?

**Comment by jeremyschlatter** [comment]
Sounds good. I just pushed a new version with a test case.

**Comment by jeremyschlatter** [comment]
Though I just saw your test case and like it more than mine :)

**Comment by neelance** [comment]
Merged.
