### ISSUE TITLE
honnef.co/go/js/dom fails to build under gopherjs on go 1.5 beta1

### ISSUE THREAD

**Issue by jmhodges** [gopherjs/gopherjs#251]
Any code that uses (or merely anonymously imports) the honnef.co/go/js/dom package and has built gopherjs will fail to compile the code to js with

    ../../../../../projects/go/src/time/zoneinfo.go:286:9: undeclared name: loadLocation

Example code:

    // +build js
    package main
    
    import (
    	"github.com/gopherjs/gopherjs/js"
    	_ "honnef.co/go/js/dom"
    )
    
    func main() {
    	js.Global.Get("window").Call("nope")
    }

and the command I ran was:

    gopherjs build keys.go

I'm able to build code using the time API correctly. This seems to be just gopherjs and its build tags support, perhaps?

**Comment by jmhodges** [comment]
On my OS X machine that this fails on, the definition of loadLocation is at src/time/zoneinfo_unix.go line 76.

**Comment by shurcooL** [comment]
GopherJS on `master` branch as of right now requires Go 1.4.

There is ongoing work to add support for Go 1.5 on `go1.5` branch, see [here](https://github.com/gopherjs/gopherjs/branches).

Also see #249 which is relevant (it has been merged into `go1.5` branch).

**Comment by jmhodges** [comment]
Ah, shoot. I just had an update with a (hacky) patch. Thanks!

**Comment by udhos** [comment]
How can I "go get" the go1.5 branch?

**Comment by shurcooL** [comment]
You cannot `go get` the go1.5 branch directly. You can `go get` the package, then cd into its folder and `git checkout go1.5`. It will be on non-master branch until you checkout master again, so keep that in mind.

**Comment by udhos** [comment]
Nice! Thanks. go1.5 branch is working properly for me. :-)

**Comment by benechols-wf** [comment]
I checked out the latest go1.5 branch, did a build of gopherjs everything worked.
Went to my code did 'gopherjs build' and got:

../../../../../../../../../../../../usr/local/go/src/testing/testing.go:614:13: StartTrace not declared by package pprof
../../../../../../../../../../../../usr/local/go/src/testing/testing.go:636:3: StopTrace not declared by package pprof

**Comment by shurcooL** [comment]
@benechols-wf That seems very strange, because I had the same problem and fixed it in commit 1bedc70a0de817865445c3092d12ac987c6cb75c.

Can you verify which commit your `gopherjs` repo is on, and that your binary is freshly built?

**Comment by neelance** [comment]
I've tested the changes of 34ceab9 with 1.5beta3. Could someone please confirm?

**Comment by udhos** [comment]
I am running 1.5beta3 with https://github.com/gopherjs/gopherjs/commit/8b960cf008e74b5c8ca387b58d55e3ba14214095

Everything is smooth so far.

**Comment by neelance** [comment]
The `go1.5` branch is merged into `master` now.
