### ISSUE TITLE
Structs are copied even when they are treated as immutable.

### ISSUE THREAD

**Issue by BenLubar** [gopherjs/gopherjs#252]
Passing a struct to a function is much slower than passing the contents of the struct. Skipping the copy for functions that do not set fields or take the address of the struct would improve performance.

Real world example: `(*image.RGBA).SetRGBA`
Toy benchmark: http://www.gopherjs.org/play/#/XeGJN8Ke0i

    BenchmarkStruct 2000000                824 ns/op
    BenchmarkArgs   2000000000               1.04 ns/op

**Comment by shurcooL** [comment]
Added a third benchmark BenchmarkStructPtr, and made it runnable:

http://www.gopherjs.org/play/#/KSmgV3Z4zi

> Skipping the copy for functions that do not set fields or take the address of the struct

How would you determine that?

**Comment by shurcooL** [comment]
Also, if you do a simple operation with the inputs, the overhead becomes a lot less noticeable:

http://www.gopherjs.org/play/#/Y3WOUSOAdg

```
BenchmarkStruct:         10000	    111200 ns/op 
BenchmarkStructPtr:    10000	    113700 ns/op 
BenchmarkArgs:          10000	    110300 ns/op 
```

**Comment by BenLubar** [comment]
I'd hardly call `fmt.Sprintln` "simple" :stuck_out_tongue:

**Comment by shurcooL** [comment]
Ok, let me try with something simpler... I was just worried `_, _, _, _, _ = s.A, s.B, s.C, s.D, s.E` might be optimized away in one case but not another.

**Comment by shurcooL** [comment]
Ok, here's something simpler (that doesn't use reflection):

http://www.gopherjs.org/play/#/JOHeG1_EWL

```
BenchmarkStruct:  5000000	       207 ns/op 
BenchmarkStructPtr: 2000000000	         1.19 ns/op 
BenchmarkArgs: 2000000000	         1.16 ns/op 
```

**Comment by neelance** [comment]
Thanks for the benchmarks. This is a good point. Analyzing for read-only access should not be too hard.

**Comment by shurcooL** [comment]
I've added results of running same benchmark in native Go [above](https://github.com/gopherjs/gopherjs/issues/252#issuecomment-120761825). Interesting that GopherJS+Chrome is slightly faster for BenchmarkStructPtr and BenchmarkArgs cases.

**Comment by neelance** [comment]
Implemented. It would be great if someone could review the analysis code.

**Comment by shurcooL** [comment]
Very nice, it definitely works on the benchmark above. Before and after:

```
$ gopherjs run main.go 
BenchmarkStruct:       2000000	       765 ns/op
BenchmarkStructPtr: 2000000000	         1.22 ns/op
BenchmarkArgs:      2000000000	         1.16 ns/op
$ gopherjs run main.go 
BenchmarkStruct:    2000000000	         1.22 ns/op
BenchmarkStructPtr: 2000000000	         1.21 ns/op
BenchmarkArgs:      2000000000	         1.20 ns/op
```

> It would be great if someone could review the analysis code.

I'm not an expert in that field, but I'll take a look.

**Comment by dominikh** [comment]
```go
package main

type T struct {
	A int
}

func f1(x T) {
	x.A++
}

func main() {
	t := T{1}
	f1(t)
	println(t.A)
}

// $ gopherjs run foo.go
// 2
```

**Comment by dominikh** [comment]
```go
package main

type T struct {
	A int
}

func f1(x T) {
	x.A /= 2
}

func main() {
	t := T{1}
	f1(t)
	println(t.A)
}

// $ gopherjs run foo.go
// 0
```

And so on. There's a lot more assignment operators than just `=`

**Comment by dominikh** [comment]
```go
package main

type T struct {
	X [1]byte
}

func f1(x T) {
	b := [1]byte{1}
	copy(x.X[:], b[:])
}

func main() {
	t := T{}
	f1(t)
	println(t.X[0])
}

// $ gopherjs run foo.go
// 1
```

**Comment by shurcooL** [comment]
What if you take a pointer of something, and modify it via the pointer rather than directly?

More importantly, it's surprising to me that all tests pass despite fundamentally incorrect basic behavior as @dominikh pointed out above. It seems the tests are not as thorough as I thought they were. How does the Go compiler avoid such regressions? Is there another set of tests, aside from the standard library, that exist for testing the Go compiler?

**Comment by dominikh** [comment]
> Is there another set of tests, aside from the standard library, that exist for testing the Go compiler?

`$GOROOT/test` has an extensive test suite for the compiler and runtime, escape analysis, and so on.

**Comment by dominikh** [comment]
```go
package main

import "time"

type T struct {
	X int
}

func f1(x T) {
	time.Sleep(time.Second)
	println(x.X)
}

func main() {
	t := T{}
	go f1(t)
	t.X = 1
	time.Sleep(2 * time.Second)
}

// $ gopherjs run foo.go
// 1
```

**Comment by neelance** [comment]
Reverted for now. @dominikh's first 3 test cases can be fixed easily and the 4th one was already broken before (have to fix it), but I can come up with even nastier test cases that are not easy to fix. The main problem are cases like this:
```
package main

type T struct {
	X int
}

func f1(x T, p *int) {
	*p = 1
	println(x.X)
}

func main() {
	t := T{}
	f1(t, &t.X)
}
```

**Comment by shurcooL** [comment]
Relevant note on why Go compiler `gc` does not do this kind of analysis (provided by @dominikh):

https://groups.google.com/forum/#!topic/golang-nuts/3v-uEJKav0I

(Note that those reasons may be less applicable for GopherJS since it doesn't have parallelism to consider.)

**Comment by neelance** [comment]
The fix for @dominikh's 4th test case was flipping a bool: 43b37e7 ;-)

**Comment by neelance** [comment]
Can't think of a good way to solve my test case. Sorry, @BenLubar.

**Comment by dominikh** [comment]
An idea I'm not sure about: Would it be possible to cache per-type $clone programs, to optimize copying types? At program start/on the first $clone call for a given type/after N calls to $clone for a given type(the exact strategy isn't important here), a specialised $copy routine for a specific type would be created, that avoids the loops and indirections and type checks. Instead, it would use direct field assignments a la `dst.X = src.X.

What's important, however, is that fields are accessed directly, i.e. via `src.X`, not via the `[]` operator. I'm not sure how feasible it would be to create these functions at runtime, or if creating them at runtime would void the performance benefits.

Given the following code and custom $clone function, the benchmark time reduces from 800ns to about 47ns (which is close to the cost of just the function call). 

```go
package foo

import "testing"

type T1 struct {
	X  int
	Y  int
	Z  int
	T2 T2
}

type T2 struct {
	X int
	Y int
	Z int
}

func f1(x T1) {
	_ = x
}

func f2(x, y, z, x2, y2, z2 int) {
	_, _, _ = x, y, z
}

func BenchmarkStruct(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f1(t)
	}
}

func BenchmarkArgument(b *testing.B) {
	var t T1
	for i := 0; i < b.N; i++ {
		f2(t.X, t.Y, t.Z, t.T2.X, t.T2.Y, t.T2.Z)
	}
}
```

```js
var $cloneT1 = function(src, typ) {
  var dst = typ.zero();
  dst.X = src.X;
  dst.Y = src.Y;
  dst.Z = src.Z;

  dst.T2.X = src.T2.X;
  dst.T2.Y = src.T2.Y;
  dst.T2.Z = src.T2.Z;
  return dst;
};
```

**Comment by neelance** [comment]
So far I have refrained from code generation at runtime. But for `$copy`/`$clone` it might be worth it. Could you measure if the performance changes when creating `$cloneT1` via `eval`, please?

**Comment by dominikh** [comment]
Using eval doesn't seem to have any effect on the performance. I should note, however, that I'm currently editing the JS manually (adding the function, and changing calls from $clone to $cloneT1), I'm not dynamically creating/calling these functions.
