### ISSUE TITLE
runtime.Version missing.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#253]
I know that package `runtime` support is define as "partial" in the [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md), but it'd be nice if this function were present.

http://www.gopherjs.org/playground/#/jvlDbk41Wy

```
prog.go:9:14: Version not declared by package runtime 
```

**Comment by neelance** [comment]
Fine with me. It should return `theVersion` of `zversion.go`. PR? :-)

**Comment by shurcooL** [comment]
It's already fixed on the `go1.5` branch. I made this issue just to track it. There's no immediate need to get it resolved sooner.

https://github.com/gopherjs/gopherjs/commit/1bedc70a0de817865445c3092d12ac987c6cb75c#diff-fd8dbdaa26f5a98755ae411b3918db12R170

**Comment by neelance** [comment]
The branch is merged so this is fixed.
