### ISSUE TITLE
Bug with select statement, variable not set when select case with no body receive directly into an existing variable.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#267]
Reporting this as I've just discovered it while writing some Go code. I haven't looked into GopherJS yet, but I am guessing it's more likely an unhanded case rather than a difficult bug to fix.

http://www.gopherjs.org/playground/#/iq0YlL5iQu - exhibits bug
http://play.golang.org/p/iq0YlL5iQu - works ok

Expected output is:

```
Hello, playground
Hello, playground
```

Actual output with GopherJS is:

```
Hello, playground
initial
```

**Comment by shurcooL** [comment]
Ok, it's a bug related to the empty body of the case statement. Inserting any, completely unrelated operations:

```Go
select {
case s = <-ch:
	_ = 123
}
```

Causes the bug to be resolved.

**Comment by neelance** [comment]
Thx for the nice test case.

**Comment by shurcooL** [comment]
Thank you for fixing it so quickly! :)
