### ISSUE TITLE
Compiler does not detect error when duplicate case values in switch statement.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#269]
This is a lower priority, mostly harmless problem. It's a situation where `gc` compiler detects an error, but `gopherjs` compiles successfully. Reporting this issue so it can be tracked.

```
package main

import "fmt"

func main() {
	switch 1 {
	case 1, 1:
		fmt.Println("Hello, playground")
	}
}
```

Expected error:

```
# command-line-arguments
/tmp/sandbox944148505/main.go:7: duplicate case 1 in switch
	previous case at /tmp/sandbox944148505/main.go:7
```

https://play.golang.org/p/_pJNqLHB0p
http://www.gopherjs.org/playground/#/_pJNqLHB0p

Actually, I've looked through the [Go spec](https://golang.org/ref/spec) and I don't quite see it mentioning this explicitly, so current GopherJS behavior may be compliant with the spec.

**Comment by dominikh** [comment]
Upstream issue: https://github.com/golang/go/issues/11578

**Comment by neelance** [comment]
The issue got fixed upstream and will be included in the next release of Go. It is not worth a workaround, so there is nothing we can do right now. Closing.
