### ISSUE TITLE
gopherjs get: Does not work reliably.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#270]
For example:

```bash
$ export GOPATH=/tmp/clean_empty_workspace
$ go get -u github.com/gopherjs/gopherjs
$ $GOPATH/bin/gopherjs get github.com/shurcooL/play/113
cannot find package "honnef.co/go/js/dom" in any of:
	/usr/local/go/src/honnef.co/go/js/dom (from $GOROOT)
	/tmp/clean_empty_workspace/src/honnef.co/go/js/dom (from $GOPATH)
```

On the other hand, using `go get` with `js` build tag works:

```bash
$ go get -d -tags=js github.com/shurcooL/play/113
```

Additionally, `gopherjs get` is missing `-u` flag and some others.

### Proposed Solutions

The logic of `go get` is quite complicated, and it tends to move forward with each point release of Go.

I see clear value to have `gopherjs build`, `gopherjs install` that mimic those commands of `go` tool. `gopherjs serve` is also extremely useful. In constrast, `gopherjs get` seems completely unneeded because you can always use `go get` with `-d` and `-tags=js`, followed by `gophers install` to simulate what `gopherjs get` is expected to achieve:

```bash
# gopherjs get import/path
go get -d -tags=js import/path
gopherjs install import/path
```

At this time, I think the best solution to this issue is to remove `gopherjs get` command. It will mean less maintenance and I think it's simpler for users.

Alternatives are: 

- Make `gopherjs get` work more reliably by shelling out to `go get` (should be quite easy).

- Do all the work of fixing the problems/missing features in source code (would be quite hard IMO, and require much more future maintenance).

**Comment by flimzy** [comment]
Would it be an option to simply have 'gopherjs get' execute 'go get -d tags=js'?

The only advantage, of course, is that 'gopherjs get' is easier to remember.

**Comment by shurcooL** [comment]
Yes, that's the alternative 1 that I mentioned:

> Make `gopherjs get` work more reliably by shelling out to `go get` (should be quite easy).

**Comment by shurcooL** [comment]
> The only advantage, of course, is that 'gopherjs get' is easier to remember.

For me, it's easier to remember `go get -d -tags=js` because I use `go` command often and I know all of its flags and behaviors.

Having to remember what `gopherjs get` does exactly would not be advantageous. Maybe other people have a different opinion.

**Comment by neelance** [comment]
`gopherjs get` IS currently shelling out:
```exec.Command("go", append([]string{"get", "-d"}, pkgs...)...)```
Probably only `-tags=js` is missing.

**Comment by shurcooL** [comment]
I see. That should indeed fix the main problem I've reported, but what about the additional ones, like:

> Additionally, `gopherjs get` is missing `-u` flag and some others.

**Comment by neelance** [comment]
We can also pass those through to the `go` command.

**Comment by neelance** [comment]
`gopherjs get` is for convenience. It now does exactly what you described above:
```
# gopherjs get import/path
go get -d -tags=js import/path
gopherjs install import/path
```
I see no reason to remove it, it's just a few lines of code, nothing fancy. If someone needs more flags, then it's probably best to just fall back to the separate commands. Do you think we need to make this option more obvious?

**Comment by shurcooL** [comment]
>  If someone needs more flags, then it's probably best to just fall back to the separate commands. Do you think we need to make this option more obvious?

I think the help/usage string for `gopherjs get` should say exactly that.
