### ISSUE TITLE
Allow out-of-tree overrides for native packages

### ISSUE THREAD

**Issue by ebroder** [gopherjs/gopherjs#272]
Not exactly sure what the right mechanism is here, but it would be really cool if you could define other overrides for native packages without needing to patch gopherjs directly.

My current use case is that I'm trying to implement support for TCP and UDP connections using Chrome's app APIs (https://developer.chrome.com/apps/sockets_tcp and https://developer.chrome.com/apps/sockets_udp). This will only work in Chrome Apps, so it doesn't make sense as part of gopherjs core.

(There are still some open questions, like "how am I going to deal with DNS resolution?" and "how much of `net.TCPConn` am I willing to stub?", but I think having out-of-tree overrides is probably the first question)

**Comment by shurcooL** [comment]
This is an interesting question in general.

(Also, on the topic of TCP and UDP connections specifically, that is really neat, and I can't wait until normal pages can have access to those APIs when http://www.w3.org/2012/sysapps/tcp-udp-sockets/ is adopted.)

Just as an intermediate solution, you could create your implementation of `net` package with TCP and UDP implemented using Chrome App APIs in a 3rd party package, for example at:

```
github.com/ebroder/tcp
```

Right? And later on, if there's progress on this issue, it can be made into something that can potentially replace/augment the GopherJS natives. I'm probably stating the obvious, but I wanted to say it out loud anyway.

**Comment by ebroder** [comment]
That would definitely work for applications under my control (I could write them to use `github.com/ebroder/tcp` instead of `net.Dial` or whatever), but it wouldn't work for compiling other existing applications, which is part of my goal.

Without being able to override the `*net.TCPConn` implementation, I can't return a `*net.TCPConn` that will actually work, even if I set a custom `Dialer` or something.

**Comment by shurcooL** [comment]
Makes sense, that won't work for libraries out of your control that already import the standard `net` package.

**Comment by neelance** [comment]
I think adding out-of-tree overrides is a feature that would only be used in rare cases. That's why I'd rather not go that way. Instead, what do you think of using https://github.com/whiteout-io/tcp-socket to map the Chrome API to the proposed Socket API and add support for that (if available in environment) to GopherJS itself?

**Comment by neelance** [comment]
Closing this because it is stale and no action on our end planned right now.
