### ISSUE TITLE
GopherJS playground doesn't work

### ISSUE THREAD

**Issue by ip** [gopherjs/gopherjs#273]
Screenshot:
![ehkkh0k](https://cloud.githubusercontent.com/assets/1111008/9392137/87626996-4783-11e5-9c3f-7dd360647057.png)

**Comment by shurcooL** [comment]
What OS (name and version) are you using?

What browser (name and version are you using?

Can you post the output you see in the console?

The playground works without issue for me.

**Comment by ip** [comment]
@shurcooL Yes, strangely it worked, but I have never visited this site before, so don't know how this worked :)

**Comment by shurcooL** [comment]
> Yes, strangely it worked, but I have never visited this site before, so don't know how this worked :)

It might've been some network issue that prevented the page from loading fully. Or another reason.

Closing since issue isn't occurring anymore, but please reopen if it does.
