### ISSUE TITLE
csp lib

### ISSUE THREAD

**Issue by gedw99** [gopherjs/gopherjs#292]
https://github.com/ubolonton/js-csp

wondering is this way of doing blocking calls help with the call stack aspects ?

**Comment by shurcooL** [comment]
Please see https://github.com/gopherjs/gopherjs/issues/107 which I think asks the same question, and also https://github.com/gopherjs/gopherjs/issues/15 which had related discussion.

**Comment by gedw99** [comment]
For #15 a solution was found at the end.

I did not know.

Any example code for trying it out in the repo ?

**Comment by rusco** [comment]
sth. like that ?
http://rusco.github.io/

**Comment by gedw99** [comment]
@rusco 
Yes this is exactly what i am interested in - thanks. It highlights the basic mechanics.

I wonder how much work it would be to abstract out these channels into endpoints. 
The idea is to allow the binding to occur for opengl apps as well as html apps.

I guess the work Endpoint is a semi valid way to think about it, but perhaps message queue is a better paradigm. Once you have the concept of message queues, with immutable data structures within the queue, then you can keep the code cleaner, and also target both opengl client (using maybe gxui) and web clients.

The message queue is not physical, its ore in the app domains or client itself. Its just a way to use the message pump.

I guess this is all leading to reactive, flux and these types of things.

**Comment by neelance** [comment]
Closing, since there seems to be nothing further to do here. @gedw99 Okay to you?

**Comment by gedw99** [comment]
Yep thanks
