### ISSUE TITLE
Panic Buffer Not Cleared

### ISSUE THREAD

**Issue by mackenzieobleness-wf** [gopherjs/gopherjs#299]
### Problem
If we panic in transpiled code, and then handle the error in JavaScript, the original panic will resurface in every subsequent call into the transpiled code. It seems like a buffer or flag is not being reset somewhere.

Is this resolvable? Or is there a better way of indicating panics to JavaScript code?

### Test Program
This program calls two transpiled methods, and displays their results in two paragraphs. The first method panics, and the JavaScript catches and prints the error. However, when the second method (which shouldn't panic), is called, it encounters the panic from the first method.

##### example.go
```go
package main

import (
	"fmt"
	"log"

	"github.com/gopherjs/gopherjs/js"
)

func main() {
	js.Global.Set("bindings", map[string]interface{}{
		"funcOne": FuncOne,
		"funcTwo": FuncTwo,
	})
}

// FuncOne always panics.
func FuncOne() string {
	defer catchError("FuncOne")

	throwError("an error for no good reason")

	return "This string is never returned."
}

// FuncTwo should never panic.
func FuncTwo() string {
	defer catchError("FuncTwo")

	return "This should be returned."
}

// Catch error recovers from a panic, then adds information to the error and panics again
// The JS code should handle the second panic.
func catchError(method string) {
	if r := recover(); r != nil {
		log.Printf("Method %s panicked.", method)
		throwError("Method ", method, " failed: ", r)
	}
}

func throwError(args ...interface{}) {
	err := fmt.Errorf("%s", fmt.Sprint(args...))
	panic(err)
}
```
##### main.js
```javascript
var resultOne, resultTwo;
try {
	resultOne = bindings.funcOne();
	console.log("FuncOne succeeded")
} catch(e) {
	console.log("Caught error from FuncOne:");
	console.log(e);
	resultOne = "FuncOne failed";
}

try {
	resultTwo = bindings.funcTwo();
	console.log("FuncTwo succeeded")
} catch(e) {
	console.log("Caught error from FuncTwo:");
	console.log(e);
	resultTwo = "FuncTwo failed";
}

document.getElementById("func1").innerHTML = resultOne;
document.getElementById("func2").innerHTML = resultTwo;
```

##### page.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>Example</title>
    <script src="./gopherjs_bug.js"></script>
</head>
<body>
    <p id="func1">Function One Result</p>
    <p id="func2">Function Two Result</p>

    <script src="./main.js"></script>
</body>
</html>
```
### Results
The dom shows:
```
FuncOne failed
FuncTwo failed
```
The console shows:
```
2015/09/08 16:26:25 Method FuncOne panicked.
Caught error from FuncOne:
Error: Method FuncOne failed: an error for no good reason(…)
2015/09/08 16:26:25 Method FuncTwo panicked.
Caught error from FuncTwo:
Error: Method FuncTwo failed: Method FuncOne failed: an error for no good reason(…)
```

Ideally, this code would result in the dom showing:
```
FuncOne failed
This should be returned.
```

**Comment by shurcooL** [comment]
Hi @mackenzieobleness-wf, thanks for reporting this issue!

I have just tested it out and I can reproduce it.

I'm still thinking about this, but so far I think this is a legitimate issue in GopherJS that we need to find a way to fix. That second caught panic should not mention "Method FuncOne failed: an error for no good reason(…)", as far as I can tell.

**Comment by neelance** [comment]
Thanks @mackenzieobleness-wf and @shurcooL for reporting and verifying. The given test case could not have been better, so it was easy to track down and fix. :+1:
