### ISSUE TITLE
`gopherjs test ./with/relative/path` failing

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#302]
The `gopherjs test` command fails when I specify an explicit path, while this works with standard `go test`.  A simple proof:

```
$ go test
PASS
ok      github.com/flimzy/flashback     0.003s
$ go test .
ok      github.com/flimzy/flashback     0.005s
```

Similar tests with gopherjs in another directory:

```
$ gopherjs test
PASS
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
ok      github.com/flimzy/flashback/webclient/pages/all 0.319s
$ gopherjs test .
import ".": import relative to unknown directory
```

Of course testing '.' isn't that useful, that just proved a simple test case.  The same happens if I specify a full path:

```
$ go test ./couch/
ok      github.com/flimzy/flashback-server/couch        0.010s
```

And with gopherjs:

```
$ gopherjs test ./webclient/pages/all/
import "./webclient/pages/all/": import relative to unknown directory
```

**Comment by shurcooL** [comment]
This is a known issue, was decided as "wontfix" at the time. See https://github.com/gopherjs/gopherjs/issues/148.

**Comment by shurcooL** [comment]
Also, to correct your terminology, `go test ./couch/` is a relative import path. It's not a full import path. `go test github.com/foo/bar/couch` is a full import path. Relative import paths are those that contain `.` or `..` elements.

**Comment by flimzy** [comment]
Thanks for the explanation.  I hadn't thought to try `github.com/.../`... that's good enough for me.

**Comment by shurcooL** [comment]
I'm going to reopen and resolve this issue. /cc @slimsag

Sure, there's always the workaround of doing:

```
$ gopherjs test $(go list ./...)
```

But that's not nice and not friendly to new people who are used to being able to do things like `go test ./...`.

I've prototyped a fix. It's not the most trivial fix, but still very manageable. Will send a PR soon.
