### ISSUE TITLE
Proposal: Move eventsource bindings into github.com/gopherjs organization.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#308]
I've recently made GopherJS bindings for EventSource API (also known as server-sent events):

https://godoc.org/github.com/shurcooL/eventsource

It currently includes a low-level binding only. I plan to work on a higher level one next (similar to the higher level binding for WebSocket, which has a `Dial` method and implements `net.Conn` interface).

Is it a good idea to move them under `github.com/gohperjs` organization namespace to join the ranks of `websocket`, `webgl` and other GopherJS bindings?

If so, I'm happy to do that. I've published under my personal account for now so the package can be viewed.

**Comment by neelance** [comment]
It is JS core API, so I think it makes sense to add it to the organization. Feel free to do so. :-)

**Comment by shurcooL** [comment]
Done. It lives at https://godoc.org/github.com/gopherjs/eventsource now. :)

I've given Web Gophers team push access, but please use the standard review system, one other person must give LGTM before merging PRs.
