### ISSUE TITLE
Binding generator?

### ISSUE THREAD

**Issue by DAddYE** [gopherjs/gopherjs#31]
Hi there,

I was wondering if there is a tool to generate bindings from js to gopherjs.

Probably we should take a look at https://github.com/borisyankov/DefinitelyTyped and se if there is something we can adapt. No?

**Comment by neelance** [comment]
This is a lot of work and I've got the impression that simple wrappers don't fit well with the Go world, especially since we have support for blocking now. That's why I'm closing this now. If someone is interested in implementing it, go ahead, I would promote such a project in the GopherJS readme.
