### ISSUE TITLE
gopherpen: firefox warns of slow code execution due to js Prototype mutation

### ISSUE THREAD

**Issue by glycerine** [gopherjs/gopherjs#317]
Firefox 41.0.1 on OSX 10.9.5. gopherpen built with go1.5.1.

I'm trying out https://github.com/gopherjs/gopherpen. I added a little text to the assets/index.html.tmpl, then built it with go build -tags=dev. When I run it, the firefox dev console reports the following alarming warning, before (or after, depending on the run), the text "Script is working!"

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

Is gopherjs is modifying the javascript Prototype? Will this may have a serious performance penalty?

Filed https://github.com/gopherjs/gopherpen/issues/1, in case it is gopherpen specific.

![mutating-prototype-firefox-41 0 1-warning-screenshot](https://cloud.githubusercontent.com/assets/445247/10270628/65a8c146-6aac-11e5-8370-dbacaa8248f2.png)

**Comment by shurcooL** [comment]
I've verified it's an issue with the following simple example:

```HTML
<html>
	<head>
		<meta charset="utf-8">
		<script type="text/javascript" src="script.js"></script>
	</head>
	<body></body>
</html>
```

```Go
package main

import "fmt"

func main() {
	fmt.Println("Hello.")
}
```

Compiling that with latest version of `gopherjs` and then opening the html page in latest version of Firefox  Developer Edition (version 43.0a2 (2015-10-04)) prints these warnings in the console:

```
Hello.
unreachable code after return statement
unreachable code after return statement
unreachable code after return statement
...
unreachable code after return statement
unreachable code after return statement
unreachable code after return statement
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
unreachable code after return statement
unreachable code after return statement
unreachable code after return statement
...
```

![image](https://cloud.githubusercontent.com/assets/1924134/10271045/bede3d5c-6ab8-11e5-96a0-7bd7fdef2b85.png)

![image](https://cloud.githubusercontent.com/assets/1924134/10271046/c58525c6-6ab8-11e5-9c96-deebd54541df.png)

**Comment by shurcooL** [comment]
Confirmed fixed.

![image](https://cloud.githubusercontent.com/assets/1924134/10273591/51aa92ec-6ae7-11e5-9e23-1e9fb89f2e2a.png)

Thanks @neelance!

**Comment by hajimehoshi** [comment]
I found these warnings on Firefox 50.1.0 with an application on `gopherjs serve`.

**Comment by shurcooL** [comment]
@hajimehoshi, if it's a real problem, can you please open a new issue with reproduce steps, and link to this one?

It's hard to track it here since this is a closed issue.

**Comment by hajimehoshi** [comment]
Sure. I tried to use http://www.gopherjs.org/play/ to create a minimum case but CSS is not applied... (https://github.com/gopherjs/gopherjs.github.io/issues/63) I'll try later.

**Comment by shurcooL** [comment]
You can use http://www.gopherjs.org/playground until that CSS issue is resolved.

**Comment by hajimehoshi** [comment]
The interesting thing is that Playground itself causes this warning. I'll file this anyway.
