### ISSUE TITLE
Unable to correctly handle certain unicode/utf-8 characters.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#319]
Go source code is Unicode text encoded in UTF-8. ([Source](https://golang.org/ref/spec#Source_code_representation).)

GopherJS fails to process some unicode characters in Go code and emits JavaScript that does not print the correct characters.

I think it fails on "astral planes", or unicode characters that require more than 2 bytes using utf-8 encoding. But this is just a hypothesis from limited evidence/investigation.

Compare:

```JavaScript
console.log("Hello, 世界. 😀!"); // U+1F600 emoji.
```

```Go
package main

import "fmt"

func main() {
	fmt.Println("Hello, 世界. 😀!") // U+1F600 emoji.
}
```

https://play.golang.org/p/M1rXP8bm6L

http://www.gopherjs.org/playground/

(You'll have to manually paste the code into GopherJS Playground. Due to the bug in GopherJS, the snippet cannot be loaded correctly.)

![image](https://cloud.githubusercontent.com/assets/1924134/10359664/88ea60f6-6d4f-11e5-8bc9-d2571767703e.png)

![image](https://cloud.githubusercontent.com/assets/1924134/10359669/9044189c-6d4f-11e5-8102-78c9091f12ec.png)

Thank you to @peggyl for the original report of this issue at https://gist.github.com/peggyl/72d47f6652d30a4f566a!

#### Relevant Reading

- http://www.fileformat.info/info/unicode/char/1f600/index.htm
- https://mathiasbynens.be/notes/javascript-unicode
- https://mathiasbynens.be/notes/javascript-escapes#unicode-code-point
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint

**Comment by siongui** [comment]
I have a function:

```
func GetFirstCharacterOfWord(word string) string {
	runeValue, _ := utf8.DecodeRuneInString(word)
	return string(runeValue)
}
```

when this is compiled to JS by GopherJS (Go 1.12.17), and ḍ (%E1%B8%8D in Chromium console) is given as input, it will return %, which is obviously incorrect. I test the code in Go and it works fine.

Not sure where goes wrong. Please advice! Thanks.
