### ISSUE TITLE
time.Now().String() should work

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#32]
Trying to convert a time.Time object to a string might not work. It is because this seems to need the access to a file where zones are defined if the Time includes a locale. As far as I know, a Time object with UTC (like a Time created by time.Parse()) doesn't cause problems. For example, on my locale machine:

``` go
package main

import (
        "time"
)

func main() {
        print(time.Now().String())
}
```

can be compiled, but the JavaScript file results in:

```
Uncaught Error: syscalls not available test.js:1145
go$panic test.js:1145
go$packages.syscall.syscall syscall_unix.go:33
go$packages.syscall.go$pkg.Syscall syscall_unix.go:41
go$packages.syscall.go$pkg.Open zsyscall_darwin_amd64.go:833
go$packages.time.readFile sys_unix.go:23
go$packages.time.loadZoneFile zoneinfo_read.go:206
go$packages.time.initLocal zoneinfo_unix.go:59
go$packages.sync.Once.Ptr.Do once.go:40
go$packages.time.Location.Ptr.get zoneinfo.go:69
go$packages.time.Time.Ptr.locabs time.go:272
go$packages.time.Time.Ptr.Format format.go:415
go$packages.time.Time.Ptr.String format.go:400
go$packages.main.go$pkg.main test.go:9
(anonymous function) test.go:9
(anonymous function)
```

I wonder if I could use Time object without accessing any files. As JavaScript's Time knows the local locale, time.Now().String() should be able to work.

**Comment by dolanor** [comment]
Hi,
I need to display a time.Duration and on my gopherjs install, a:
```go
d, _ := time.ParseDuration("1m30s")
fmt.Println("%T, %v", d, d)
// prints: "int64, 90000000000"
```
And then, any attempt to call `d.String()` will be faced with: `String is not a function`

I tried on the gopherjs playground, and of course it doesn't have the same behavior. I have `GopherJS 1.12-2`. I don't know if it's linked to this issue or it's something else, and maybe I should open a new issue.

**Comment by theclapp** [comment]
GopherJS tip (3e4dfb77656c424b6d1196a4d5fed0fcf63677cc) with Go 1.12.7 on my mac works for me:

```go
package main

import (
	"fmt"
	"runtime"
	"time"
)

func main() {
	d, _ := time.ParseDuration("1m30s")
	fmt.Printf("%T, %v\n", d, d)
	fmt.Printf("%s\n", d)
	fmt.Printf("%s\n", d.String())
	fmt.Printf("%s\n", runtime.Version())
}
```

prints

```sh
% gopherjs run issue_32.go
time.Duration, 1m30s
1m30s
1m30s
go1.12.7
% gopherjs version
GopherJS 1.12-2
```

Maybe an upgrade would fix things?

**Comment by dolanor** [comment]
Actually, to repeat my use case in a more similar way, I received a `time.Duration` in a struct unmarshaled from `gob` bytes. Trying to call this `time.Duration`'s `String()` function failed with the `String is not a function`.

I found a workaround, which consists of:
```
durationWronglyConsideredAsInt64, _ := GetTimerDuration()
goodDuration := time.Duration(int64(durationWronglyConsideredAsInt64))
```
And then it's rightfully considered as `time.Duration`, and I can call `.String()` on it

(And I tried with just this, and it failed:
```
goodDuration := time.Duration(durationWronglyConsideredAsInt64)
```
)

**Comment by theclapp** [comment]
What's the actual type returned by `GetTimerDuration()`?  I mean, `time.Duration` is just an `int64`, so it's not like there's a complex struct that needs to be initialized (at least from the Go point of view; I think int64s are emulated in GopherJS as two int32's).  If GetTimerDuration isn't returning a `time.Duration`, that seems like the problem right there.

If it _is_ returning a `time.Duration`, well, I don't know what to tell you.  That's weird.

Could you post a full main() function or link to the GopherJS playground that reproduces the problem?

**Comment by dolanor** [comment]
Here is the gopherjs playground:
https://gopherjs.github.io/playground/#/ONanWJXXtL

And the equivalent go playground:
https://play.golang.org/p/91dh16Ry_BK

**Comment by theclapp** [comment]
Y'all this is weird.  From @dolanor's first gopherjs playground link:

```go
type Message struct {
	Duration time.Duration
}

m := Message{Duration: time.Minute}

var buf bytes.Buffer
err := gob.NewEncoder(&buf).Encode(m)
if err != nil {
	panic(err)
}

m2 := Message{}
err = gob.NewDecoder(&buf).Decode(&m2)
if err != nil {
	panic(err)
}
fmt.Printf("m2 => type: %T, value: %v, decimal: %d\n", m2.Duration, m2.Duration, m2.Duration)
// prints m2 => type: int64 [should be time.Duration], value: 60000000000 [should be 1m0s], decimal: 60000000000 [this is fine]
```

So somehow the gob decoder is not setting the type of `m2.Duration` correctly.

Somebody that knows more gopherjs internals than I do is going to have to weigh on this.  Sorry @dolanor.  Might want to open a new issue.
