### ISSUE TITLE
No new variables on left side of :=

### ISSUE THREAD

**Issue by emersion** [gopherjs/gopherjs#326]
The following code doesn't work:

```go
func getMouseCoords(event *js.Object) (x, y int) {
	x := int(event.Get("pageX").Int() / 5)
	y := int(event.Get("pageY").Int() / 5)
	return x, y
}
```

The error message is: `no new variables on left side of :=`

Is this the expected behavior? I thought `(x, y int)` was just an hint, and didn't define variables.

**Comment by flimzy** [comment]
Yes, that is the expected behavior.  See [here](https://golang.org/doc/effective_go.html#named-results).

**Comment by dominikh** [comment]
You get the same behaviour with the official Go compiler. And no, these aren't just "hints" or documentation, they introduce actual local variables in the scope of the function body.

**Comment by emersion** [comment]
Ow, thanks, sorry!
