### ISSUE TITLE
Uint8array to []byte

### ISSUE THREAD

**Issue by sirudog** [gopherjs/gopherjs#329]
First of all, sorry for the lengthy question. I am experimenting with go-capnproto (https://github.com/glycerine/go-capnproto) and gopherjs at the same time, while I am new to golang. 

What I would like to do is to send a capnproto message (binary stream) from the browser, and to decode this stream on the node.js server.
Sending the message from the browser already works: I get a node.js Buffer containing the bytes of the message. But I have problems with the decoding.
I have this function in Go which decodes the byte stream of a message into a LoginRequest object (this is the object generated by go-capnproto lib based on my capnproto schema):
```
func GetLoginRequestFrom(buffer []byte) messages.LoginRequest {
	var request messages.LoginRequest
	segment, _, err := capn.ReadFromMemoryZeroCopy(buffer)
	
	if err != nil {
            return request
        }

    return messages.ReadRootLoginRequest(segment)
}
```
The generated js code for this go func is this:
```
GetLoginRequestFrom = function(buffer) {
		var $ptr, _r, _tuple, buffer, err, request, segment, $s, $r;
		/* */ $s = 0; var $f, $c = false; if (this !== undefined && this.$blk !== undefined) { $f = this; $c = true; $ptr = $f.$ptr; _r = $f._r; _tuple = $f._tuple; buffer = $f.buffer; err = $f.err; request = $f.request; segment = $f.segment; $s = $f.$s; $r = $f.$r; } s: while (true) { switch ($s) { case 0:
		request = new messages.LoginRequest.ptr(ptrType.nil, 0, 0, 0, 0, 0, 0);
		_tuple = capn.ReadFromMemoryZeroCopy(buffer);
		segment = _tuple[0];
		err = _tuple[2];
		if (!($interfaceIsEqual(err, $ifaceNil))) {
			return request;
		}
		_r = messages.ReadRootLoginRequest(segment); /* */ $s = 1; case 1: if($c) { $c = false; _r = _r.$blk(); } if (_r && _r.$blk !== undefined) { break s; }
		return _r;
		/* */ } return; } if ($f === undefined) { $f = { $blk: GetLoginRequestFrom }; } $f.$ptr = $ptr; $f._r = _r; $f._tuple = _tuple; $f.buffer = buffer; $f.err = err; $f.request = request; $f.segment = segment; $f.$s = $s; $f.$r = $r; return $f;
	};
```
I call GetLoginRequestFrom function in node.js like this (msg is of type Buffer that I received from the browser, so I wrap it into a Uint8Array. I do this because to my best knowledge, it is treated as []byte in Go):
```
var array = new Uint8Array(msg);
var deserializedRequest = messages.GetLoginRequestFrom(array);
```
The problem I get is in this line:
```
js:
_tuple = capn.ReadFromMemoryZeroCopy(buffer);
Go:
segment, _, err := capn.ReadFromMemoryZeroCopy(buffer)
```
Here is the source of ReadFromMemoryZeroCopy (https://github.com/glycerine/go-capnproto/blob/master/mem.go)
```
func ReadFromMemoryZeroCopy(data []byte) (seg *Segment, bytesRead int64, err error) {

	if len(data) < 4 {
		return nil, 0, io.EOF
	}

	if binary.LittleEndian.Uint32(data[0:4]) >= uint32(MaxSegmentNumber) {
		return nil, 0, ErrTooMuchData
	}

	segnum := int(binary.LittleEndian.Uint32(data[0:4]) + 1)
	hdrsz := 8*(segnum/2) + 4

	b := data[0:(hdrsz + 4)]

	total := 0
	for i := 0; i < segnum; i++ {
		sz := binary.LittleEndian.Uint32(b[4*i+4:])
		if uint64(total)+uint64(sz)*8 > uint64(MaxTotalSize) {
			return nil, 0, ErrTooMuchData
		}
		total += int(sz) * 8
	}
	if total == 0 {
		return nil, 0, io.EOF
	}

	hdrv := data[4:(hdrsz + 4)]
	datav := data[hdrsz+4:]
	m := &multiBuffer{make([]*Segment, segnum)}
	for i := 0; i < segnum; i++ {
		sz := int(binary.LittleEndian.Uint32(hdrv[4*i:])) * 8
		m.segments[i] = &Segment{m, datav[:sz], uint32(i), false}
		datav = datav[sz:]
	}

	return m.segments[0], int64(4 + hdrsz + total), nil
}
```
Which is converted to js like this:
```
ReadFromMemoryZeroCopy = function(data) {
		var $ptr, _q, _tmp, _tmp$1, _tmp$10, _tmp$11, _tmp$12, _tmp$13, _tmp$14, _tmp$2, _tmp$3, _tmp$4, _tmp$5, _tmp$6, _tmp$7, _tmp$8, _tmp$9, b, bytesRead, data, datav, err, hdrsz, hdrv, i, i$1, m, seg, segnum, sz, sz$1, total, x, x$1, x$2, x$3, x$4, x$5;
		seg = ptrType.nil;
		bytesRead = new $Int64(0, 0);
		err = $ifaceNil;
		if (data.$length < 4) {
			_tmp = ptrType.nil;
			_tmp$1 = new $Int64(0, 0);
			_tmp$2 = io.EOF;
			seg = _tmp;
			bytesRead = _tmp$1;
			err = _tmp$2;
			return [seg, bytesRead, err];
		}
		if (binary.LittleEndian.Uint32($subslice(data, 0, 4)) >= ($pkg.MaxSegmentNumber >>> 0)) {
			_tmp$3 = ptrType.nil;
			_tmp$4 = new $Int64(0, 0);
			_tmp$5 = $pkg.ErrTooMuchData;
			seg = _tmp$3;
			bytesRead = _tmp$4;
			err = _tmp$5;
			return [seg, bytesRead, err];
		}
		segnum = ((binary.LittleEndian.Uint32($subslice(data, 0, 4)) + 1 >>> 0) >> 0);
		hdrsz = (8 * ((_q = segnum / 2, (_q === _q && _q !== 1/0 && _q !== -1/0) ? _q >> 0 : $throwRuntimeError("integer divide by zero"))) >> 0) + 4 >> 0;
		b = $subslice(data, 0, ((hdrsz + 4 >> 0)));
		total = 0;
		i = 0;
		while (true) {
			if (!(i < segnum)) { break; }
			sz = binary.LittleEndian.Uint32($subslice(b, ((4 * i >> 0) + 4 >> 0)));
			if ((x = (x$1 = new $Uint64(0, total), x$2 = $mul64(new $Uint64(0, sz), new $Uint64(0, 8)), new $Uint64(x$1.$high + x$2.$high, x$1.$low + x$2.$low)), x$3 = new $Uint64(0, $pkg.MaxTotalSize), (x.$high > x$3.$high || (x.$high === x$3.$high && x.$low > x$3.$low)))) {
				_tmp$6 = ptrType.nil;
				_tmp$7 = new $Int64(0, 0);
				_tmp$8 = $pkg.ErrTooMuchData;
				seg = _tmp$6;
				bytesRead = _tmp$7;
				err = _tmp$8;
				return [seg, bytesRead, err];
			}
			total = total + (((sz >> 0) * 8 >> 0)) >> 0;
			i = i + (1) >> 0;
		}
		if (total === 0) {
			_tmp$9 = ptrType.nil;
			_tmp$10 = new $Int64(0, 0);
			_tmp$11 = io.EOF;
			seg = _tmp$9;
			bytesRead = _tmp$10;
			err = _tmp$11;
			return [seg, bytesRead, err];
		}
		hdrv = $subslice(data, 4, ((hdrsz + 4 >> 0)));
		datav = $subslice(data, (hdrsz + 4 >> 0));
		m = new multiBuffer.ptr($makeSlice(sliceType$15, segnum));
		i$1 = 0;
		while (true) {
			if (!(i$1 < segnum)) { break; }
			sz$1 = (binary.LittleEndian.Uint32($subslice(hdrv, (4 * i$1 >> 0))) >> 0) * 8 >> 0;
			(x$4 = m.segments, ((i$1 < 0 || i$1 >= x$4.$length) ? $throwRuntimeError("index out of range") : x$4.$array[x$4.$offset + i$1] = new Segment.ptr(m, $subslice(datav, 0, sz$1), (i$1 >>> 0), false)));
			datav = $subslice(datav, sz$1);
			i$1 = i$1 + (1) >> 0;
		}
		_tmp$12 = (x$5 = m.segments, (0 >= x$5.$length ? $throwRuntimeError("index out of range") : x$5.$array[x$5.$offset + 0]));
		_tmp$13 = new $Int64(0, ((4 + hdrsz >> 0) + total >> 0));
		_tmp$14 = $ifaceNil;
		seg = _tmp$12;
		bytesRead = _tmp$13;
		err = _tmp$14;
		return [seg, bytesRead, err];
	};
```
My understanding of []byte in Go is that it is a slice on a byte array, so I expect that if I pass my Uint8Array to GetLoginRequestFrom function in the converted js code , it will be represented as a slice (with all its properties like $array, $offset, $length...)  But I see that the buffer param is not converted into a slice ([]byte), which causes an exception thrown by the ReadFromMemoryZeroCopy function: TypeError: Cannot read property 'NaN' of undefined
Obviously, the data parameter passed to this function is not a slice, it is still of type Uint8Array, so data.$length will result 'undefined' in this line: 
```
if (data.$length < 4)
```
I have two workarounds for this problem:
1. Change the generated js code by forcing the slicing of the buffer:
```
_tuple = capn.ReadFromMemoryZeroCopy(new sliceType(buffer));
```
where sliceType is defined like:
```
sliceType = $sliceType($Uint8);
```
2.Change my function in Go by using an array as the buffer param, and making a slice manually by buffer[:] :
```
func GetLoginRequestFrom(buffer [64]byte) messages.LoginRequest {
	var request messages.LoginRequest
	segment, _, err := capn.ReadFromMemoryZeroCopy(buffer[:])
	
	if err != nil {
            return request
    }

    return messages.ReadRootLoginRequest(segment)
}
```
then gopherjs generates the correct js code which just works:
```
GetLoginRequestFrom = function(buffer) {
		var $ptr, _r, _tuple, buffer, err, request, segment, $s, $r;
		/* */ $s = 0; var $f, $c = false; if (this !== undefined && this.$blk !== undefined) { $f = this; $c = true; $ptr = $f.$ptr; _r = $f._r; _tuple = $f._tuple; buffer = $f.buffer; err = $f.err; request = $f.request; segment = $f.segment; $s = $f.$s; $r = $f.$r; } s: while (true) { switch ($s) { case 0:
		buffer = $clone(buffer, arrayType$1);
		request = new messages.LoginRequest.ptr(ptrType.nil, 0, 0, 0, 0, 0, 0);
		_tuple = capn.ReadFromMemoryZeroCopy(new sliceType(buffer));
		segment = _tuple[0];
		err = _tuple[2];
		if (!($interfaceIsEqual(err, $ifaceNil))) {
			return request;
		}
		_r = messages.ReadRootLoginRequest(segment); /* */ $s = 1; case 1: if($c) { $c = false; _r = _r.$blk(); } if (_r && _r.$blk !== undefined) { break s; }
		return _r;
		/* */ } return; } if ($f === undefined) { $f = { $blk: GetLoginRequestFrom }; } $f.$ptr = $ptr; $f._r = _r; $f._tuple = _tuple; $f.buffer = buffer; $f.err = err; $f.request = request; $f.segment = segment; $f.$s = $s; $f.$r = $r; return $f;
	};
``` 
But this forces me to set the length of the buffer parameter, something I want to avoid, as the size of the message sent by the browser can be anything. Also I see an extra $clone call on the buffer parameter, which I also want to avoid.

So I prefer option 1, as it is more usable, it looks also more efficient, but it feels bad that I have to change the generated js code.

So my questions are:
- Am I doing it the proper way? Or does it make any sense at all to do it like this? 
- Is it efficient to do this capnp binary stream decoding like I do? (without copying arrays, etc) How could I make it better/faster?
- Do I understand correctly that a Uint8Array is represented as []byte in Go, which is a slice on the typed array? If so, why do I have to manually change the generated js code to make this conversion?
- Can I achieve my goal without changing the generated js code?

Hope it was not boring to read and I made myself clear enough to get some help, which I would really appreciate :-)
Thanks

**Comment by shurcooL** [comment]
> Can I achieve my goal without changing the generated js code?

Yes, I think you should be able to. You shouldn't have to manually edit generated output.

> Do I understand correctly that a Uint8Array is represented as []byte in Go, which is a slice on the typed array? If so, why do I have to manually change the generated js code to make this conversion?

Have you seen https://godoc.org/github.com/gopherjs/gopherjs/js already? I'm guessing you have, but that's where this conversion behavior is documented.

It's true that `Uint8Array` type in JavaScript world maps to `[]byte` type in Go world. However, they're not the same. One can become the other via an internalization/externalization process.

If you have a JavaScript variable named `myJSArray` that is of type `Uint8Array` (in normal JavaScript), then here's how you can access it and _convert_ it to a `[]byte` inside Go code:

```Go
var jsArray *js.Object = js.Global.Get("myJSArray") // This is your actual JavaScript object, represented as *js.Object in Go.

var goSlice []byte = jsArray.Interface().([]byte)
```

Basically, you use `js.Object.Interface()` method and a type assertion. It's documented [here](https://godoc.org/github.com/gopherjs/gopherjs/js#Object.Interface).

However, this mapping and internalization/externalization is taken care for you automatically if you make your Go func available to the JavaScript world. You can do:

```Go
func main() {
	js.Global.Set("ReadFromMemoryZeroCopy", ReadFromMemoryZeroCopy)
}
```

That will make the Go version of `ReadFromMemoryZeroCopy` available to your JavaScript code, and you can call it with a `Uint8Array` parameter (it'll internalize it to `[]byte`).

I suggest you read this section of the README:

https://github.com/gopherjs/gopherjs#providing-library-functions-for-use-in-other-javascript-code

Connecting the JS and Go worlds can be tricky at first, but once you figure it out, it will all make sense.

Also, you might want to do more things in Go and fewer things in JS, that'll let you avoid having to worry about these conversions.

Let me know if that helps. If you're still having trouble, post here again and I'll be happy to provide more specific details.

**Comment by sirudog** [comment]
Wow, that was a quick and spot on help! Thanks a lot! It all works now  :+1:
Just for the record, my Go func looks like this, and then I get the correct js code which just works:
```
func GetLoginRequestFrom(buffer []byte) *js.Object {
	var request messages.LoginRequest
	segment, _, err := capn.ReadFromMemoryZeroCopy(buffer)
	
	if err != nil {
        return js.MakeWrapper(request)
    }

    return js.MakeWrapper(messages.ReadRootLoginRequest(segment))
}
```
Regarding the documentation you linked here, I have read it and also checked that example where the MakeWrapper function is used, but it was not obvious somehow to me if it was something I needed to use, and if so, how to use it in my case. (Maybe it is just me...) But now it all makes sense.

And finally, as a side-note, this combination of librabries (go-capnroto, gopherjs, some go wrapper functions) is the only workable solution at the moment for using capnproto in the javascript/node.js world.  But I'll keep an eye on the native js implementations...
