### ISSUE TITLE
GopherJS source doesn't play well with godoc.org

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#337]
I've noticed that when we use only the `js` build target in a `.go` file, it causes [godoc.org](https://godoc.org) to ignore it.  This brings up the question of whether we care, and if so, how we want to address this issue.

As an example: https://godoc.org/github.com/gopherjs/jsbuiltin

Is this something the godoc team might be persuaded to support? Or is it something we need to address on our own by coming up with some sort of work-around or best practice?

**Comment by shurcooL** [comment]
> Is this something the godoc team might be persuaded to support?

I think there's a chance.

godoc.org already supports Windows-only packages.

**Comment by shurcooL** [comment]
I think you should open this issue on the issue tracker there.

https://github.com/golang/gddo/issues

**Comment by flimzy** [comment]
Done. https://github.com/golang/gddo/issues/342

**Comment by shurcooL** [comment]
https://github.com/golang/gddo/issues/342 has been resolved! \o/

As soon as godoc.org is redeployed, https://godoc.org/github.com/gopherjs/jsbuiltin should start working (and we can close this issue then).

**Comment by shurcooL** [comment]
godoc.org has been redeployed and this issue is resolved.

https://godoc.org/github.com/gopherjs/jsbuiltin is now working.
