### ISSUE TITLE
Windows Issue: gopherjs test ... does fail under Windows

### ISSUE THREAD

**Issue by rusco** [gopherjs/gopherjs#342]
Probably related to #341 : 

``` go
//file dummy_test.go:

package dummy

import "testing"

func TestNothing(t *testing.T) {
}
```
### go test ...pathtodummypackage

gives: **ok**
### gopherjs test ......pathtodummypackage

gives: **FAIL**

without any further info.
(Win7, 64/Node 4.2.1+sourcemap).
There are no syscalls involved while testing, right ?

**Comment by flimzy** [comment]
This may be fixed now. See https://github.com/gopherjs/gopherjs/pull/710#issuecomment-1601548466

**Comment by nevkontakte** [comment]
Our CI runs smoke tests on Windows and they don't exhibit this bug, so I think it is indeed fixed.
