### ISSUE TITLE
Expose error type to external JavaScript

### ISSUE THREAD

**Issue by spamguy** [gopherjs/gopherjs#345]
It could be I'm doing this wrong, but it's not obvious what the workaround would be.

The Go library I'm working with has a number of X-to-error maps. When I say 'error', I mean the actual type.
```
type State struct {
	resolutions   map[common.Province]error
}
```
GopherJS does not seem to be exposing errors to external JavaScript. If I dig into `resolutions` before GopherJS code exits, I can see the error's value a few levels down. If I wrap `resolutions` in `js.MakeWrapper()`, the resulting values in the JS object are generic objects. Example output:
```
> JSON.stringify(js.MakeWrapper(state).Resolutions())
"{"NTH":{}}"
```

**Comment by neelance** [comment]
`error` is a Go interface, so the externalized value depends on the concrete type of its value. If the type has no exported fields, then you'll end up with an empty JS object.

**Comment by spamguy** [comment]
Sorry for the slow response.

As best I can tell errors are being generated through fmt.Errorf(). That's little more than a string, no? As an example, an error generated through Errorf() has one property in generated JS called `s` with the error message. After passing through `js.MakeWrapper()`, the property is scrubbed, leaving just `{ }`.

**Comment by neelance** [comment]
>  an error generated through Errorf() has one property in generated JS called `s` with the error message

An error generated by Errorf() is a Go value, not a JS value, so it has no defined JS properties, it may only have Go fields. Only exported Go fields are turned into JS properties when externalizing, a Go field with the name `s` will thus not be externalized.
