### ISSUE TITLE
Error not returned in templates for undefined

### ISSUE THREAD

**Issue by vron** [gopherjs/gopherjs#346]
Hi,

Just wanted to let you know of an issue I have found which I think is a bug, consider the difference between the two outputs below:

https://play.golang.org/p/nAR5GNUDa-
http://www.gopherjs.org/playground/#/6p7zRGb_5q

**Comment by shurcooL** [comment]
That's definitely a bug, thanks for reporting.

The GopherJS playground doesn't continue execution past the `tt, err = tt.Parse(str)` line, yet there are no errors being throw in JS console either.

I have a guess it could be related to nil functions and/or reflection. But it could be other things.
