### ISSUE TITLE
Pointers become null

### ISSUE THREAD

**Issue by alexandreStein** [gopherjs/gopherjs#348]
Hello, 

I maybe use GopherJS the wrong way, but I'm trying to user pointer in a package and the JS result is **null**.

I made an example at [GopherJS playground](http://www.gopherjs.org/play/#/8nj9N2j5OC).

Is that normal or not?

Thank you in advance.
Best regards

**Comment by shurcooL** [comment]
Why did you include `js.Object` here?

```Go
type MetaData struct {
	Name   string
	Fields []*MetaData

	Root bool

	js.Object
}
```

It doesn't seem needed in this case (unless you're trying to achieve something else). Also, if you were to use it, it needs to be a pointer `*js.Object`.

Change your `MetaData` struct definition to:

```Go
type MetaData struct {
	Name   string
	Fields []*MetaData

	Root bool
}
```

And it [fixes](http://www.gopherjs.org/play/#/YJIKO5xPga) your problem:

```
Var: [{meta [] false}] 
Pointer: [0x1]
```

Output is the same as on [Go Playground](http://play.golang.org/p/YJIKO5xPga).

**Comment by alexandreStein** [comment]
Thank you, I was simply badly using GopherJS.

Sorry for that.
