### ISSUE TITLE
[FATAL ERROR] variable shadowing of the constructor functions in *.inc.js

### ISSUE THREAD

**Issue by Archs** [gopherjs/gopherjs#351]
A typical javascript module would contains the following boilerplate to support `AMD loading` and direct usage as a normal script tag:
```javascript
(function(factory) {
    //AMD
    if (typeof define === "function" && define.amd) {
        define(["knockout", "exports"], factory);
    //normal script tag
    } else {
        factory(ko);         // ko from global javascript namespace 
    }
})(function(ko, exports) {  // using ko as real argument
    var t = ko.observable(123);
    ko.testVar = "testVar in a.inc.js";
   // other function goes here
    console.log("in a.inc.js:", t());
});
```
When this code is in one *.inc.js files, the following `gopherjs js code` would be produced:
```javascript
$packages["github.com/Archs/js/examples/incTest/a"] = (function() {
	var $pkg = {}, $init, ko, js, Hello; // ko here is the imported golang package name, 
          // which shadows the real ko in global javascritp namespace
	(function() {
(function(factory) {
    //AMD
    if (typeof define === "function" && define.amd) {
        define(["knockout", "exports"], factory);
    //normal script tag
    } else {
        factory(ko);  // notice, variable shadowling happends here
    }
})(function(ko, exports) {    // notice here, ko is shadowed
    var t = ko.observable(123);
    ko.testVar = "testVar in a.inc.js";
    console.log("in a.inc.js:", t());
});

}).call($global);
ko = $packages["github.com/Archs/js/gopherjs-ko"];  // here is what variable ko is used for
js = $packages["github.com/gopherjs/gopherjs/js"];
... // more line to go
```

When you run the code above code, error happeds and the script execution aborts:
```
Uncaught TypeError: Cannot read property 'observable' of undefined   // this is the results of variable shadowing
```

The fact is that when an imported golang package has the same name as the variables of the entrance function contained in the `js moduels` of the `*.inc.js` files, it will result in this fatal error.

Since we'd better not modify the javascript library we included, would it be ok if the golang package names are mangled in `gopherjs generated code` :question:

**Comment by Archs** [comment]
package name alias would affect the generated code:
``` javascript
import (
	kko "github.com/Archs/js/gopherjs-ko"
)
```

**Comment by neelance** [comment]
A solution might be to include the .inc.js files at a different scope than the generated code. That way, the included code could not access the generated code directly, which might be a good idea.

**Comment by Archs** [comment]
Yeah, That's good! That would be of great use especially when wrapping js package with plugins :smile:
