### ISSUE TITLE
Cannot locate zgoos_darwin.go in dev version of Go

### ISSUE THREAD

**Issue by adg** [gopherjs/gopherjs#355]
`$GOROOT/src/runtime/zgoos_darwin.go` and the like have been [moved to the `runtime/internal/sys` package](https://go-review.googlesource.com/#/c/16817/), and so gopherjs prints this error:

```
$ gopherjs build -m app.go
stat /Users/adg/go/src/runtime/zgoos_darwin.go: no such file or directory
```

The workaround is to use Go 1.5. But this change will be in Go 1.6, so this issue should track the changes to gopherjs required to accommodate this change.

**Comment by shurcooL** [comment]
Thanks for reporting this Andrew.

The way GopherJS has handled changes between Go releases in the past, when the new release gets close, there's usually a new branch (like `go1.6`) that will have the fixes for that new release.

The current `master` branch definitely requires Go 1.5, so you'll need to use that.

Perhaps now's a good time to start the `go1.6` branch and start testing for compatibility and fixing issues like this one. It's up to @neelance.

**Comment by h8liu** [comment]
Is it ready yet?

**Comment by shurcooL** [comment]
@h8liu Not yet. See the `go1.6` branch for latest state.
