### ISSUE TITLE
Gratipay ?

### ISSUE THREAD

**Issue by rusco** [gopherjs/gopherjs#356]
Wouldn't it be a good idea to set up a Gratipay (former Gittip) account for the gopherjs compiler ?

**Comment by shurcooL** [comment]
I think this is largely up to Richard.

In theory, the new model of Gratipay is an excellent fit for this kind of project. If there are people/companies that want to support GopherJS, they could put money towards the GopherJS team on Gratipay, and people who are contributing to the project and want to use that money could pull it in.

**Comment by whit537** [comment]
You can [apply here](https://gratipay.com/new). Happy to answer any questions! :-)

**Comment by neelance** [comment]
Sorry, but I don't think this model makes any real difference. This is my open source work, I do it for free and that's okay with me. It got me an awesome job and some recognition, can't ask for more. ;-)
