### ISSUE TITLE
Import cycle not allowed error

### ISSUE THREAD

**Issue by jbuberel** [gopherjs/gopherjs#357]
This morning [2015-12-03], I tried doing a clean install of gopherjs on an OSX laptop running go1.5.

Received this error:

```
$ go get -u github.com/gopherjs/gopherjs
../go15/src/net/http/h2_bundle.go:26:2: cannot find package "golang.org/x/net/http2/hpack" in any of:
	/Users/jbuberel/go15/src/golang.org/x/net/http2/hpack (from $GOROOT)
	/Users/jbuberel/workspace-shared/src/golang.org/x/net/http2/hpack (from $GOPATH)
	/Users/jbuberel/workspace/src/golang.org/x/net/http2/hpack
import cycle not allowed
package github.com/gopherjs/gopherjs
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
```

My environment information:

```
$ go version
go version go1.5 darwin/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jbuberel/workspace-shared:/Users/jbuberel/workspace"
GORACE=""
GOROOT="/Users/jbuberel/go15"
GOTOOLDIR="/Users/jbuberel/go15/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

```

**Comment by shurcooL** [comment]
Hi Jason,

Thanks for reporting this.

I also have OS X, Go 1.5.1, and running `go get -u github.com/gopherjs/gopherjs` works [without issues](http://virtivia.com:27080/7gvvyrbf15sb.txt) for me right now (even in an empty GOPATH workspace).

Based on the error report you've shared, I am guessing there's something wrong with your Go 1.5 installation. Note how it says:

> ../go15/src/net/http/h2_bundle.go:26:2: cannot find package "golang.org/x/net/http2/hpack" in any of:

I know that http2 is a part of upcoming Go 1.6, bundled into net/http. However, it should not be a part of of Go 1.5 tree. I'm guessing you had tip installed previously and it's somehow getting in the way (left over files remaining, maybe if you copied 1.5 on top of 1.6?).

I recommend you try these steps:

1. Clear your GOPATH/pkg folders to ensure no stale (or built with wrong compiler version) archive files are getting in the way. You have 2 workspaces in your GOPATH, so be sure to clear both. This is harmless as they will be created during next time you go install stuff.

2. If that doesn't work, completely remove your current Go installation and reinstall it again, to make sure it's clean.

I believe that should fix your problem, so running `go get -u github.com/gopherjs/gopherjs` again should just work, but please let us know if not.

**Comment by jbuberel** [comment]
You were correct - it was a local env problem. Now fixed.

**Comment by shurcooL** [comment]
Great to hear that!
