### ISSUE TITLE
Exposing some file operations in a nodejs environment

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#372]
I want to read some files from disk for some of my tests, but `os.Open()` isn't working, as GopherJS doesn't support system calls. I've solved my immediate issue by using Node's `fs` module.  Is there a better way I'm unaware of?

Assuming there's not a better way, I'd like to discuss some possible solutions:

It seems to me that most file-related functionality of Go's `os` package would be fairly easily emulated with [Node's `fs` module](https://nodejs.org/api/fs.html).  Certain parts could likely also be emulated using the [File API](https://developer.mozilla.org/en-US/docs/Web/API/File) in browsers.

Would it be reasonable to flesh out GopherJS's `os` package in this way?

I expect certain low-level functionality wouldn't always work (neither node nor the File API appear to support seeking, for instance), but for many simple operations (opening and reading a file, in particular), I expect this could be quite nice, and fairly easy to implement.

What are your thoughts?

**Comment by shurcooL** [comment]
> I want to read some files from disk for some of my tests, but `os.Open()` isn't working, as GopherJS doesn't support system calls. I've solved my immediate issue by using Node's `fs` module.  Is there a better way I'm unaware of?

Are you aware of https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md? It's mentioned in the README:

> For system calls (file system access, etc.), see [this page](https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md).

**Comment by flimzy** [comment]
I was not aware of that, thanks.  I'll take a look at that.
