### ISSUE TITLE
js.Global.Set("$", ...) doesn't work

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#374]
For some tests, I have a need to set the global `$` variable (I'm setting up some jQuery mocks), and it's not working, thanks to [this code](https://github.com/gopherjs/gopherjs/blob/master/compiler/expressions.go#L593):

					globalRef := func(id string) string {
						if recv.String() == "$global" && id[0] == '$' {
							return id
						}
						return recv.String() + "." + id
					}

I can work around this by calling `js.Global.Set("$global.$", ...)` instead, which is good enough for me, now that I found the solution.  But it makes me wonder if it could be improved.

At the very least, perhaps `$` could be a special-case exception to the special case, since we know GopherJS doesn't use `$` alone, and many other libraries do, so it is likely the most common use case.

Another option might be to allow some sort of escape sequence to indicate a literal $. Perhaps a variable name beginning with `$$` would be treated as `$`. Likely something more appropriate could be thought of.

At the very least, I'd suggest a documentation update (at least in the gopherjs/js package's description of the `Set()` and `Get()` methods).  I'd be happy to submit a PR with the documentation fixes, but I'll wait to see if a behavioral change is in order first.

**Comment by shurcooL** [comment]
I'm not familiar with the context, but I wonder if `id[0] == '$'` was meant to be `(len(id) > 1 && id[0] == '$')` instead?

Note that it's not the same as `strings.HasPrefix`. It's more like `HasPrefixButDoesntEqualPrefix`.
