### ISSUE TITLE
defer + go routine/channel + blocking = possible crash

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#381]
When I uncommented the Example-executing code in #380, I ran into the following bug, which I have now condensed into a minimal reproduction case.  It may be that I'm running into GopherJS's limitation that the main Go routine can't block, but even in that case, some more informative and consistent error reporting would be nice.

Here's the code:

    package main

    import "fmt"

    func main() {
        foo()
    }

    func foo() {
        outC := make(chan string)
        go func() {
            outC <- ""
        }()

        defer func() {
            _ = <-outC
        }()

        fmt.Printf("Some output. Without this, GopherJS hangs.\n")
        return
    }

Go:

    Some output. Without this, GopherJS hangs

GopherJS:

    gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
    Some output. Without this, GopherJS hangs
    /home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:1473
          throw err;
          ^

    TypeError: _r.$blk is not a function
        at Object.$packages.main.foo [as $blk] (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:16211:137)
        at Object.$packages.main.main [as $blk] (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:16186:66)
        at Object.$packages.main.$init [as $blk] (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:16223:68)
        at fun (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:1465:37)
        at $goroutine (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:1463:19)
        at $runScheduled [as _onTimeout] (/home/jonhall/go/src/github.com/flimzy/extest/extest.go.328785025:1501:7)
        at Timer.listOnTimeout (timers.js:92:15)

Note in particular that in the deferred function, `err := recover()` happens before the blocking code `_ = <-outC`, which leads to the appearance that the error is not related to blocking code.  However, if I remove the blocking operation, by commenting out `_ = <-outC`, the code executes successfully in GopherJS as well.

Also, if I comment out the only `fmt.Printf` line (leaving `_ = <-outC` in place), the execution simply hangs, rather than generating an error.

**Comment by flimzy** [comment]
I have made some progress on debugging this.  Still no solid solution yet.

From the above .go source, GopherJS creates three transpiled JS functions:

1. `foo = function() { ...` (also of note, this has two cases, case 0 and case 1)
2. `$go((function(outC) { return function $b() { ...`
3. `$deferred.push([(function(outC) { return function $b() { ...`

Program execution runs like this:

* #1, case 0 executes
  At this stage, #2 and #3 are also defined, and pushed on to their appropriate stacks
* #1 case 1 executes and returns, as it should
* #3 begins running, but is blocked waiting for input to the `outC` channel, so it `break`s
* Now #1 case 1 executes a second time, causing the crash

By editing the JS output directly, I was able to avoid the crash by adding `$s = 2;` right before the relevant return in function #1:

    @@ -16206,6 +16206,7 @@
                    }; })(c), []]);
                    _r = fmt.Printf("abcdefg\n", new sliceType([])); /* map[0xc82010d890:true 0xc820110d00:true 0xc820110dd0:true 0xc8201303c0:true 0xc820110db0:true 0xc820110e20:true 0xc820130480:true 0xc820110d20:true 0xc82010d860:true 0xc8201340c0:true 0xc820130400:true] */ $s = 1; case 1: if($c) { $c = false; _r = _r.$blk(); } if (_r && _r.$blk !== undefined) { break s; }
                    _r;
    +        $s = 2;
                    return;
                    /* */ }/* 3 */ return; } } catch(err) { $err = err; $s = -1; } finally { $callDeferred($deferred, $err); if($curGoroutine.asleep) {/* FOO: %!s(int=11) */  if ($f === undefined) { $f = { $blk: foo }; } $f.$ptr = $ptr; $f._r = _r; $f.c = c; $f.$s = $s; $f.$deferred = $deferred; $f.$r = $r; return $f; } }
            };

This may or may not be the "proper" solution, but it does prevent the last chunk of the `foo()` function from executing again.

**Comment by flimzy** [comment]
This is proving beyond my ability to effectively troubleshoot. I may continue looking into it, but it's proving more an educational exercise than an effective bugfixing one.  I'm sure @neelance would be much better able to solve this--hopefully easily.

**Comment by shurcooL** [comment]
I can reproduce this too.

I ran into this when implementing a blocking `Close() error` method, which is being called via `defer resp.Body.Close()`.

If I re-write it to call `resp.Body.Close()` without defer, the issue goes away.

This is probably related to #426 as well.

**Comment by shurcooL** [comment]
> When I uncommented the Example-executing code in #380, I ran into the following bug, which I have now condensed into a minimal reproduction case.  

When working on #388 today with @neelance, I got to the point of trying examples and ran into the same issue. I've pretty much reduced it to the same minimal reproduce case as @flimzy, which needs to be resolved to make progress.

But I noticed one extra observation about the MRC that I'll share here. I noticed it was only happening under the following conditions:

1. There is a deferred func that is blocking.
2. There is a return value.

Your sample does not have a return value, but it does have a return statement, which is needed to reproduce the issue.

Put simply, this works without issues:

```Go
func run() {
	ch := make(chan struct{})
	go func() { ch <- struct{}{} }()
	defer func() { <-ch }()
	fmt.Println("stuff")
}
```

However, adding a `return` makes it produce `TypeError: _r.$blk is not a function` error:

```Go
func run() {
	ch := make(chan struct{})
	go func() { ch <- struct{}{} }()
	defer func() { <-ch }()
	fmt.Println("stuff")
	return
}
```

Similarly, it also produces that error if there's a return value:

```Go
func run() bool {
	ch := make(chan struct{})
	go func() { ch <- struct{}{} }()
	defer func() { <-ch }()
	fmt.Println("stuff")
	return true
}
```

The surprise good news here is that `os.Pipe()` seems to work okay and not be the limiting factor (but we'll need to confirm this by first resolving the simple case above).

Here's a medium size reproduce case (to be tested after the basic example is resolved):

```Go
func runExampleMedium() bool {
	r, w, err := os.Pipe()
	if err != nil {
		panic(err)
	}
	outC := make(chan string)
	go func() {
		var buf bytes.Buffer
		_, err := io.Copy(&buf, r)
		if err != nil {
			panic(err)
		}
		r.Close()
		outC <- buf.String()
	}()
	defer func() {
		w.Close()
		out := <-outC
		fmt.Println(out)
	}()
	fmt.Fprintln(w, "wheee")
	return true
}
```

And here's a full size reproduce case, to be tested after all above examples are working. It's almost the real code that runs when executing examples.

```Go
func runExample() (ok bool) {
	if true {
		fmt.Printf("=== RUN   %s\n", "eg.Name")
	}

	// Capture stdout.
	stdout := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout = w
	outC := make(chan string)
	go func() {
		var buf bytes.Buffer
		_, err := io.Copy(&buf, r)
		r.Close()
		if err != nil {
			fmt.Fprintf(os.Stderr, "testing: copying pipe: %v\n", err)
			os.Exit(1)
		}
		outC <- buf.String()
	}()

	start := time.Now()
	ok = true

	// Clean up in a deferred call so we can recover if the example panics.
	defer func() {
		dstr := fmtDuration(time.Now().Sub(start))

		// Close pipe, restore stdout, get output.
		w.Close()
		os.Stdout = stdout
		out := <-outC

		var fail string
		err := recover()
		if g, e := strings.TrimSpace(out), strings.TrimSpace("this is some output from example code"); g != e && err == nil {
			fail = fmt.Sprintf("got:\n%s\nwant:\n%s\n", g, e)
		}
		if fail != "" || err != nil {
			fmt.Printf("--- FAIL: %s (%s)\n%s", "eg.Name", dstr, fail)
			ok = false
		} else if true {
			fmt.Printf("--- PASS: %s (%s)\n", "eg.Name", dstr)
		}
		if err != nil {
			panic(err)
		}
	}()

	// Run example.
	{
		fmt.Println("this is some output from example code")
	}
	return
}
```

Thanks again @flimzy for looking into this.
