### ISSUE TITLE
gopherjs test fails

### ISSUE THREAD

**Issue by davelondon** [gopherjs/gopherjs#395]
GopherJS: 0faf2ef97c0ada75462340a914f01fec80521216
Node: node/5.6.0
Go: go version go1.5.1 darwin/amd64

Given the following project:

gotest.go:
````go
package jstest
````
gotest_test.go
```go
package jstest

import "testing"

func TestNil(t *testing.T) {

}
```

... running gopherjs test produces an error:

```
$ gopherjs test
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
PASS
fatal error: all goroutines are asleep - deadlock!
FAIL	github.com/davelondon/jstest	0.359s
```

Of course go test passes:

```
$ go test
PASS
ok  	github.com/davelondon/jstest	0.008s
```

**Comment by shurcooL** [comment]
Hi, thanks for reporting this.

However, I'm unable to reproduce. `gopherjs test` works as expected for that input:

```
$ go test
PASS
ok  	github.com/shurcooL/play/31	0.018s
$ gopherjs test
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
PASS
ok  	_/Users/Dmitri/Go/src/github.com/shurcooL/play/310.504s
$ gopherjs test -v
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
=== RUN   TestNil
--- PASS: TestNil (0.00s)
PASS
ok  	_/Users/Dmitri/Go/src/github.com/shurcooL/play/310.503s
$ 
```

Using:

```
go version go1.5.3 darwin/amd64
GopherJS version 0faf2ef97c0ada75462340a914f01fec80521216
```

**Comment by davelondon** [comment]
Yes I can't reproduce it in a docker container. I'll see if there's something wrong with the setup of my Mac.

**Comment by davelondon** [comment]
OK, this is what I've done:

Rebooted Mac
Deleted $GOPATH/src, $GOPATH/bin, $GOPATH/pkg
Upgraded Go to 1.5.3
Downgraded Node to 4.3.0
go get github.com/gopherjs/gopherjs
go get github.com/davelondon/jstest

Still has the same error. Can you think of anything else to try?

**Comment by davelondon** [comment]
I'll close this issue and continue trying to resolve this myself. I'll post again here when I find the solution.

**Comment by nullstyle** [comment]
I'm seeing this as well using 00f306e07eaaaab04ea5dba605cd0e1eff9c6fb7, and node 6.6.0

**Comment by nullstyle** [comment]
https://github.com/nullstyle/gopherjs/commit/8d4d6d07a8d9acca07efebeba727363324c33004 illustrates a hackish workaround I did to resolve the issue for me.  I don't yet know enough about the internals of gopherjs to find the correct way to solve the underlying `os.Exit()` error.
