### ISSUE TITLE
`gopherjs test github.com/eaburns/flac` fails

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#417]
```
$ go test github.com/eaburns/flac
ok      github.com/eaburns/flac 0.006s

$ gopherjs test github.com/eaburns/flac
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
PASS
fatal error: all goroutines are asleep - deadlock!
FAIL    github.com/eaburns/flac 0.338s
```

IIUC that flac package and its dependencies are in pure Go so the test should be passed in theory.

**Comment by shurcooL** [comment]
Cannot reproduce with latest version of GopherJS and that package.

```
$ go get -u github.com/eaburns/flac
$ go test github.com/eaburns/flac
ok  	github.com/eaburns/flac	0.023s
$ gopherjs test github.com/eaburns/flac
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
PASS
ok  	github.com/eaburns/flac	0.548s
$ 
```

Can you try updating GopherJS to latest version (`go get -u github.com/gopherjs/gopherjs`), updating that package to latest version (`go get -u github.com/eaburns/flac`) and redoing the test?

There have been some bug fixes with goroutine deadlock detection in GopherJS in the recent past.

**Comment by hajimehoshi** [comment]
Yeah, I've updated GopherJS but the still deadlock happens.

**Comment by hajimehoshi** [comment]
Ah, it's succeeded after installing node-gyp. This is still mysterious but it'd not be a practical problem. Thanks.
