### ISSUE TITLE
Error when using reflect.Select

### ISSUE THREAD

**Issue by davelondon** [gopherjs/gopherjs#420]
The following test works correctly when running natively (printing "Received on chan multi"). However when run via gopherjs, it errors with "Uncaught Error: Native function not implemented: reflect.rselect":

https://play.golang.org/p/p9yfcLB5t8

**Comment by shurcooL** [comment]
According to https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md, `reflect` package is supposed to be fully supported, so this is a bug. Thanks for reporting.

**Comment by neelance** [comment]
@davelondon Thanks for reporting. It was not supported initially but should have been right now. Somehow it slipped through the cracks. I've taken care of it now.

**Comment by neelance** [comment]
Hmm, the test of the reflect package passes now, but your test case does not. Looking into it...

**Comment by neelance** [comment]
Works now. :-)
