### ISSUE TITLE
godep is asking to install 'vendored'

### ISSUE THREAD

**Issue by dfuentes77** [gopherjs/gopherjs#423]
I'm brand new to go.  When I try to run godep save, I've run into this error which I found the reference to "vendored"  comes from your package.  I'd appreciate any help on how to handle this with godep.  Thanks in advance.

$ godep save ./...
godep: Package (vendored) not found

**Comment by shurcooL** [comment]
> I'm brand new to go. When I try to run godep save

Could you provide more details about what you're trying to do and achieve?

**Comment by dfuentes77** [comment]
I basically ran `godep save ./... ` inside of a go env that uses the gopherjs package.  It outputted this:

`godep: Package (github.com/gopherjs/gopherjs/js) not found`

I then installed that package w/

`go get github.com/gopherjs/gopherjs/js`

I then ran `godep save ./... ` again and received this:

`godep: Package (vendored) not found`

I then grepped for 'vendored' to find out who is using it

`$ grep -ri vendored *`
...
`src/github.com/gopherjs/gopherjs/tests/misc_test.go:	"vendored"
src/github.com/gopherjs/gopherjs/tests/misc_test.go:	if vendored.Answer != 42 {
src/github.com/gopherjs/gopherjs/tests/vendor/vendored/vendored.go:package vendored`
...

I actually just tested a quick fix where I edited `github.com/gopherjs/gopherjs/tests/misc_test.go` locally and change `"vendored"` in the import section to:

`"github.com/gopherjs/gopherjs/tests/vendor/vendored"`

it stopped saying `not found` and continued to the next dependency that was `not found`, until I installed all those subsequent packges, and it went back to complaining:

`godep: Package (vendored) not found`

**Comment by slimsag** [comment]
Hi @dfuentes77 -- I think the question @shurcooL had was "why do you wish to vendor GopherJS using godep in the first place"?

I'm not sure about Godep, but you might have better luck with [govendor](https://github.com/kardianos/govendor) -- but I have never used it to vendor GopherJS because it is already so stable. Generally you only vendor packages that are 'external', like user-written packages etc. Vendoring GopherJS is a bit like trying to vendor the standard library `net/http` package -- it doesn't make very much sense IMO.

**Comment by shurcooL** [comment]
If I understand correctly, @dfuentes77, do you have a project that imports `github.com/gopherjs/gopherjs`, and you're trying to run `godep save ./...` inside that project. Is that right?

If so, I think this is the same issue as #415. Can you check if that's the case?

**Comment by shurcooL** [comment]
Closing because no response after many months, so there's nothing actionable left to do here. As far as I can tell, this is a duplicate of #415.

Feel free to comment or reopen if there any updates here.
