### ISSUE TITLE
First time "go get -u gopherjs" has error

### ISSUE THREAD

**Issue by h8liu** [gopherjs/gopherjs#425]
```
package github.com/fsnotify/fsnotify: cannot find package "github.com/fsnotify/fsnotify" in any of:
	/usr/local/go/src/github.com/fsnotify/fsnotify (from $GOROOT)
	/home/ubuntu/gopath/src/github.com/fsnotify/fsnotify (from $GOPATH)
```

Next time it will go away though. Not sure why.

**Comment by shurcooL** [comment]
The command to install GopherJS should be:

```
go get -u github.com/gopherjs/gopherjs
```

Not `go get -u gopherjs`. Can you try that? It should work without issues on first try, even in a completely empty GOPATH:

```bash
~ $ export GOPATH=/tmp/emptyfolder
~ $ go get -u github.com/gopherjs/gopherjs
~ $ 
```

**Comment by shurcooL** [comment]
I'll close this because it's not an issue with GopherJS. The above command should work. Please comment here or re-open if there's a problem.
