### ISSUE TITLE
Deferring runtime.Gosched() causes error

### ISSUE THREAD

**Issue by nytehauq** [gopherjs/gopherjs#426]
Specifically: "Uncaught TypeError: _r.$blk is not a function" on Chrome.

Code:

```
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Println("wat")

	defer runtime.Gosched()

	return
}
```

Without `return` or `defer` this runs as expected. The error supposedly originates at `fmt.Println("wat")`, according to the trace anyway. FWIW, it becomes "Uncaught TypeError: Cannot read property '$blk' of undefined" if you change `fmt` to `log`.

**Comment by shurcooL** [comment]
I can reproduce this.

@neelance, `runtime` package support is listed as "partial" in [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md), but it doesn't specify which parts of runtime are supported/not supported in the details column. So I can't know if `runtime.Gosched()` is supported.

**Comment by shurcooL** [comment]
There's a good chance this might be same issue as #381.
