### ISSUE TITLE
Proposal: Add to gopherjs serve the ability to reverse-proxy other service(s)

### ISSUE THREAD

**Issue by jargv** [gopherjs/gopherjs#430]
Here's the use case:

In production, I'll have nginx set up to serve my static assets and route to my various microservices. But during development I would like the convenience of `gopherjs serve`. In order to keep things simple during development, it would be nice to be able to run, for example: `gopherjs serve --proxy /my/api:localhost:6000/api`. The exact meaning of this flag would be that all requests to the path /my/api/* would be proxied to localhost:6000/api/*. The similar functionality in webpack-dev-server is quite handy.

I'd be willing to take a whack at adding this if there's general interest in the idea. I'm new(ish) to Golang, but it seems like the reverse proxy in net/http/httputil would make it pretty straightforward.

**Comment by jargv** [comment]
Upon starting this, I quickly realized that my current use case requires websockets which are not proxied by net/http/httputil. So I'm currently using a different solution. I will revisit this if there's interest shown, otherwise I'll just close this in a week or so.

**Comment by neelance** [comment]
This idea might be related: We could write a loader for [Webpack](https://webpack.github.io/). This way, the webpack-dev-server could serve all the pieces you want and maybe even take care of automatically recompiling if we somehow make it aware of all the Go source files involved.

**Comment by jargv** [comment]
I didn't see a lot of interest in this idea, so I'm going to close. If there's a future increase in interest, I'd be happy to pick this up again.
