### ISSUE TITLE
Proposal: webassembly-previews-released

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/gopherjs#432]
No doubt everyone has read about webassembly-previews-released being turned on in the major browsers.

http://www.infoq.com/news/2016/03/webassembly-previews-released

As a gopher, I would really like go support for this.
Gopherjs was created to allow gophers to reuse skills and libraries towards building web apps.

So I think it's worth discussing what is the way forward.
I would like the Google go developers to fully support a build output for webassembly-previews-released, and I read a few weeks ago in this issue list about doing the same for gopherjs.

All this seems like an interesting opportunity.

How can gopherjs and web assembly be leveraged together ? Or should they be completly different streams ?

Can the web API binding work in gopherjs be leveraged ?

I know this is very premature discussion. I wrote on the golang nuts Google group that I really want people to push Google to support golang to webassembly-previews-released.

**Comment by neelance** [comment]
First: I love WebAssembly. In my opinion it is the proper way forward.

However, it is not a technology that GopherJS can use. GopherJS compiles on the AST level, not on the machine code level.

WebAssembly could be used as a backend for the normal Go compiler. Interoperability is a difficult topic, but maybe some lessons learned with the `js` package could come in handy. If this approach eventually makes GopherJS obsolete, then I'm 100% fine with it. I see GopherJS as a stepping stone which highlights the demand for alternatives to JavaScript.

**Comment by joeblew99** [comment]
It looks like wasm has no GC for v1.for v2 they will add a GC.
This means that it's not easy to compile from go to wasm for v1.

The way forward is that gopherjs is an awesome tool, and it will likely work hand in hand with wasm. Still too early to tell

**Comment by slimsag** [comment]
If gopherjs is skipped and the gc compiler itself is used to emit web
assembly, then no garbage collector is needed from wasm because the Go
runtime itself would provide it. Either way, a long time off I bet.

**Comment by joeblew99** [comment]
Ah. I did not know that. 
I don't get how the GC compiler can do that. At runtime, go code relies on doing GC inherently.
At runtime inside a browser, the wasm has no stack for which it can us ?

**Comment by slimsag** [comment]
WebAssembly is inherently trying to be no different than x86 or ARM assembly, except in the fact that it is verified to be safe for execution within a browser.

x86 and ARM processors also do not supply a garbage collector at all, it's something that you must write on top. This is what the Go `runtime` package provides, among many other things. If WebAssembly provided a garbage collector, it might help port GC'd languages to the web, and maybe make them faster.. but the lack of GC support in WebAssembly does not rule out the potential for writing a GC on top of WebAssembly as you would for any other architecture.

Still, it's a lot of hard work (I would bet on it being 3+ years away), and it doesn't belong anywhere near GopherJS which just does AST level translations. IMO this issue belongs on the Go issue tracker, not here.

**Comment by joeblew99** [comment]
Cool to learn this. I can see how it all interrelates.

How about you raise it on the suggested issue tracker, since your more
glued up on this ?
Will be great to read more on this from others, and see where it goes ?
I can close it here ...

**Comment by slimsag** [comment]
I was just providing context, I don't have time at the moment to spearhead this sort of effort or discussion. Sorry!

Feel free to copy+paste whatever you want from my replies if that is useful.

**Comment by neelance** [comment]
Anything further to do here related to GopherJS?

**Comment by slimsag** [comment]
I don't think so

**Comment by joeblew99** [comment]
Closing...
