### ISSUE TITLE
Go Vendoring is not supported

### ISSUE THREAD

**Issue by mpl** [gopherjs/gopherjs#434]
% echo $GOPATH
	/home/mpl
	
	% pwd
	/home/mpl/src/foo
	
	% cat baz/main.go 
	package main
	
	import (
		"foo/echo"
	)
	
	func main() {
		echo.Echo()
	}
	
	% cat echo/echo.go 
	package echo
	
	import "bar"
	
	func Echo() {
		println(bar.Hello)
	}
	
	% cat vendor/bar/bar.go 
	package bar
	
	const Hello = "hello world"
	
	% cd baz
	% go build
	% ./baz
	hello world
	
	% gopherjs build
	cannot find package "bar" in any of:
		/home/mpl/go1/src/bar (from $GOROOT)
		/home/mpl/src/bar (from $GOPATH)
	
	% go version
	go version go1.6 linux/amd64
	
	gopherjs built at rev 14ba2f52062a79512bbb6768908c95032395ce94

**Comment by shurcooL** [comment]
I can reproduce. It looks like a valid bug with /vendor/ support in a non-trivial case.

**Comment by fabian-z** [comment]
Possibly related commit and issue: https://github.com/gopherjs/gopherjs/commit/f8510c9aef19750ec5a1178b33932a7f9defd197, https://github.com/gopherjs/gopherjs/issues/353

The test that was added in f8510c9aef fails for me in master:

```
$ cd gopherjs/tests && go test
# _/tmp/gopherjs/tests
misc_test.go:10:2: cannot find package "vendored" in any of:
	/usr/lib/go/src/vendored (from $GOROOT)
	/tmp/go/src/vendored (from $GOPATH)
FAIL	_/tmp/gopherjs/tests [setup failed]
```

My current workaround is to create a symbolic link in the vendor directory and run the gopherjs build with appropriate environment variable:

```
$ cd vendor
$ ln -s . src
$ cd ..
$ GOPATH=$(pwd)/vendor gopherjs build
```

Not pretty, but it gets the job done in the meantime. I would be very glad to get rid of this workaround, though. I also noticed the gopherjs cmd doesn't search the vendor tree first (compare "cannot find package" output to cmd/go).

**Comment by mpl** [comment]
@fabian-z hah, thanks for the trick. That might help me in the meantime.

**Comment by fabian-z** [comment]
Unfortunately, I still get the error I described above (```/usr/lib/go/src/runtime/error.go:58:7: undeclared name: efaceOf```).

To give a little bit more detail: My setup uses [shurcooL/gopherjslib](https://github.com/shurcooL/gopherjslib) together with a forked out subtree of [shurcooL/go: gopherjs_http](https://github.com/shurcooL/go/tree/master/gopherjs_http) - located at [nfdesign/gopherjs_http](https://dev.nf-design.eu/nfdesign/gopherjs_http).

In-process compilation of GopherJS works perfectly if given a populated GOPATH (see my former comment for the workaround). If the necessary packages are not contained in the GOPATH/src directory itself but only in GOPATH/src/package/vendor, the in-process build fails with the aforementioned error.

Currently, this means I have to use several workarounds and I'm actually not able to use my favorite IDE for debugging. I would appreciate any pointers for this issue.

**Comment by fabian-z** [comment]
I now had the chance to run a test with a gopherjs binary build (instead of using gopherjslib) from current master - the issue is the very same as described above (including the exact same error message). So this issue is not related to my applications usage of gopherjslib / gopherjs_http in any way.

It is again fixed by providing a bogus GOPATH from the vendor directory (see workaround as described above).
Can a GopherJS dev clarify on whether I should open a new bug report, continue here or continue in #459? This clearly looks like a vendoring issue to me, so my proposal would be to reopen this issue since Vendoring support is not completely fixed by f3c4379.

**Comment by mpl** [comment]
@fabian-z fwiw, I trusted them when they called it fixed and I did not retry with the exact repro I gave above. I can retry tomorrow if you want, however with the actual setup I use (which is pretty similar to the above example repro), the issue seems to be fixed for me, and I don't need the symlink trick you provided anymore.

**Comment by mpl** [comment]
@fabian-z oh wait, one additional bit of info that might matter: I did notice that I still had problems on go tip (which might look like the above error). Things only work with Go 1.6 for me (which is good enough for now).

**Comment by fabian-z** [comment]
@mpl Thanks for the information and your offer :smile:  I just tried your repro case with my current Go version (1.6.2), where it works as it should for the ```gopherjs build``` command. I therefore think we are actually looking on two different issues here.
The connection of the ```undeclared name: efaceOf``` error to vendoring is still unclear to me - the fact that my workaround works at all suggests some relation though.

**Comment by fabian-z** [comment]
I was able to make a simple reproduction case out of my applications structure. I will use the same format as @mpl.

```
$ echo $GOPATH && pwd
/tmp/go/
/tmp/go

$ go version
go version go1.6.2 linux/amd64

$ tree
.
├── bin
│   └── gopherjs
└── src
    └── testpackage
        ├── main.go
        └── vendor
            └── vendorpackage
                └── test.go

(gopherjs ce68d34 source & pkg dir ommited)

$ cat src/testpackage/vendor/vendorpackage/test.go
package vendorpackage

const Hello = "hello world"

$ cat src/testpackage/main.go 
package main

import "vendorpackage"

func main() {

	println(vendorpackage.Hello)

}

$ go build testpackage
$ ./testpackage 
hello world

$ ./bin/gopherjs build testpackage
../../usr/lib/go/src/runtime/error.go:58:7: undeclared name: efaceOf

```
