### ISSUE TITLE
Wrongly reusing cached precompiled code when changing build tags

### ISSUE THREAD

**Issue by simen** [gopherjs/gopherjs#440]
I have a package that needs to run both on the native server and in a js client. I use build tags to omit code that rely on huge libraries like `reflect`, `time` and `fmt`. I had some very inconsistent results today where unused libraries would stick around even after I was completely sure I had excised them.

It turns out the problem was that gopherjs was reusing cached precompiled packages from `$GOPATH/pkg/darwin_js` and `$GOPATH/pkg/darwin_js_min`. When I deleted these directories and recompiled, everything worked as expected.

Easily worked around when you know it, but should probably be fixed at some point?

**Comment by shurcooL** [comment]
Thanks for reporting this. I can confirm the issue.

**Comment by shurcooL** [comment]
Hmm, this might be the same issue as #559, is that right? If not the same, definitely related.

**Comment by shurcooL** [comment]
I've fixed #559 just now. Is it possible for you to check if this issue still occurs with latest GopherJS?
