### ISSUE TITLE
Provide a lightweight fmt

### ISSUE THREAD

**Issue by bep** [gopherjs/gopherjs#442]
This may be related to #186 ... 

I have this fairly smallish app, and I by pure habit imported `fmt` to do:

```go
panic(fmt.Sprintf("Error: %s", err) 
```

Etc.

But realize that my build goes from 80kb to 600kb.

And that isn't worth it just to simplify string building. Not sure what's inside `fmt` that makes it so bulky (Unicode tables?) ... But it would be nice to have something similar, but lighter.

**Comment by shurcooL** [comment]
Depending on how you're planning to use GopherJS, it may be very hard, if not unavoidable to not import `fmt` and some other very common standard library packages. Unless you write all your code by hand and avoid any dependencies that may import those packages.

#186 may indeed be the better general solution.

**Comment by bep** [comment]
> it may be very hard, if not unavoidable to not import fmt and some other very common standard library packages.

You are right. I have slept on it, closing.
