### ISSUE TITLE
Use of js.Error's Error() method causes a compiler panic

### ISSUE THREAD

**Issue by theclapp** [gopherjs/gopherjs#450]
```go
func f(e *js.Error) string {
	return e.Error() // <== compiler panics here
}

func main() {
	fmt.Printf("%s", f(&js.Error{}))
}
```
Compiler panics.  Msg is "Invalid js package object: Error".

See http://www.gopherjs.org/playground/#/ugeBCzPwYG, press "run", and check your JS console.

compiler/expressions.go hardcodes a list of functions and types that are known to be in the js package, and Error isn't on the list, so it panics.

```go
	return e.String() // instead of e.Error()
```

seems to work instead, though.

**Comment by shurcooL** [comment]
Yep, that's a valid bug. Thanks for reporting.

The panic is on this line:

https://github.com/gopherjs/gopherjs/blob/028c56b1a74aa0b24f8861f78bceafa5bbcd3eb8/compiler/expressions.go#L661

And panic stack trace looks like this:

```
panic: Invalid js package object: Error

goroutine 1 [running]:
panic(0x5196a0, 0xc820636f90)
	src/runtime/panic.go:481 +0x3e6
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc820291b80, 0x1840440, 0xc8205cac80, 0x9dbaa0)
	src/github.com/gopherjs/gopherjs/compiler/expressions.go:661 +0x15c0e
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc820291b80, 0x1840440, 0xc8205cac80, 0x1884300, 0x9dbaa0, 0x18247)
	src/github.com/gopherjs/gopherjs/compiler/expressions.go:1118 +0x104
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateResults(0xc820291b80, 0xc820636bf0, 0x1, 0x1, 0x0, 0x0)
	src/github.com/gopherjs/gopherjs/compiler/statements.go:746 +0x1ce
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc820291b80, 0x1840478, 0xc820357760, 0x0)
...
```

**Comment by shurcooL** [comment]
Compiler panic also happens if you call [`Stack()` method](https://godoc.org/github.com/gopherjs/gopherjs/js#Error.Stack) of `*js.Error`.

**Comment by shurcooL** [comment]
A fix for the compiler panic may look like this:

```diff
diff --git a/compiler/expressions.go b/compiler/expressions.go
index f83b925..50023ce 100644
--- a/compiler/expressions.go
+++ b/compiler/expressions.go
@@ -657,6 +657,8 @@ func (c *funcContext) translateExpr(expr ast.Expr) *expression {
 						return c.internalize(recv, types.NewInterface(nil, nil))
 					case "Unsafe":
 						return recv
+					case "Error", "Stack":
+						// Fallthrough; these don't need special handling.
 					default:
 						panic("Invalid js package object: " + sel.Obj().Name())
 					}
```

That way, it stops being a compiler panic and becomes a runtime JS error (the `*js.Error` contains a nil `*js.Object`, so trying to read a property on `null` fails).

I'll let @neelance take this because I don't know what's the best way to resolve this issue completely, I can only cover it up.

I don't think you're supposed to be creating `js.Error` yourself; it's meant to be provided to you by the compiler when there's a JS error. But it is exported, so it's valid Go code to create it... Maybe it shouldn't be exported?

**Comment by theclapp** [comment]
> I don't think you're supposed to be creating js.Error yourself

That's a good point.  In real life I'm not, that was just the test case.  In real life I have a library routine panicing, and I'm trying to catch the JS error in a QUnit test case.

Here's a better test case.

```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
	. "github.com/theclapp/qunit"
)

func TestQUThrows() {
	Test("f panics and qa.Throws catches it", func(qa QUnitAssert) {
		f := func() {
			panic("error!")
		}
		qa.Throws(func() interface{} { f(); return nil },
			func(err *js.Error) bool {
				return err.Error() == "Error: error!" // Panic here
			},
			"err.Error")
	})
}

func main() {
	TestQUThrows()
}
```

**Comment by theclapp** [comment]
Thanks!  Fix confirmed.

**Comment by neelance** [comment]
@theclapp Thanks for reporting!
