### ISSUE TITLE
gopherjs serve results in go/1.6.2/libexec/src/runtime/error.go:58:7: undeclared name: efaceOf

### ISSUE THREAD

**Issue by gorakhargosh** [gopherjs/gopherjs#459]
Namaste,

```
 [130]fish> gopherjs serve -w foo
serving at http://localhost:8080 and on port 8080 of any available addresses
../../../../usr/local/Cellar/go/1.6.2/libexec/src/runtime/error.go:58:7: undeclared name: efaceOf
```

```
fish> tree
m.
└── src
    └── foo
        └── script.go
```

Sending a GET request to localhost:8080/foo/ results in the above error.

How does one get gopherjs serve to work?

**Comment by bep** [comment]
Not sure what the foo is all about, but the root is the "package root" of your gopherjs package(s).

So, to give an example from a repo of mine.

```
gopherjs serve github.com/bep/gr/examples
```

If you do 

```
gopherjs serve
```

You "serve" the entire gopath ...

**Comment by gorakhargosh** [comment]
This is what I get when I run your example:

```
~/burrow
fish> gopherjs serve github.com/bep/gr/examples
serving at http://localhost:8080 and on port 8080 of any available addresses
../../../usr/local/Cellar/go/1.6.2/libexec/src/runtime/error.go:58:7: undeclared name: efaceOf

fish> echo $GOPATH
/Users/yesudeep/burrow
```

**Comment by shurcooL** [comment]
Take a look at https://github.com/gopherjs/gopherjs/issues/434, it mentions problems with `efaceOf`.

I think this is unrelated to `gopherjs serve`, but rather to your setup of gopherjs in general. If you try to do `gopherjs build` with those examples, do you get the same error?

**Comment by gorakhargosh** [comment]
Nope. not the same error. for some odd reason, it's working now. closing this bug.

thank you! :)
