### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by cryptix** [gopherjs/gopherjs#46]
Hi,

the [godoc link](http://godoc.org/github.com/gopherjs/gopherjs/jslib) in the `Using the builder as a libary` section returns 404.
I guess the `jslib` package got renamed to `compiler` but I'm to new to gopherjs to know.

**Comment by shurcooL** [comment]
`jslib` is now at http://godoc.org/github.com/go-on/gopherjslib. I use my own fork because there was a breaking API change and the author didn't respond to my PR that fixed it for like 3-4 days.
