### ISSUE TITLE
Broken link in README.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#464]
As reported by @hansrodtang (thanks!) [on Gophers Slack](https://gophers.slack.com/archives/general/p1463967835021293), the following link in GopherJS [README.md](https://github.com/gopherjs/gopherjs#what-is-supported) no longer takes you to where it used to:

> Performance is quite good in most cases, see [HTML5 game engine benchmark](http://ajhager.github.io/enj/).

The link is not quite broken, but it redirects to the home page of http://www.ajhager.com/ and the enj demo is nowhere to be found there.

@ajhager, since it points to your demo on your website, can you please give an update here? Is there an updated URL we should use instead, or do you recommend we remove the link to that demo (possibly putting something else in its place)? Thanks!

**Comment by ajhager** [comment]
I'm doing Go again, thankfully, so I can fix this up. I'll push it to the engi project page and submit a PR.

**Comment by shurcooL** [comment]
Great, thanks. :)

**Comment by ajhager** [comment]
Should be fixed by #465
