### ISSUE TITLE
reflect.DeepEqual fails with *js.Object types

### ISSUE THREAD

**Issue by bep** [gopherjs/gopherjs#473]
See http://www.gopherjs.org/playground/#/54CnvrqcGt

```go
package main

import (
	"github.com/gopherjs/gopherjs/js"
	"reflect"
)

type Val struct {
	*js.Object
	Name string
}

func main() {

	v1 := &Val{Object: js.Global.Get("Object").New(), Name: "v1"}
	v2 := &Val{Object: js.Global.Get("Object").New(), Name: "v2"}

	eq := reflect.DeepEqual(v1, v2)

	println("Eq:", eq)
}
```
Tracking down `Uncaught RangeError: Maximum call stack size exceeded` errors has been the number one pain in a otherwise very enjoyable GopherJS experience. Once I managed to get the complete stacktraces from the browser, the causes are obvious.

But the example above isn't obvious to me.

I can understand why a circular referenced object should fail (however, you should consider document it as a difference between the Go stdlib), but the abvove I would expect to plainly return `false`. But there may be stuff here I don't see.

**Comment by shurcooL** [comment]
I can reproduce.

`reflect` package is marked as fully supported in the [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md), so this is a valid bug.

**Comment by shurcooL** [comment]
Confirmed fixed.

I've [regenerated](https://github.com/gopherjs/gopherjs.github.io/commit/1e1b3dc7144fc14a6ec05965581fe15098918a0f) the playground and it's working there too now. http://www.gopherjs.org/playground/#/54CnvrqcGt
