### ISSUE TITLE
Any way to avoid "system calls not available" when using third lib like bson?

### ISSUE THREAD

**Issue by glight2000** [gopherjs/gopherjs#474]
I'm using gopherjs with a struct like this:
```go
type User strut {
	Id     bson.ObjectId `json:"id" bson:"_id,omitempty"`
}
```
The lib bson will cause "system calls not available" error.
How can I use it or some other lib like it.
Thanks~

**Comment by shurcooL** [comment]
What is the import path of `bson` library? Is it [`gopkg.in/v2/mgo/bson`](https://godoc.org/gopkg.in/v2/mgo/bson)?

**Comment by glight2000** [comment]
@shurcooL Yes, It is `"gopkg.in/mgo.v2/bson"`,

**Comment by shurcooL** [comment]
What's a minimum snippet that can be used to reproduce this problem?

I tried the following Go program and it worked without issues for me:

```Go
package main

import (
	"fmt"

	"gopkg.in/mgo.v2/bson"
)

type User struct {
	Id bson.ObjectId `json:"id" bson:"_id,omitempty"`
}

func main() {
	u := User{}

	fmt.Println("user is:", u)
}
```

```bash
$ go run main.go 
user is: {ObjectIdHex("")}
$ gopherjs run main.go 
user is: {ObjectIdHex("")}
```

Do you have the system call module installed? See https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md.

**Comment by glight2000** [comment]
@shurcooL 
Code snippet like this:

test.go
```go
package main

import "gopkg.in/mgo.v2/bson"

func main() {
	user := new(User)
	user.id = bson.NewObjectId()
	print(user.id.Hex())
}

type User struct {
	id bson.ObjectId
}
```

*test.html
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>test</title>
</head>
<body>
<div class="container">
    look at console log...
</div> <!-- /container -->
<script src="./test.js"></script>
</body>
</html>
```

`gopherjs build test.go` and then browse test.html.

console log:
```
test.js:11378warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md$packages.syscall.printWarning @ test.js:11378$packages.syscall.RawSyscall @ test.js:11542$packages.syscall.Getpid @ test.js:12117$packages.os.Getpid @ test.js:15929$packages.gopkg.in/mgo.v2/bson.NewObjectId @ test.js:26603$packages.main.main @ test.js:28352$packages.main.$init @ test.js:28361$goroutine @ test.js:1464$schedule @ test.js:1521$go @ test.js:1497(anonymous function) @ test.js:28372(anonymous function) @ test.js:28375
test.js:28353575cc733cd8d8affffe456c1
```

When Unmarshal from json string to struct, it will cause this issue too.

Can it be just a warning or something that does not interrupt other JS functions...

About `system call module`, I'm not familiar with NodeJs... I'm using html+js(gopherjs).

**Comment by shurcooL** [comment]
Ok. You've provided enough information for me to able to answer your questions now.

> The lib bson will cause "system calls not available" error.

Yes, that happens because the package imports `os` and calls `os.Getpid()` inside `NewObjectId()`:

https://github.com/go-mgo/mgo/blob/29cc868a5ca65f401ff318143f9408d02f4799cc/bson/bson.go#L237

As documented in the [compatibility table](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md), GopherJS supports `os` package only partially, and that is under Node.js, not in browser.

> Any way to avoid "system calls not available" when using third lib like bson?
>
> How can I use it or some other lib like it.

I can think of a few options:

- Find another package that doesn't use unsupported dependencies (easiest).

- Make a fork of that package and find a way to get rid of its dependency/use of unsupported packages in the browser like `os`.

- Take the above, and try to submit a PR upstream behind a build tag `// +build js`, so it only applies when building the package for `js` architecture.

- Find a way to make GopherJS support `os` package fully in browser (probably not possible, the browser just doesn't expose the same capabilities to the running JavaScript as a normal Go process gets).

**Comment by glight2000** [comment]
@shurcooL Thank you very much for providing the answer and details.

And I'm confusing that, is gopheris purposed not using javascript? However, in the construction of the project or selecting js frameworks still need to know a lot of js or nodejs.

Is there any mature combinations for gopherjs develpment, such as gopherjs + angular or pure golang way? Any  articles recommend?

**Comment by shurcooL** [comment]
No problem.

> And I'm confusing that, is gopheris purposed not using javascript? However, in the construction of the project or selecting js frameworks still need to know a lot of js or nodejs.

GopherJS's purpose is to give you the opportunity to write most of your front-end code in Go which will still run in all browsers. However, that doesn't mean you can expect not to be aware of limitations of running in a limited environment like browser or Node.js.

It's no different than cross-compiling Go for iOS or Android targets, it lets you write most of the logic in Go, but you still have to be familiar with the details and limitations of mobile devices.

> Is there any mature combinations for gopherjs develpment, such as gopherjs + angular or pure golang way? Any articles recommend?

I mostly approach it by starting with pure Go and building my way up, creating any that I need that are missing. I know there are bindings for Polymer and some people use that.

I suggest you look at https://github.com/gopherjs/gopherjs/wiki/bindings for a list of existing bindings, libraries, ports. See https://github.com/gopherjs/gopherjs/wiki/Community-Tutorials-and-Blogs for a list of articles/blogs (there are't many at this time, so help is very welcome).

**Comment by glight2000** [comment]
@shurcooL 
These informations are very helpful and made me more clearly about gopherJs.
Thanks a lot, again.

**Comment by shurcooL** [comment]
Happy to help! :)

You should also see https://github.com/gopherjs/gopherjs#community section, feel free to join the [#gopherjs Channel on Gophers Slack](https://gophers.slack.com/messages/gopherjs/) or elsewhere and see what other people are up to!
