### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/gopherjs#489]
try running the following as a Dockerfile, with "docker run ."

````
FROM golang
RUN go get -u github.com/gopherjs/gopherjs
````

Output is:
````
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM golang
 ---> 8ecba0e9bd48
Step 2 : RUN go get -u github.com/gopherjs/gopherjs
 ---> Running in 295a1bfe99eb
# github.com/gopherjs/gopherjs
src/github.com/gopherjs/gopherjs/tool.go:483: cmdServe.Help undefined (type *cobra.Command has no field or method Help)
The command '/bin/sh -c go get -u github.com/gopherjs/gopherjs' returned a non-zero code: 2


````

**Comment by joeblew99** [comment]
@shurcooL is related to the build tool integration ?

I get the same error not matter what version og golang i use btw

**Comment by joeblew99** [comment]
@shurcooL

Its blowing up on line 483 of tool.go. I had a look at the last few commits, and this seems to be related:
 https://github.com/gopherjs/gopherjs/commit/2ba3b0eacdac4f55862a05f577b76780c0a4fd57#diff-58512a66b026b6909e0ea84d0468c58d


Can you try it out with docker also ? The docker file is in the first comment. Onyl 2 lines :)

**Comment by flimzy** [comment]
I am getting the same thing without Docker. I first noticed when my Travis-CI builds started failing ([example](https://travis-ci.org/flimzy/anki/builds/145222331), and can reproduce on my own system easily enough:

    $ go get -u github.com/gopherjs/gopherjs
    # github.com/gopherjs/gopherjs
    ../../gopherjs/gopherjs/tool.go:483: cmdServe.Help undefined (type *cobra.Command has no field or method Help)

**Comment by shurcooL** [comment]
I will take a look now, thanks for reporting.

**Comment by flimzy** [comment]
This appears to be related to a recent change to the cobra public API:  https://github.com/spf13/cobra/pull/305

**Comment by shurcooL** [comment]
Yep, that's exactly what it was. Thanks Jonathan. :)

I'll push an update that updates our API usage and fixes it now.
