### ISSUE TITLE
Support for GOBIN?

### ISSUE THREAD

**Issue by ohler** [gopherjs/gopherjs#494]
From https://golang.org/cmd/go/#hdr-GOPATH_environment_variable :

> The bin directory holds compiled commands. Each command is named for its source directory, but only the final element, not the entire path. That is, the command with source in DIR/src/foo/quux is installed into DIR/bin/quux, not DIR/bin/foo/quux. The "foo/" prefix is stripped so that you can add DIR/bin to your PATH to get at the installed commands. If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin. GOBIN must be an absolute path.

IIUC, gopherjs implements this, except for the last bit about GOBIN.  Is that intentional or a bug/missing feature?

**Comment by shurcooL** [comment]
It's a bug/missing feature. We should support GOBIN.

If it's not resolved before then, this will be resolved when #485 is merged.

**Comment by nevkontakte** [comment]
This has been implemented in https://github.com/gopherjs/gopherjs/commit/78745daf41c9ed67c548488a6f26b1acbd968165
