### ISSUE TITLE
Support reflect.StructOf function (new to Go 1.7).

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherjs#499]
[`reflect.StructOf` function](https://godoc.org/reflect#StructOf) has been added in Go 1.7 and GopherJS currently does not support it, as can be seen on the [compatibility table](https://github.com/gopherjs/gopherjs/blob/65dd5e201a11ceb651774a2617c879722d3cbe31/doc/packages.md) as of commit https://github.com/gopherjs/gopherjs/commit/65dd5e201a11ceb651774a2617c879722d3cbe31.

This issue is to track its support status. /cc @neelance It is not the highest priority issue at this time and may take more time to get around to.

**Comment by flimzy** [comment]
This has now been fixed with https://github.com/gopherjs/gopherjs/pull/1015
