### ISSUE TITLE
Proposal: Add version string to communicate GopherJS's mature status, better tracking of release history.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#500]
I'd like us to add a version string to the GopherJS compiler. Given how stable and mature it is by now, it should've had one a while ago. This is similar to how Go 1.0 was eventually a stable version name.

Nothing will change regarding how to download/update to latest version. `master` branch will still have the latest "patch" version and we will not be tagging those releases (think of each commit to `master` branch as a patch release). So still `go get -u github.com/gopherjs/gopherjs` to get latest GopherJS. No changes to that - this is purely to help communicate and track history.

The version scheme is:

```
x.x-y
```

Where x.x is the major and minor version of Go, e.g., 1.7 for today's Go 1.7. It'd be 1.6 for Go 1.6.3.

y is the version of GopherJS compiler for its version of Go. It will start at 1 and can increment for each significant change/addition/improvement/breaking change. **It will correspond to new entries in the release history that note what has changed.** It's a way for us to communicate externally the changes in a more summarized way than individual commits.

So, first release for Go 1.7 will be GopherJS 1.7-1. Then 1.7-2, 1.7-3, etc.

Once 1.8 comes out and GopherJS supports it, the version will bump up to 1.8-1.

```
1.7-1
1.7-2
1.7-3
1.8-1
1.8-2
1.9-1
...
```

Note that you can/should always use latest Go patch version. So it's fine to use Go 1.7.1 or 1.7.3 whenever those come out with GopherJS 1.7-1.

I've discussed this with @neelance and he was in agreement; we iterated on the versioning scheme to arrive at the above solution.

**Comment by neelance** [comment]
@shurcooL Close?

**Comment by shurcooL** [comment]
Yes, this is done now via #501 and the blog post.
