### ISSUE TITLE
go get fails with go 1.7 warning

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/gopherjs#502]
````
go get -u github.com/gopherjs/gopherjs
# github.com/gopherjs/gopherjs/compiler
../../gopherjs/gopherjs/compiler/compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_7___

`````

**Comment by neelance** [comment]
Stupid question: Which version of Go are you using?

**Comment by joeblew99** [comment]
good question , not stupid.

on Win:
i also tried "go get github.com/gopherjs/gopherjs"  on windows 10, go 1.6.3, and got the exact same error message too.

on OSX:
````

go version go1.6.3 darwin/amd64


x-MacBook-Pro:cmd apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

````

**Comment by joeblew99** [comment]
on windows

````

go get github.com/gopherjs/gopherjs
# github.com/gopherjs/gopherjs/compiler
C:\Users\root\workspace\go\src\github.com\gopherjs\gopherjs\compiler\compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_7___

>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\root\workspace\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

````

**Comment by PSG-Luna** [comment]
This seems entirely intended, latest gopherJS only works with go 1.7

**Comment by joeblew99** [comment]
you are kidding  right ?

**Comment by PSG-Luna** [comment]
Am not, if you want to use GopherJS with Go 1.6.x, you should be using the go1.6 branch, master is set to work with 1.7

**Comment by flimzy** [comment]
"___GOPHERJS_REQUIRES_GO_VERSION_1_7___" seems pretty clear to me.

**Comment by joeblew99** [comment]
okkie dockie.

I cant upgrade yet. Too many dependencies that will blow up.
How do i go get the 1.6.3 version of gopherjs ???

**Comment by shurcooL** [comment]
The latest version of GopherJS 1.7-1 requires Go 1.7. You can read more about it on the announcement post:

http://www.gopherjs.org/blog/2016/08/21/gopherjs-1.7-1-release/

I'll quote the relevant part:

> The support for Go 1.7 means that GopherJS 1.7-1 requires Go 1.7 and no longer works with Go 1.6. It’s highly recommended to be using the latest version of Go and GopherJS, but if you cannot update from Go 1.6 right away, you should continue to use GopherJS on the [`go1.6` branch](https://github.com/gopherjs/gopherjs/commits/go1.6).

**Comment by joeblew99** [comment]
@shurcooL thanks for reply.

i bit the bullet and upgraded. 
All Fixed
