### ISSUE TITLE
Defer order of evaluation/value copy bug.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#505]
``` Go
package main

import "fmt"

type X struct {
    S string
}

func (x X) Close() {
    fmt.Println("Value-Closing", x.S)
}

func main() {
    x := X{"Value-X First"}
    defer x.Close()
    x = X{"Value-X Second"}
    defer x.Close()

    // Go 1.7 (gc) output:
    // Value-Closing Value-X Second
    // Value-Closing Value-X First

    // Go 1.7 (GopherJS 1.7-1) output:
    // Value-Closing Value-X Second
    // Value-Closing Value-X Second
}
```

http://www.gopherjs.org/playground/#/Cuab7rRTeJ

This is a shortened version of https://play.golang.org/p/4eI58LBh6i (the other cases work ok). It's worth adding a regression test for all of them though.

There are [a few other known defer bugs](https://github.com/gopherjs/gopherjs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20defer) atm, so there's a chance this is a duplicate. Reporting anyway because getting subtle details of the Go spec right is very important.

**Comment by neelance** [comment]
Resolved by removing code (yey): 08d4c6cdac22b2f4a2eeaaa32e69691e2d343e4c
