### ISSUE TITLE
gopherjs build -m fails when compiling on Cloud9 host

### ISSUE THREAD

**Issue by steveoc64** [gopherjs/gopherjs#509]
Very obscure edge case, but will note it down for the record : 

When connected on a Cloud9 machine  (remote IDE / container thing with shell access,  using ubuntu and possibly NaCL as well)

Environment configured as follows : 

```
steveoc64:~/workspace (master) $ which go
/home/ubuntu/go1.7/go/bin/go

steveoc64:~/workspace (master) $ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GORACE=""
GOROOT="/home/ubuntu/go1.7/go"
GOTOOLDIR="/home/ubuntu/go1.7/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007680455=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

steveoc64:~/workspace (master) $ go version
go version go1.7 linux/amd64

steveoc64:~/workspace (master) $ uname -p
x86_64
```

If I compile the front end of my app without the -m flag, everything looks good : 

```
steveoc64:~/workspace (master) $ make
cd app && gosimple
gopherjs build app/*.go -o dist/public/app.js
-rw-r--r-- 1 ubuntu ubuntu 8154536 Sep  5 04:14 dist/public/app.js
```
... which generates the file dist/public/app.js correctly. The generated code works 100% as expected.

If I compile the front end of my app with the -m flag, gopherjs throws an obscure error : 

```
steveoc64:~/workspace (master) $ make
cd app && gosimple
gopherjs build app/*.go -o dist/public/app.js -m
../../../src/runtime/runtime.go:11:14: GOOS not declared by package sys
make: *** [dist/public/app.js] Error 1
```

The source of runtime.go that is collapsing looks like this : 

```
1 // Copyright 2009 The Go Authors. All rights reserved.
  2 // Use of this source code is governed by a BSD-style
  3 // license that can be found in the LICENSE file.
  4 
  5 package runtime
  6 
  7 import (
  8         "runtime/internal/atomic"
  9         _ "unsafe" // for go:linkname
 10 )
 11 
 12 //go:generate go run wincallback.go
 13 //go:generate go run mkduff.go
 14 //go:generate go run mkfastlog2table.go
 15 
 16 var ticks struct {
 17         lock mutex
 18         pad  uint32 // ensure 8-byte alignment of val on 386
 19         val  uint64
 20 }
```
 
Can easily work around this for now (by simply not minifying when using Cloud9), but its a head scratcher none the less.

Anything obvious ?

PS:   Using the exact same setup and code version on a number of native Linux machines == no problem using "gopherjs build -m".

PPS: gosimple linter reports no warnings on the codebase

**Comment by shurcooL** [comment]
Some insights.

```
../../../src/runtime/runtime.go:11:14: GOOS not declared by package sys
```

This refers to the "augmented" by gopherjs `runtime` package. See:

https://github.com/gopherjs/gopherjs/blob/45518c130e5bd1525f20110830a4986365a153de/compiler/natives/src/runtime/runtime.go#L11

Line 11 indeed refers to `sys.GOOS`.

What's the version of `gopherjs` you're using on the Cloud9 environment?

How was Go 1.7 installed there?

I suspect the Go 1.7 installation there is somehow modified from the original, which is causing its "runtime/internal/sys" package to be different than normal and incompatible with GopherJS.

Can you try uninstalling and reinstalling Go 1.7 on the Cloud9 machine from scratch? Failing that, try zipping up the entire `/home/ubuntu/go1.7/go` folder where it's installed, copy that over to your local machine, and carefully compare its exact contents with your own. Is it exactly the same, file by file, byte for byte?

**Comment by steveoc64** [comment]
Thanks D.   Your thoroughness never fails to impress :)

All fixed now, will close issue with comments.

- Got  it with the augmented code now, couldn't see where the original could be falling over at line 11. That makes perfect sense now.

- Cloud9 comes with go 1.6 as part of the VM they provide, by default.   New install involved un-tarring the distro into a custom dir (~/go1.7), and then setting the shell vars to point to the custom location.

- Post installation of go1.7, I then run "go get -u xxxx/xxxx" on every dependent go package, starting with gopherjs.

Followed your sugeestions, about re-building from a clean install from scratch, and observing the output of each stage carefully.  Sure enough, a clean install produced a correctly functioning gopherjs build, and a correctly working app.

I suspect what happened is that during the initial install, the re-building of the packages may have terminated due to exec'ing the wrong version of go, and then leaving some sort of hybrid set of built packages to compile against.  

Lesson learned ... when upgrading go versions, rebuild all, and dont accept shortcuts.  No problem at the Cloud9 end either,  the error as it turns out is not related to running gopherjs in a container.
 (which seemed reasonable given the error message).  Lots of RedHerrings all round.

Thanks again, issue closed.

**Comment by shurcooL** [comment]
Glad to hear it turned out to be a non-issue and you could get it resolved! :)
