### ISSUE TITLE
FreeBSD: gopherjs build "undeclared name: sysAF_LINK"

### ISSUE THREAD

**Issue by steveoc64** [gopherjs/gopherjs#511]
Q:  Might this be something that #485 will address ?

Been running through available combinations on DigitalOcean, to ensure coverage for gopherjs across the different platforms that are available.

NOTE:   I have another droplet on FreeBSD 10.3 with the same application codebase, using go1.6, and that all works fine.

Platform:  FreeBSD 10.3 

freshly created droplet, with freshly installed go 1.7

```
digitalocean [freebsd@testbox4 ]$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/freebsd/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
```

gives : 

```
digitalocean [freebsd@testbox4 ]$ make
cd app && gosimple
gopherjs build app/*.go -o dist/public/app.js
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:25:42: undeclared name: sysAF_LINK
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:31:35: undeclared name: sysAF_LINK
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:91:43: undeclared name: sysAF_INET
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:100:43: undeclared name: sysAF_INET6
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:105:7: undeclared name: sysAF_INET
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:112:7: undeclared name: sysAF_INET6
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:181:13: undeclared name: sysAF_INET6
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:223:10: undeclared name: sysRTAX_MAX
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:224:12: undeclared name: sysAF_UNSPEC
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:225:24: undeclared name: sysRTAX_MAX
../../../../../../../local/go/src/vendor/golang_org/x/net/route/address.go:225:24: too many errors
```

The offending address.go is in the src/vendor dir of the base go installation.

it includes the following build constraints in the top of the file : 
+build darwin dragonfly freebsd netbsd openbsd

.. and from what I can see, its only the BSDs that need to have definitions for these sysAF_\* flags ?

```
1 // Copyright 2016 The Go Authors. All rights reserved.
      2 // Use of this source code is governed by a BSD-style
      3 // license that can be found in the LICENSE file.
      4
      5 // +build darwin dragonfly freebsd netbsd openbsd
      6
      7 package route
      8
      9 import "runtime"
     10
     11 // An Addr represents an address associated with packet routing.
     12 type Addr interface {
     13         // Family returns an address family.
     14         Family() int
     15 }
     16
     17 // A LinkAddr represents a link-layer address.
     18 type LinkAddr struct {
     19         Index int    // interface index when attached
     20         Name  string // interface name when attached
     21         Addr  []byte // link-layer address when attached
     22 }
     23
     24 // Family implements the Family method of Addr interface.
     25 func (a *LinkAddr) Family() int { return sysAF_LINK }
     26

```

and all of the sysAF_\* constants are dutifully defined in the various zsys_{$GOOS}.go files in the same source dir, for each BSD style OS.

.. will test again with a DragonflyBSD install soon, after I get this one sorted.

**Comment by shurcooL** [comment]
> Q: Might this be something that #485 will address ?

It seems unlikely. From what I can tell, this is an actual issue with building the `vendor/golang_org/x/net/route` package on FreeBSD. That PR is about addressing bugs and maintainability of the build tool, not the compiler.

I expect that most people have used/tested GopherJS on OS X, Linux and Windows, so it's possible this is indeed a FreeBSD-specific issue.

But then again, I am seeing `darwin` build constraint also mentioned in the file you listed.

**Comment by shurcooL** [comment]
Ok, I have a pretty good guess of what could be going on, and it is FreeBSD-specific.

The `sysAF_LINK` const is defined in the following file:

```
/usr/local/go/src/vendor/golang_org/x/net/route/zsys_darwin.go:
    8  	sysAF_INET   = 0x2
    9  	sysAF_ROUTE  = 0x11
   10: 	sysAF_LINK   = 0x12
   11  	sysAF_INET6  = 0x1e
   12  
```

Notice it ends with a `_darwin.js` suffix, so it filters by GOOS=darwin only.

The FreeBSD values are defined in multiple files, depending on the architecture:

```
/usr/local/go/src/vendor/golang_org/x/net/route/zsys_freebsd_386.go:
    8  	sysAF_INET   = 0x2
    9  	sysAF_ROUTE  = 0x11
   10: 	sysAF_LINK   = 0x12
   11  	sysAF_INET6  = 0x1c
   12  

/usr/local/go/src/vendor/golang_org/x/net/route/zsys_freebsd_amd64.go:
    8  	sysAF_INET   = 0x2
    9  	sysAF_ROUTE  = 0x11
   10: 	sysAF_LINK   = 0x12
   11  	sysAF_INET6  = 0x1c
   12  

/usr/local/go/src/vendor/golang_org/x/net/route/zsys_freebsd_arm.go:
    8  	sysAF_INET   = 0x2
    9  	sysAF_ROUTE  = 0x11
   10: 	sysAF_LINK   = 0x12
   11  	sysAF_INET6  = 0x1c
   12  
```

If GopherJS builds that package with GOARCH=js, then none of the files would match, and there's no file named `zsys_freebsd_js.go`.

If this theory is accurate, then I suspect DragonflyBSD _will_ work, because it's defined by GOOS=dragonfly only, not by GOARCH:

```
/usr/local/go/src/vendor/golang_org/x/net/route/zsys_dragonfly.go:
    8  	sysAF_INET   = 0x2
    9  	sysAF_ROUTE  = 0x11
   10: 	sysAF_LINK   = 0x12
   11  	sysAF_INET6  = 0x1c
   12  
```

**Comment by shurcooL** [comment]
@steveoc64, if the above makes sense to you and you'd like to test out, I suggest the following steps.

Make a copy of `/usr/local/go/src/vendor/golang_org/x/net/route/zsys_freebsd_amd64.go` file, rename it to `zsys_freebsd.go`, and add a `// +build js` build constraint at the top of the file (with a blank line after).

Do that, and check if `gopherjs` can build successfully. If so, that'll confirm it and we can think of a way to resolve it.

**Comment by steveoc64** [comment]
Got it ...

I will have a hack at that, and see if it fixes things.  Saw the +Darwin thing earlier, and thought it odd that it wasnt an issue with OSX as well, but your expl covers that.

Gimme a minute - Will try it now.   BRB.

Can test the Dragonfly theory later tonight.

**Comment by steveoc64** [comment]
Perfect !!

```
$ cp zsys_freebsd_amd64.go zsys_freebsd.go
$ add +build js  to the new file
```

```
$ make
cd app && gosimple
gopherjs build app/*.go -o dist/public/app.js -m
-rw-r--r--  1 freebsd  freebsd  5327908 Sep  7 05:27 dist/public/app.js
cd server && gosimple
go build -o dist/cmms-server server/*.go
-rwxr-xr-x  1 freebsd  freebsd  12875830 Sep  7 05:27 dist/cmms-server
all done
```

Can proceed with this workaround, but will have a think about a more elegant way to solve this class of problems later on.

**Comment by shurcooL** [comment]
Great, thanks for confirming that it worked!

We can now think about a way to upstream that fix into this project, so people won't have to do extra steps to make it work on FreeBSD.

One way I can think of is to add that `zsys_freebsd.go` file into the [`compiler/natives` overrides](https://github.com/gopherjs/gopherjs/tree/master/compiler/natives/src). It's going to add a little maintenance overhead (having to potentially update it or deal with other changes in Go 1.8), but it doesn't seem too bad to me.

If anyone has other better ideas how to resolve this, I'd love to hear them.

**Comment by steveoc64** [comment]
Thought - given that all those constants are the same across all affected BSD like systems ... and the fact that its only these BSD systems that are affected by this "bug", would it be practical to simply re-define these constants in compiler/natives ?

Another Thought - wondering what might have changed between 1.6 and 1.7 ?

**Comment by steveoc64** [comment]
You beat me to it !!   Was suggesting adding the flags to compiler/natives would be a good idea, when a stream of people came in the office and started talking about other things before I could post the comment.

Im thinking that the compiler/natives approach would work best, but its going to need some good comments in that file to explain whats going on and why its there ... otherwise it may look like magic numbers.

Leave the compiler/native update with me with me for now (so I can test it in the target environment that is causing the issue in the first place), and Ill post a PR when Im happy with it.

Good progress though !!  Its good to see it working smoothly on lots of different platforms.

**Comment by shurcooL** [comment]
> Another Thought - wondering what might have changed between 1.6 and 1.7 ?

That package didn't exist in Go 1.6. See https://github.com/golang/go/tree/go1.6.3/src/vendor.

**Comment by steveoc64** [comment]
Am happy to close this after the last PR. Will leave that up to you.

In the meantime, I will harrass the maintainers at golang.org about fixing the original files in the vendor dir, because I consider that the actual problem that is causing this gopherjs bug is part of that upstream. (plz correct me if Im wrong)

**Comment by shurcooL** [comment]
> because I consider that the actual problem that is causing this gopherjs bug is part of that upstream. (plz correct me if Im wrong)

To be able to say if it's a problem upstream, we'd have to know their intention. If they intend to have that package support FreeBSD only on `amd64`, `386` and `arm` architectures, but not `arm64`, `js`, `mips64`, `mips64le`, `ppc64`, `s390x` or any other architectures, then they have no problem and the current code does exactly that. If it's their intention to support additional GOARCH values when GOOS=freebsd, then they do have a problem upstream.

If you run `go tool dist list | grep freebsd`, the output is:

```
freebsd/386
freebsd/amd64
freebsd/arm
```

So I suspect what they're doing is perfectly valid for the purposes of Go only.

> In the meantime, I will harrass the maintainers at golang.org about fixing the original files in the vendor dir

I would advise against harassing, but asking them nicely is potentially worth a shot. You could phrase it as considering adding minimal support for "all other architectures" by re-arranging it so that `amd64` file applies to all GOARCH values other than `386` and `arm`.

But that might add to their maintenance cost slightly, so most likely they won't want to do it. But you never know.

Either way, this is really minor and we can fix it on our end.

**Comment by neelance** [comment]
To me it looks like we can close this. Please reopen if there is still something to do.
