### ISSUE TITLE
Non-determinism in generating (minified) .js output.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#514]
This is an issue that's very similar to #152. I think we've either regressed in this, or it's a different/new case.

In https://github.com/gopherjs/gopherjs/issues/152#issuecomment-69503749, @neelance said:

> Deterministic output is definitely a goal.

And I believe that's still true. That's why I'm opening this to track that issue (since I can't find [any open one](https://github.com/gopherjs/gopherjs/issues?utf8=%E2%9C%93&q=is%3Aissue%20deterministic), other than this one).

I'll add more details on how to reproduce this, but I think it's fairly easy from my experience (I'm very happy to provide full details if others can't reproduce this). Just build any non-trivial Go package with gopherjs twice (with minification on), and the second time generated .js output will be slightly different.

**Comment by shurcooL** [comment]
I can't seem to reproduce the non-deterministic output when using `gopherjs build` anymore, so that's great.

It still happens in other contexts, but I think the issue is likely in the code of `gopherjs_http` or `gopherjslib` that incorrectly use `compiler` package.

I also see that `go generate github.com/gopherjs/gopherjs.github.io/playground` does not generate reproducible results. Is there a reason it shouldn't?

**Comment by neelance** [comment]
@shurcooL The nondeterminism with `go generate github.com/gopherjs/gopherjs.github.io/playground` is because of the temporary directory and the source file names which are included in the output.

**Comment by shurcooL** [comment]
I see. That's a completely valid reason then.

I should be able to confirm that's the only remaining source of non-determinism by fixing the temp directory, e.g., to `filepath.Join(os.TempDir(), "gopherjs-playground")`.

> It still happens in other contexts, but I think the issue is likely in the code of `gopherjs_http` or `gopherjslib` that incorrectly use `compiler` package.

Using the `compiler` package and building with source in memory (rather than on disk) should mean there's no random filepaths, so I wonder where the non-determinism is coming from there... 😕
