### ISSUE TITLE
How does gopherjs handle utf8 string

### ISSUE THREAD

**Issue by bobzhang** [gopherjs/gopherjs#527]
sorry if it is a naive question.
from the documentation: https://godoc.org/github.com/gopherjs/gopherjs/js
go type string is translated to js string.
but go is encoded using utf8, so that 
`print "日本語"` will behave differently between go and gopherjs?
if this works as designed, how do I print unicode in gopherjs?

**Comment by kelwang** [comment]
fmt.Println("你好")
or
js.Global.Get("console").Call("log", "你好")

**Comment by bobzhang** [comment]
thanks, is there any way to write go code to generate js code like `console.log("你好")`?

**Comment by shurcooL** [comment]
The second line that @kelwang wrote would generate exactly that JS code.

See on playground:

http://www.gopherjs.org/playground/#/1I_RMlngCH

**Comment by kelwang** [comment]
nice

**Comment by bobzhang** [comment]
@shurcooL thanks for your explanation. what is the type of `js.Global.Get("console").Call`, I am a bit confused that why two "你好"(one in js.Global, the other in println) are transpiled differently? How does gopherjs decide behind the scene, thanks

**Comment by neelance** [comment]
@bobzhang Please use `gopherjs build` to generate the JS file and look into it to see which code GopherJS generates.
