### ISSUE TITLE
"system calls not available" message issue

### ISSUE THREAD

**Issue by 4ydx** [gopherjs/gopherjs#532]
The following line is the issue:

js.Global.Get("console").Call("error", "warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md")

In Firefox on Ubuntu the above results in a parsing error: "unterminated string literal".

By removing "https://" this will go away (has to do with // I would imagine).

EG

```
-               js.Global.Get("console").Call("error", "warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md")
+               js.Global.Get("console").Call("error", "warning: system calls not available, see github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md")
```

**Comment by 4ydx** [comment]
It seems that syscall is being built.  I am not sure why.

**Comment by 4ydx** [comment]
The following line seems to be the issue:

js.Global.Get("console").Call("error", "warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md")

I tried editing the code under compiler/native myself, removing "https://" but after a recompile gopherjs mysteriously still has "https://" embedded in the string.  I removed ~/go/pkg files matching gopherjs etc.  But I cannot seem to get gopherjs to not have this value.  I must be missing something trivial, but this is driving me crazy.

**Comment by 4ydx** [comment]
Ok I am seeing now that this isn't as easy to build as just running "go build".

**Comment by shurcooL** [comment]
What version of Firefox? What version of Ubuntu?

Can you reproduce the issue by running this command in browser JS console?

```JS
window.console.error("warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md");
```

Or does it not happen when you do that directly?

I can't reproduce in Chrome nor Firefox on macOS. Trying Firefox 45.0.2 on Ubuntu 16.04 in a VM... Still no luck:

![image](https://cloud.githubusercontent.com/assets/1924134/19303414/6df1fb64-901d-11e6-9d1b-fc39e9d0f7e2.png)

**Comment by 4ydx** [comment]
Totally my fault.  I was rudimentarily scrubbing comments dynamically from javascript code and had forgotten about it so the "//" in https://... was being unnecessarily truncated.
