### ISSUE TITLE
Callback Question

### ISSUE THREAD

**Issue by 4ydx** [gopherjs/gopherjs#533]
This is probably really dense on my part, but how do I handle callbacks in gopherjs?

EG:

window.doSomething(constraints).then(handleSuccess).catch(handleError);

**Comment by 4ydx** [comment]
I found examples of deferred calls in the Jquery wrapper.  I think I am starting to understand this a bit more.

https://github.com/gopherjs/jquery/blob/master/jquery.go#L828

**Comment by shurcooL** [comment]
```JavaScript
window.doSomething(constraints).then(handleSuccess).catch(handleError);
```

Using `js` package, that would be:

```Go
handleSuccess := func(result *js.Object) { ... }
handleError := func(...) { ... }

js.Global.Call("doSomething", constraints).Call("then", handleSuccess).Call("catch", handleError)
```

You can also see an example [here](https://github.com/gopherjs/gopherjs/blob/00f306e07eaaaab04ea5dba605cd0e1eff9c6fb7/compiler/natives/src/net/http/fetch.go#L26-L38).

Glad to hear it's starting to make sense.

**Comment by theclapp** [comment]
FWIW, if you can refactor your code to write on a channel, that's listened to by a goroutine, that might be better.  No point in just rewriting Javascript in Go, _if_ you can avoid it.
