### ISSUE TITLE
Bug: Getting a substring never causes 'out of index' error

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#543]
http://www.gopherjs.org/play/#/S6teI-bnkF

``` go
package main

import (
    "fmt"
)

func main() {
    str := "foo"
    fmt.Println(str[0:999])
}
```

This should cause an error `panic: runtime error: slice bounds out of range` but not.

**Comment by shurcooL** [comment]
Thanks for reporting, this is a bug.

**Comment by neelance** [comment]
@hajimehoshi Thanks a lot for reporting this bug! :)
