### ISSUE TITLE
Unclear why tip isn't supported

### ISSUE THREAD

**Issue by mvdan** [gopherjs/gopherjs#544]
So I just tried installing gopherjs:

```
compiler/compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_7___
```

My first thought - that's weird, the check seems broken since I'm on tip (1.8). Looking into it, I find:

```
// +build !go1.8
// +build go1.7

package compiler

const ___GOPHERJS_REQUIRES_GO_VERSION_1_7___ = true
```

Requiring Go 1.7 isn't mentioned in the README. But most importantly, I think this should say "requires exactly" instead of "requires". Otherwise, people like me will be confused.

I'd also be very interested to hear why tip is intentionally left broken. Is it because you focus on one stable version at a time? This should probably be in the README too.

**Comment by dominikh** [comment]
> I'd also be very interested to hear why tip is intentionally left broken. Is it because you focus on one stable version at a time? This should probably be in the README too.

GopherJS largely uses the Go standard library, and parts of the stdlib use internal runtime hooks. These hooks often change between Go versions, subtly breaking GopherJS's output. That requires updates to GopherJS whenever a new Go version is released.

I agree about making the requirements explicit in the documentation.

**Comment by mvdan** [comment]
Sounds good. I think this is important enough to have in the README itself - quite a lot of people will be running either old stable versions or tip.

**Comment by shurcooL** [comment]
Agreed, we should mention that exactly Go 1.7.x (not 1.6.x nor 1.8.x) is required in the README.

Perhaps it's also a good idea to provide some explanation for why that's the case in a comment near `___GOPHERJS_REQUIRES_GO_VERSION_1_7___` const.

**Comment by shurcooL** [comment]
I've done something that helps this issue on Go 1.8 branch, see commit bd008d940617ea060e15e0c77965997e18a2a8bb.

**Comment by mvdan** [comment]
tip/master hasn't worked for two years as far as I can tell, since 1.12.x is the latest supported version today. I don't thin it makes sense to keep this issue open at this point.
