### ISSUE TITLE
readdirent error on install

### ISSUE THREAD

**Issue by scisci** [gopherjs/gopherjs#549]
Not sure if this is specific to my system (2008 Macbook Pro running OSX 10.11.6), but when I try to install gopherjs I keep getting these errors as the only output:

```
tool.go:24:2: readdirent: input/output error
tool.go:25:2: readdirent: input/output error
```

**Comment by shurcooL** [comment]
> when I try to install gopherjs I keep getting these errors

What version of Go do you have installed, and is it installed correctly?

What do `go version` and `go env` print?

Did you follow the instructions in README to install GopherJS? https://github.com/gopherjs/gopherjs#installation-and-usage

**Comment by scisci** [comment]
Nevermind, this was an older version of gopherjs forgot go get -u.
