### ISSUE TITLE
Does not panic upon division by zero when assigned to _.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#551]
The following program panics when compiled using `gc`:

```Go
package main

func main() {
	x := 0
	_ = 1 / x
}
```

It does not panic when compiled with GopherJS.

This is the same issue as https://github.com/golang/go/issues/18024 upstream, and it was uncovered by me when working on go1.8 branch thanks to https://github.com/golang/go/commit/c2bb52b8304a814b8e2b447953c3341ac31bbee8 causing `fixedbugs/issue8613.go` test to run as part of [`TestGoRepositoryCompilerTests`](https://github.com/gopherjs/gopherjs/blob/e34a5cd6a1bc7c4fde759f2d3039852fc68b5fcc/tests/gorepo_test.go#L12).

Low priority, I'm reporting for tracking purposes.

**Comment by neelance** [comment]
Fixed by f3471911039c5eec1b0ea655c810e25cd736560f.
