### ISSUE TITLE
Request: "gopherjs doc" command

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#556]
Having GopherJS-specific versions of 'go doc' and 'godoc' would be nice.

This could possibly help address the documentation issues mentioned [here](https://github.com/gopherjs/gopherjs/issues/542#issue-184678638).

An effectively duplicate feature request already exists on [godoc](https://github.com/golang/go/issues/3398), to support build tag in the official godoc package.  But until that's accomplished, supporting it here might be worth while.

Thoughts @neelance , @shurcooL ?  If it's deemed a good idea, I may try to work on this myself.

**Comment by shurcooL** [comment]
Related issue and PR:

https://github.com/golang/gddo/issues/342
https://github.com/golang/gddo/pull/343

Given that's done, can you elaborate what exactly are you looking for? What problem are you trying to resolve?

**Comment by flimzy** [comment]
I guess I hadn't remembered all the details of those bugs/PRs, despite my involvement in them.

It does accomplish what I had in mind, by use of `GOARCH=js godoc ...`.

**Comment by flimzy** [comment]
Maybe it would be worth considering making `gopherjs doc` run `GOARCH=js go doc`? I think similar proposals have been considered for other commands. I don't remember what conclusions were reached...

**Comment by shurcooL** [comment]
> Maybe it would be worth considering making `gopherjs doc` run `GOARCH=js go doc`?

That's worth considering, because it's very low extra maintenance cost and doesn't deviate us further away from normal Go.

We currently do that for `gopherjs get` only.

**Comment by flimzy** [comment]
I'll see about throwing together a PR for that then, since it does sound quite simple.

**Comment by shurcooL** [comment]
Let's decide that we want to do this, since we're still on the "considering" stage. The implementation is indeed trivial.

@neelance What do you think about this?

**Comment by neelance** [comment]
Sure, why not. It is useful and it adds no complexity.
