### ISSUE TITLE
Feature request: Implement `Formatter` interface on *js.Object

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#560]
As a debugging aid, it would sometimes be handy to be able to use a `*js.Object` as a [Formatter](https://golang.org/pkg/fmt/#Formatter).

In particular, I would like to see the '%v' print the result of `JSON.stringify()` on the object. Some of the others verbs might be worth implementing as well.

It might also serve as a short-cut for some other common uses in production code(I haven't thought hard about whether this would actually be a good idea).

Thoughts?

**Comment by shurcooL** [comment]
Sounds reasonable to me... as in, I can't find good reasons to say "no" to a feature request, which is what I prefer to do by default. @neelance?

I suspect it'd be worth doing a prototype and seeing if it works as well as one would expect, or if there are unexpected and unpleasant gotchas.

**Comment by flimzy** [comment]
I think there is an unexpected gotcha.  Implementing the `Formatter` interface requires including the `fmt` package for the `fmt.State` interface type.  Including the 'fmt' package in the `js` module appears to cause an import cycle. And even if it didn't `fmt` is a pretty hefty requirement for something so simple.

Unless there's another way around this I'm unaware of, I think this feature is DOA.

An alternative, which would work for my debugging case, but seems evil, would be to implement the `GoStringer` interface instead. But I don't think there's any way to faithfully represent all JS objects as Go, so that seems like an abuse of the interface.

**Comment by neelance** [comment]
You are right, I think this can not be done without importing `fmt`. :-(
