### ISSUE TITLE
Code pauses execution while window/tab is not in focus

### ISSUE THREAD

**Issue by redstarcoder** [gopherjs/gopherjs#565]
I am running Chromium Version 53.0.2785.89 (64-bit) on Arch Linux.

Currently all my code pauses execution while the tab isn't in focus. I'm not sure why or how to prevent this from happening, as the code itself doesn't have any concept or awareness of focus. At first I passed this issue off as a Javascript issue as I don't use it very often, so I didn't think about it at all. Then I realised that'd be silly of course because Javascript chatrooms and email continue to function while the tab isn't in focus :).

The application itself is [here](https://starfish.000webhostapp.com/) ([source](https://github.com/redstarcoder/go-starfish/tree/js)). It's an interpreter for the esolang *><> I'm working on. [Here](https://starfish.000webhostapp.com/?script=AwLgdgjA1AJg9gQiA)'s an application that simply counts up and clears the output.

If you run the application that's supposed to simply count up and clear the output, you'll see that it functions correctly while you're looking at it. As soon as you switch to a different tab though, it won't count up. Try waiting about a minute (or any amount of time) and switch back. You'd expect the number to be well over 600, but you'll find that's not the case (it hasn't changed).

I tried looking for other issues related to this to no avail. How do I prevent this behaviour, and get my GopherJS application running more like how I'd expect a native Go application to run?

**Comment by neelance** [comment]
Chrome and Firefox both clamp `setTimeout` of background tabs to 1000ms. That's probably the reason for what you are seeing.

**Comment by redstarcoder** [comment]
@neelance, thanks so it's not halting altogether? Just becomes very very slow ... That makes sense thanks for the heads-up! So this won't be a huge issue for any of my applications I think ...
