### ISSUE TITLE
Caching broken for complex import trees

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#568]
On the main GopherJS project I'm working on, I've noticed that caching seems to be broken in a large number of situations. I've resorted to running `rm -rf $GOPATH/pkg/*_js` unconditionally before all my builds, to avoid surprises.

Today I took the time to find a minimal reproduction case:

`main.go`:

    package main

    import (
    	"fmt"
    	"github.com/flimzy/jstest/foo"
    )

    func main() {
    	var x int
    	x = foo.Foo()
    	fmt.Printf("x = %d\n", x)
    }

`foo.go`:

	package foo

	import (
		"github.com/flimzy/jstest/bar"
	)

	func Foo() int {
		return bar.Bar()
	}

`bar.go`:

    package bar

    func Bar() int {
    	return 1
    }

`gopherjs run` output:

    $ gopherjs run *.go
    x = 1

Then edit `bar.go`, and change the return type to anything other than 'int', then run again. I used `int64` in this example, but observed the same* with `string`, `float32`, `uint8`, etc.

    $ gopherjs run *.go
    x = 0

*By 'same', I mean no error; the return value is sometimes as expected (i.e. `1` in this case), making the problem harder to detect.

Expected output:

    $ gopherjs run *.go
    foo/foo.go:8:9: cannot use bar.Bar() (value of type int64) as int value in return statement

Note that changing the return type of `foo.Foo()` invalidates the cache as expected.

**Comment by flimzy** [comment]
Related to #440

**Comment by shurcooL** [comment]
Is it also related to #559?

**Comment by flimzy** [comment]
> Is it also related to and/or duplicate of #559?

It certainly seems related, but the circumstances are different (i.e. I experience broken caching when there was no other error).  I don't know if the underlying cause is the same without digging into the caching logic.

**Comment by flimzy** [comment]
After looking at the code, and the two bugs more closely, I think this is a duplicate of #559.  The title of #559 confused me a bit.

**Comment by jackkleeman** [comment]
+1 I am constantly struggling with this issue

**Comment by shurcooL** [comment]
@jackkleeman, this is a closed duplicate issue. Please use #559 for discussion.
