### ISSUE TITLE
A lot of "unreachable code" warnings on Firefox

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#575]
It seems like this occurs even in the playground itself, so it's hard to suggest a minimum code snippet with the playground.

http://www.gopherjs.org/playground/#/uo5azM3CaP

**Comment by shurcooL** [comment]
I can reproduce in Firefox 52.0a2.

![image](https://cloud.githubusercontent.com/assets/1924134/22172946/e7d6d284-df81-11e6-86bf-d7e3263447a0.png)

**Comment by shurcooL** [comment]
I'm seeing this issue occur again with latest playground, built with latest gopherjs. Reopning to track it. I'll try to add more details soon, but this is very easy to reproduce. I tested with Firefox Nightly.

**Comment by shurcooL** [comment]
It happens on the same input as in the original issue report.

http://www.gopherjs.org/playground/#/uo5azM3CaP

![image](https://cloud.githubusercontent.com/assets/1924134/23883789/a66c5a1c-083f-11e7-8731-b7dcbe441c43.png)

**Comment by shurcooL** [comment]
Investing this a little further. To reproduce this with a simpler setup (a small Go package, and `gopherjs serve`), this will suffice:

```Go
package main

import "strconv"

func main() {
	u, err := strconv.ParseUint("42", 10, 64)
	if err != nil {
		panic(err)
	}
	if u != 42 {
		panic("u != 42")
	}
}
```

The unreachable code only happens for certain packages/functions. For example, importing only `fmt` and using `fmt.Println` doesn't cause it.

The above program generates:

![image](https://cloud.githubusercontent.com/assets/1924134/24377643/0959da2c-130e-11e7-827f-4b71686ab0fa.png)

The relevant line looks like this:

![image](https://cloud.githubusercontent.com/assets/1924134/24377702/3b5bdfe8-130e-11e7-9cd3-690c8aa353c1.png)

**Comment by shurcooL** [comment]
Looking at the source of [`strconv.ParseUint`](https://gotools.org/strconv#atoi.go-L134-L137), it becomes quite clear what's causing the issue and why it only affects some functions:

```Go
		...

		n1 := n + uint64(v)
		if n1 < n || n1 > maxVal {
			// n+v overflows
			n = maxUint64
			err = ErrRange
			goto Error
		}
		n = n1
	}

	return n, nil

Error:
	return n, &NumError{"ParseUint", s, err}
}
```

**Comment by shurcooL** [comment]
This is also affecting:

- "encoding/json".Decoder.peek
- "math.big".nat.probablyPrimeMillerRabin
- "net".conf.hostLookupOrder
- "net".answer
- "net".dnsRoundTripUDP
- "net".exchange
- "mime/multipart".Reader.NextPart

And possibly more. Those were just some that I found from some of my large codebase compiled with GopherJS.

**Comment by CruxToad** [comment]
I don't know whether related, [closure compiler](https://developers.google.com/closure/compiler/docs/gettingstarted_app) reports "unreachable code" even for such a simple program as "Hello, world":
```go
package main

func main() {
	println("Hello, world!")
}
```
```
main.js:2227: WARNING - unreachable code
		/* */ } return; } if ($f === undefined) { $f = { $blk: $init }; } $f.$s = $s; $f.$r = $r; return $f;
		                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

main.js:2237: WARNING - unreachable code
		/* */ } return; } if ($f === undefined) { $f = { $blk: $init }; } $f.$s = $s; $f.$r = $r; return $f;
		                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

main.js:2333: WARNING - unreachable code
		/* */ } return; } if ($f === undefined) { $f = { $blk: $init }; } $f.$s = $s; $f.$r = $r; return $f;
```
```js
2224: $pkg.$init = function() {};
2225: /* */ var $f, $c = false, $s = 0, $r; if (this !== undefined && this.$blk !== undefined) { $f = this; $c = true; $s = $f.$s; $r = $f.$r; } s: while (true) { switch ($s) { case 0:
2226: init();
2227: /* */ } return; } if ($f === undefined) { $f = { $blk: $init }; } $f.$s = $s; $f.$r = $r; return $f;
```
And when the compiler is started with `ADVANCED` compilation level (as shown below), it also shows tons of warnings about "incorrect number of parameters" and something about "instantiation of non-constructor". Cannot say whether those are false positives though.
```bash
java -jar ~/closure.jar --js main.js --js_output_file main.min.js --compilation_level ADVANCED_OPTIMIZATIONS
```

**Comment by j7b** [comment]
With just
```
package main
import _ "fmt"
func main() {}
```
Serve on Darwin using firefox (macos) gives 3 "unreachable code after return statement" first is in internal/poll FD.ptr.prototype.WriteTo: 
```
	/* while (true) { */ case 1:
			_r = syscall.Sendto(fd.Sysfd, p, 0, sa); /* */ $s = 3; case 3: if($c) { $c = false; _r = _r.$blk(); } if (_r && _r.$blk !== undefined) { break s; }
			err$2 = _r;
			if ($interfaceIsEqual(err$2, new syscall.Errno(11)) && fd.pd.pollable()) {
				err$2 = fd.pd.waitWrite(fd.isFile);
				if ($interfaceIsEqual(err$2, $ifaceNil)) {
					/* continue; */ $s = 1; continue;
				}
			}
			if (!($interfaceIsEqual(err$2, $ifaceNil))) {
				$s = -1; return [0, err$2];
			}
			$s = -1; return [p.$length, $ifaceNil];
		/* } */ $s = 1; continue; case 2:
```
My eyeball-interpreter couldn't figure out where ```/* while (true) { */``` happens but where that's commented out would make sense if it wasn't.

**Comment by nevkontakte** [comment]
https://github.com/gopherjs/gopherjs/pull/1071 should eliminate "unreachable code" warnings in Firefox for both cases that this issue mentions.

The Closure compiler warnings mentioned in https://github.com/gopherjs/gopherjs/issues/575#issuecomment-290949543 are of a different kind, based on a much more advanced analysis it does. AFAIK, GopherJS is not very friendly to Closure compiler in general. I have plans to do some work on reducing output size, so I'm going to punt on this problem until then.
