### ISSUE TITLE
Add support for `--benchtime`

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#576]
The standard go tool supports the `-benchtime` option when running benchmark tests.  GopherJS does not appear to have this support.

        -benchtime t
            Run enough iterations of each benchmark to take t, specified
            as a time.Duration (for example, -benchtime 1h30s).
            The default is 1 second (1s).

**Comment by shurcooL** [comment]
I haven't looked at it, but I expect it's likely trivial to add. Let me know if that's not so.

**Comment by flimzy** [comment]
@shurcooL It was even more trivial than I imagined. See #578
