### ISSUE TITLE
GopherJS 1.8-wip: "warning: system calls not available" printed whenever "os" package imported.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#583]
I've mentioned this in https://github.com/gopherjs/gopherjs/pull/552#issuecomment-276149197, but I've confirmed it happens in [1.8](https://github.com/gopherjs/gopherjs/pull/552) only now.

I've investigated it and found the root cause.

![image](https://cloud.githubusercontent.com/assets/1924134/22808229/e6cce14a-eef8-11e6-80ec-3d674f7d8a24.png)

It happens with GopherJS 1.8-wip only when "os" package is imported (not necessarily directly). That package is often imported by other packages, such as ["net/http"](https://godoc.org/net/http?imports), or if you're getting `os.Stdout`, etc.

It happens because of `Executable()` addition to `os` package in Go 1.8.

As a result, `os.Getwd()` gets called as part of `os` package initialization:

```Go
var initCwd, initCwdErr = Getwd()
```

Source: https://github.com/golang/go/blob/09762ccff79ebf08839f8954ab99c17d41f071e2/src/os/executable_darwin.go#L9.

Calling `os.Getwd()` in browser ends up making a call to `Syscall`, which causes the warning to get printed to console (note that it's actually printed as an error to console).

**Comment by shurcooL** [comment]
There are multiple ways we can resolve this. Do you have preferences on this @neelance?

We could override `Getwd` on browser to return error right away.

We could try to override `initCwd` and `initCwdErr` variables `Getwd()` never gets called, but I'm not sure if it's possible since it's single declaration for 2 variables, and the variable names are unexported, so they might change between Go versions more often... They might also have different names depending on the desktop architecture (note that the linked file is `executable_darwin.go`, for darwin. There are others.

**Comment by shurcooL** [comment]
> There are multiple ways we can resolve this. Do you have preferences on this @neelance?

Friendly ping @neelance.

**Comment by neelance** [comment]
What about excluding `executable_darwin.go` from the build?

**Comment by neelance** [comment]
Btw: Thanks for pinging.

**Comment by shurcooL** [comment]
> What about excluding `executable_darwin.go` from the build?

> note that the linked file is `executable_darwin.go`, for darwin; but there are others

![image](https://cloud.githubusercontent.com/assets/1924134/23005791/22597534-f3cc-11e6-97d0-7ae5139fae0c.png)

There are multiple files, we'd have to exclude them all. For example, if someone uses GopherJS on Windows, their default `GOOS` value will be `windows`, and the file `executable_windows.go` will be used instead.

**Comment by shurcooL** [comment]
Although, it's worth noting [`executable_windows.go`](https://github.com/golang/go/blob/64c02460d703f718a44326646d19c417eeb1999a/src/os/executable_windows.go) doesn't try to call `os.Getwd`.

**Comment by shurcooL** [comment]
This `go1.8`-branch-specific issue has been resolved in 65da89e863576b090142057ae89b6a527fd85a91, which is now a part of `go1.8` branch. Closing.
