### ISSUE TITLE
Seeded math/rand gives different output

### ISSUE THREAD

**Issue by ninov** [gopherjs/gopherjs#587]
Hello,
Consider the following go program:

```
package main

import "math/rand"
import "fmt"

func main() {
	rand.Seed(1)
	fmt.Println(rand.Int())
}
```

When running with `go` (tested with 1.7.5 and 1.3.3), it always prints `5577006791947779410`.
When compiling with gopherjs and running it, it always prints `134020434`.

In my undestanding of gopherjs, this program should print the same number in the JS version as in the go version, because it transpiles the PRNG of math/rand into JS, so seeding it with the same number should give the same pseudo-random numbers.

**Comment by neelance** [comment]
GopherJS is a 32 bit environment, so `rand.Int()` returns an `int` with 32 bits, whereas your local `go` has 64 bit `int`s. Try this:
```
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	rand.Seed(1)
	fmt.Println(rand.Int())
	rand.Seed(1)
	fmt.Println(int32(rand.Int63()))
}
```

**Comment by shurcooL** [comment]
To expand on that, given the original program in `main.go`:

```bash
$ GOARCH=amd64 go run main.go
5577006791947779410

$ GOARCH=386 go run main.go
134020434

$ gopherjs run main.go
134020434
```

**Comment by ninov** [comment]
Oh, my bad. Sorry for the inconvenience.

**Comment by neelance** [comment]
No problem.
