### ISSUE TITLE
Playground menu link is routing to the wrong URL 

### ISSUE THREAD

**Issue by j-raw** [gopherjs/gopherjs#593]
When a user clicks the Playground menu item they are taken to "https://gopherjs.github.io/play" They instead should be taken to "/playground"    The prior appears incorrectly.

**Comment by shurcooL** [comment]
> When a user clicks the Playground menu item

Where?

**Comment by j-raw** [comment]
@shurcooL Click the Playground link [here] (https://gopherjs.github.io/)

**Comment by shurcooL** [comment]
Got it, thanks for reporting the issue. We're already aware and tracking it in https://github.com/gopherjs/gopherjs.github.io/issues/63#issuecomment-278016990. The entire old website is broken and needs to be dealt with.
