### ISSUE TITLE
Invalid code generated for funcs with unnamed return parameters that defer blocking code.

### ISSUE THREAD

**Issue by nwidger** [gopherjs/gopherjs#603]
https://gopherjs.github.io/playground/#/JcN1xwSTbp

If I run this Playground link in Firefox 52.0, the `should get here` alert dialog appears.  If I run the same link in Chrome 56.0.2924.87, it prints `calling alert(err)` but not `returned from alert(err)` and the following stack trace is generated:

```
Uncaught (in promise) TypeError: Cannot read property 'Error' of undefined
    at Object.main [as $blk] (eval at $b (playground.js:66), <anonymous>:2943:14)
    at Object.$init [as $blk] (eval at $b (playground.js:66), <anonymous>:2963:68)
    at fun (eval at $b (playground.js:66), <anonymous>:1477:37)
    at $goroutine (eval at $b (playground.js:66), <anonymous>:1475:19)
    at $runScheduled (eval at $b (playground.js:66), <anonymous>:1515:7)
    at $schedule (eval at $b (playground.js:66), <anonymous>:1531:5)
    at queueEntry (eval at $b (playground.js:66), <anonymous>:1686:11)
    at $send (eval at $b (playground.js:66), <anonymous>:1556:5)
    at $b (eval at $b (playground.js:66), <anonymous>:2895:70432)
    at v.$externalizeWrapper (eval at $b (playground.js:66), <anonymous>:1871:24)
```

Removing the `defer` statement after `http.Get` resolves the issue in Chrome:

https://gopherjs.github.io/playground/#/DK-J3eMXYr

Is using defer like this incorrect?  If it is I would expect to either see a compilation error or see the same issue in both Firefox and Chrome.

**Comment by shurcooL** [comment]
I can reproduce in Chrome 57.0.2987.98.

This is definitely a bug and shouldn't be happening.

**Comment by shurcooL** [comment]
It seems the value of `err` is somehow `undefined` (aka `js.Undefined`).

https://gopherjs.github.io/playground/#/Q5xYbr2_yf

That prints `undefined` in browser console in Chrome, which is very unexpected.

**Comment by nwidger** [comment]
It definitely seems to be related to `io.Copy` being called in a `defer` statement.  This does not exhibit the same issue:

https://gopherjs.github.io/playground/#/d-r8POieip

**Comment by shurcooL** [comment]
I suspect this may be related to the fix 50101461d59f26b13c876f57aab314ce55387671, and #381, #426, #493 issues it resolved. /cc @neelance

**Comment by shurcooL** [comment]
Here's a simplified reproduce case:

```Go
package main

import (
	"time"
)

func f() error {
	defer func() {
		time.Sleep(time.Second)
	}()
	return nil
}

func main() {
	err := f()
	print(err) // prints "undefined"
}
```

**Comment by shurcooL** [comment]
Interestingly, it works fine if the return parameter has a name, even if that name is blank identifier.

Both these work ok:

```Go
package main

import "fmt"
import "time"

func f() (err error) {
	defer func() {
		time.Sleep(time.Second)
	}()
	return nil
}

func main() {
	err := f()
	fmt.Println(err) // prints "<nil>" which is correct
}
```

```Go
package main

import "fmt"
import "time"

func f() (_ error) {
	defer func() {
		time.Sleep(time.Second)
	}()
	return nil
}

func main() {
	err := f()
	fmt.Println(err) // prints "<nil>" which is correct
}
```

So, this bug should be easy to fix, it's just an unhandled edge case.

**Comment by nevkontakte** [comment]
I ran into this bug too and I think I know what's the issue here. Consider the following program:

```go
func TestReturnWithBlockingDefer(t *testing.T) {
	f := func() int {
		defer time.Sleep(0)
		return 42
	}
	got := f()
	if got != 42 {
		t.Errorf("Unexpected return value %v. Want: 42.", got)
	}
}
```

Here's the code `f` compiles into:

```js
f = (function $b() {
	var $s, $deferred, $r;
	/* */ $s = 0; var $f, $c = false; if (this !== undefined && this.$blk !== undefined) { $f = this; $c = true; $s = $f.$s; $deferred = $f.$deferred; $r = $f.$r; } var $err = null; try { s: while (true) { switch ($s) { case 0: $deferred = []; $deferred.index = $curGoroutine.deferStack.length; $curGoroutine.deferStack.push($deferred);
	$deferred.push([time.Sleep, [new time.Duration(0, 0)]]);
	$s = -1; return 42;
	/* */ } return; } } catch(err) { $err = err; $s = -1; return 0; } finally { $callDeferred($deferred, $err); if($curGoroutine.asleep) { if ($f === undefined) { $f = { $blk: $b }; } $f.$s = $s; $f.$deferred = $deferred; $f.$r = $r; return $f; } }
});
```

When the function executes the first time, it successfully passes through the `$s = -1; return 42;` statement and would've returned 42 as expected if the deferred function didn't get blocked. But the deferred function does get blocked, and when function `f` is called the second time it's executed with `$s == -1` and completely skips the `return 42` statement. Instead it passes through the `/* */ } return;` statement and returns `undefined` as a result.

**Comment by nevkontakte** [comment]
Thinking a bit more about this, the right fix is to treat the return statement as blocking in case any of the deferred functions are blocking. And for a blocking return statement we need to compute the return value, store it in a temporary variable, generate a new resumption case and then returned the stored value.
