### ISSUE TITLE
gopherjs serve -w makes no sense and should not be possible.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#606]
`-w` flag has some meaning for `build` and `install` commands, but it's not needed for `serve`. We should make it error if used with `serve` to avoid confusion. **Edit:** Better yet, simply remove the flag from `serve` command.

I've seen this before in some reported issue, and I saw it again at https://github.com/myitcv/gopherjs/pull/20/files#r106279586. /cc @myitcv

**Comment by myitcv** [comment]
Thanks for picking up on this @shurcooL - all fixed [in the latest "release"](https://github.com/myitcv/gopherjs/wiki/Changelog) on the React side.

**Comment by shurcooL** [comment]
Thank you @myitcv, I'm glad things are a little bit better on all fronts.
