### ISSUE TITLE
Proposal: minify flag automatically adds minify build tag

### ISSUE THREAD

**Issue by myitcv** [gopherjs/gopherjs#611]
### Headline proposal 

When the `-m` (`--minify`) flag is provided to those commands that can accept it, add the `minify` build tag automatically.

### Detail

This proposal is principally aimed at the use of `.inc.js` files.

I'm now bundling the React javascript files with my [React bindings](https://godoc.org/github.com/myitcv/gopherjs/react) via a similar approach to that [described by @flimzy](https://github.com/gopherjs/gopherjs/issues/468#issuecomment-282565423)

The choice of whether to import a package that includes a minified Javascript file or the full "dev" version is currently based on the `debug` build flag:

```go
// +build !debug

package bundle

import _ "github.com/myitcv/gopherjs/react/internal/prod"
```

I'd like to propose that when the `-m` (`--minify`) is provided this automatically sets the `minify` build tag (e.g. `gopherjs serve -m` would be equivalent in effect to `gopherjs serve -m --tags minify`). The above approach could then switch to using the inverted `minify` build flag and the net effect would be exactly as expected.

This will allow bindings developers to unify on a common approach for use of `.inc.js` files (irrespective of whether #468 is resolved)

Thoughts?

**Comment by shurcooL** [comment]
I'm okay with doing this, as long as there are no good reasons why this shouldn't be done.

So far, I can't think of why adding this would be bad... But still thinking. Once we add this, it'll be much harder to remove it.

Is there anything similar in the standard Go toolchain? I know it automatically sets build tags for the current Go version, as well as architecture and OS. But is there anything else that it does that would be more akin to the minify flag/build tag?

**Comment by tj** [comment]
I'd personally rather see support for commonjs in node_modules. The biggest problem with *.inc.js is that you'll get tons of duplicate sub-dependencies for modules using underscore etc.

**Comment by myitcv** [comment]
@shurcooL 

> Once we add this, it'll be much harder to remove it.

Very true, hence important we give it some thought.

> Is there anything similar in the standard Go toolchain? I know it automatically sets build tags for the current Go version, as well as architecture and OS. But is there anything else that it does that would be more akin to the minify flag/build tag?

I very much doubt it, because the Go tool chain works _extremely_ hard to avoid compiler flags. With GopherJS it's more an artefact of the Javascript/web/frontend world that we have the concept of minification and hence the `-m` flag. Hence I'm not aware of a compiler flag driving a build tag in the Go toolchain.

@tj - not quite sure I understand what you mean. Can you explain more? 

The concept of `.inc.js` and indeed this proposal are intentionally agnostic of any decision to use things like NodeJS/`npm` etc.

Rather in this case as the writer of a package of GopherJS bindings, I've made an explicit decision that I want to bundle some Javascript (via a package `.inc.js`) when the bindings are used. In this proposal I'm simply trying to align the bundling of minified production files or development files with the use of the pre-existing `-m` flag to obviate the user having to explicitly add a build tag which would otherwise be required to choose one or the other (as is currently the case with `--tags debug` per my example in the description)

**Comment by tj** [comment]
Sorry yea wrong place to discuss the inc.js stuff, ignore me :D

**Comment by flimzy** [comment]
I recall a discussion where possibly Rob Pike came down firmly against the suggestion of a build tag for testing mode. I might be able to find it when I am back from vacation in 3 weeks if necessary. But the justification was essentially "code should work the same in production as in testing." 

So while a "minify" tag might seem in principle the same as a "test" tag, I'm not sure if that reasoning applies.

Personally, I have little opinion on this matter.

I only wonder if it's worth committing ourselves to supporting this flag essentially forever, only to save a few characters in a few build scripts.

**Comment by shurcooL** [comment]
That's actually very similar to the main concern that I've got so far.

Introducing this creates the possibility of someone abusing the `minify` tag to have different behavior. As a result, when something goes wrong in `minify` mode, you will no longer be able to simply turn it off and look at code, because there's a chance the code becomes different without the minify flag.

**Comment by myitcv** [comment]
@flimzy @shurcooL - thanks. Really useful discussion

> I recall a discussion where possibly Rob Pike came down firmly against the suggestion of a build tag for testing mode. I might be able to find it when I am back from vacation in 3 weeks if necessary. But the justification was essentially "code should work the same in production as in testing."

I recall having seen a number of discussions along these lines (hence the comment above about compiler flags). And I completely agree with the sentiment.

A few thoughts.

Minification should not, by definition, change the behaviour of Javascript code. At least I assume when we talk about minification in the GopherJS world we're talking about the [`SIMPLE_OPTIMIZATIONS`](https://developers.google.com/closure/compiler/docs/compilation_levels) level of the Google Closure compiler. So the minified code should be identical to the original, modulo identifier and non-significant white space adjustments, just a lot smaller on disk.

So in that respect, the minify flag is not changing the behaviour of our code; to my mind it totally honours the letter and spirit of Rob's comments.

The Facebook strategy of `.js` files is another matter entirely.

Facebook have [two versions](https://facebook.github.io/react/docs/installation.html#development-and-production-versions) of the React `.js` files: 

* development - has some extra runtime warnings/checks etc to warn against probably incorrect behaviour (they mainly have to do this at runtime because there are no static analysis tools that can achieve this)
* production - no additional sanity checks

The development version is somewhat analogous in my mind to the race detector mode of the Go toolchain. 

Facebook happen to distribute the development version unminified (to help with debugging) and the production version pre-minified. But the decision to pre-minify the production version is irrelevant; I could just as easily make the decision that I want to minify the development version in my GopherJS app; again, minification doesn't change the behaviour.

So I think the discussion boils down to these two separate points:

1. Do we want to overload `-m` to in effect be a shorthand for `-m --tags minify`? @flimzy you're right, it's effectively a convenience thing
2. Is it sensible for Facebook to have their two versions of the React `.js` files... and therefore is it sensible for `github.com/myitcv/gopherjs/react` to give the option of which to bundle?

This proposal is about point 1; I'm minded given the discussion to think we probably don't have evidence that the flag set `-m --tags minify` is sufficiently common to provide a shorthand version, and therefore that we park the proposal for now.

The discussion about point 2 is very valuable. I'll create a separate issue in `github.com/myitcv/gopherjs/react` world to continue that.

**Comment by myitcv** [comment]
> The discussion about point 2 is very valuable. I'll create a separate issue in `github.com/myitcv/gopherjs/react` world to continue that.

Here is that issue: https://github.com/myitcv/gopherjs/issues/31

**Comment by shurcooL** [comment]
> This proposal is about point 1; I'm minded given the discussion to think we probably don't have evidence that the flag set `-m --tags minify` is sufficiently common to provide a shorthand version, and therefore that we park the proposal for now.

👍

**Comment by myitcv** [comment]
Great in which case I close this for now. Thanks again for the fruitful discussion!
