### ISSUE TITLE
Is slow running js code called from Go a problem?

### ISSUE THREAD

**Issue by jackkleeman** [gopherjs/gopherjs#614]
I have a go function calling a js function which takes some time to complete. On slower browsers, the function was ending, with the error: cannot block in JavaScript callback, fix by wrapping code in goroutine.

But the slow code wasn't Go, it was JS called from Go! That go code was itself initially called by JS, but through the promisify library, so it wasn't blocking.

I wish I could give reproducible code but this only happened occasionally and on slow browsers.

**Comment by neelance** [comment]
Wild guess: Maybe you have some channel operation that usually does not block because the value is already available but on slow browsers there is some race condition and it blocks?

**Comment by shurcooL** [comment]
If the code is slow or even _potentially_ slow, depending on factors, it's best to to treat it as "blocking" and only call in a goroutine in callbacks.

To treat code as non-blocking, you need to be confident that's the case under all conditions.

**Comment by jackkleeman** [comment]
Ok, noted, thanks!
