### ISSUE TITLE
Int64 and UIn64 values seem to be truncated 

### ISSUE THREAD

**Issue by lambdacrash** [gopherjs/gopherjs#619]
Hi!
I encounter a problem with a Go function returning a `int64` or `uint64`. When I call it in JS, the returned value seems to be truncated.

Few lines of code will help:
`TestTypes.go`
``` go
package main
import (
	"fmt"
	"math"
	"github.com/gopherjs/gopherjs/js"
)
func main() {
	js.Global.Set("h", map[string]interface{}{
		"uint8": func() uint8 {
			i := uint8(math.MaxInt8 - 12)
			fmt.Println(i)
			return i
		},
		"uint16": func() uint16 {
			i := uint16(math.MaxInt16 - 12)
			fmt.Println(i)
			return i
		},
		"uint32": func() uint32 {
			i := uint32(math.MaxInt32 - 12)
			fmt.Println(i)
			return i
		},
		"uint64": func() uint64 {
			i := uint64(math.MaxInt64 - 12)
			fmt.Println(i)
			return i
		},
		"int8": func() int8 {
			i := int8(math.MaxInt8 - 12)
			fmt.Println(i)
			return i
		},
		"int16": func() int16 {
			i := int16(math.MaxInt16 - 12)
			fmt.Println(i)
			return i
		},
		"int32": func() int32 {
			i := int32(math.MaxInt32 - 12)
			fmt.Println(i)
			return i
		},
		"int64": func() int64 {
			i := int64(math.MaxInt64 - 12)
			fmt.Println(i)
			return i
		},
	})
}
```

`index.html`
``` html
<html>
<head>
    <meta charset="UTF-8"/>
    <script src="TestTypes.js"></script>
    <script type="application/javascript">
        const compute = function () {
            console.log(h.uint64())
            console.log(h.uint32())
            console.log(h.uint16())
            console.log(h.uint8())
            console.log(h.int64())
            console.log(h.int32())
            console.log(h.int16())
            console.log(h.int8())
        }
        compute()
    </script>
</head>
<body>
</body>
</html>
```

The `TestTypes.go` is compiled with GopherJS 
```
gopherjs build TestTypes.go
```

When I run the code in Firefox, Chrome, Safari, the `int64` and `uint64` values are truncated:
```
9223372036854775795  TestTypes.js:3141:4
9223372036854776000  index3.html:7:13
2147483635  TestTypes.js:3141:4
2147483635  index3.html:8:13
32755  TestTypes.js:3141:4
32755  index3.html:9:13
115  TestTypes.js:3141:4
115  index3.html:10:13
9223372036854775795  TestTypes.js:3141:4
9223372036854776000  index3.html:11:13
2147483635  TestTypes.js:3141:4
2147483635  index3.html:12:13
32755  TestTypes.js:3141:4
32755  index3.html:13:13
115  TestTypes.js:3141:4
115  index3.html:14:13
```

Did i make a mistake?

**Comment by shurcooL** [comment]
JavaScript doesn't have native integer types. The Number type is represented as 64-bit floating point, so the largest exact integral value is 2<sup>53</sup>-1, or 9007199254740991. See https://stackoverflow.com/a/307200.

Because of that, the internal representation of `int64` and `uint64` in GopherJS is via two JavaScript Number variables.

This might either be a limitation, or a bug, in the process of externalizing the internal GopherJS integer representation into a JavaScript Number value. I'm not sure which yet.

It may be possible to improve precision, but as I understand, there will definitely be large integers that can't be represented accurately by a JavaScript Number type.

**Comment by lambdacrash** [comment]
Hi schurcooL,
Thank you for your answer. So, this is not an issue.

**Comment by shurcooL** [comment]
It looks like everything's working as intended. Try this in your browser's JavaScript console:

```
var x = 9223372036854775807;
x;
```

Here's what I get in Chrome:

![image](https://cloud.githubusercontent.com/assets/1924134/24772426/48d3cff4-1adf-11e7-8ccb-b570e38d2c7a.png)

**Comment by neelance** [comment]
Right, when externalizing a 64 bit integer it gets turned into a JS float with all its precision losses. If you need 64 bit integers outside of your Go code, then you also need to build some custom way to express those and convert accordingly when passing those values from Go to JS.
