### ISSUE TITLE
No fast way to check for presence of key in object?

### ISSUE THREAD

**Issue by alltom** [gopherjs/gopherjs#621]
I'm looking for an equivalent to this JavaScript for `*js.Object`, but I don't see it in the js package:

```js
if ("foo" in o) {
  // ...
}
```

**Comment by shurcooL** [comment]
That's a good question. Is that ES6 syntax? If so, what's ECMAScript 5 equivalent? Can `hasOwnProperty` method be used?

**Comment by alltom** [comment]
Oh yeah, that function would work in my case. Thanks. :)

"in" is actually as old as dirt. I'm sure it's faster than calling a
function, but IIRC it has gotchas.

**Comment by flimzy** [comment]
`in` could probably be added to the [jsbuiltin](https://github.com/gopherjs/jsbuiltin) package with minimal effort.  It's just a matter of deciding:

1. Is it worth it? (Does `in` provide anything that `hasOwnProperty` doesn't?  Functionality? Performance?)
2. What should the function signature look like?

**Comment by shurcooL** [comment]
From a discussion with @neelance and @myitcv, we didn't see this as something that's critical to warrant being added to `js` package itself. The bar for adding things there is really high.

Instead, using `hasOwnProperty` function is one solution. (Which worked for @alltom's needs above.)

Another solution is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/has, and potentially a polyfill for it.

Finally, @flimzy said this can potentially be added to `jsbuiltin` package, and I think that'd be a good location for it.
