### ISSUE TITLE
Interface() undocumented

### ISSUE THREAD

**Issue by alltom** [gopherjs/gopherjs#622]
[The comment for Object.Interface](https://godoc.org/github.com/gopherjs/gopherjs/js#Object.Interface) just says "Interface returns the object converted to interface{}. See GopherJS' README for details." But the README doesn't seem to mention Interface (any more?).

**Comment by alltom** [comment]
It came up when I was surprised that dom.Element doesn't round-trip, so I figure I must not understand what `Interface()` does:

```go
var body dom.Element = dom.GetWindow().Document().(dom.HTMLDocument).Body()
js.Global.Set("foo", body)
body2 := js.Global.Get("foo").Interface().(dom.Element)
// Uncaught Error: interface conversion: *js.Object is not dom.Element: missing method AddEventListener
```

**Comment by fiatjaf** [comment]
`github.com/gopherjs/gopherjs/js`, the package where `js.Object` is defined, doesn't know about `dom` objects, which are defined at `honnef.co/go/js/dom`.

To mess up with the DOM using only `github.com/gopherjs/gopherjs/js` you can do things like `js.Global.Get("document").Call("querySelector", ".myclass")` and so on (that's what `honnef.co/go/js/dom` does in, it just wraps that kind of calls into a nicer API).

If you want to use `honnef.co/go/js/dom`, you must discover how it translates `*js.Object` into its own objects (elements, events etc.). Here's someone who has already done that for you: https://github.com/shurcooL/go/blob/20b4b0a352116a106a505a8c528b6513e7e0d5c2/gopherjs_http/jsutil/jsutil.go#L41-L51

**Comment by alltom** [comment]
Oh. Oh well, thanks!

**Comment by shurcooL** [comment]
> [The comment for Object.Interface](https://godoc.org/github.com/gopherjs/gopherjs/js#Object.Interface) just says "Interface returns the object converted to interface{}. See GopherJS' README for details." But the README doesn't seem to mention Interface (any more?).

Hmm. I feel like we can improve the "See GopherJS' README for details." part, it's not very specific and might be out of date. Let's use this issue to track that.

**Comment by shurcooL** [comment]
Yeah, confirmed it's out of date. When that phrase was added in 88f12aa6b316ade3347e7723510a954e09edff1d, the JavaScript <-> Go conversion table was in README. By now, it's located in the [package comment of `js` package](https://github.com/gopherjs/gopherjs/blob/3496c6f94e1b945f3fc9580f6982675c0a74cd6c/js/js.go#L5-L23).
