### ISSUE TITLE
Question: Best practice for exposing variables to the global scope?

### ISSUE THREAD

**Issue by 4ydx** [gopherjs/gopherjs#632]
Is there a recommended way to integrate automated testing done via something like https://github.com/sclevine/agouti?

As it stands I am using global hooks like js.Global.Get("window").Set("MyFunc", myFunc) where perhaps myFunc returns a *js.Object in order to access values sitting inside gopherjs generated scope.

**Comment by shurcooL** [comment]
I'm not sure. I've haven't run into this need yet.

I've only exported functionality from Go to JavaScript world, but not variables.

What you're thinking can work, but be careful if modifying your Go variables from JavaScript can break some internal assumptions your Go code makes.

**Comment by neelance** [comment]
You can't expose variables directly, since the Go world and the JS world don't mix directly. Use accessor functions and add them to the global scope via `js.Global`. Btw: `js.Global.Get("window")` is identical to just `js.Global`.

**Comment by 4ydx** [comment]
If this isn't something that people are doing much of, is there some other testing technique being used?

**Comment by shurcooL** [comment]
To accomplish what?

**Comment by 4ydx** [comment]
If I am using indexeddb, for instance, I would like to be able to make sure that values in the db are what then should be when the user performs given actions.  My current approach would be to provide a method handle to grab the data so that I can automate the testing process using chromedriver.

Maybe there is a good way that I don't know of to mock something like indexeddb/websockets/etc from within gopherjs tests?

**Comment by flimzy** [comment]
> Maybe there is a good way that I don't know of to mock something like indexeddb/websockets/etc from within gopherjs tests?

My approach has been to load a JS mock library, if I'm trying to mock the JS functionality itself.
