### ISSUE TITLE
Syntactic Sugar Proposal: add js.NewObject()

### ISSUE THREAD

**Issue by theclapp** [gopherjs/gopherjs#641]
Writing `js.Global.Get("Object").New()` everywhere is tedious.  I usually write a `current_package.NewObject()` function that does the same.

I propose adding `NewObject()` to the `js` package.

Alternatively: is there a better way around this?  Maybe I should just `var Object = js.Global.Get("Object")` in every package and leave it at that?  Then I could say `Object.New()` which is even shorter than `js.NewObject()`

What's your favorite solution to this (admittedly minor) issue?

**Comment by shurcooL** [comment]
> What's your favorite solution to this (admittedly minor) issue?

My favorite solution is to create fewer JavaScript objects. 😛

**Comment by tj** [comment]
Without knowing anything about how the internals work, it would be awesome if it were optional. 

Often I'd do something like this to get around having to expose `js.Object` outside of the API, but it'd be be cool to just default an empty object if it's nil or something. No clue if that would cause issues with the runtime/compiler though!

```js
// Config for credentials.
type Config struct {
	o               *js.Object
	Region          string `js:"region"`
	AccessKeyID     string `js:"accessKeyId"`
	SecretAccessKey string `js:"secretAccessKey"`
}

// SetConfig updates the default config.
func SetConfig(config Config) *js.Object {
	config.o = js.Global.Get("Object").New()
	return AWS.Get("config").Call("update", config)
}
```

**Comment by tj** [comment]
Oh damn, this part really hurts:

> When creating a struct literal with a *js.Object in it, you have to initialize any other fields separately.

That alone kind of ruins the UX when going from Go -> JS in bindings.

**Comment by shurcooL** [comment]
My personal preference is to keep the API surface of `js` package as small as possible. It's a special package, so understanding it is important, and it's easier when the package is smaller. The criteria for something being added is usually that it cannot be done outside of `js` package. If it can be done outside, then it's probably better to have it outside.

@neelance and I have already rejected adding anything to `js` to deal with checking for presence of key in object, because we found that it was possible to do without adding to `js` API. See #621.

So I doubt we'd want to add a func just for syntactic shortcut.

**Comment by theclapp** [comment]
Thanks @shurcooL for the comment.  No worries, and that makes sense to me.

After writing this issue I explored other / better(?) / shorter ways to get a new object, and I think I like

```go
var O = func() *js.Object { return js.Global.Get("Object").New() }
// or could be just `o`, i.e. not exported

// ...

someVar := &someStruct{ Object: O() }
```

I'm still interested in whether other folks have other ideas about this (again, admittedly minor) issue.

**Comment by flimzy** [comment]
> I'm still interested in whether other folks have other ideas about this (again, admittedly minor) issue.

I very rarely find myself needing this.  Probably 95% of my use case for creating new JS objects this way is just in unit tests, to validate that my Go code behaves properly with various JS inputs. And even then, I've rarely been tempted to create a package-level variable, let alone ponder a larger-scale solution.

It's quite possible that your use cases are sufficiently different from mine to warrant what you're doing.  But I also wonder if this might be an XY problem, and an entirely different approach would be appropriate.  If you feel like elaborating (perhaps providing links to code where you do this), I'd be happy to take a gander and offer my opinion. No guarantees that my opinion will be of any special value,though. :)
