### ISSUE TITLE
strange error happening in just one function of a Go library after compiled

### ISSUE THREAD

**Issue by fiatjaf** [gopherjs/gopherjs#642]
There is this [Lua VM implemented in Go](https://github.com/yuin/gopher-lua), which I actually [run through gopherjs some time ago and made a thin wrapper over it](https://github.com/fiatjaf/glua) so it could be used easily from Javascript.

It works, it's amazing that it works so easily. But someday, when using my JS package, I stumbled upon an unexpected behavior in one Lua function, it is not even an error, just that the `string.gsub` function isn't behaving correctly. I thought it could be an error in the Go VM implementation, but no.

Ignoring my JS package, I just run these in a blank repository:

```sh
fiatjaf@cantillon ~/c/g/s/test> ls
gopherlua.go
fiatjaf@cantillon ~/c/g/s/test> cat gopherlua.go 
package main

import lua "github.com/yuin/gopher-lua"

func main() {
        L := lua.NewState()
        defer L.Close()
        if err := L.DoString(`
print(string.gsub("banana", "a", "A", 2))
    `); err != nil {
                panic(err)
        }
}
fiatjaf@cantillon ~/c/g/s/test> go run gopherlua.go 
bAnAna  2
fiatjaf@cantillon ~/c/g/s/test> rm -rf ~/comp/go/pkg/linux_js*
fiatjaf@cantillon ~/c/g/s/test> gopherjs run gopherlua.go 
banana  0
fiatjaf@cantillon ~/c/g/s/test> 
```

So something wrong is happening in the transition between the Go code and the Lua code.

The `string.gsub` function is implemented in Go as part of the Lua standard library, [the code for it is this](https://github.com/yuin/gopher-lua/blob/b402f3114ec730d8bddb074a6c137309f561aa78/stringlib.go#L146-L172):

```go
func strGsub(L *LState) int {
	str := L.CheckString(1)
	pat := L.CheckString(2)
	L.CheckTypes(3, LTString, LTTable, LTFunction)
	repl := L.CheckAny(3)
	limit := L.OptInt(4, -1)

	mds, err := pm.Find(pat, unsafeFastStringToReadOnlyBytes(str), 0, limit)
	if err != nil {
		L.RaiseError(err.Error())
	}
	if len(mds) == 0 {
		L.SetTop(1)
		L.Push(LNumber(0))
		return 2
	}
	switch lv := repl.(type) {
	case LString:
		L.Push(LString(strGsubStr(L, str, string(lv), mds)))
	case *LTable:
		L.Push(LString(strGsubTable(L, str, lv, mds)))
	case *LFunction:
		L.Push(LString(strGsubFunc(L, str, lv, mds)))
	}
	L.Push(LNumber(len(mds)))
	return 2
}
```

Can anyone see any strange thing happening in there? Maybe the problem is hiding itself in a deeper layer.

Thank you very much.

**Comment by flimzy** [comment]
I don't know about that specific instance, but gopher-lua [depends on](https://godoc.org/github.com/yuin/gopher-lua?imports) `unsafe` and `runtime`. `unsafe` is completely unsupported in GopherJS, and `runtime` has only partial support. I would start by looking for where and how these two packages are used, to see if that points to a cause of your problem.

**Comment by shurcooL** [comment]
I have a fairly good guess.

> unsafeFastStringToReadOnlyBytes

I'm guessing that uses unsafe package, or reflect package, to perform string manipulation in a way GopherJS doesn't support. Can you post its source code?

If that's the case, you'll need to provider a safe alretrnative implementation for `js` architecture using build tags.

**Comment by fiatjaf** [comment]
Ok, I don't know how and where `unsafe` is being used, but I don't think the problem is there.

I dug up more and found the inconsistent behavior happening this line: https://github.com/yuin/gopher-lua/blob/b402f3114ec730d8bddb074a6c137309f561aa78/pm/pm.go#L446

This is inside a `switch` statement where the Lua pattern passed to `gsub` is parsed:

```
default:
	sc.Next()
	pat.Patterns = append(pat.Patterns, &singlePattern{&charClass{ch}})
```

Through some `log.Print()` calls I found that, both when running it in Go and gopherjs, `ch` is `97`. But in gopherjs `pat` is `&{false false []}` before the append, but `&{false false [0x1]}` after, while in Go it is the same before, but after it is `&{false false [0xc42000ed10]}`.

The `&singlePattern{&charClass{ch}}` thing shouldn't be anything magical, as

```go
type singlePattern struct {
	Class class
}

type charClass struct {
	Ch int
}
```

**Comment by fiatjaf** [comment]
In a related point, if `unsafe` is completely unsupported, how does this code even run anyway?

**Comment by shurcooL** [comment]
Programs that import and rely on `unsafe` package are not guaranteed to work. But there is no promise it won't work at all, just that behavior is undefined.

**Comment by shurcooL** [comment]
> Through some `log.Print()` calls I found that, both when running it in Go and gopherjs, `ch` is `97`. But in gopherjs `pat` is `&{false false []}` before the append, but `&{false false [0x1]}` after, while in Go it is the same before, but after it is `&{false false [0xc42000ed10]}`.

The difference in pointer address 0x1 vs 0xc42000ed10 is likely harmless. GopherJS simulates pointer addresses. What's important is that both values are not `nil`.

**Comment by fiatjaf** [comment]
I'm not sure if `unsafe` is causing any problems here, but the problem I've pointed above seems to be a real one. I've isolated it and it continues to happen.

Here it is happening in the GopherJS playground: https://gopherjs.github.io/playground/#/Wu1miLZALj

**Comment by fiatjaf** [comment]
> The difference in pointer address 0x1 vs 0xc42000ed10 is likely harmless. GopherJS simulates pointer addresses. What's important is that both values are not nil.

Oh.

**Comment by fiatjaf** [comment]
> I have a fairly good guess.

Solved it by replacing `unsafeFastStringToReadOnlyBytes()` with `[]byte()`.

Thank you very much!

**Comment by shurcooL** [comment]
Ok, I don't know how and where `unsafe` is being used, but I don't think the problem is there.

`unsafe` is used in `unsafeFastStringToReadOnlyBytes`:

```Go
func unsafeFastStringToReadOnlyBytes(s string) []byte {
	sh := (*reflect.StringHeader)(unsafe.Pointer(&s))
	bh := reflect.SliceHeader{sh.Data, sh.Len, sh.Len}
	return *(*[]byte)(unsafe.Pointer(&bh))
}
```

Try replacing that with a safe version and see if that's sufficient to fix your problem:

```Go
// +build js

func unsafeFastStringToReadOnlyBytes(s string) []byte {
	return []byte(s)
}
```

**Comment by fiatjaf** [comment]
Thank you very much.

**Comment by shurcooL** [comment]
No problem.

> Is there a way I can provide a that as a safe alternative without having to modify/fork `github.com/yuin/gopher-lua`?

`github.com/yuin/gopher-lua` will need to be modified. You can send a PR that moves `unsafeFastStringToReadOnlyBytes` from `utils.go` into a new file `unsafe.go`:

```Go
// +build !js,!appengine,!safe

package lua

import (
	"reflect"
	"unsafe"
)

func unsafeFastStringToReadOnlyBytes(s string) []byte {
	sh := (*reflect.StringHeader)(unsafe.Pointer(&s))
	bh := reflect.SliceHeader{sh.Data, sh.Len, sh.Len}
	return *(*[]byte)(unsafe.Pointer(&bh))
}
```

And create another new file `safe.go` for platforms that cannot use `unsafe` package:

```Go
// +build js appengine safe

package lua

func unsafeFastStringToReadOnlyBytes(s string) []byte { return []byte(s) }
```

Reference: https://github.com/camlistore/go4/blob/16ace784e4b16df1d51c3435223b1d602cd43bfa/reflectutil/swapper_unsafe.go#L5-L12 and https://github.com/camlistore/go4/blob/16ace784e4b16df1d51c3435223b1d602cd43bfa/reflectutil/swapper_safe.go#L5-L9.
