### ISSUE TITLE
Object.scrollTop (scrollLeft) is not a function

### ISSUE THREAD

**Issue by derblitz** [gopherjs/gopherjs#653]
Javascript allows you to get the scrollbar locations within a div tag using the scrollTop / scrollLeft functions. I was not able to get it working with gopherjs.

I tried it this way:
```
fmt.Println(divContainer.Call("scrollTop").Int())
```

The browser console however returned the following message:
TypeError: divContainer.BasicHTMLElement.BasicElement.BasicNode.Object.scrollTop is not a function

Using the DOM binding project ("honnef.co/go/js/dom") I'm facing the same issue.

**Comment by neelance** [comment]
`scrollTop` is not a function, it is just a simple field, see https://developer.mozilla.org/en/docs/Web/API/Element/scrollTop. Use `Get` instead of `Call`.

**Comment by derblitz** [comment]
Oh, my go. thanks for quick response and solution!

I confirm, this way it works:
```
fmt.Println(divContainer.Get("scrollTop"))
```
