### ISSUE TITLE
How can I use ghoperjs like otto?

### ISSUE THREAD

**Issue by phenrigomes** [gopherjs/gopherjs#660]
I am testing otto, but I found ghoperjs performance better.

**Comment by theclapp** [comment]
I don't see how you could use GopherJS like otto.  Otto interprets JS within a Go program.  To run it, you need the JS code you want to run, and the Go compiler.  GopherJS compiles Go to Javascript.  To run it, you need the Go code you want to run, GopherJS itself, and a JS runtime, such as a browser or node.js.  They're two different directions.

If you want to run Go on your browser or in your webpage, GopherJS is a good place to start.  If you want to run JS on your server, like Node does, then it sounds like otto is a good place to start.  (I haven't used otto.)

What, specifically, are you trying to do, and where -- what environment -- are you trying to do it?

**Comment by flimzy** [comment]
I'm going to close this, as it hasn't seen any activity in 18+ months. If this is still relevant, please comment, and we can reopen.
