### ISSUE TITLE
It caused "dial tcp 127.0.0.1:8881: setsockopt: bad address" error when I used client.Do from "net/http" module in golang  

### ISSUE THREAD

**Issue by fearblackcat** [gopherjs/gopherjs#663]
<pre>
Error: Post http://127.0.0.1:8881: dial tcp 127.0.0.1:8881: setsockopt: bad address
    at $callDeferred (/js/testhttp.js:1412:17)
    at $panic (/js/testhttp.js:1451:3)
    at getDataFromPost (/js/testhttp.js:109234:4)
    at Object.v.$externalizeWrapper [as testhttprpc] (/js/testhttp.js:1867:24)
    at Object.<anonymous> (/js/testrpc.js:13:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
</pre>

 ```
        url := "http://127.0.0.1:8881"
	fmt.Println("URL:>", url)

	var jsonStr = []byte(`{"id": 2}`)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonStr))
	req.Header.Set("Content-Type", "application/json")
        client := &http.Client{
		Transport: &http.Transport{
			MaxIdleConnsPerHost: 5,
		},
	}
        resp, err := client.Do(req) // this line caused error
	if err != nil {
		panic(err)
	}
```

Does gopherjs support  net/http module in golang ?

**Comment by myitcv** [comment]
@fearblackcat take a look through the wiki on guidance regarding `net/http`:

https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas

Line starts _"For making HTTP requests..."_

**Comment by shurcooL** [comment]
> Does gopherjs support net/http module in golang ?

Yes, it does. I use `net/http` in all my frontend programs.

You need to use `http.DefaultTransport` rather than creating `&http.Transport{MaxIdleConnsPerHost: 5}`. The default transport is overridden to be a custom transport that uses Fetch API or XHR API.

**Comment by fearblackcat** [comment]
@shurcooL  I changed the http.Transport to http.DefaultTransport. But it also cannot be used.
`
Error: Post http://127.0.0.1:8881: net/http: neither of Fetch nor XMLHttpRequest APIs is available`

These is my code.

<pre>
 client := &http.Client{
		Transport: http.DefaultTransport,
	}
	resp, err := client.Do(req)
</pre>

**Comment by shurcooL** [comment]
My advice was for using `net/http` in the browser, which provides XHR and Fetch APIs.

It doesn't work for node, because node doesn't provide those APIs. You'd need to install a polyfill. See #586.

But if you need to run it on backend instead of browser, why not use normal Go compiler?

**Comment by fearblackcat** [comment]
@shurcooL  Thanks to reply. It helps me enormously
