### ISSUE TITLE
Installation and use - nothing is working

### ISSUE THREAD

**Issue by JohanPienaar** [gopherjs/gopherjs#666]
I've followed the Installation and Usage steps... 
"_Get or update GopherJS and dependencies with: go get -u github.com/gopherjs/gopherjs
Now you can use gopherjs..._" Terminal says no!  I keep getting: "-bash: gopherjs: command not found" on both Windows and Mac. Where did I go wrong? 

PS: Go version:  1.8.3

**Comment by shurcooL** [comment]
Those instructions assume you've already added your `GOPATH/bin` directory to your `PATH`. Have you done that?

**Comment by JohanPienaar** [comment]
Oh assumptions! The root of all evil :) 
Cheers - that worked!!
