### ISSUE TITLE
what's the data type corresponding to byte array ([]byte) in javascript

### ISSUE THREAD

**Issue by fearblackcat** [gopherjs/gopherjs#667]
question is same to title.   Is it array? I mean in front side web browser.

**Comment by flimzy** [comment]
The [gopherjs/js](http://godoc.org/github.com/gopherjs/gopherjs/js) docs provide a handy table, which shows that `[]int8` (for which `[]byte` is an alias), converts to a `Int8Array` in JavaScript.

**Comment by fearblackcat** [comment]
@flimzy  thx.

**Comment by myitcv** [comment]
Just to flag up https://github.com/gopherjs/gopherjs/issues/617#issuecomment-297129541 in this context; that issue (and corresponding PR to follow) will ensure that values pass to/from Go/Javascript worlds are as "expected" (the issue looks to refine what we mean by "expected").
