### ISSUE TITLE
Request: (*Object)Time() time.Time method

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#668]
It's possible to convert a JS `Date` object to `time.Time` with a struct:

    type foo struct {
        *js.Object
        FooTimestamp time.Time `js:"timestamp"`
    }

But I don't see any way to do it otherwise.

Would it be reasonable to add a `Time()` method to the `*js.Object` type to do this, to match `Int64()`, `String()`, `Bool()`, `Float()`, etc, etc?

I envisage a function signature of:

    func (o *Object) Time() time.Time

Which would panic if `o` is not an instance of JS type `Date`.

**Comment by shurcooL** [comment]
> But I don't see any way to do it otherwise.

It's possible to convert it directly. See the table at [`js`](https://godoc.org/github.com/gopherjs/gopherjs/js) package docs:

![image](https://user-images.githubusercontent.com/1924134/28754657-76752934-7517-11e7-9646-5ea78f527189.png)

https://gopherjs.github.io/playground/#/P7ktYq34Zl

**Comment by flimzy** [comment]
Oh right. Thanks. Not sure why I overlooked that.  :+1:

**Comment by myitcv** [comment]
Just to confirm the perhaps obvious: this conversion will remain post #617.
