### ISSUE TITLE
Consider embedding Go standard library into GopherJS binary.

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherjs#672]
This issue is to discuss a potential idea and figure out if it's good or not.

Right now, GopherJS relies on the user's installed copy of Go to access the Go standard library and tests.

Another property of GopherJS is that it supports exactly one version of Go at a time - the current version. It doesn't work with a newer version, because there's no support for changes. It doesn't work with older versions, because certain things it needs may be missing there.

We could consider embedding the entire Go standard library to make `gopherjs` binary more independent.

This has the following tradeoffs.

### Current Approach

- Nothing to do to stay as is. Less implementation time/effort.
- Smaller GopherJS binary, faster compilation of the `gopherjs` binary.
- Probably easier development of GopherJS, less overhead.
- Consistent results/behavior with the native Go compiler, because the versions are guaranteed to be in sync.
- TODO: List the rest.

### Alternative Approach

- Costs implementation time/effort.
- A working copy of `gopherjs` binary no longer stops working when user updates to newer version of Go.
- Larger binary, slower compilation of `gopherjs` binary.
- Potentially more control over standard library files.
- TODO: List the rest.

At this point, I don't know if it's worth doing this. First step is to keep adding to advantages/disadvantages above until we have a complete picture, then we can make a more informed decision.

**Comment by flimzy** [comment]
How, if at all, might this affect the ability to vendor GopherJS? (a feature a few people have requested in the past)

**Comment by shurcooL** [comment]
It may or may not be related. I'm not sure how vendoring ties into this. It might be the case that vendoring can be fixed independently. Or maybe this change would make it easier. Answering that question needs investigation.

**Comment by dmitshur** [comment]
This proposal ended up being considered in #941 (as "Alternative 2"), but ultimately [not chosen](https://github.com/gopherjs/gopherjs/issues/941#issuecomment-583767534). The alternative solution of adding a `GOPHERJS_GOROOT` that provides the needed Go version standard library on disk was used instead.

It seems we can close this now because the underlying need has been resolved. If something changes in the future to make it worth reconsidering this, it can be reopened (or a new issue filed).
