### ISSUE TITLE
feature request: output a single file / package without the synthetic sugar

### ISSUE THREAD

**Issue by OneOfOne** [gopherjs/gopherjs#676]
Hello,

I love gopherjs, however I need the part where it outputs *only* the code for the file I give it rather than the stdlib + `github.com/gopherjs/gopherjs/js`.

Is there currently a way to do that? (even using the package directly rather than the binary)

**Comment by flimzy** [comment]
Can you elaborate on why you need this? Are your needs similar to #524, or something else?

**Comment by OneOfOne** [comment]
Actually that's exactly what I wanted, so this is a dup.
