### ISSUE TITLE
Proposal: Include github.com/johanbrandhorst/protobuf in gopherjs org

### ISSUE THREAD

**Issue by johanbrandhorst** [gopherjs/gopherjs#677]
Hi!

I've been working on bindings for the Google Protocol Buffer implementation for JS, https://www.npmjs.com/package/google-protobuf, coupled with bindings for the unofficial spec-compliant gRPC-Web client by Improbable, https://github.com/improbable-eng/grpc-web. I've developed a `protoc` plugin called `protoc-gen-gopherjs` which generates types and interfaces for working with google protobufs and gRPC from the browser. A demo can be seen on https://grpcweb.jbrandhorst.com. The repo is https://github.com/johanbrandhorst/protobuf.

As I can't see any other effort to mix GopherJS and Protobufs/gRPC-Web, I think it would be great for the exposure of the library and for the GopherJS org to have an official implementation for consolidation of effort and hopefully collaboration on the library itself.

The current status of the project is a conservative Alpha, as I believe it is well tested and should be ready for "production use" whatever that means in the GopherJS context, but I'd love to hear about other people testing it before marking it as beta or 1.0. See https://jbrandhorst.com/post/gopherjs-integration-tests/, https://jbrandhorst.com/post/circleci-docker-compose/ and of course https://sourcegraph.com/github.com/johanbrandhorst/protobuf@master/-/blob/test/client/main.go for more information on my rigorous testing.

Outstanding issues:
- proto2 support, something I've deliberately excluded so far to keep code generation simpler, but will consider including if there is enough demand for it.
- Better documentation, examples. I plan on writing another blog post now that the library does not depend on generated JS files. See the old blog post for reference (NOTE: outdated content): https://jbrandhorst.com/post/gopherjs-grpcweb/
- When the official implementation of `grpc-web` comes around, the library will probably need a little rewriting. I'm not particularly worried about this right now as development on the official library seems to have stalled while waiting for the Fetch browser streaming standard to be finalized to enable client-side and bidirectional streaming.

Would love to hear your thoughts.

**Comment by shurcooL** [comment]
I don't have objections. As I understand, you want to use `gopherjs` org namespace for a GopherJS related binding that doesn't already exist here.

But I just want to point out a few things:

> to have an official implementation

It's not going to be an official implementation, just one that happens to live under this namespace. It will be supported by you and whoever is interested to contribute, not necessarily everyone involved in GopherJS development.

Additionally, it's not neccessary to have the package be in this org to be considered a canonical solution or for discoverability. What matters more is that the package should be listed on the [Bindings wiki page](https://github.com/gopherjs/gopherjs/wiki/Bindings).

As you can see on that page, some canonical bindings are under this namespace, e.g.:

- github.com/gopherjs/websocket - bindings for WebSocket

But some are not, e.g.:

- honnef.co/go/js/dom - DOM bindings
- honnef.co/go/js/xhr - XHR bindings
- github.com/go-humble/locstor - local storage API bindings

So, having the repo under this org or elsewhere is up to you - whatever you prefer. But it's not neccessary to be here to be considered a canonical/discoverable binding for some API.

**Comment by johanbrandhorst** [comment]
You make a good point about discoverability, I think I'll probably keep it where it is now then to prevent disruption to existing users (if any). If it becomes clear that it would be of benefit to the ecosystem to have packages gathered under this namespace I'll reopen this issue. Thanks @shurcooL :).
