### ISSUE TITLE
Add sourceRoot to source maps

### ISSUE THREAD

**Issue by pdf** [gopherjs/gopherjs#685]
Populating `sourceRoot` in source maps would help debuggers successfully locate source files on the filesystem.

**Comment by shurcooL** [comment]
I'm not familiar with source maps very closely. But this sounds reasonable. Would you mind providing some references/information about `sourceRoot`?

**Comment by pdf** [comment]
The "spec", if you can call it that, is rather poorly written, the only reference to `sourceRoot` is here:

http://sourcemaps.info/spec.html#h.75yo6yoyk7x5

I've just realised though that there's no sensible way to use it for Go anyway, due to multi-value GOPATH.

Closing for now, sorry for the noise @shurcooL.

**Comment by shurcooL** [comment]
No problem.

If there are other opportunities to make the generated sourcemaps better, we can always revisit it.
