### ISSUE TITLE
Thrown Websocket errors do not translate to *js.Error errors

### ISSUE THREAD

**Issue by johanbrandhorst** [gopherjs/gopherjs#691]
I'm not sure if this is actually a bug or working as intended, but it seems to be impossible to assert thrown Websocket errors into `*js.Error`s.

This playground link reproduces the behaviour: https://gopherjs.github.io/playground/#/854Urr_pAS.

If this is working as intended, is there some other way to get at the error (with the stack)?

**Comment by shurcooL** [comment]
This appears not to be related to GopherJS, it's how JavaScript works too, and it has to do with implementing the WebSocket spec correctly regarding security/avoiding leaking information to scripts.

See https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation.

(This might also be related to https://github.com/gopherjs/websocket/issues/7, but not sure.)

**Comment by johanbrandhorst** [comment]
If I understand correctly then the error should be provided as an event to the errorHandler? I've updated my example:

https://gopherjs.github.io/playground/#/h1FrRUcO2c

I was hoping there would be some way to stop the warning but I guess not.

**Comment by myitcv** [comment]
> I was hoping there would be some way to stop the warning but I guess not.

I think XHR request errors fall into the same category unfortunately.
