### ISSUE TITLE
Can't build after upgrade to 1.9-1 (possibly version skew)

### ISSUE THREAD

**Issue by microo8** [gopherjs/gopherjs#694]
My distribution now updated go to 1.9, so I updated gopherjs to 1.9-1.

```
$ go version
go version go1.9 linux/amd64

$ gopherjs version
GopherJS 1.9-1
```

But now I cannot build the project that worked in 1.8. Everything compiled with `go build` works, but `gopherjs build` puts out this error message:

```
cannot import, possibly version skew (unknown export format version -1 ("")) - reinstall package
```

**Comment by shurcooL** [comment]
Hmm. Try making a backup of your GOPATH/pkg folder, and then remove it (or just the `_js` directories in it). Does that help?

I suspect this might be related to the change of importer in be6782731291d00d6088ebb4f19c5209bc25194f. But it's surprising that it wouldn't just rebuild the stale archive files.

**Comment by microo8** [comment]
I've removed all `_js` and `_js_min` folders. And now it works. Thanks :+1:
