### ISSUE TITLE
go get fails on Windows

### ISSUE THREAD

**Issue by 200sc** [gopherjs/gopherjs#695]
### What version of Go are you using (go version)?

go1.9 windows/amd64

### What version of GopherJS are you using ?

GopherJS 1.7 (was attempting to update to 1.9)

### What did you do?

`go get -u github.com/gopherjs/gopherjs`

### What did you expect to see?

No errors.

### What did you see instead?

```
..\..\gopherjs\gopherjs\tool.go:768:9: undefined: syscall.Rlimit
..\..\gopherjs\gopherjs\tool.go:769:10: undefined: syscall.Getrlimit
..\..\gopherjs\gopherjs\tool.go:769:28: undefined: syscall.RLIMIT_STACK
```

Looks like the runtime.GOOS check there needs to be in a file that has a `!windows` build tag.

**Comment by shurcooL** [comment]
Thanks for reporting. Indeed. It's from the recently merged #687. We'll need to move that functionality behind a build tag, as you said.
