### ISSUE TITLE
compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_9___

### ISSUE THREAD

**Issue by xiajohnnyxia** [gopherjs/gopherjs#709]
Why I change the Golang's version in **1.8.4** ,
and it also returned the unsupport version in **1.9** when i was building `gopherjs`.

```
/src/github.com/gopherjs/gopherjs/compiler/compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_9___
/src/github.com/gopherjs/gopherjs/compiler/package.go:436: o.IsAlias undefined (type *types.TypeName has no field or method IsAlias
```

**Comment by slimsag** [comment]
GopherJS currently requires Go 1.9; you'll need to use that version of Go.

Ensure `go version` shows 1.9 as well.

**Comment by xiajohnnyxia** [comment]
I used the `1.9` and it returned unsupport version.And I changed 1.7 1.8 1.9.The same result i got.

**Comment by slimsag** [comment]
Only Go 1.9 is supported, changing to 1.7 or 1.8 will not help you.

> I used the 1.9 and it returned unsupport version

What was the exact error? What was the output of `go version` ?

**Comment by xiajohnnyxia** [comment]
Sorry,I was looking in the wrong.My version is 1.8.I always think about that is the latest.Thank you for your help.

**Comment by slimsag** [comment]
Glad to hear you got it figured out! 😄
