### ISSUE TITLE
Failure configuring node-gyp for GopherJS

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#726]
Today one of my GopherJS-targeted projects [began failing](https://travis-ci.org/go-kivik/pouchdb/builds/313958028?utm_source=email&utm_medium=notification) in Travis-CI when running `node-gyp rebuild` as documented [here](https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md#nodejs-on-os-x-and-linux).

Yesterday it was [working](https://travis-ci.org/go-kivik/pouchdb/builds/313371407).

I get the same error on my local Debian 9.3 machine, too. I have tried upgrading to Node.js 8.x, and then 9.x, but receive the same error.

```
make: Entering directory '/home/jonhall/go/src/github.com/gopherjs/gopherjs/node-syscall/build'
  CXX(target) Release/obj.target/syscall/syscall.o
../syscall.cc: In function ‘intptr_t toNative(v8::Local<v8::Value>)’:
../syscall.cc:28:51: warning: ‘v8::Local<v8::Object> v8::Array::CloneElementAt(uint32_t)’ is deprecated: Cloning is not supported. [-Wdeprecated-declarations]
       native[i] = toNative(array->CloneElementAt(i));
                                                   ^
In file included from /home/jonhall/.node-gyp/9.2.1/include/node/v8.h:26:0,
                 from /home/jonhall/.node-gyp/9.2.1/include/node/node.h:63,
                 from ../syscall.cc:2:
/home/jonhall/.node-gyp/9.2.1/include/node/v8.h:3512:31: note: declared here
                 Local<Object> CloneElementAt(uint32_t index));
                               ^
/home/jonhall/.node-gyp/9.2.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/syscall.node
  COPY Release/syscall.node
make: Leaving directory '/home/jonhall/go/src/github.com/gopherjs/gopherjs/node-syscall/build'
```

I'm still investigating. Perhaps someone more familiar with nodejs knows how to solve this?

I know this really isn't a GopherJS bug, but I imagine the solution will be valuable to other GopherJSers, and may be worth adding to the documentation.

**Comment by flimzy** [comment]
Disregard, that error was a red herring; it was happening in the successful case, too.

**Comment by shurcooL** [comment]
Not sure if you spotted it by now or not, but it’s a warning, not an error. That’s why it’d happen in success case too.

```
../syscall.cc:28:51: warning: ...
```

(Also, this is a good example of how the decision to have Go compiler emit only errors, not warnings, is helpful.)
