### ISSUE TITLE
Array via interface conversion fails

### ISSUE THREAD

**Issue by DesWurstes** [gopherjs/gopherjs#727]
The JS code is
```javascript
var temporaryVariable = Uint32Array.from([2,3,4])
```

the Go code is
```
js.Global.Get("temporaryVariable")...
```

How can I access the value of `temporaryVariable`?

I've read the table

| Go type               | JavaScript type       | Conversions back to interface{} |
| --------------------- | --------------------- | ------------------------------- |
| bool                  | Boolean               | bool                            |
| integers and floats   | Number                | float64                         |
| string                | String                | string                          |
| []int8                | Int8Array             | []int8                          |
| []int16               | Int16Array            | []int16                         |
| []int32, []int        | Int32Array            | []int                           |
| []uint8               | Uint8Array            | []uint8                         |
| []uint16              | Uint16Array           | []uint16                        |
| []uint32, []uint      | Uint32Array           | []uint                          |
| []float32             | Float32Array          | []float32                       |
| []float64             | Float64Array          | []float64                       |
| all other slices      | Array                 | []interface{}                   |
| arrays                | see slice type        | see slice type                  |
| functions             | Function              | func(...interface{}) *js.Object |
| time.Time             | Date                  | time.Time                       |
| -                     | instanceof Node       | *js.Object                      |
| maps, structs         | instanceof Object     | map[string]interface{}          |

but I couldn't find which method I should use to use `[]uint`. Is there something like js.Global.Get("temporaryVariable").UintArray()?

**Comment by DesWurstes** [comment]
`.([]uint)`

**Comment by shurcooL** [comment]
To clarify for posterity, I believe it should be:

```Go
js.Global.Get("temporaryVariable").Interface().(uint32)
```

**Comment by DesWurstes** [comment]
@shurcooL It compiles, but running the JS with Node yields:
```
        throw err;
        ^

Error: interface conversion: interface is *js.Object, not []uint8
    at $callDeferred (/Users/Notchshero/go/bin/Temporary.js:1412:17)
    at $panic (/Users/Notchshero/go/bin/Temporary.js:1451:3)
    at $assertType (/Users/Notchshero/go/bin/Temporary.js:1340:5)
    at main (/Users/Notchshero/go/bin/Temporary.js:2330:7)
    at $init (/Users/Notchshero/go/bin/Temporary.js:2389:4)
    at $goroutine (/Users/Notchshero/go/bin/Temporary.js:1471:19)
    at $runScheduled (/Users/Notchshero/go/bin/Temporary.js:1511:7)
    at $schedule (/Users/Notchshero/go/bin/Temporary.js:1527:5)
    at $go (/Users/Notchshero/go/bin/Temporary.js:1503:3)
    at Object.<anonymous> (/Users/Notchshero/go/bin/Temporary.js:2400:1)
    at Object.<anonymous> (/Users/Notchshero/go/bin/Temporary.js:2403:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

The code is this:

```golang
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

func main() {
	t := js.Global.Get("polymodInput").Interface().([]byte)
	...
}

func PolyMod(v []byte) uint64 {
	...
	return x
}
```

Should I open a new issue for this or change the title?

**Comment by shurcooL** [comment]
Reopening this one is fine. You should provide JS code too.

**Comment by DesWurstes** [comment]
JS:
```
var key = [1,2]
function k () {
    // GopherJS code
    "use strict";
    (function() {
        ...
    }).call(this);
}
```

Go:
```
package main

import (
  "github.com/gopherjs/gopherjs/js"
)

func main() {
  _ = js.Global.Get("key").Interface().([]byte)
}

```

Error:
```
Error: interface conversion: interface is *js.Object, not []uint8
...
```

**Comment by myitcv** [comment]
@DesWurstes the line from the type conversion table in the description you need to be reading is that of the Javascript type `Array`. 

https://gopherjs.github.io/playground/#/5lj8aowQuI

A regular Javascript `Array` value can only be converted to an `[]interface{}` value in Go because the values in an `Array` can be of any type.

More specific Javascript-typed values can be converted to more specific Go-typed values, as shown in my example for `Uint8Array`

**Comment by DesWurstes** [comment]
Thank you.
