### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by freeozyl80** [gopherjs/gopherjs#730]
Looking for help : |
![qq 20171219001135](https://user-images.githubusercontent.com/8967606/34115671-43e6cc08-e451-11e7-968b-a57ba4b394ca.png)

**Comment by theclapp** [comment]
Worked for me in the playground.  Suspect that Code doesn't provide the same environment as a browser, and that `js.Global` or `js.Global.Get("document")` is nil.

Try `println(js.Global)` and `println(js.Global.Get("document"))`.  And maybe try running your generated code in a browser or in Node.js, which are both supported environments.  Not sure Code is.

**Comment by kelwang** [comment]
looks like you are using go run to run gopherjs. It's generally okay to use go build or go install. But to run it, you might need to use gopherjs run, or compile it to js file.

**Comment by freeozyl80** [comment]
：D    3q@kelwang
