### ISSUE TITLE
allow go1.10

### ISSUE THREAD

**Issue by glycerine** [gopherjs/gopherjs#735]
It would be nice to allow Go versions past 1.9.
~~~
$ go build
...
../compiler/compiler.go:20:9: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_9___
$ go version
go version go1.10beta1 darwin/amd64
~~~

I realize this may be alot of work, though.

**Comment by myitcv** [comment]
Hi @glycerine - see https://github.com/gopherjs/gopherjs/issues/725 which is tracking support for Go 1.10

**Comment by glycerine** [comment]
Thanks Paul. Closing as dupicate.
