### ISSUE TITLE
transpile only mode

### ISSUE THREAD

**Issue by suntong** [gopherjs/gopherjs#756]
I am looking for a way to transpile Go 

1. file by file, and 
1. without adding any dependencies supporting codes.

In more details,  I need the [builtin library](http://legacytotheedge.blogspot.ca/2014/03/gopherjs-go-to-javascript-transpiler.html) not included in the result, as:

> 1470 LOC and 45kb, uncompressed and unminified.  The bulk of which is the builtin library.
It will only compile what it needs to.  ...  This goes for core packages too.  If I change that code so it requires "fmt", the result explodes to 12845 LOC and 624kb ("fmt" imports a LOT of stuff).

and that was a while ago, now this simple Go code:

```go
package main

func test() {
  return 1 + 2 + 3
}
```

was transpiled into Javascript with 13,496 lines of code, 10 times more than before, and I believe the bulk of which is still the builtin library. Hence the request. Thanks.

**Comment by theclapp** [comment]
Check out https://github.com/dave/jsgo.

**Comment by suntong** [comment]
Ok... how to make use of it for my above purpose? 

So I tried it as per your suggestion, and I created this, 

https://gist.github.com/suntong/8f7866e5ca14980cc595d0031d3d9be4

using https://compile.jsgo.io/, it gives me this (for above url):

https://cdn.jsgo.io/pkg10/gist.github.com/8f7866e5ca14980cc595d0031d3d9be4.cd395299c9e67d1dab16f91b4bfc3a4eb87f1703.js

but I didn't find my own code there, only boiler-plate code. I tried several and none of them contain my own transpiled code (e.g., [this](https://cdn.jsgo.io/pkg10/gist.github.com/a8b9db9fe0ae6b1b299c498f983370e6.fe082f895db8c7c4893c47a98e2beb5ac7ff8d3b.js)). 

So how can I find my own code from it? 

Thx

**Comment by suntong** [comment]
Oh, got it, 

> you'll be shown a link to the page: jsgo.io/dave/jstest.

> If you look at the Network panel in your browser inspector as the page loads, you'll see all the packages in the dependency tree downloading separately. 

moving forward...

**Comment by suntong** [comment]
Got it. Thx @theclapp!

**Comment by theclapp** [comment]
Glad this worked out of the box for you.

My actual intent was that that project could point the way towards doing what you wanted, that is, separating packages out into different files.  But if it actually did what you want all by itself, great!  :)

**Comment by suntong** [comment]
Not quite, but after jumping over several hoops, I _think_ I'm there. 

How `jsgo` is able to do that? I run `gopherjs` on the CLI, and the only option for me is to build the whole package into a single big file. If `jsgo` is able to do, would I be able to do that as well, using just `gopherjs`? -- just trying to find the easiest way, to avoid jumping over those several hoops...

thx

**Comment by theclapp** [comment]
The author (Dave Brophy (not me, in case that's not clear)) talks about it in the Gophers #gopherjs channel [here](https://gophers.slack.com/archives/C039C0R2T/p1518596059000101).  I think the core of it is this:

> So the splitting JS up by package wasn't actually hard at all... GopherJS  already has a public WritePkgCode method that writes the JS for a particular package separately: https://github.com/gopherjs/gopherjs/blob/296de816d4fe28b61803072c3f89360e9d1823ff/compiler/compiler.go#L178
> 
> I just needed to wrap it in a function to defer execution until I had all the packages downloaded, and get them to execute in the right order... That's what the bootstrap code does: https://github.com/dave/jsgo/blob/ab51a6b29c27e1fffa8aa56350862747b181e732/compile/compile.go#L355-L357

For more, well, read the rest of Dave's description, and check out the guts of his project.  I'm afraid that's about all I can offer.  I mean, I haven't looked at Dave's code, so as far as I'm concerned it might as well be magic.  :)

**Comment by suntong** [comment]
Got it. Anything would help. Thanks again for helping!
