### ISSUE TITLE
Reproducible output: image/draw

### ISSUE THREAD

**Issue by dave** [gopherjs/gopherjs#759]
While developing jsgo, I noticed that the entire stdlib builds reproducibly apart from `image/draw`. Only the un-minified code shows the problem.

This switch statement: https://github.com/golang/go/blob/master/src/image/draw/draw.go#L608-L615

... the variables `src0$1`, `src0$2` and `src0` are re-arranged.

<img width="1142" alt="screen shot 2018-02-24 at 08 43 40" src="https://user-images.githubusercontent.com/925351/36627161-1486867e-193f-11e8-84c6-d6d4c2cea3ac.png">

I'll dig into the compiler code and try to work out what's wrong.

**Comment by dave** [comment]
So the problem seems to be that [this](https://github.com/gopherjs/gopherjs/blob/95deb33d587c9f6e24b494ea9bdf9648c48f9a60/compiler/utils.go#L371) is returning several copies of the `src0` object... These have identical `Name` and `Pos()`, so can't be sorted properly [here](https://github.com/gopherjs/gopherjs/blob/95deb33d587c9f6e24b494ea9bdf9648c48f9a60/compiler/utils.go#L373-L376).

**Comment by dave** [comment]
https://github.com/gopherjs/gopherjs/issues/759 fixes this bug. I have a suspicion that `EscapingObjects` shouldn't be returning these objects at all, but this is way out of my sphere of knowledge, so this is a light-touch fix that won't change the behaviour.

**Comment by dave** [comment]
I'm running a few final checks to see if it resolves the reproducible code bug and doesn't introduce any more...

**Comment by dave** [comment]
Yes, this after this PR, I get reproducible JS across the whole standard library. @shurcooL

**Comment by shurcooL** [comment]
> #759 fixes this bug.

That's this issue. Did you mean PR #760?

Also, how does this intersect with #742? I haven't gotten around to reviewing it properly, but I want to soon.

**Comment by dave** [comment]
Yes sorry #760 is the right PR. I believe this is unconnected to #742.
