### ISSUE TITLE
Minifying prelude saves 9KB on all compiles

### ISSUE THREAD

**Issue by dave** [gopherjs/gopherjs#762]
The prelude (added to the top of every generated command) is plain JS, and can't be minified by the compiler. https://github.com/gopherjs/gopherjs/pull/761 adds a manually minified version of the prelude (I used https://skalman.github.io/UglifyJS-online/). This saves 9KB on the minified file size.

**Comment by dave** [comment]
@shurcooL

**Comment by shurcooL** [comment]
Thanks for the suggestion.

As far as I know, for all production uses, GopherJS output is both minified and gzip-compressed. So it's important to compare minify+gzip numbers too.

I ran the numbers:

|                 | `Prelude` | `removeWhitespace(Prelude)` | `PreludeMinified` |
|-----------------|-------------------|-------------------------------------|---------------------------|
| no compression  | 56489             | 41690                               | 32762                     |
| gzip compressed | 12360             | 10540                               | 9322                      |

So, realistically, it's a savings of 1218 bytes that have to go over the wire. Of course, it's more bytes (8928) that need to be parsed/processed by the JS engine.
