### ISSUE TITLE
gopherjs test -c : doesn't not compile more than one file

### ISSUE THREAD

**Issue by morndiaye** [gopherjs/gopherjs#764]
I'm trying to generate list of *_test.js but it seem that only the first _test.go is building. 
"gopherjs test"  is able to run list of tests but "gopherjs test  -c"  compile only one test   instead of compiling all the tests.

**Comment by shurcooL** [comment]
Resolving this would be easier with more clear reproduction steps (e.g., what was the exact code you tried it on, what exact commands did you run, what output did you get, etc.).

**Comment by morndiaye** [comment]
I'm trying to generate javascript test and running in a browser.

what was the exact code:
I use cryptography libraries (xts and xtea  part of the https://godoc.org/golang.org/x/crypto) 

what exact commands did I run:
1) **Running test**
gopherjs test -v  golang.org/x/crypto/xts  golang.org/x/crypto/xtea
    **Output**:
gopherjs: Source maps disabled. Install source-map-support module for nice stack traces. See https://github.com/gopherjs/gopherjs#gopherjs-run-gopherjs-test.
=== RUN   TestXTS
--- PASS: TestXTS (0.03s)
=== RUN   TestShorterCiphertext
--- PASS: TestShorterCiphertext (0.00s)
PASS
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
ok  	golang.org/x/crypto/xts	0.383s
gopherjs: Source maps disabled. Install source-map-support module for nice stack traces. See https://github.com/gopherjs/gopherjs#gopherjs-run-gopherjs-test.
=== RUN   TestBlocksize
--- PASS: TestBlocksize (0.00s)
=== RUN   TestCipherInit
--- PASS: TestCipherInit (0.00s)
=== RUN   TestInvalidKeySize
--- PASS: TestInvalidKeySize (0.00s)
=== RUN   TestEncodeDecode
--- PASS: TestEncodeDecode (0.00s)
=== RUN   TestCipherEncrypt
--- PASS: TestCipherEncrypt (0.00s)
=== RUN   TestCipherDecrypt
--- PASS: TestCipherDecrypt (0.00s)
PASS
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
ok  	golang.org/x/crypto/xtea	0.387s

All tests are launched

2) **Generate javascript test**
gopherjs test -v  golang.org/x/crypto/xts  golang.org/x/crypto/xtea
**Output**:
-rw-rw-r-- 1 css css 1948315 Feb 27 16:50 xts_test.js
-rw-rw-r-- 1 css css   81423 Feb 27 16:50 xts_test.js.map

In this part, only xts_test.js is generated instead of  xts_test.js and xtea_test.js and it does not contain all tests.

Result of xts_test.js in a browser:
PASS                                xts_test.js:8891

**Comment by shurcooL** [comment]
The `gopherjs` command mimics the CLI of the `cmd/go` command. In `cmd/go`, the `-c` flag can only be used on a single package a time. See:

```
$ go test -v golang.org/x/crypto/xts golang.org/x/crypto/xtea
=== RUN   TestXTS
--- PASS: TestXTS (0.00s)
=== RUN   TestShorterCiphertext
--- PASS: TestShorterCiphertext (0.00s)
PASS
ok  	golang.org/x/crypto/xts	0.007s
=== RUN   TestBlocksize
--- PASS: TestBlocksize (0.00s)
=== RUN   TestCipherInit
--- PASS: TestCipherInit (0.00s)
=== RUN   TestInvalidKeySize
--- PASS: TestInvalidKeySize (0.00s)
=== RUN   TestEncodeDecode
--- PASS: TestEncodeDecode (0.00s)
=== RUN   TestCipherEncrypt
--- PASS: TestCipherEncrypt (0.00s)
=== RUN   TestCipherDecrypt
--- PASS: TestCipherDecrypt (0.00s)
PASS
ok  	golang.org/x/crypto/xtea	0.008s
$ go test -v -c golang.org/x/crypto/xts golang.org/x/crypto/xtea
cannot use -c flag with multiple packages
```

You can just invoke `gopherjs -c` twice to get the results you want:

```
gopherjs test -v -c golang.org/x/crypto/xts
gopherjs test -v -c golang.org/x/crypto/xtea
```

This bug needs to be fixed by adding a "cannot use -c flag with multiple packages" error message when multiple packages are provided to `gopherjs test -c`.
