### ISSUE TITLE
Deal with CircleCI 1.0 End of Life on August 31, 2018.

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherjs#766]
See https://circleci.com/blog/sunsetting-1-0/:

> TL;DR: After August 31, 2018, CircleCI 1.0 will no longer be available for Linux and macOS users.

We're currently using CircleCI 1.0 for this project (/cc @neelance):

![image](https://user-images.githubusercontent.com/1924134/36761547-8d914b20-1bed-11e8-88fa-e67e3c395631.png)

Need to deal with it by the time it's shut down. Options include:

- migrate to CircleCI 2.0 (if it's still free)
- migrate to another CI

**Comment by myitcv** [comment]
Per https://circleci.com/pricing/#faq-section-linux I have contacted CircleCI (copying @shurcooL) asking them what our options are. 

We can of course evaluate Travis in parallel.

**Comment by neelance** [comment]
Is there any reason against CircleCI 2.0? I'm already using it for another project and it is great.

**Comment by myitcv** [comment]
None at all! Just mentioned that as a hedge; I've got no experience of CircleCI 2, so great to hear it's good!

**Comment by myitcv** [comment]
Ok, just heard back - unsurprisingly we can keep the free service and just need to follow https://circleci.com/docs/2.0/migrating-from-1-2/ in order to upgrade.
