### ISSUE TITLE
How to call a GopherJS function from javascript?

### ISSUE THREAD

**Issue by maxence-charriere** [gopherjs/gopherjs#767]
Hello,

I have this function
```go
func Hello() {
    fmt.Println("hello world")
}
```

I generate the js file with gopherjs.

Then I would like to call it from standard javascript.
How to do it ?

**Comment by 1l0** [comment]
Go:
```go
js.Global.Set("Hello", Hello)
```
Javascript:
```javascript
Hello();
```

**Comment by maxence-charriere** [comment]
Got it.
Thank you.

**Comment by shurcooL** [comment]
If you want additional information on this topic, you might find https://dmitri.shuralyov.com/blog/24 helpful. It covers the process of making a Go function available to be called from JavaScript in full detail.
