### ISSUE TITLE
syscall error

### ISSUE THREAD

**Issue by Inkeliz** [gopherjs/gopherjs#776]
```
src/syscall/syscall_nonlinux.go:5:18: undeclared name: SYS_EXIT
/src/syscall/syscall.go:53:39: too few arguments in call to Syscall
```
I'm using Windows and go1.10. I'm trying to build (`gopherjs build`) this code:

```
package main
//go:generate gopherjs build main.go -o js/app.js -m
// +build ignore

import (
  "log"
)

func main() {
    log.Println("Hello World")
}
```

**Comment by shurcooL** [comment]
I don’t think any of GopherJS developers use or support Windows, so building with `GOOS=windows` likely doesn’t work. However, you should be able to build with `GOOS=linux gopherjs build` or `GOOS=darwin gopherjs build`.

**Comment by Inkeliz** [comment]
Thank you so much, it works pretty nice. Even features that is not mentioned in the page of compatibilities.

I have one question, I think it's the last one, I don't know if I need to open one new issue. But, It's possible to get data from one `<input type="file">`? I mean the user "upload" the file, but instead of send it to one server the file is processed locally, using the JS which is compiled from Golang.

**Comment by shurcooL** [comment]
Yes, that is absolutely possible.

The `<input>` element has a `files` property that you can access. It’s likely going to be a blob. You can convert that to a byte slice and then run any Go code on it.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement.

In the `dom` wrapper package, the `files` property is available as [`HTMLInputElement.Files`](https://godoc.org/honnef.co/go/js/dom#HTMLInputElement.Files) method.

**Comment by Inkeliz** [comment]
I'll take a look in the first alternative, that uses the Javascript. I'm trying with ` HTMLInputElement.Files` but don't have sucess for now, it only show `[object File]`, one of my test was:

	js.Global.Get("document").Call("write", `<input class="x" type="file">`)

	root := dom.GetWindow().Document()
	input := root.QuerySelector(".x")

	input.AddEventListener("change", true, func(dom.Event) {
		f := input.(*dom.HTMLInputElement)
		fmt.Println(f.Files()[0].Object.String())
	})

In the docs it says "The dom package does not define any methods on File nor does it provide access to the blob or a way to read it.". :\

**Comment by Inkeliz** [comment]
I found one similar issue, https://github.com/dominikh/go-js-dom/issues/32. I don't know if have a better method, if something change in the GopherJS since this issue. But for now I'm using something very similar to your reply.

```
func blobToBytes(blob *js.Object) []byte {
	var b = make(chan []byte)
	fileReader := js.Global.Get("FileReader").New()
	fileReader.Set("onload", func() {
		b <- js.Global.Get("Uint8Array").New(fileReader.Get("result")).Interface().([]byte)
	})
	fileReader.Call("readAsArrayBuffer", blob)
	return <-b
}

func main() {

	js.Global.Get("document").Call("write", `<input class="x" type="file">`)

	root := dom.GetWindow().Document()
	input := root.QuerySelector(".x")

	input.AddEventListener("change", true, func(dom.Event) {
		go func() {
			result := blobToBytes(input.(*dom.HTMLInputElement).Files()[0].Object)
			fmt.Println(string(result))
		}()
	})
}
```

If someone have the same problem, but will be nice if the `Files` have something like `.Bytes()`. :D

**Comment by shurcooL** [comment]
> In the docs it says "The dom package does not define any methods on File nor does it provide access to the blob or a way to read it.". :\

Indeed. You need to do it yourself with something like:

```Go
// blobToBytes converts a Blob to []byte.
func blobToBytes(blob *js.Object) []byte {
	b := make(chan []byte)
	fileReader := js.Global.Get("FileReader").New()
	fileReader.Set("onload", func() {
		b <- js.Global.Get("Uint8Array").New(fileReader.Get("result")).Interface().([]byte)
	})
	fileReader.Call("readAsArrayBuffer", blob)
	return <-b
}
```

**Comment by Azareal** [comment]
```GOOS=linux gopherjs build
'GOOS' is not recognized as an internal or external command,
operable program or batch file.``` That doesn't seem to work on Windows.

**Comment by paralin** [comment]
@Azareal `$env:GOOS="linux"`
