### ISSUE TITLE
gcimporter15 is gone so build fails

### ISSUE THREAD

**Issue by cvermilion** [gopherjs/gopherjs#788]
`gopherjs` depends on the `golang.org/x/tools/go/gcimporter15` package, which has been deprecated for some time:

https://godoc.org/golang.org/x/tools/go/gcimporter15
> Deprecated: this package will be deleted in October 2017. New code should use golang.org/x/tools/go/gcexportdata.

The removal was finally done [last night](https://github.com/golang/tools/commit/5dfd8930f264888dd5fe26820a0ac605a384dd33), so now `go get github.com/gopherjs/gopherjs` fails for me with an error like:

```
go get -d github.com/gopherjs/gopherjs
package golang.org/x/tools/go/gcimporter15: cannot find package "golang.org/x/tools/go/gcimporter15" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter15 (from $GOROOT)
	/home/circleci/project/src/golang.org/x/tools/go/gcimporter15 (from $GOPATH)
```

**Comment by myitcv** [comment]
Thanks @cvermilion - I've pushed up #789 as a sticking plaster until we migrate, per the
deprecation notice, to `golang.org/x/tools/go/gcexportdata`

**Comment by shurcooL** [comment]
Thanks for reporting this @cvermilion and sending the PR @myitcv!
