### ISSUE TITLE
access: request for increased Github PR/issue access

### ISSUE THREAD

**Issue by myitcv** [gopherjs/gopherjs#799]
Hi @neelance @shurcooL @hajimehoshi - as discussed offline, I'd like to request increased Github access to:

* help manage issues
* review, merge PRs etc

I've been contributing to the GopherJS project for some time now, helping to respond on Slack, [raising issues](https://github.com/gopherjs/gopherjs/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Amyitcv+), [responding to issues](https://github.com/gopherjs/gopherjs/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Amyitcv+), and [contributing PRs](https://github.com/gopherjs/gopherjs/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amyitcv).

Outside of GopherJS I'm also a [member/approver](https://github.com/golang/go/issues/24596) on the Go project.

Thanks for considering.

**Comment by hajimehoshi** [comment]
lgtm!

**Comment by dmitshur** [comment]
We've added you. Thank you Paul!

**Comment by myitcv** [comment]
Thanks @dmitshur and @hajimehoshi. I look forward to helping to get the GopherJS project on a more sure footing for the future.

**Comment by myitcv** [comment]
Please can someone also add me to the GopherJS org? 

https://github.com/orgs/gopherjs/people

Thanks

**Comment by hajimehoshi** [comment]
@neelance ?

**Comment by neelance** [comment]
Done.
