### ISSUE TITLE
Omitted variadic function parameter should be nil

### ISSUE THREAD

**Issue by bzub** [gopherjs/gopherjs#806]
### Example
```go
func(s ...string) {
    if s == nil {
        fmt.Println("s is nil")
    }
}()
```
With Go compiler `s == nil` ([playground](https://play.golang.org/p/G2jPMo5sT-0))
With GopherJS `s != nil` ([playground](https://gopherjs.github.io/playground/#/1jQnzf995r))

### Spec
https://golang.org/ref/spec#Passing_arguments_to_..._parameters

**Comment by myitcv** [comment]
Hmm I was fairly certain I'd filed and issue for this in the past, @bzub. But I guess I misremembered because I can't find anything.

I've just pushed up #807 to fix this; perhaps you could give it a try:

```
cd $(go list -f '{{.Dir}}' github.com/gopherjs/gopherjs) && \
git fetch origin pull/807/head && \
git checkout FETCH_HEAD && \
go install
```
