### ISSUE TITLE
docs for js tags

### ISSUE THREAD

**Issue by neelance** [gopherjs/gopherjs#81]
related to #79

**Comment by myitcv** [comment]
Will be covered as part of #633 and #634 - but can leave as a placeholder for now

**Comment by shurcooL** [comment]
I don't see value in leaving this issue open. It looks like a mental note @neelance made for himself in 2014, I don't think it's relevant anymore. #79 itself can track that.

I'll close this. If something specific needs to be done, it's better to open a new issue and describe it in more detail.
