### ISSUE TITLE
`Invoke` doesn't consider dot-dot-dot arguments?

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#818]
https://gopherjs.github.io/playground/#/OrjvxTxNQR

```go
package main

import (
	"fmt"

	"github.com/gopherjs/gopherjs/js"
)

func main() {
        x := js.InternalObject(func(x ...int) {
                fmt.Println(x)
        })
        x.Invoke(1, 2)
}
```

I think this should show `[1, 2]` but crashes:

```
panic: Cannot read property 'length' of undefined 
```

**Comment by myitcv** [comment]
I'm not quite sure why you are using `js.InternalObject` here. That bypasses the externalising of the function value which is, I think, not what you intended here. Instead:

```go
package main

import (
	"fmt"

	"github.com/gopherjs/gopherjs/js"
)

func main() {
	js.Global.Set("banana", func(x ...int) {
                fmt.Println(x)
        })
        js.Global.Get("banana").Invoke(1, 2)
}
```

https://gopherjs.github.io/playground/#/L0FeOKl1r2

**Comment by hajimehoshi** [comment]
Ah ok, I should've used `MakeFunc` instead of `InternalObject`, and I should not expect how `InternalObject` behaves. Thanks.
