### ISSUE TITLE
 cannot convert math.MaxInt64

### ISSUE THREAD

**Issue by andyafter** [gopherjs/gopherjs#822]
cannot convert math.MaxInt64 (untyped int constant 9223372036854775807) to int

The error returned when trying to compile things into js.

**Comment by theclapp** [comment]
Can you show more of the code you're trying to compile?

The Go playground reports the same difficulty trying to convert math.MaxInt64 into an int:

    fmt.Println(int(math.MaxInt64))
    => prog.go:9:17: constant 9223372036854775807 overflows int

so it might not be a GopherJS thing.

**Comment by andyafter** [comment]
<img width="383" alt="screen shot 2018-05-21 at 11 02 11 pm" src="https://user-images.githubusercontent.com/3354145/40314445-14ad5b3c-5d4b-11e8-87cf-0443526591bb.png">

**Comment by shurcooL** [comment]
GopherJS emulates a 32-bit environment. `int` is 32 bits, so the `math.MaxInt64` constant is too large for it. It will fit into a `int64` variable though.

See https://github.com/gopherjs/gopherjs#general.

**Comment by theclapp** [comment]
Yeah, `int(math.MaxInt64)` will never work, anywhere.  Why would you think it would?

In any case, consider

```go
func MinInt(inputs ...int) int {
	if len(inputs) == 0 {
		return math.MaxInt32
	}
	found := inputs[0]
	for _, value := range inputs[1:] {
		if value < found {
			found = value
		}
	}
	return found
}
```

**Comment by shurcooL** [comment]
> `int(math.MaxInt64)` will never work, anywhere

Not sure what you mean, but it would work on a 64-bit environment where `int` is 64 bits.

**Comment by theclapp** [comment]
I said:
> Yeah, int(math.MaxInt64) will never work, anywhere.

That was wrong.  In some environments (like macOS native Go) `int` is 64 bits.  Sorry.

**Comment by andyafter** [comment]
Yep I am compiling this project in OSX. And this piece of code has been working for a very long time. Is there anything I could do to stop this compiling error when using `gopherjs`?

**Comment by andyafter** [comment]
Is there any possibility that I could emulate a 64 bits environment in this case?

**Comment by crvv** [comment]
Your code is wrong. `int(math.MaxInt64)` is not the biggest integer on 32 bits platforms.
Please read
https://stackoverflow.com/questions/6878590

**Comment by andyafter** [comment]
Yeah so the only way to make it work is to refactor it for 32bit platform I guess?

**Comment by flimzy** [comment]
I'm going to close this, as it hasn't seen any activity in 18+ months. If this is still relevant, please comment, and we can reopen.
