### ISSUE TITLE
How could I join gopherjs slack channel?

### ISSUE THREAD

**Issue by andyafter** [gopherjs/gopherjs#823]
As the title presents. Also how should there be a gopherjs discord channel?

**Comment by myitcv** [comment]
@andyafter sign up to the gophers slack team https://invite.slack.golangbridge.org/ and then simply join `#gopherjs`

**Comment by flimzy** [comment]
I'm going to close this, as it hasn't seen any activity in 18+ months. If this is still relevant, please comment, and we can reopen.
