### ISSUE TITLE
unsafe.Pointer workaround

### ISSUE THREAD

**Issue by dobegor** [gopherjs/gopherjs#829]
I want to port an embeddable VM written in Go to JavaScript. The reason is to create a playground with ability to observe memory, stacks, I/O ports etc. and interactively debug programs. And for fun, of course.

Since gopherjs does not implement `unsafe` package (for a very good reason) how can I adapt the following code (at least with a build tag): https://github.com/dobegor/ngaro/blob/master/vm/core.go#L378

I need to reinterpret the integer stored as float64 and vice-versa to support float operations in VM. Though it's using `unsafe` package to achieve this, it's absolutely safe and impossible to crash.

Is there any recommended way to achieve this? JS numbers are all floats, anyway.

**Comment by myitcv** [comment]
@dobegor 

> Since gopherjs does not implement unsafe package

That's not actually the case. 

Are you trying to do something like this ([playground](https://gopherjs.github.io/playground/#/RM3yL8R1fv))?

```go
package main

import (
        "fmt"
        "github.com/gopherjs/gopherjs/js"
        "unsafe"
)

func main() {
        var i int = 45
        o := js.InternalObject(&i)
        var f float32 = *(*float32)(unsafe.Pointer(o.Unsafe()))
        fmt.Printf("i (%T) = %v; f (%T) = %v\n", i, i, f, f)
}
```

**Comment by dobegor** [comment]
@myitcv
Yes, that’s just what I need!
I was looking into this document when I was looking if unsafe package is supported: https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md which states that unsafe package isn’t available. 

Awesome thanks for the tip!

**Comment by dobegor** [comment]
@myitcv @shurcooL 
I actually have a little question about this panicking behavior in gopherJS:
this works okay with `int` and `float64`:
https://gopherjs.github.io/playground/#/_LNpzhM1ag 
but returns NaN and panics if I change `int` to `int64`:
https://gopherjs.github.io/playground/#/iSpfwEL1s-

I do realize that `int64` support is done in software, but maybe I'm doing something utterly wrong and that shouldn't happen.

**Comment by shurcooL** [comment]
That happens because GopherJS represents `int64` internally using two JavaScript numbers: the low and high components of the `int64`. An `int` is represented by a single JavaScript number that directly maps to the `int` value. For example, see:

https://github.com/gopherjs/gopherjs/blob/8dffc02ea1cb8398bb73f30424697c60fcf8d4c5/compiler/prelude/types.go#L68-L78

https://github.com/gopherjs/gopherjs/blob/8dffc02ea1cb8398bb73f30424697c60fcf8d4c5/compiler/prelude/types.go#L96-L101
