### ISSUE TITLE
Extremely new to react and redux.

### ISSUE THREAD

**Issue by streetlist** [gopherjs/gopherjs#834]
Is gopherjs able to perform or do redux functions/feature?

**Comment by flimzy** [comment]
GopherJS itself has no relation to React or Redux. There are, however, a few projects that provide GopherJS bindings for React. It's probably best to look at those, and seek support from one of those projects.  You can find some of them listed on the list of GopherJS bindings: https://github.com/gopherjs/gopherjs/wiki/bindings
