### ISSUE TITLE
Support for vgo builds outside GOPATH

### ISSUE THREAD

**Issue by bfreis** [gopherjs/gopherjs#835]
Hi,

I have no clue how easy or difficult this would be. Any chance of adding support for looking up packages the way `vgo` does? It allows go modules to be built outside of the `GOPATH`, and it looks up dependencies in `$GOPATH/go/src/mod/${IMPORT_PATH}@${VERSION}/`, where import_path and version are as defined in the `go.mod` file in the project folder.

I've never looked into GopherJS code, but I'm assuming this wouldn't be terribly complicated?

Cheers!
Bruno

**Comment by flimzy** [comment]
Wouldn't this break compatibility with `go`?

**Comment by bfreis** [comment]
Hi @flimzy ,

I can't say for sure, as I'm not knowledgeable of the internals of either GopherJS, Vgo toolchain, or Go toolchain.

But what I can say is that, from a practical perspective, it seems that the VGo binary behaves exactly like the Go binary in "normal" Goland codebases (ie, with a "traditional" GOPATH). To "activate" the special features, you have to create a file called `go.mod`.

So I would assume that it wouldn't break compatibility - VGo is intended to be released as part of Go 1.11, AFAIK. If they don't break the "backwards compatible" promise, it should be compatible.

Cheers!
Bruno

**Comment by myitcv** [comment]
@bfreis @flimzy - this should be possible. At the moment GopherJS uses [`go/build`](https://godoc.org/go/build) for package discovery; this will need to be replaced by something like the planned [`go/packages`](https://github.com/golang/go/issues/14120#issuecomment-383994980).

**Comment by flimzy** [comment]
If this is slated for inclusion in Go 1.11, doesn't it make sense for GopherJS to wait until Go 1.11, as well?

I'd be very concerned about projects that work with both Go and GopherJS, being treated differently in the two environments.

**Comment by myitcv** [comment]
> If this is slated for inclusion in Go 1.11, doesn't it make sense for GopherJS to wait until Go 1.11, as well?

Sorry, yes, agreed - that was implicit in my answer. Arguably we could/should wait for an initial cut of `go/packages` to land first too (although that's not strictly necessary, might just save us some work).

**Comment by myitcv** [comment]
Just an FYI on this issue, I am working on `vgo` support for GopherJS, support that will be in-line with the experimental release of `vgo` within Go 1.11. 

This will initially be be merged into https://github.com/myitcv/gopherjs. 

I will also raise a PR against this repo, but I know @shurcooL has a lot on at the moment.

**Comment by Gee5ive** [comment]
@myitcv any updates on this?

**Comment by myitcv** [comment]
@Gee5ive https://github.com/myitcv/gopherjs/tree/go1.11 is being actively maintained.

It has Go 1.11 support, almost complete support for modules, as well as the changes from the following PRs that are still open in this main repo:

* [vendor: vendor go/types to workaround bug in method set calc.](https://github.com/gopherjs/gopherjs/pull/811)
* [compiler: fix variadic args not being nil when zero length](https://github.com/gopherjs/gopherjs/pull/807)
* [compiler: use hash calculation for determining archive staleness](https://github.com/gopherjs/gopherjs/pull/805)
* [ci: upgrade to CircleCI 2](https://github.com/gopherjs/gopherjs/pull/797)
* [compiler/prelude: format .js files using prettier](https://github.com/gopherjs/gopherjs/pull/794)
* [compiler/prelude: move prelude to separate .js files](https://github.com/gopherjs/gopherjs/pull/791)
* [js: add MakeFullWrapper to expose exported methods and struct fields](https://github.com/gopherjs/gopherjs/pull/790)

**Comment by myitcv** [comment]
@Gee5ive (and others) I've just merged the changes in the `go1.11` branch of https://github.com/myitcv/gopherjs into `master` (of that fork) and created a `go1.10` branch for posterity.

**Comment by flimzy** [comment]
I'm closing this in favor of #855, which is an effective duplicate, after modules have been made official.
