### ISSUE TITLE
len not reporting correct length 

### ISSUE THREAD

**Issue by aaronstgeorge-wf** [gopherjs/gopherjs#841]
On commit `8dffc02ea1cb8398bb73f30424697c60fcf8d4c5` the following code panics:

```go
a := "a"
b := "b"
ab := a + b
if len(a+b) != len(ab) {
	panic("unreachable")
}
```
Using `go1.10.3 darwin/amd64` it does not.

**Comment by theclapp** [comment]
Funky.

```go
a := "a"
b := "b"
ab := a + b
fmt.Println(a, b, ab, len(a), len(b), len(ab), len(a+b))
if len(a+b) != len(ab) {
	panic("unreachable")
}
```
=>
```
a b ab 1 1 2 0 
 
panic: unreachable
```

Playground: https://gopherjs.github.io/playground/#/i3cHB2SJj3

**Comment by theclapp** [comment]
Compiled JS says it all:

```js
_r = fmt.Println(new sliceType([new $String(a), new $String(b), new $String(ab),
    new $Int(a.length), new $Int(b.length), new $Int(ab.length),
    new $Int(a + b.length)]));
if (!((a + b.length === ab.length))) {
	$panic(new $String("unreachable"));
}
```

`len(a+b)` => `a + b.length`.

`len((a + b))` does in fact compile to `(a + b).length` and does == 2, so there you go.

Playground: https://gopherjs.github.io/playground/#/4QvJ5cYmvG
