### ISSUE TITLE
Semantic version tag to GopherJS itself

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#847]
I realized that I need to write `v0.0.0-(datetime)` version to represent dependency on GopherJS. I'd be happy if GopherJS has semantic version tags to `go.mod` cleaner. I think v0.x.y would be fine. Any thoughts?

**Comment by flimzy** [comment]
GopherJS already follows the equivalent Go version numbers. i.e. `1.10-4`.  Are you suggesting adjusting this to follow semver, i.e. `1.10.4`?  Or create an entirely new versioning scheme?

**Comment by hajimehoshi** [comment]
Sorry if I am wrong, but does GopherJS already version tags?

My suggestion is just to add tags. I don't have a strong opinion what version numbers should be used for GopherJS. If GopherJS's API is stable enough, version 1.x.y would be fine, but I don't think it is necessary that GopherJS version follows Go version.

**Comment by flimzy** [comment]
It doesn't have [tags](https://github.com/gopherjs/gopherjs/releases), but it does have a [version number](https://github.com/gopherjs/gopherjs/blob/8dffc02ea1cb8398bb73f30424697c60fcf8d4c5/compiler/version_check.go). Currently it is set to 1.10-4.

**Comment by myitcv** [comment]
> I don't see any reason for a separate versioning system--especially when the GopherJS API follows the Go API as closely as possible.

I think I agree with @hajimehoshi in that GopherJS should follow semver, and hence add releases/tags accordingly.

GopherJS as a tool, and the non-internal packages `github.com/gopherjs/gopherjs/...`, can all be dependencies of other projects. 

With go modules, use of semver-compatible versions (tags) for dependencies (modules) is a requirement:

https://tip.golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

I'm no expert on semver (https://semver.org/); clearly we would need to give some thought as to how to follow the Go version numbers whilst allowing for intervening releases of GopherJS, for example to fix a bug between `1.11.1` and `1.11.2`. But hopefully this is possible, else we might need to reconsider our approach.

**Comment by hajimehoshi** [comment]
So the import path would be `github.com/gopherjs/gopherjs/v10/js` or `github.com/gopherjs/gopherjs/v11/js`?

**Comment by myitcv** [comment]
@hajimehoshi I was just working through that _exact_ point 👍 

I actually think `github.com/gopherjs/gopherjs/js` should be a separate module, and hence can be versioned separately. `github.com/gopherjs/gopherjs` would then have a dependency on `github.com/gopherjs/gopherjs/js`, much like libraries/programs would have dependencies on `github.com/gopherjs/gopherjs/js`.

**Comment by myitcv** [comment]
FYI I'm trying out this strategy in https://github.com/myitcv/gopherjs/pull/16 for anyone interested.

**Comment by flimzy** [comment]
We've adopted a new semver-based versioning scheme for GopherJS, detailed [here](https://github.com/gopherjs/gopherjs/wiki/Developer-Guidelines#versions).  TL;DR;

<semver>+go<go version>

At present, these versions are roughly in line with each other (at writing, the current vesion is `1.16.0+go1.16.3`), but this will allow us to document changes at a rate differently from Go upstream support, and possibly even introducing breaking changes (i.e. to the gopherjs tool) and reflect them properly in our version.  I.e. we may at some point have `2.0.0+go1.17`.

We've also begun creating [tags of these versions](https://github.com/gopherjs/gopherjs/releases/tag/1.16.0%2Bgo1.16.3), which should faciliate their use with `go.mod`.

I hope this satisfactorally addresses the issue!  If there's anything outstanding, feel free to comment and we can re-open.
