### ISSUE TITLE
Slow execution of typ.KeyFor (for a struct) and replace functions

### ISSUE THREAD

**Issue by pbrown12303** [gopherjs/gopherjs#848]
I have a high-level operation that executes in about 16 milliseconds in Go but takes about 5.5 seconds in the browser (with performance sampling turned on). Most of the browser time is spent in the JavaScript implementation of a low-level locking routine written in Go, `LockBaseElement`. The reason for the lock structure is that the Go code is designed for highly-parallel execution. Note that I don't expect any parallelism in the JavaScript execution and the routine that is taking so long to execute is single threaded anyway. I am trying to understand why there is such a performance difference between the two environments. 

The Go code for locking (below) keeps a map of the objects that are locked (the `beLocks` attribute). The `LockBaseElement()` function (which is where most of the time is being spent in the JavaScript version) gets the identifier from the object (a simple struct access with no locking), checks the `beLocks` map to see if the object is already locked and, if it is not, locks the object and adds a corresponding entry to the map. 

The `LockBaseElement()` function is invoked for every access to every operation in my design. For the operation in question it is invoked 72,903 times. New locks are added 146 times. In other words, most of the time the map is only being used for a lookup.

Most of the time appears to be spent in the JavaScript implementation of the Go map operations (based on the performance sampling data), specifically `typ.KeyFor` and `replace`. I need some help in understanding what is going on here - I'm not that familiar with the intricacies of JavaScript. I am happy to provide the entire Gopher-generated file, but as it is 73,000 lines long I didn't want to just dump it here. 

 Here's the Go code:

```
// Copyright 2017 Paul C. Brown. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package core

import (
	"github.com/satori/go.uuid"
	"log"
	//	"runtime/debug"
	"sync"
)

type HeldLocks struct {
	sync.Mutex
	beLocks             map[uuid.UUID]BaseElement
	waitGroup           *sync.WaitGroup
	functionCallManager *FunctionCallManager
}

func NewHeldLocks(wg *sync.WaitGroup) *HeldLocks {
	var hl HeldLocks
	hl.beLocks = make(map[uuid.UUID]BaseElement)
	hl.waitGroup = wg
	hl.functionCallManager = NewFunctionCallManager()
	return &hl
}

func (hlPtr *HeldLocks) GetWaitGroup() *sync.WaitGroup {
	return hlPtr.waitGroup
}

func (hlPtr *HeldLocks) LockBaseElement(be BaseElement) {
	hlPtr.Lock()
	defer hlPtr.Unlock()
	id := be.getIdNoLock()
	if AdHocTrace == true {
		log.Printf("In LockBaseElement for be %s \n", id)
	}
	if hlPtr.beLocks[id] == nil {
		if AdHocTrace == true {
			log.Printf("In LockBaseElement, lock not found for be %s of type %T \n", id, be)
			//			debug.PrintStack()
		}
		//		log.Printf("Locking %s", id)
		hlPtr.beLocks[id] = be
		be.TraceableLock()
	}
}

func (hlPtr *HeldLocks) ReleaseLocks() {
	hlPtr.Lock()
	defer hlPtr.Unlock()
	for _, be := range hlPtr.beLocks {
		be.TraceableUnlock()
	}
	hlPtr.beLocks = make(map[uuid.UUID]BaseElement)
	hlPtr.functionCallManager.ExecuteFunctions(hlPtr.waitGroup)
}

func (hlPtr *HeldLocks) ReleaseLocksAndWait() {
	hlPtr.ReleaseLocks()
	hlPtr.waitGroup.Wait()
}
```

Here's the Gopher-generated code for the function LockBaseElement:

`	ptrType$1.methods = [{prop: "GetWaitGroup", name: "GetWaitGroup", pkg: "", typ: $funcType([], [ptrType$2], false)}, {prop: "LockBaseElement", name: "LockBaseElement", pkg: "", typ: $funcType([BaseElement], [], false)}, {prop: "ReleaseLocks", name: "ReleaseLocks", pkg: "", typ: $funcType([], [], false)}, {prop: "ReleaseLocksAndWait", name: "ReleaseLocksAndWait", pkg: "", typ: $funcType([], [], false)}];
`

Here's the Gopher-generated code for typ.keyFor (for the struct):

`      typ.keyFor = function(x) {
        return Array.prototype.join.call($mapArray(x, function(e) {
          return String(elem.keyFor(e)).replace(/\\/g, "\\\\").replace(/\$/g, "\\$");
        }), "$");
      };
`

**Comment by theclapp** [comment]
It looks to me like `typ.keyFor` is string-ifying the UUID key at least once, sometimes twice, every time through LockBaseElement.  Said stringification appears to include replacement of `\` with `\\` and `$` with `\$`, and then joining with `$` as the delimiter.  A UUID in this context is a `[16]byte` array; I'm unclear on whether the `keyFor` function actually traverses the array and stringifies each byte and does the mentioned replacement or not, but (just a guess) I think it probably does.  It does seem like that would be a relatively expensive operation.

I think core Go synthesizes a custom key generation function for each type used as a map key, which for a [16]byte is probably something very close to a bare [bytes.Compare](https://golang.org/pkg/bytes/#Compare), which would be very fast.

Can you try a different key type?  Maybe use `map[string]BaseElement` and then `if hlPtr.beLocks[string(id[:])] == nil`.  (Or you might not have to slice `id`, I'm not sure.)  Or that might end up doing the same or a similar conversion, I don't know.  Just a suggestion on where to look.

**Comment by pbrown12303** [comment]
I changed the datatype of identifiers from uuid.UUID to string. Pure go execution time for the experiment dropped from 16ms to 8.9ms. The JavaScript execution time dropped from 5.5 seconds to 123ms. Still longer than the Go execution time but good enough for human interaction purposes. Thanks @theclapp for your suggestion!

**Comment by pbrown12303** [comment]
I will close this as the workaround (using string instead of uuid.UUID) sufficiently improved performance.
