### ISSUE TITLE
JS Constructor With Argument 

### ISSUE THREAD

**Issue by upsampled** [gopherjs/gopherjs#858]
I am trying to reproduce the following JS in  GopherJS:

```
var myForm = $('#fileUploadForm')[0];
formData = new FormData(myForm);
```
I know how to reproduce the first line using the gopherjs/jquery package, but the second line I am having trouble with. I know i can write

`formData = new FormData();`

as

`formData = js.Global.Get("FormData").New()`

But I do not know how to pass the` js.Object` created by the jQuery bindings as an argument to the `FormData` constructor (`FormData(myForm);`). Is this even possible using GopherJS or do i need to append the data to the default `FormData` object?

**Comment by theclapp** [comment]
`Object.New()` takes Object arguments.  See [here](https://godoc.org/github.com/gopherjs/gopherjs/js#Object.New).

So just pass it the normal way

```go
formData = js.Global.Get("FormData").New(myForm)
```
