### ISSUE TITLE
file does not load after compile in js

### ISSUE THREAD

**Issue by zsaidov** [gopherjs/gopherjs#871]
golang code:
```
func loadFile(src string) (interface{}, error) {
	data, err := ioutil.ReadFile(src)
	if err != nil {
		return nil, err
	}
	return data, nil
}
```
after compile this code with `-gopherjs build` file does not load.
Error:
```
Err = 13
Op = "open"
Path = "./text.txt"
```

**Comment by theclapp** [comment]
What environment?  That is, browser or Node (or something else)?

See https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md

The short answer: Reading a file on a browser will never work.  In Node it might; see the above link.
