### ISSUE TITLE
Hi i m facing issue for the gopherjs: command not found Please help

### ISSUE THREAD

**Issue by MAYANK-29** [gopherjs/gopherjs#873]
_Originally posted by @dmitshur in https://github.com/gopherjs/gopherjs/issues/666#issuecomment-318515698_

**Comment by dmitshur** [comment]
I'm not sure what the question is. Did you follow the instructions at https://github.com/gopherjs/gopherjs#installation-and-usage?

**Comment by gitburd** [comment]
yes. i followed the directions and have the same issue.

**Comment by dmitshur** [comment]
@gitburd What operating system are you using?

Doing `go get -u github.com/gopherjs/gopherjs` installs GopherJS and places the `gopherjs` binary in `$GOPATH/bin`. Have you added `$GOPATH/bin` to your `PATH` environment variable?

**Comment by gitburd** [comment]
@dmitshur, thanks for replying. I'm using MacOs Mojave. this is in my .zshrc ```export PATH="$HOME/bin:/usr/local/bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin/$PATH"``` 
  Here is what I'm getting. <img width="795" alt="Screen Shot 2019-12-20 at 12 58 28 PM" src="https://user-images.githubusercontent.com/29719099/71293338-f0466d00-2329-11ea-8f06-781ca8bc4abd.png">

**Comment by nevkontakte** [comment]
@gitburd if you carefully read the error message (last line specifically) you will see that it says "GopherJS requires Go version 1.12", whereas you are using Go 1.13. There is an on-going work to support Go 1.13, but it's not finished yet. Until then you'll need to use Go 1.12.

**Comment by dmitshur** [comment]
> Until then you'll need to use Go 1.12.

Additionally, if the decision in issue #941 is made "yes", then it'll be possible to point a `GOPHERJS_GOROOT` environment variable to a Go 1.12 installation, but still use Go 1.13 (or any other version) as your primary Go installation. I'm still waiting to hear more feedback in that issue.

**Comment by flimzy** [comment]
It looks like this issue was probably resolved (or would be after #941 was merged). If you're still having this problem, please comment and we can reopen.
