### ISSUE TITLE
gopherjs build error on Windows

### ISSUE THREAD

**Issue by EchoofthePast** [gopherjs/gopherjs#875]
I am using windows 7 for my operating system and have the most up to date version of Go at the moment version 1.11.1. 
I have just recently reinstalled all the packages hoping that it would rectify my problem but has not 

My problem seems to be consistent and no solution exists that i can  find, I have searched extensively and have found that others are having similar problems and the solutions have not corrected my problem.

I am trying to transpile a gopherjs file. when i run gopherjs build filename.go I receive an error in terminal

←[31m/src/syscall/syscall_nonlinux.go:5:18: undeclared name: SYS_EXIT
←[39m←[31m/src/syscall/syscall.go:53:39: too few arguments in call to Syscall
←[39m 

The first problem that i see with this is that the syscall_nonlinux.go file doesn't even exist in the go root directory and the second error denotes a function with in syscall.go (the file does exist) but the error makes no sense.

I have been stuck on this for some time now and have tried all I can do. 
Please help if possible,

**Comment by theclapp** [comment]
Running on Windows requires a bit of a hack.  From the README:

> gopherjs uses your platform's default GOOS value when generating code. Supported GOOS values are: linux, darwin. If you're on a different platform (e.g., Windows or FreeBSD), you'll need to set the GOOS environment variable to a supported value. For example, GOOS=linux gopherjs build [package].

So, try

```sh
GOOS=linux gopherjs build filename.go
```

**Comment by EchoofthePast** [comment]
I added GOOS=linux to my system environment variables and the restarted VSC and then ran gopherjs build filename.go and  it worked!!
Thank you with all my heart.

**Comment by theclapp** [comment]
Don't set GOOS system wide, only set it for that session.  I think the command is

```sh
set GOOS=linux
gopherjs build filename.go
```

but it might be `setenv`.  I imagine you could easily write a script, even in Windows, to do this on a command-by-command basis.

This has been working this way (or broken this way, if you like) for a while.  I think if the maintainers were going to fix it, they would have.

**Comment by inliquid** [comment]
@EchoofthePast do not add `GOOS=linux` to your system. As the result you will get ELF binaries when you compile regular *.go programs instead of Windows binaries, so they won't run on Windows. This problem is bug and must be fixed.

**Comment by Inkeliz** [comment]
I hit the same issue in the past. I think it can be mitigated. I don't know if have any side-effect, I didn't test it in all cases, but for simply `gopherjs build` it works. Running the `go test` all tests works, with the exception of the `fixedbugs/*`, which all fails.

Just include this 5 lines at [`func init()`](https://github.com/gopherjs/gopherjs/blob/d547d1d9531ed93dbdebcbff7f83e7c876a1e0ee/tool.go#L45-L62):

	if os.Getenv("GOOS") == "windows" {
		fmt.Fprintf(os.Stderr, "GOOS is Windows. The GopherJS is falling back to GOOS=linux\n")
		os.Setenv("GOOS", "linux")
		build.Default.GOOS = "linux"
	}


Showing a message for the use is good, in my option, so this change is noticible and not silent. The change of the GOOS is just locally, the `os.Setenv` is locally, if the user run `go build` will create the `.exe`.

**Comment by EchoofthePast** [comment]
Thank you to everyone.
