### ISSUE TITLE
gopher compiler identifying files

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#885]
I think I can across a situation where `go build` and `gopher` behave slightly differently in terms of which files are used to compile.

Can someone direct me to the code in this project that deals with file walking etc.

**Comment by myitcv** [comment]
@pjebs are you building from the command line? If so, start in https://github.com/gopherjs/gopherjs/blob/master/tool.go and make your way through to https://github.com/gopherjs/gopherjs/blob/master/build/build.go.

If you can share more details of the behaviour you are seeing we might be able to help.
