### ISSUE TITLE
kotlin js file size issues

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#888]
Here are some articles that could be useful for gopher js project to minimise file size:

https://discuss.kotlinlang.org/t/kotlin-js-file-size/2501/12

https://discuss.kotlinlang.org/t/a-new-dead-code-elimination-tool-for-js/3777

**Comment by flimzy** [comment]
Linking this to our canonical "large files" issue, so it's referenced there:  https://github.com/gopherjs/gopherjs/issues/136
