### ISSUE TITLE
Make "//gopherjs:blocking" the default

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#89]
Suppose I have a blocking call on an interface,

```Go
var r io.Reader = T{}

n, err = r.Read(b) //gopherjs:blocking
```

Adding `//gopherjs:blocking` allows it to work without `panic: not supported by GopherJS: non-blocking call to blocking function`.

However, marking a func call as blocking does not seem to apply recursively, so if the `r.Read` happens inside another func which is marked as blocking, I get a panic.

```Go
foo := func (r io.Reader, b []byte) (n int, err error) {
	n, err = r.Read(b) // Adding //gopherjs:blocking here fixes it, but what if foo() is inside another library?
	return
}

var r io.Reader = T{}

// I would imagine this could/should mark the r.Read(b) inside foo() as blocking too?
n, err := foo(r, b) //gopherjs:blocking
```

See complete example [here](http://www.gopherjs.org/play/#/15JW1iT9Uy). It works on the normal Go playground [here](http://play.golang.org/p/15JW1iT9Uy).

Unless there's a workaround, this is currently preventing me from implementing io.Reader and have it be usable inside standard library (which I cannot modify to add a `//gopherjs:blocking` comment).

For example,

```Go
var r io.Reader = T{}
err := json.NewDecoder(r).Decode(&v) // gopherjs:blocking has no effect here,
                                     // since r.Read() happens inside the
                                     // encoding/json standard package.
```

Thanks to @dominikh for discussing/explaining/providing sample code. I wanted to make a public issue so that progress can be tracked and people can be referred to here if needed. As always, GopherJS rocks and thanks for making it! This is a testament of how far it got.

**Comment by hackwaly** [comment]
It should markBlocking to a function that call a method of interface which that method has any implementation (not dead code) is already known blocking.
So any other implementation which is non-blocking may be called as blocking. This case can be solved by make blocking version wrapper to non-blocking version.

Hope we can see `io.Copy` works with blocking `Read` soon.

**Comment by hackwaly** [comment]
I've try to fix this. It's not easy.
Gopherjs compile package one by one. However, consider a virtual method call whether is blocking or not should inspect all packages to see if there's some blocking implementation.

**Comment by neelance** [comment]
It is still one of my primary goals to fix the bugs of blocking output that prevent changing the default to assuming `//gopherjs:blocking`. Then we can do some performance measurements.

**Comment by neelance** [comment]
Progress! I've worked much on this issue in the past few weeks and have reached the first milestone:
All tests of currently supported packages are passing now also when assuming `//gopherjs:blocking` everywhere. Try the `assume-blocking` branch if you are interested. Some packages took a performance hit. Next step is to check whether this is due to overhead or simply because less tests are skipped now.

**Comment by szabba** [comment]
+1

**Comment by dominikh** [comment]
I've prepared a little example at http://play.golang.org/p/zzFuOxW8i7 which implements an http.RoundTripper using my xhr package, allowing the use of plain net/http for making requests. 

If you want to test it, either replace the google.com URL with one that allows cross-domain requests, or start Chrome with the `--disable-web-security` flag.

It's a prototype (which doesn't handle headers, POST etc yet), but it demonstrates the huge advantage that proper support for blocking gives us.

**Comment by hackwaly** [comment]
Yeah! `js.Object` became struct due to performance reason.
It works fine. I feel no sensible overhead in my chrome proxy app.

**Comment by neelance** [comment]
Branch `assume-blocking` merged into `master`. `//gopherjs:blocking` is gone now. ;-)

**Comment by rusco** [comment]
:clap:

**Comment by elliott5** [comment]
Well done Richard!

**Comment by szabba** [comment]
:+1:

**Comment by hajimehoshi** [comment]
:congratulations:

**Comment by jaracil** [comment]
Thank you. 👍

**Comment by shurcooL** [comment]
This is an incredible milestone! Congrats!

Just want to point out that now all these things are possible:

> If a blocking `io.Reader` is supported, then it is possible to wrap a [websocket](http://godoc.org/github.com/gopherjs/websocket) connection in a way that implements `net.Conn` interface. Doing that will allow using `net/rpc/jsonrpc` package for RPC. It will also allow creating an `http.Client` with a custom `http.Transport` that wraps around [xhr](http://godoc.org/honnef.co/go/js/xhr). All that will allow running more interesting existing Go code (that relies on those low level building blocks) and more possibilities in the frontend.
