### ISSUE TITLE
ES6 time

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#891]
It's probably about (or fast approaching) time for gopher.js to produce ES6 javascript files.

For those that still require ES5, I can write up an instructions on transpiling for these combinations:
ES5 => babel
ES5 + minify => babel + uglify
ES6 + minify => babel-minify

I won't have the expertise to convert gopher.js to produce ES6 code.

**Comment by flimzy** [comment]
Why?

**Comment by flimzy** [comment]
Nice analysis.  I think the key comes down to one point, though:

> ES6 code is faster and smaller.

What is your source for this claim?  Yes, ES6 offers some syntax optimizations that make human-written code shorter, but I don't expect most of this will affect the type of generated code produces by GopherJS (although I may be wrong, and would be happy to be proven wrong).

As for the speed of ES6, I don't think it's true that, on average, ES6 is faster. [This resource](http://incaseofstairs.com/six-speed/) shows that some specific operations are faster, others are slower. Most have no change at all.

Is there any reason to think that it would actually benefit GopherJS?

**Comment by pjebs** [comment]
Please note: https://github.com/gopherjs/gopherjs/issues/320 is 3 years old. The browser adoption landscape has now changed substantially.

**Comment by pjebs** [comment]
I haven't got benchmarks but I can only assume the syntax optimisations for human-writability must translate to at least equal to an approach where a human wrote an equivalent code in ES5 and at best faster due to the JS engine able to make optimisations in a lower-level language such as assembly.

It's just a guess. I also assume that if a gap does exist (on aggregate), this gap will intuitively only get wider in favour of ES6.

**Comment by pjebs** [comment]
> ES6 code is faster and smaller.

They are definitely smaller. In my own projects, I have seen that in every case.

**Comment by pjebs** [comment]
@flimzy The benchmarks link you provided above says: `Run on 1/4/2017 using babel 6.21.0, babel-runtime 6.20.0, and traceur 0.0.111.`

**Comment by jaracil** [comment]
ES6 has generators. It can be used to implement goroutines in a much less verbose way.

This [link](https://cmichel.io/how-are-generators-transpiled-to-es5) shows the difference (in verbosity) between ES6 and ES5 implementing generators.

**Comment by flimzy** [comment]
@jaracil : This possibility was discussed in #107, and the conclusion at the time was that it wouldn't be feasible.

**Comment by nevkontakte** [comment]
GopherJS has more pressing issues for now (like #989 and friends), but a here are a few thoughts for future:

  - ES6 does offer some nice features we could use. I suspect that async/await could simplify goroutine implementation, and classes could also simplify type system implementation. Both claims, however, need to be proven with a prototype.
  - GopherJS `math` package implementation already [depends](https://github.com/gopherjs/gopherjs/blob/bed99a852dfeb7c8aad4ac454357a198750247e1/compiler/natives/src/math/math.go#L230-L233) of types arrays, which is a part of ES6 spec.
  - If we wanted to, we could still support ES5 seamlessly by vendoring babel and using https://github.com/robertkrimen/otto or https://github.com/dop251/goja to run it. This way nodejs will not become a mandatory build-time dependency.

**Comment by benma** [comment]
For another point in favour of ES6, see this comment in the related issue:

https://github.com/gopherjs/gopherjs/issues/524#issuecomment-956265776

We cannot make code splitting work, and webpack also spits out warnings such as 

> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Our dev team has been wrestling with this for days already (with no result yet). If the output would be ES6, it would work much easier with webpack.

**Comment by nevkontakte** [comment]
@benma if you could file this as a separate issue with a minimal reproduction example for this warning along with the expected/observed behavior, it would be a lot easier for us to investigate possible solutions that require less than grand architectural redesigns :)

FWIW, according to our [survey](https://forms.gle/LexHDXXEEmzRoVRx7) results, only ~9% of users are targeting ES5 specifically, so perhaps embracing ES2015 features is becoming a sensible step.

**Comment by benma** [comment]
@nevkontakte It turned out that this warning did not impact code splitting - that now [works](https://github.com/gopherjs/gopherjs/issues/524#issuecomment-963118012) but the warning still remains.

The warning goes away is I replace `$global.require` with `require` in the generated output. I will try to post an example soon. Skimming the generated code, it seems using `require` directly should work.

**Comment by nevkontakte** [comment]
I think it's a good time to have another go at this discussion. To that end, I created a new proposal, which declares that ES 2015 features can be used in GopherJS-generated code and formalizes the principles for using newer APIs in future: https://github.com/gopherjs/gopherjs/issues/1121. If anyone has opinions in favor or against, I would appreciate you taking time to share them in the new issue.
