### ISSUE TITLE
x not declared by package y

### ISSUE THREAD

**Issue by zgordan-vv** [gopherjs/gopherjs#892]
Hello! Everytime when I am trying to use package github.com/unidoc/unidoc/pdf/creator, it gives me:

pdf_report.go:383:15: NewParagraph not declared by package creator
pdf_report.go:395:22: NewTable not declared by package creator

etc. Other packages from this repo work well. Can I work aroud this in some way?

**Comment by derickweng** [comment]
Are you fixed it？

**Comment by nevkontakte** [comment]
@derickweng  I've checked out the latest version of this library and was able to `gopherjs build ./...` it with no errors. If you have an issue with this particular library, please provide the exact description of your problem.
