### ISSUE TITLE
gopherjs serve static css

### ISSUE THREAD

**Issue by softkot** [gopherjs/gopherjs#904]
gopherjs serve static css with text/plain mime type instead of proper text/css one causing google chrome to reject those stylesheets  with error message

`Refused to apply style from 'http://........./style.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
`

please fix it to serve with right mime type to ease the debug process.

**Comment by softkot** [comment]
My fault. It works properly.

**Comment by kidandcat** [comment]
how was it your fault? I'm having the same problem, please explain

**Comment by softkot** [comment]
As far i remember there was wrong path to css
