### ISSUE TITLE
TinyGo to produce smaller files sizes

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#905]
Has anyone tried using tinygo https://github.com/tinygo-org/tinygo with gopherjs to produce smaller file sizes?

**Comment by slimsag** [comment]
TinyGo and GopherJS have polar goals: TinyGo tries to produce small binaries at the expense of the programmer, GopherJS tries to maintain full compatibility with the Go stdlib at the expense of larger binaries.

TinyGo itself already can produce WASM output and supports `syscall/js`, I've nearly ported Vecty to it for example: https://github.com/gopherjs/vecty/pull/232

If you want small file sizes, you need to avoid importing large packages (fmt, etc) heavily.

**Comment by aykevl** [comment]
Actually, TinyGo does support the fmt package, or at least the basics of it. It just results in much larger file sizes - like 50kB or so. It's just a big package. And yes, it is probably harder to use than GopherJS but that's not intentional: the goal is to support the whole stdlib.
Just wanted to clarify a few things :)

**Comment by nevkontakte** [comment]
TinyGo and GopherJS work in very different ways, so I don't think there is a practical way to _integrate_ them: TinyGo uses LLVM and its sophisticated low-level optimizations, GopherJS tries to transpile one high-level to another with minimal sacrifices to code readability.

(As a slight tangent, I'd be curious to see what would it look like if TinyGo generated JavaScript similar to Emscripten, but that's unlikely to reuse any of GopherJS codebase).

If project requires small output sizes and using WebAssembly is acceptable, trying TinyGo itself is probably a good idea. I presume there may be some tricks GopherJS could borrow from TinyGo's book and replicate internally, but I'm not familiar with it enough to be able to tell what those would be.

If you have suggestions for specific optimizations that we could try and port, feel free to reopen the issue. I do have to note that the first order of business for GopherJS is to catch back up with mainline Go, pursuing optimizations is kind of pointless if you can't compile modern Go with it.
