### ISSUE TITLE
gopherjs: command not found 

### ISSUE THREAD

**Issue by JuanVargas** [gopherjs/gopherjs#906]
I installed the most recent version of gopherjs on my linux/mint box. Up until now I never had any problems installing Go packages using the generic

go get -u github.com/gopherjs/gopherjs

but in the case of gopherjs the additional step of copying the gopherjs executable into $GOROOT/bin is necessary (and it is not documented)

**Comment by hajimehoshi** [comment]
Hi,

`go get` installs the binary into `$GOPATH/bin`, not `$GOROOT/bin`.

**Comment by dmitshur** [comment]
> but in the case of gopherjs the additional step of copying the gopherjs executable into $GOROOT/bin is necessary (and it is not documented)

It should not be necessary, it's fine for the `gopherjs` binary to be anywhere, including the usual `$GOPATH/bin` location. What makes you believe it needs to be copied to `$GOROOT/bin`?

**Comment by nevkontakte** [comment]
Considering that the described behavior appears to be the correct one and lack of activity, I'm closing this bug.
