### ISSUE TITLE
Element.createShadowRoot is deprecated

### ISSUE THREAD

**Issue by billyyumyum** [gopherjs/gopherjs#913]
Getting this warning in the browser console. Is GopherJS compiling with deprecated code?

Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.

**Comment by hajimehoshi** [comment]
There is no caller of `createShadowRoot` on GopherJS side. Probably your library using GopherJS called it, didn't it?

**Comment by billyyumyum** [comment]
Probably but when GopherJS runs shouldn't it use attachShadow instead of createShadowRoot automatically?

**Comment by hajimehoshi** [comment]
GopherJS just runs Go program on browsers as it is. Whether `attachShadow` is called or not is not GopherJS's responsibility.
