### ISSUE TITLE
Question: Passing properties into New()

### ISSUE THREAD

**Issue by zzwx** [gopherjs/gopherjs#921]
Hello, I'm struggling with creating a wrapper that would pass JavaScript properties specifically to three.js WebGLRenderer constructor that accepts ``WebGLRenderer( parameters : Object )`` and might look like this:

 ```js
var renderer = new THREE.WebGLRenderer( { antialias: true } );
```

What I have accomplished with just **antialias** is this:

```go
// The WebGLRenderer displays the scenes using WebGL.
type WebGLRenderer struct {
	*js.Object
}

// WebGLRendererParams allows to specify WebGL parameters for initialization
type WebGLRendererParams struct {
	*js.Object

	Antialias bool `js:"antialias"`
}

// NewWebGLRenderer creates new WebGLRenderer using parameters
func NewWebGLRenderer(params *WebGLRendererParams) WebGLRenderer {
	return WebGLRenderer{
		Object: three.Get("WebGLRenderer").New(params),
	}
}
```

Unfortunately when I create the object, the parameters don't seem to be passing along to the JavaScript side. So basically my code doesn't work:

```go
renderer := three.NewWebGLRenderer(&three.WebGLRendererParams{Antialias: true})
```

What am I missing?

**Comment by theclapp** [comment]
Check the [tips and gotchas](https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas) in the wiki.  The "violations" I see are: 

* Do not use items or fields of type js.Object directly. *js.Object must always be a pointer. **_A struct that embeds a *js.Object must always be a pointer._**

So `NewWebGLRenderer` needs to return `*WebGLRenderer`

* When creating a struct literal with a *js.Object in it, you have to initialize any other fields separately.

So when you call `NewWebGLRenderer`, you need something more like

```go
o := &three.WebGLRendererParams{Object: js.Global.Get("Object").New()}
o.Antialias = true
renderer := three.NewWebGLRenderer(o)
```

Creating a constructor for `WebGLRendererParams` can make that less ugly.

Hope that helps.

**Comment by zzwx** [comment]
I think I got it working if I initialize parameters like this. Thank you for the hint!
