### ISSUE TITLE
Any tutorials on making PWA / web3.js etc?

### ISSUE THREAD

**Issue by hiqsociety** [gopherjs/gopherjs#927]
It's a great project. I'm looking into making PWA and web3.js

Any tutorials?

**Comment by slimsag** [comment]
You can call into it using https://golang.org/pkg/syscall/js/ but there are no tutorials or examples that I am aware of.

**Comment by nevkontakte** [comment]
https://github.com/jaynagpaul/go-web3 seems to offer web3.js bindings (although I don't know if they are functional).

As for PWA, there's not much to say that would be GopherJS-specific. https://web.dev/progressive-web-apps/ is a good general resource that will help you with PWA fundamentals and will help you writing your manifest.

I'll be happy to answer more specific questions if you have any.
