### ISSUE TITLE
Feature request : flatbuffers support please.

### ISSUE THREAD

**Issue by hiqsociety** [gopherjs/gopherjs#928]
flatbuffers?

**Comment by theclapp** [comment]
There are apparently flatbuffers libraries for both Javascript and Go.  What've you tried / what'd you get / what'd you expect / what broke?

**Comment by hiqsociety** [comment]
1. i havent tried. 
2. it’s not in standard module / libraries offered for gopherjs?
3. prefer to have it standardized so i can write consistent code… that’s the purpose of using gopherjs

**Comment by hiqsociety** [comment]
i’ve already implemented flatbuffers on the server side.

**Comment by theclapp** [comment]
I'm not sure what you mean by your points 2 and 3.  GopherJS can import many arbitrary Go libraries and they Just Work with no changes.  (I mean, some don't, but many do.)  So the standardized version would just be the standard Flatbuffers Go libraries at https://github.com/google/flatbuffers/tree/master/go.  So, try importing the Go code in your GopherJS code and let us know what (if anything) goes wrong.

**Comment by hiqsociety** [comment]
i’ll try and revert. thx.
