### ISSUE TITLE
Trouble installing gopherjs

### ISSUE THREAD

**Issue by limitlessloop** [gopherjs/gopherjs#931]
Hi,

I'm having trouble installing gopherjs.

I ran

```bash
go get -u github.com/gopherjs/gopherjs
```
And nothing is returned in the command line.

I followed these instructions to make sure my PATH was correct

https://github.com/golang/go/wiki/SettingGOPATH

But still can't get it to work.

Any suggestions?

**Comment by dmitshur** [comment]
> nothing is returned in the command line

Nothing being printed is often the expected outcome when when a command succeeds. Can you check the exit code that `go get -u github.com/gopherjs/gopherjs` returns? Did you check your `$GOPATH/bin` directory to see if a `gopherjs` binary was installed there?

Also, what OS are you on, and what does `go version` print?

**Comment by limitlessloop** [comment]
> Nothing being printed is often the expected outcome when a command succeeds.

Thanks. Most installations I've used show some sort of progress so I wasn't sure if this was the case or not.

I can confirm the binary is there and my `$GOPATH/bin links to it. When I type `gopherjs` in the terminal it says unkown command.

The version is

```bash
go version go1.12.7 darwin/amd64
```

I'm unfamiliar with go so I'm not sure if there's anything else I'm supposed to do. I created a hello world app and was able to run that using go.

**Comment by limitlessloop** [comment]
Ok I managed to fix it. My `PATH` was not correctly loading `$GOPATH/bin`. I'm not sure why because `/usr/local/go/bin` is in my `PATH`. I've manually added `:$GOPATH/bin` to the end of my PATH and it seems to be working. Thanks again for your help.

**Comment by dmitshur** [comment]
> I've manually added :$GOPATH/bin to the end of my PATH and it seems to be working.

Yep, this needs to be done manually. In contrast, `/usr/local/go/bin` gets added to `PATH` by the macOS installed which you probably used.

> Thanks again for your help.

No problem! 👍
