### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [gopherjs/gopherjs#934]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by flimzy** [comment]
What would the benefit be for GopherJS, of fuzz testing? Throwing random source files at a compiler doesn't seem like a very useful analysis.

Doubly so, when there isn't even enough volunteer workforce to fix known bugs found by humans.

**Comment by yevgenypats** [comment]
Hi @flimzy, 

Thanks for the quick reply.

Firstly, its not completely random, go-fuzz is coverage-guided.
Secondly, regarding the workforce , of course I wasn't aware of the amount of resources available to this project.

If you think this currently not relevant/not enough resources then it's not a problem and you can ping me in the future if this becomes relevant again.

Cheers,
Yevgeny

**Comment by flimzy** [comment]
While fuzz testing is not out of the question, it looks like this particular project has been absorbed into GitLab, so I'm going to close this issue for now.  If this is a mistake, feel free to comment and we can re-open.
