### ISSUE TITLE
Define a new type to mark functions as blocking

### ISSUE THREAD

**Issue by andrebq** [gopherjs/gopherjs#94]
I was thinking for some time on how to represent functions that might block.

Since most of the time the blocking will happen because the system is waiting for IO operation (except when reading/writing in channels). I thought that we could create a new type for gopherjs, something like js.IOError.

Every function that might block should have an IOError in the signature. This would allow easy identification to interfaces (they would be type checked) and we could write a pass on gopherjs to ensure that any function calling a blocking function or doing operations on channels should also return js.IOError.

What do you think?

**Comment by neelance** [comment]
My preferred solution atm is #89 . If this works, then we will not need a special signature.
