### ISSUE TITLE
Webgl app and golang

### ISSUE THREAD

**Issue by ali2210** [gopherjs/gopherjs#944]
I had run on my system but system throw merage files error then abort the program
$go get -u github.com/gopherjs/gopherjs
How to resolve this error

**Comment by dmitshur** [comment]
What was the error? What version of Go are you using? What OS are you on?

**Comment by flimzy** [comment]
I'm going to close this, as it hasn't seen any activity in 18+ months. If this is still relevant, please comment, and we can reopen.
