### ISSUE TITLE
Undefined $24ptr variable variant in init function

### ISSUE THREAD

**Issue by paralin** [gopherjs/gopherjs#946]
Getting some errors here for an init() call which is initializing a pointer to a function with package-level variables (outside of an init() function)... 

`myLocalVar$24ptr is not defined`

```go
var myLocalVar = MyType{}

var AddToLocalVar = myLocalVar.AddToLocalVar
```

While the $24ptr part is not found there is a variable defined named `myLocalVar`.

```js
myLocalVar = new MyType();
$pkg.AddToLocalVar = $methodVal((myLocalVar$24ptr || (myLocalVar$24ptr = new ptrType(function() { return myLocalVar; }, function($v) { myLocalVar = 
```

The error is that the first part of that $methodVal is not defined (the $24ptr variant of the variable)

I'm seeing this against go1.12 and latest gopherjs.

**Comment by paralin** [comment]
This is definitely a bug that applies to the general case of making a package level variable that binds to a function on a non-pointer package-level variable at init time. It's trying to indirect the myLocalVar but getting a javascript undefined variable error (I think this is intended to be caught with the OR but it throws an error in Chrome).

**Comment by flimzy** [comment]
@paralin I realize I'm really late to this party, and you likely have moved on. But would it be possible to add a reproduction case to this issue?

**Comment by paralin** [comment]
@flimzy Unfortunately I have indeed moved on but will revisit gopherjs soon. I'll re-open if this is still an issue then. Thanks.
