### ISSUE TITLE
Link a GopherJs event to a local Golang event.

### ISSUE THREAD

**Issue by siredwin** [gopherjs/gopherjs#952]
I understand that this package does not allow network access. 
So, I cant use the `net` package or general `net.dial` functionality.

My main aim is to link a Javascript `onClick` event to a local Golang event(which uses `net.dial`) to gain network access.

I tried using `net/http` to start a local server inside(that does server-side events) gopherjs but it failed because it does not allow network access.

How do i link a gopherjs event to a local Golang function dialing a socket? Even if it is to just initialize a bool variable.

**Comment by siredwin** [comment]
It looks like Ajax is working so far. Any other recommendations?

**Comment by dolanor** [comment]
Actually, it allows net access.
I use it as a websocket  client (gorilla/websocket) to a backend server in Go.
What do you mean by GopherJS event? Like an event from the webpage/DOM?
I guess you just register a callback?
You might have to declare some Go function to be available from the browser with some: `js.Global.Set("nameInJS", a.Go.Function)`

**Comment by nevkontakte** [comment]
Considering the age if this question and lack of activity, I'm going to close the issue. Feel free to open it again, if it's still relevant.
