### ISSUE TITLE
context pkg seems to import fmt

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#954]
I've worked hard to make sure that I don't import directly or indirectly "fmt" package.

I'm looking at the generated gopher code. For some reason, the `context` package is importing "fmt" when it should not be: https://godoc.org/context?import-graph

I don't seem to know why.

**Comment by pjebs** [comment]
```
go version go1.12.6 darwin/amd64
GopherJS 1.12-2

```
According to this article: https://forum.golangbridge.org/t/removing-context-packages-dependency-on-fmt/6404

At some point, context package did import "fmt". Maybe gopherjs is using an "old" version of context?

**Comment by pjebs** [comment]
Ok I see go1.12 context imports fmt.

@dmitshur when will gopherjs support v1.13?

**Comment by pjebs** [comment]
@neelance

**Comment by dmitshur** [comment]
> @dmitshur when will gopherjs support v1.13?

I don't know. The tracking issue for Go 1.13 support is #929.

**Comment by pjebs** [comment]
For anyone interested: 

I have implemented a context package that doesn't use fmt for GopherJS purposes.
It can be found here: https://github.com/rocketlaunchr/react/tree/master/forks/context

It uses Francesc Campoy's code with some adjustments.

I recommend you use it until GopherJS supports Go1.13 or 1.14.
