### ISSUE TITLE
Compile from string?

### ISSUE THREAD

**Issue by yjp20** [gopherjs/gopherjs#961]
I have a strange use case of gopherjs where I want to take a `map[string]string` mapping the file name to the file contents and use that to compile to javascript in the form of a string. I've looked around for a few hours and the best resources I've found were the gopherjs/build package and the gopherjs playground, but not knowing exactly how everything works it's a bit much to digest.

If it isn't too much to ask, would it be possible to add support for this kind of parsing or help me with a snippet that can achieve the function?

**Comment by dmitshur** [comment]
I think what you're looking for is available in the package [`github.com/shurcooL/gopherjslib`](https://pkg.go.dev/github.com/shurcooL/gopherjslib?tab=doc). If you have a `files map[string]string`, then you can do:

```Go
var out bytes.Buffer
builder := gopherjslib.NewBuilder(&out, nil)
for name, b := range files {
    builder.Add(name, strings.NewReader(b))
}
err := builder.Build()
// Use out ...
```

**Comment by yjp20** [comment]
Ah, that was what I was looking for. Thanks :)
