### ISSUE TITLE
syscall/js: support for Go 1.14 changes

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherjs#962]
There will be changes to the `syscall/js` API in [Go 1.14](https://tip.golang.org/doc/go1.14#wasm):

- JavaScript values referenced from Go via js.Value objects can now be garbage collected.
- js.Value values can no longer be compared using the == operator, and instead must be compared using their Equal method.
- js.Value now has IsUndefined, IsNull, and IsNaN methods.

We should make it so that when people update their Go code to target `syscall/js` API in Go 1.14, it can continue to build with both GOARCH=wasm (Go WebAssembly) and GOARCH=js (GopherJS).

I think this can be done in a backwards-compatible way by adding the Equal, IsUndefined, IsNull, and IsNaN methods to js.Value.

/cc @hajimehoshi

**Comment by visualfc** [comment]
https://github.com/visualfc/gopherjs/tree/go1.14/compiler/natives/src/syscall/js

**Comment by mvdan** [comment]
I just got bit by this too; I was really confused at `js.Value.IsUndefined` not being defined for a while.
