### ISSUE TITLE
Go 1.14 support

### ISSUE THREAD

**Issue by pjebs** [gopherjs/gopherjs#963]
Is it possible to skip go1.13 support and go to v14?

**Comment by inliquid** [comment]
We should definitely target go1.14.

**Comment by buremba** [comment]
Any progress on this?

**Comment by nevkontakte** [comment]
Since Go 1.16 has been just released, I'm closing this issue in favor of https://github.com/gopherjs/gopherjs/issues/989, please follow it for updates 🙏
