### ISSUE TITLE
Possible to reduce the size of the output file?

### ISSUE THREAD

**Issue by unisqu** [gopherjs/gopherjs#967]
1. The reason why we are not using gopherjs is because of the bloated size of the generated output. If this can be fixed, will be great.

2. How much optimization to the bundled output can be achieved? Would like to know how optimum gopherjs is able to generate its js equivalent code (not counting media files etc)?

**Comment by flimzy** [comment]
This is already being tracked here: https://github.com/gopherjs/gopherjs/issues/136

**Comment by dmitshur** [comment]
Yep, let's use issue #136 for general binary size discussion, and new issues for specific actionable tasks.
