### ISSUE TITLE
js: Interface method can't handle circular references

### ISSUE THREAD

**Issue by dannyroes** [gopherjs/gopherjs#968]
Calls to `.Interface()` cause infinite recursion if they encounter a circular reference. Looks like this was fixed specifically for DOM cases in #87. Are there any strategies for working around this in general when 3rd party code returns objects structured this way?

index.htm:
```
<html>
<head>
<script type="text/javascript">
function getObject() {
	var a = {};
	var b = {'a': a};
	a.b = b;
	return a;
}
</script>
<script type="text/javascript" src="main.js"></script>
</head>
</html>
```

main.go:
```
package main

import "github.com/gopherjs/gopherjs/js"

func main() {
	js.Global.Call("getObject").Interface()
}
```

Causes a `too much recursion` error.

**Comment by FrankReh** [comment]
Sorry, can't propose a solution now. Can only offer that the reflect package has a DeepEqual function which could serve as an example to someone of walking an arbitrary structure and dealing with circular references. My first thought would have been to use a map but the go authors used a slice to keep the history.
