### ISSUE TITLE
ReleaseTags of default build context is inherited from Go version used to build GopherJS, which may be newer than 1.12

### ISSUE THREAD

**Issue by flimzy** [gopherjs/gopherjs#969]
Running `gopherjs` with the new `GOPHERJS_GOROOT` option sets build tags according to the running version of Go, not the compatible version of the standard library.

To reproduce, run GopherJS 1.12 with Go 1.13 (or newer, presumably):

```shell
$ go version
go version go1.13 linux/amd64
$ gopherjs version
GopherJS 1.12-3
```

and create a simple `main.go` as so:

```golang
// +build go1.13

package main 

func main() {
}
```

Then attempt to compile it, and notice it works.

```shell
$ gopherjs build .
```

It should fail:

```shell
$ go version
go version go1.12 linux/amd64
$ go build .
can't load package: package .: build constraints exclude all Go files in /home/jonhall/go/src/github.com/flimzy/tes
```

**Comment by flimzy** [comment]
I believe this is the result of compiling `gopherjs` with Go 1.13, and thus pulling in the Go 1.13 version of `go/build`.

Two possible solutions might be:

1. Update the documentation to compile GopherJS against Go 1.12
2. Find some way to vendor the Go 1.12 stdlib needed for compiling GopherJS

**Comment by dmitshur** [comment]
Thanks for reporting this @flimzy. I hadn't anticipated this, and it's helpful to know about it.

I'll need some time to think about what's the best solution.

Can you share if this caused some real-world breakage for you, or did you only realize this may cause problems in theory?

**Comment by dmitshur** [comment]
Ok, here's an example of how having a mismatched ReleaseTags could cause a problem.

Imagine someone has a valid Go package with Go 1.12 and 1.13+ code:

```Go
// +build !go1.13

// doesn't use errors.Unwrap, errors.Is and errors.As, since they're new to 1.13
```

```Go
// +build go1.13

// uses errors.Unwrap, errors.Is and errors.As
```

Then GopherJS 1.12-3 will build that package correctly if it was built with Go 1.12, but fail to do so if it was built with Go 1.13+.

So, I think the fight fix is to hardcode the ReleaseTags of the default GopherJS build context to correspond to the Go standard library version that it supports the most, namely Go 1.12 at this time.

**Comment by flimzy** [comment]
> Can you share if this caused some real-world breakage for you, or did you only realize this may cause problems in theory?

Yes, I noticed a real-world breakage when compiling a package that depends on `https://github.com/pkg/errors`, which exhibits exactly the behavior you imagined in your following comment.

**Comment by dmitshur** [comment]
Thanks for reporting and sending a fix!
