### ISSUE TITLE
What is a replacement of `Interface` method when using syscall/js?

### ISSUE THREAD

**Issue by inliquid** [gopherjs/gopherjs#974]
I was trying to migrate some client parts from `github.com/gopherjs/gopherjs/js` to `syscall/js` and found that there is no method `Interface` anymore. How to correctly perform such kind of translations in this case?

```go
	d := js.Global.Get(translatorVar).Interface().(map[string]interface{})
```

```go
	r := js.Global.Get("Uint8Array").New(req.Response).Interface().([]byte)
```

**Comment by dmitshur** [comment]
The `Interface` method was very high level. I don't think there is a 1:1 replacement for it. Instead, lower level methods must be used.

What is the definition of `translatorVar`? If it's a JSON object, then you can use [`Value.Get`](https://pkg.go.dev/syscall/js#Value.Get) method to access individual object properties.

[`js.CopyBytesToGo`](https://pkg.go.dev/syscall/js#CopyBytesToGo) can be used to copy bytes from a JavaScript `Uint8Array` to a Go byte slice.

/cc @hajimehoshi @neelance

**Comment by inliquid** [comment]
Thanks, yes I understand that `syscall/js` is rather simpler and a bit low-level. I thought that there might be some examples or code snippets for typical conversion cases?
Yes, I think `CopyBytesToGo` can fit very well in my case, thank you for suggestion.
`translatorVar` is JavaScript object, which contains some translations as maps (or JS-equivalent), smth like this:
```js
        var translator = {
            "es": {
                "Hola!": "Hello!",
            }
        };
```
I need to iterate over keys and values. I see there is `Length`  and `Index` method for `js.Value`, which makes it possible to iterate over arrays/slices, but what about such kind of objects? Should I use reflect or anything else?

**Comment by nevkontakte** [comment]
The `syscall/js` package was designed with WebAssembly in mind, and at the moment WebAssembly only supports passing in primitive types from JavaScript. That is, at least until [reference-types](https://github.com/WebAssembly/reference-types) and [interface-types](https://github.com/WebAssembly/interface-types) proposals are accepted into the standard and implemented in Go.

Until then, to be compatible with WebAssembly you'll have to serialize your object into JSON, pass it to Go with `CopyBytesToGo()` and unserialize it again. Admittedly, this isn't very efficient both in performance and memory usage, but is the only way to transfer the whole object.

You can also follow Dmitri's suggesting and use Value.Get() to access individual properties, or expose a set of JS functions that would provide higher-level interface to the contents of the object.

Considering the age of the question, I assume it is no longer relevant, so I'm closing the issue. Feel free it reopen it if that's not the case.
