### ISSUE TITLE
Transpiling junegunns fzf "Cannot internalize utils.Char"

### ISSUE THREAD

**Issue by dithmer** [gopherjs/gopherjs#975]
Hello,

I am trying to transpile junegunn/fzf, a really really good fuzzy-finder written in Golang.

My main-Function looks like this:

```
package main

import (
	"github.com/gopherjs/gopherjs/js"
	"github.com/junegunn/fzf/src/algo"
	"github.com/junegunn/fzf/src/util"
)

func main() {
	js.Global.Set("fzf", map[string]interface{}{
		"FuzzyMatchV2": algo.FuzzyMatchV2,
	})
}
```

Calling `fzf.FuzzyMatchV2(true, false, false, "Hello World", "aW", true, null)` leads to an error:

> ..js:1419 Uncaught Error: runtime error: cannot internalize util.Chars

The util.Chars-Struct looks like this:

```
type Chars struct {
	slice           []byte // or []rune
	inBytes         bool
	trimLengthKnown bool
	trimLength      uint16

	// XXX Piggybacking item index here is a horrible idea. But I'm trying to
	// minimize the memory footprint by not wasting padded spaces.
	Index int32
}
```

If you want to try it, use my fork of fzf, branch "gopherjs". There is a small change, which takes out some unix syscall dependencies, to make the build happen.

> https://github.com/dithmer/fzf/tree/gopherjs

I cannot find out what is leading to this error. Any help is appreciated. 

Thanks in advance.

**Comment by nevkontakte** [comment]
Hi @dithmer, sorry for getting back to you so late. I've tried to reproduce this issue with the latest version of GopherJS using https://github.com/dithmer/fzf/tree/gopherjs, but I'm getting build errors for `golang.org/x/sys/unix`, which GopherJS doesn't support:

```
../../../golang.org/x/sys/unix/affinity_linux.go:14:35: undeclared name: _NCPUBITS
../../../golang.org/x/sys/unix/affinity_linux.go:17:25: undeclared name: cpuMask
../../../golang.org/x/sys/unix/affinity_linux.go:50:27: undeclared name: cpuMask
../../../golang.org/x/sys/unix/fcntl.go:14:30: undeclared name: SYS_FCNTL
../../../golang.org/x/sys/unix/fcntl.go:31:42: undeclared name: Flock_t
../../../golang.org/x/sys/unix/fdset.go:11:12: undeclared name: FdSet
../../../golang.org/x/sys/unix/fdset.go:16:12: undeclared name: FdSet
../../../golang.org/x/sys/unix/fdset.go:21:12: undeclared name: FdSet
../../../golang.org/x/sys/unix/fdset.go:26:12: undeclared name: FdSet
../../../golang.org/x/sys/unix/ioctl.go:47:47: undeclared name: Termios
../../../golang.org/x/sys/unix/ioctl.go:47:47: too many errors
```

Could you provide a minimal reproduction example using the latest version of GopherJS?
