### ISSUE TITLE
fmt.Println("Hello World") seems to give confusing output

### ISSUE THREAD

**Issue by Merith-TK** [gopherjs/gopherjs#979]
I am using this go file
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
```
and when i `gopherjs build` it, i get this file 
https://hatebin.com/mysbdgaobp

Shouldnt it just write a console.log? and why does it give me this massive JS file? i used this once to convert a bubblesort in go, to js for my CS class and it returned normal JS

**Comment by flimzy** [comment]
There's nothing "garbage" or wrong about that output. It is exactly what is expected. GopherJS compiles the entire Go runtime into the output file. This is discussed at length elsewhere.

**Comment by theclapp** [comment]
Yeah, if you want `console.log`, use [`print` or `println`](https://golang.org/ref/spec#Bootstrapping), not `fmt.Println`.

**Comment by Merith-TK** [comment]
Ah, i see, that makes sense, i didnt know it compiled the entire runtime, that explains why the file is relatively massive
