### ISSUE TITLE
Best practice for distributing Go packages that make use of GopherJS at runtime?

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#98]
One blocking issue I'm running into with https://github.com/shurcooL/Go-Package-Store/pull/18 right now is this.

It imports `.../gopherjs/build` (indirectly) and compiles the frontend .go code to JavaScript when serving html.

That works fine. The problem is with distributing the root package.

Normally, when you do `go get -u some/package`, go get will recursively get all of its dependencies.

So, currently to install Go Package Store (with javascript, not GopherJS):

```bash
go get -u github.com/shurcooL/Go-Package-Store
```

However, since the .go code for GopherJS is hidden behind a `// +build js` tag, **the [dependencies](https://github.com/shurcooL/Go-Package-Store/blob/dde10d17edd37b796a8b351af105594d9dfbe775/assets/script.go#L7-L8) of the go code meant to be compiled by GopherJS compiler are not fetched**.

I tried to do an [import with blank identifier](https://github.com/shurcooL/Go-Package-Store/blob/dde10d17edd37b796a8b351af105594d9dfbe775/main.go#L27) to force go get to get dependencies, but that causes compile errors as the meant-for-GopherJS has `init()` and global variables that are executed and cause panics, since the DOM isn't available.

My best runner-up alternative solution right now is to change the installation steps to:

```bash
go get -u github.com/shurcooL/Go-Package-Store
go get -u -d -tags=js github.com/shurcooL/Go-Package-Store/...
```

But that's twice the steps and pretty unidiomatic...

I'm looking for suggestions for better ways, if anyone can share some ideas.

(Note that I don't want to include the generated javascript inside the repository; I'd really prefer to have it compiled on demand from source when the process starts. It's not very slow, and it makes the code cleaner. But of course that's a viable alternative; to bake in the generated javascript instead of generating it at runtime... This is something `go generate` may come in handy for.)

**Comment by shurcooL** [comment]
Made some progress on this today, I was able to use a `go:generate` directive to statically build GopherJS packages into `.js` files for distribution.

It's still not as clean as I want it to be, because it adds a non-compressed .js file to the repo.

Next steps will be to try using `go-bindata` to achieve that.

**Comment by shurcooL** [comment]
Made significant progress on this today, and I think I'm very close to being able to (rightfully) close this issue.

**Comment by neelance** [comment]
Cool! I'm curious to see what you come up with.

**Comment by shurcooL** [comment]
I've finally put everything together, cleaned it up (for the most part) and committed. The solution can be seen in the updated https://github.com/shurcooL/Go-Package-Store/pull/18/files.

I will merge that PR soon and it will close this issue. Thank you for the patience, as it took me a long time to resolve this.
