### ISSUE TITLE
Recommended 1.12+ instructions don't work with out-of-go{root,path} packages

### ISSUE THREAD

**Issue by computermouth** [gopherjs/gopherjs#981]
I'm pretty sure my directory structure is nothing particularly new. And I'm pretty sure the answer to this issue is just going to be true support for modules.

But I've got a binary in cmd/server/, some js targeted code in js/home/, and a shared library between the two in pkg/dynamic/. I'm just looking to share a template between my server-side code and client-side code. 

```
computermouth@crunchbox:~/projects/cookies$ go1.12.16 env GOROOT
/home/computermouth/sdk/go1.12.16
computermouth@crunchbox:~/projects/cookies$ GOPHERJS_GOROOT="$(go1.12.16 env GOROOT)" gopherjs build -m ./js/home/
cannot find package "github.com/computermouth/cookies/pkg/dynamic" in any of:
	/home/computermouth/sdk/go1.12.16/src/github.com/computermouth/cookies/pkg/dynamic (from $GOROOT)
	/home/computermouth/go/src/github.com/computermouth/cookies/pkg/dynamic (from $GOPATH)
computermouth@crunchbox:~/projects/cookies$ GOPHERJS_GOROOT="$(go1.12.16 env GOROOT)"^Copherjs build -m ./js/home/
computermouth@crunchbox:~/projects/cookies$ tree .
.
├── cmd
│   └── server
│       └── main.go
├── go.mod
├── go.sum
├── js
│   └── home
│       └── main.go
├── pkg
│   └── dynamic
│       └── main.go
└── README.md

6 directories, 6 files
```

**Comment by flimzy** [comment]
Is `github.com/computermouth/cookies/pkg/dynamic` installed in your GOPATH?

As an alternative, you can vendor your dependencies for GopherJS, that is supported.

**Comment by computermouth** [comment]
No, none of it is in the GOPATH. With Go's modules, this all works just fine outside of GOPATH.

I could vendor the dependencies, but with `go mod vendor`, it will see that `cookies/pkg/dynamic` is in-tree and would not move it to the vendor directory.

**Comment by flimzy** [comment]
> No, none of it is in the GOPATH. With Go's modules, this all works just fine outside of GOPATH.

Yes, but GopherJS does not support go modules yet. So working with GOPATH is required.

**Comment by davmaz** [comment]
This is not reflected in the godoc.org page. It states >1.12 but as noted, there is no module support, and if you ARE using modules, or 1.14.2 it doesn't work. Or document 'how' to use 1.12 instead of the most recent version.

**Comment by davmaz** [comment]
Sorry for note above. It IS addressed in the installation guide. It would be nice if it worked with 1.14.2 though...

**Comment by davmaz** [comment]
After trying to use multiple versions of go, I'm giving up on gopherjs DUE TO THIS ISSUE. It really needs an update so it can be used with the latest version.

**Comment by nevkontakte** [comment]
Sorry this has caused frustration for you 😔 Proper Go Modules support is something we would like to implement in the coming months, please subscribe to https://github.com/gopherjs/gopherjs/issues/855 if you are still interested.

There also exists @visualfc's fork (https://github.com/goplusjs/gopherjs/), which does seem to support modules already, so you can try and see if it works for you.
