### ISSUE TITLE
Possible to reduce the size of the bloated js bundle?

### ISSUE THREAD

**Issue by hiqsociety** [gopherjs/gopherjs#985]
Great work by the way! I love this project.
I'm wondering with time, is it possible that this bloated js bundle issue will be resolved? And roughly when will it be a bit larger than the real nodejs?

**Comment by dmitshur** [comment]
There will be an update posted on #894 soon, but this project is not actively developed at this time, so binary size isn't going to change.

More active development is happening on Go's WebAssembly support, so I recommend looking at that (also see issues golang/go#29478 and golang/go#6853). There may also be forks that will take a different approach.

**Comment by gitmko0** [comment]
sounds great. how do we wasm gopherjs? where's the repo for the transitioning of this project to wasm "type"?

**Comment by dmitshur** [comment]
See [golang.org/wiki/WebAssembly](https://golang.org/wiki/WebAssembly).

**Comment by nevkontakte** [comment]
This can been discussed in a lot of detail in https://github.com/gopherjs/gopherjs/issues/136.

In short, currently there isn't a way to significantly cut down output size without a breaking change for the existing users or incompatibility with mainline Go. This is something that we'd like to address eventually though, so feel free to subscribe to #136.
