### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherjs#987]
I've tried making a trivial commit just now that should pass CI, https://github.com/gopherjs/gopherjs/commit/2b03b95c2fc028dbe3f1522edb43ce905a11c50e, but it [failed](https://circleci.com/gh/gopherjs/gopherjs/1846?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

There was a problem with [this step](https://github.com/gopherjs/gopherjs/blob/fce0ec30dd00773d3fa974351d04ce2737b5c4d9/circle.yml#L20) in `circle.yml`:

```
cd node-syscall && node-gyp rebuild && mkdir -p ~/.node_libraries && cp build/Release/syscall.node ~/.node_libraries/syscall.node

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@10.0.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: ENOENT: no such file or directory, mkdir '/root/.cache/node-gyp/10.0.0'
gyp ERR! System Linux 4.15.0-1092-aws
gyp ERR! command "/root/.nvm/versions/node/v10.0.0/bin/node" "/root/.nvm/versions/node/v10.0.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/go/src/github.com/gopherjs/gopherjs/node-syscall
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 


Exited with code exit status 1
```

**Comment by nevkontakte** [comment]
I haven't looked closely into this, but maybe https://github.com/goplusjs/gopherjs/commit/245251031d2d6e59cd961a615611765f65c6cec8#diff-21b1fe66043572c76c549a4fc5f186e9a69c330b186fc91116b9b70a4d047902 from @visualfc's fork is the fix.

**Comment by dmitshur** [comment]
Thanks for the suggestion. That doesn't appear to be it, because we've already made that change in #938.

**Comment by dmitshur** [comment]
I've investigated this and confirmed that the problem is that the latest version of `node-gyp`, v7.1.2 at this time, no longer works with Node version v10.0.0 selected in circle.yml. Things start to work as before if `node-gyp@5.1.1` is installed.

To fix this, we either need to update Node to a newer version that node-gyp v7 requires (Node v14.13.1 fixed the immediate error in my brief testing), or ensure the older node-gyp version is selected. I'll probably take the shorter path of downgrading node-gyp for now, and upgrading both of them can be a future enhancement.
