### ISSUE TITLE
GopherJS should use GOOS=js instead of build.Default.GOOS

### ISSUE THREAD

**Issue by nevkontakte** [gopherjs/gopherjs#991]
Currently GopherJS [specifies](https://github.com/gopherjs/gopherjs/blob/bed99a852dfeb7c8aad4ac454357a198750247e1/build/build.go#L62) `GOOS = build.Default.GOOS` when it sets up its build context.

This is problematic because when, for example, building on Linux all sources with `linux` build tag will be picked up unless they explicitly specify `!js`, which in the standard library mostly isn't the case. This is not great for a two reasons:

 1. We try to build a lot of standard library stuff we probably don't need (e.g. the `internal/syscall/unix` package). This is very likely leads to unnecessary output bloat.
 2. Output may differ when building on hosts with a different os despite the fact that we are targeting the same execution environment (browser or node).

I think it is better to use `GOOS=js` at all times to avoid both problems. This will also improve consistency with WebAssembly, which also uses `GOOS=js` (and `GOARCH=wasm`). 

However, this is a potentially breaking change since people _might_ be expecting GopherJS to pick up linux/windows/whatever code, even though I can't think of a reason why.

@flimzy @neelance @dmitshur any thoughts?

**Comment by dmitshur** [comment]
If I understand correctly, this suggestion is the same as issue #693.

**Comment by nevkontakte** [comment]
Indeed, thanks for pointing that out. I'll close this as a duplicate then.
